exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('card-list').del()
    .then(function () {
      // Inserts seed entries
      return knex('card-list').insert([

        /*WHITES*/
        {
          name: 'Acrobatic Maneuver',
          set: 'Kaladesh',
          cost: '3',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Exile target creature you control, then return that card to the battlefield under its owner\'s control.\nDraw a card.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417574&type=card',
          flavor: 'Renegades find ever more creative ways to work around the Consulate\'s aether regulations.'
        },
        {
          name: 'Aerial Responder',
          set: 'Kaladesh',
          cost: '3',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Soldier',
          rarity: 'Uncommon',
          effects: 'Flying, vigilance, lifelink',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417575&type=card',
          power: '2',
          toughness: '3',
          flavor: 'Dwarves have an instinct for repair, an inherent understanding of how systems work, and a reputation for fearlessness.  They\'re the perfect candidates for the Fair\'s emergency response team.'
        },
        {
          name: 'Aetherstorm Roc',
          set: 'Kaladesh',
          cost: '4',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Bird',
          rarity: 'Rare',
          effects: 'Whenever Aetherstorm Roc or another creature enters the battlefield under your control, you get (E) (an energy counter).\nWhenever Aetherstorm Roc attacks, you may pay (E)(E).  If you do, put a +1/+1 counter on it and tap up to one target creature defending player controls.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417576&type=card',
          power: '3',
          toughness: '3'
        },
        {
          name: 'Angel of Invention',
          set: 'Kaladesh',
          cost: '5',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Angel',
          rarity: 'Mythic',
          effects: 'Flying, vigilance, lifelink\nFabricate 2 (When this creature enters the battlefield, put two +1/+1 counters on it or create two 1/1 colorless Servo artifact creature tokens.)\nOther creatures you control get +1/+1.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417577&type=card',
          power: '2',
          toughness: '1'
        },
        {
          name: 'Authority of the Consuls',
          set: 'Kaladesh',
          cost: '1',
          color: 'White',
          supertype: 'Enchantment',
          rarity: 'Rare',
          effects: 'Creatures your opponents control enter the battlefield tapped.\nWhenever a creature enters the battlefield under an opponent\'s control, you gain 1 life.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417578&type=card',
          flavor: 'Citizens are free to do as they wish, within the confines of the Consulate\'s laws.'
        },
        {
          name: 'Aviary Mechanic',
          set: 'Kaladesh',
          cost: '2',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Artificer',
          rarity: 'Common',
          effects: 'When Aviary Mechanic enters the battlefield, you may return another permanent you control to its owner\'s hand.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417579&type=card',
          power: '2',
          toughness: '2',
          flavor: 'Pilots take crippled skyships to the Aviaries, trusting Ghirapur\'s most talented mechanics to get them back into the air.'
        },
        {
          name: 'Built to Last',
          set: 'Kaladesh',
          cost: '1',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Target creature gets +2/+2 until end of turn.  If it\'s an artifact creature, it gains indestructible until end of turn. (Damage and effects that say "destroy" don\'t destroy it.)',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417580&type=card',
          flavor: 'Consulate-built automatons have a lifetime warranty.'
        },
        {
          name: 'Captured by the Consulate',
          set: 'Kaladesh',
          cost: '4',
          color: 'White',
          supertype: 'Enchantment',
          subtype: 'Aura',
          rarity: 'Rare',
          effects: 'Enchant creature you don\'t control\nEnchanted creature can\'t attack.\nWhenever an opponent casts a spell, if it has a single target, change the target to enchanted creature if able.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417581&type=card',
          flavor: '"At last, the infamous Pia Nalaar." --Tezzeret'
        },
        {
          name: 'Cataclysmic Gearhulk',
          set: 'Kaladesh',
          cost: '5',
          color: 'White',
          supertype: 'Artifact Creature',
          subtype: 'Construct',
          rarity: 'Mythic',
          effects: 'Vigilance\nWhen Cataclysmic Gearhulk enters the battlefield, each player chooses an artifact, a creature, an enchantment, and a planeswalker from the nonland permanents he or she controls, then sacrifices the rest.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417582&type=card',
          power: '4',
          toughness: '5'
        },
        {
          name: 'Consulate Surveillance',
          set: 'Kaladesh',
          cost: '4',
          color: 'White',
          supertype: 'Enchantment',
          rarity: 'Uncommon',
          effects: 'When Consulate Surveillance enters the battlefield, you get (E)(E)(E)(E) (four energy counters).\nPay (E)(E): Prevent all damage that would be dealt to you this turn by a source of your choice.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417583&type=card'
        },
        {
          name: 'Consul\'s Shieldguard',
          set: 'Kaladesh',
          cost: '4',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Soldier',
          rarity: 'Uncommon',
          effects: 'When Consul\'s Shieldguard enters the battlefield, you get (E)(E) (two energy counters).\nWhenever Consul\'s Shieldguard attacks, you may pay (E).  If you do, another target attacking creature gains indestructible until end of turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417584&type=card',
          power: '3',
          toughness: '4'
        },
        {
          name: 'Eddytail Hawk',
          set: 'Kaladesh',
          cost: '2',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Bird',
          rarity: 'Common',
          effects: 'Flying\nWhen Eddytail Hawk enters the battlefield, you get (E)(E) (two energy counters).\nWhenever Eddytail Hawk attacks, you may pay (E).  If you do, another target attacking creature gains flying until end of turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417585&type=card',
          power: '1',
          toughness: '2'
        },
        {
          name: 'Fairgrounds Warden',
          set: 'Kaladesh',
          cost: '3',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Soldier',
          rarity: 'Uncommon',
          effects: 'When Fairgrounds Warden enters the battlefield, exile target creature an opponent controls until Fairgrounds Warden leaves the battlefield.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417586&type=card',
          power: '1',
          toughness: '3',
          flavor: '"You\'re coming with me."'
        },
        {
          name: 'Fragmentize',
          set: 'Kaladesh',
          cost: '1',
          color: 'White',
          supertype: 'Sorcery',
          rarity: 'Common',
          effects: 'Destroy target artifact or enchantment with converted mana cost 4 or less.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417587&type=card',
          flavor: '"Too much friction on your bearings, your countersink is inconsistent, and there are lines in your casting.  Dispose of it, and begin again." --Dovin Baan'
        },
        {
          name: 'Fumigate',
          set: 'Kaladesh',
          cost: '5',
          color: 'White',
          supertype: 'Sorcery',
          rarity: 'Rare',
          effects: 'Destroy all creatures.  You gain 1 life for each creature destroyed this way.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417588&type=card',
          flavor: '"Ghirapur\'s gremlin population poses a threat to the infrastructure of the fairgrounds.  Threats must be eliminated." --Sram, senior edificer'
        },
        {
          name: 'Gearshift Ace',
          set: 'Kaladesh',
          cost: '2',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Pilot',
          rarity: 'Uncommon',
          effects: 'First strike\nWhenever Gearshift Ace crews a Vehicle, that Vehicle gains first strike until end of turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417589&type=card',
          power: '2',
          toughness: '1',
          flavor: 'Some display their trophies at the Hall of Mechanists.  Others display their talent in the streets of Ghirapur.'
        },
        {
          name: 'Glint-Sleeve Artisan',
          set: 'Kaladesh',
          cost: '3',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Artificer',
          rarity: 'Common',
          effects: 'Fabricate 1 (When this creature enters the battlefield, put a +1/+1 counter on it or create a 1/1 colorless Servo artifact creature token.)',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417590&type=card',
          power: '2',
          toughness: '2',
          flavor: '"Shine bright, bolts tight."'
        },
        {
          name: 'Herald of the Fair',
          set: 'Kaladesh',
          cost: '3',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Human',
          rarity: 'Common',
          effects: 'When Herald of the Fair enters the battlefield, target creature you control gets +1/+1 until end of turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417591&type=card',
          power: '3',
          toughness: '2',
          flavor: '"Welcome, one and all!  Right this way!  Open your eyes, your ears, and your imaginations to the wonders of the Inventors\' Fair!"'
        },
        {
          name: 'Impeccable Timing',
          set: 'Kaladesh',
          cost: '2',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Impeccable Timing deals 3 damage to target attacking or blocking creature.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417592&type=card',
          flavor: 'When Baral constructed his trap for Chandra, he did not account for the arrival of an enormous leonin wielding a twin-headed axe.'
        },
        {
          name: 'Inspired Charge',
          set: 'Kaladesh',
          cost: '4',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Creatures you control get +2/+1 until end of turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417593&type=card',
          flavor: 'One dwarf on a build team ensures competence.  All dwarves on the team ensures brilliance.'
        },
        {
          name: 'Master Trinketeer',
          set: 'Kaladesh',
          cost: '3',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Artificer',
          rarity: 'Rare',
          effects: 'Servos and Thopters you control get +1/+1.\n(3W): Create a 1/1 colorless Servo artifact creature token.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417594&type=card',
          power: '3',
          toughness: '2',
          flavor: '"Let us never forget the joy that lies at the heart of invention."'
        },
        {
          name: 'Ninth Bridge Patrol',
          set: 'Kaladesh',
          cost: '2',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Soldier',
          rarity: 'Common',
          effects: 'Whenever another creature you control leaves the battlefield, put a +1/+1 counter on Ninth Bridge Patrol.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417595&type=card',
          power: '1',
          toughness: '1',
          flavor: 'The Consulate keeps watch at each of the eleven bridges to ensure that the market remains a haven for commerce, not for con artists.'
        },
        {
          name: 'Pressure Point',
          set: 'Kaladesh',
          cost: '2',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Tap target creature.\nDraw a card.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417596&type=card',
          flavor: 'Everything has an off switch.'
        },
        {
          name: 'Propeller Pioneer',
          set: 'Kaladesh',
          cost: '4',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Human Artificer',
          rarity: 'Common',
          effects: 'Flying\nFabricate 1 (When this creature enters the battlefield, put a +1/+1 counter on it or create a 1/1 colorless Servo artifact creature token.)',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417597&type=card',
          power: '2',
          toughness: '1',
          flavor: '"The sky isn\'t the limit.  It\'s the starting point."'
        },
        {
          name: 'Refurbish',
          set: 'Kaladesh',
          cost: '4',
          color: 'White',
          supertype: 'Sorcery',
          rarity: 'Uncommon',
          effects: 'Return target artifact card from your graveyard to the battlefield.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417598&type=card',
          flavor: '"There\'s no reason to buy a new one when I\'ve got the tools to fix the one you\'ve got." --Ripu, repair specialist'
        },
        {
          name: 'Revoke Privileges',
          set: 'Kaladesh',
          cost: '3',
          color: 'White',
          supertype: 'Enchantment',
          subtype: 'Aura',
          rarity: 'Common',
          effects: 'Enchant creature\nEnchanted creature can\'t attack, block, or crew Vehicles.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417599&type=card',
          flavor: '"By order of Consulate Mandate 482, I am required to detain you, citizen."'
        },
        {
          name: 'Servo Exhibition',
          set: 'Kaladesh',
          cost: '2',
          color: 'White',
          supertype: 'Sorcery',
          rarity: 'Uncommon',
          effects: 'Create two 1/1 colorless Servo artifact creature tokens.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417600&type=card',
          flavor: '"The judges really put them through their paces, but they prevailed.  I think they even impressed Head Judge Tezzeret." --Ritika, artificer'
        },
        {
          name: 'Skyswirl Harrier',
          set: 'Kaladesh',
          cost: '5',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Bird',
          rarity: 'Common',
          effects: 'Flying',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417601&type=card',
          power: '3',
          toughness: '4',
          flavor: 'The great birds dive through the sky, wings skimming the aether streams, to fall upon their unsuspecting prey.'
        },
        {
          name: 'Skywhaler\'s Shot',
          set: 'Kaladesh',
          cost: '3',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Destroy target creature with power 3 or greater.  Scry 1.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417602&type=card',
          flavor: 'In the moment of truth, it is as though time stands still, nd the whale waits, suspended in the sky.'
        },
        {
          name: 'Tasseled Dromedary',
          set: 'Kaladesh',
          cost: '1',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Camel',
          rarity: 'Common',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417603&type=card',
          power: '0',
          toughness: '4',
          flavor: 'There is no dress code for the Inventors\' Fair, but you\'ll be hard-pressed to find anyone or anything not done up in their finest.'
        },
        {
          name: 'Thriving Ibex',
          set: 'Kaladesh',
          cost: '4',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Goat',
          rarity: 'Common',
          effects: 'When Thriving Ibex enters the battlefield, you get (E)(E) (two energy counters).\nWhenever Thriving Ibex attacks, you may pay (E)(E).  If you do, put a +1/+1 counter on it.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417604&type=card',
          power: '2',
          toughness: '4',
          flavor: 'Textiles at the Inventors\' Fair feature threads from every corner of Kaladesh.'
        },
        {
          name: 'Toolcraft Exemplar',
          set: 'Kaladesh',
          cost: '1',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Artificer',
          rarity: 'Rare',
          effects: 'At the beginning of combat on your turn, if you control an artifact, Toolcraft Exemplar gets +2/+1 until end of turn. If you control three or more artifacts, it also gains first strike until end of turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417605&type=card',
          power: '1',
          toughness: '1',
          flavor: '"If you wish to produce the finest work, you must start with the finest tools."'
        },
        {
          name: 'Trusty Companion',
          set: 'Kaladesh',
          cost: '2',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Hyena',
          rarity: 'Uncommon',
          effects: 'Vigilance\nTrusty Companion can\'t attack alone.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417606&type=card',
          power: '3',
          toughness: '2',
          flavor: 'It shows affection an automaton never could.'
        },
        {
          name: 'Visionary Augmenter',
          set: 'Kaladesh',
          cost: '4',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Artificer',
          rarity: 'Uncommon',
          effects: 'Fabricate 2 (When this creature enters the battlefield, put two +1/+1 counters on it or create two 1/1 colorless Servo artifact creature tokens.)',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417607&type=card',
          power: '2',
          toughness: '1',
          flavor: '"It\'s a multifunctional radial extension system with superlateral, force-amplifying rigging.  Of course it will win."'
        },
        {
          name: 'Wispweaver Angel',
          set: 'Kaladesh',
          cost: '6',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Angel',
          rarity: 'Uncommon',
          effects: 'Flying\nWhen Wispweaver Angel enters the battlefield, you may exile another target creature you control, then return that card to the battlefield under its owner\'s control.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417608&type=card',
          power: '4',
          toughness: '4'
        },
        /*End Whites*/
        /*BLUES*/
        {
          name: 'Aether Meltdown',
          set: 'Kaladesh',
          cost: '2',
          color: 'Blue',
          supertype: 'Enchantment',
          subtype: 'Aura',
          rarity: 'Uncommon',
          effects: 'Flash (You may cast this spell anytime you could play an instant.)\nEnchant creature or Vehicle\nWhen Aether Meltdown enters the battlefield, you get (E)(E) (two energy counters).\nEnchanted permanent gets -4/-0.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417609&type=card'
        },
        {
          name: 'Aether Theorist',
          set: 'Kaladesh',
          cost: '2',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Vedalken Rogue',
          rarity: 'Common',
          effects: 'When Aether Theorist enters the battlefield, you get (E)(E)(E) (three energy counters).\n(T), Pay (E): Scry 1. (Look at the top card of your library.  You may put that card on the bottom of your library.)',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417610&type=card',
          power: '1',
          toughness: '3'
        },
        {
          name: 'Aether Tradewinds',
          set: 'Kaladesh',
          cost: '3',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Return target permanent you control and target permanent you don\'t control to their owner\'s hands.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417611&type=card',
          flavor: 'Consulate engineers have developed safe methods of harvesting aether, but renegades aren\'t always so careful.'
        },
        {
          name: 'Aethersquall Ancient',
          set: 'Kaladesh',
          cost: '7',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Leviathan',
          rarity: 'Rare',
          effects: 'At the beginning of your upkeep, you get (E)(E)(E) (three energy counters).\nPay (E)(E)(E)(E)(E)(E)(E)(E): Return all other creatures to their owners\' hands.  Activate this ability only any time you could cast a sorcery.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417612&type=card',
          power: '6',
          toughness: '6'
        },
        {
          name: 'Ceremonious Rejection',
          set: 'Kaladesh',
          cost: '1',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Counter target colorless spell.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417613&type=card',
          flavor: 'The judges at the Fair are held in such high esteem that a nod of recognition can inspire an inventor for a lifetime--and a wave of dismissal can end a career.'
        },
        {
          name: 'Confiscation Coup',
          set: 'Kaladesh',
          cost: '5',
          color: 'Blue',
          supertype: 'Sorcery',
          rarity: 'Rare',
          effects: 'Choose target artifact or creature.  You get (E)(E)(E)(E) (four energy counters), then you may pay an amount of (E) equal to that permanent\'s converted mana cost.  If you do, gain control of it.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417614&type=card',
          flavor: '"Citizens, do not resist.  This is for your safety.  Tezzeret bids you to surrender your inventions.  Now."'
        },
        {
          name: 'Curio Vendor',
          set: 'Kaladesh',
          cost: '2',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Vedalken',
          rarity: 'Common',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417615&type=card',
          power: '2',
          toughness: '1',
          flavor: '"Step right up!  Try your hand!  It\'ll thrill the senses and boggle the mind!"'
        },
        {
          name: 'Disappearing Act',
          set: 'Kaladesh',
          cost: '3',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'As an additional cost to cast Disappearing Act, return a permanent you control to its owner\'s hand.\nCounter target spell.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417616&type=card',
          flavor: '"Baral took my family from me back then.  I\'d do anything to face him now." --Chandra Nalaar'
        },
        {
          name: 'Dramatic Reversal',
          set: 'Kaladesh',
          cost: '2',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Untap all nonland permanents you control.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417617&type=card',
          flavor: '"Nobody asked you to butt in, Jace.  But thanks." --Chandra Nalaar'
        },
        {
          name: 'Era of Innovation',
          set: 'Kaladesh',
          cost: '2',
          color: 'Blue',
          supertype: 'Enchantment',
          rarity: 'Uncommon',
          effects: 'Whenever an artifact or Artificer enters the battlefield under your control, you may pay (1).  If you do, you get (E)(E) (two energy counters).\nPay (E)(E)(E)(E)(E)(E), Sacrifice Era of Innovation: Draw three cards.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417618&type=card'
        },
        {
          name: 'Experimental Aviator',
          set: 'Kaladesh',
          cost: '5',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Human Artificer',
          rarity: 'Uncommon',
          effects: 'Flying\nWhen Experimental Aviator enters the battlefield, create two 1/1 colorless Thopter artifact creature tokens with flying.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417619&type=card',
          power: '0',
          toughness: '3',
          flavor: '"The little thopters seemed lonely up here, so I thought I\'d join them."'
        },
        {
          name: 'Failed Inspection',
          set: 'Kaladesh',
          cost: '4',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Counter target spell.  Draw a card, then discard a card.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417620&type=card',
          flavor: 'The most dangerous thing an artificer can do is believe an invention is perfect.'
        },
        {
          name: 'Gearseeker Serpent',
          set: 'Kaladesh',
          cost: '7',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Serpent',
          rarity: 'Common',
          effects: 'Gearseeker Serpent costs (1) less to cast for each artifact you control.\n(5U): Gearseeker Serpent can\'t be blocked this turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417621&type=card',
          power: '5',
          toughness: '6',
          flavor: 'Its collection is vast, yet each ship has a special place in its heart.'
        },
        {
          name: 'Glimmer of Genius',
          set: 'Kaladesh',
          cost: '4',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Scry 2, then draw two cards.  You get (E)(E) (two energy counters).',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417622&type=card',
          flavor: 'Creators live for that moment of inspiration: precious, profound, perfect.'
        },
        {
          name: 'Glint-Nest Crane',
          set: 'Kaladesh',
          cost: '2',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Bird',
          rarity: 'Uncommon',
          effects: 'Flying\nWhen Glint-Nest Crane enters the battlefield, look at the top four cards of your library. You may reveal an artifact card from among them and put it into your hand. Put the rest on the bottom of your library in any order.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417623&type=card',
          power: '1',
          toughness: '3'
        },
        {
          name: 'Hightide Hermit',
          set: 'Kaladesh',
          cost: '5',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Crab',
          rarity: 'Common',
          effects: 'Defender\nWhen Hightide Hermit enters the battlefield, you get (E)(E)(E)(E) (four energy counters).\nPay (E)(E): Hightide Hermit may attack this turn as though it didn\'t have defender.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417624&type=card',
          power: '4',
          toughness: '4'
        },
        {
          name: 'Insidious Will',
          set: 'Kaladesh',
          cost: '4',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Rare',
          effects: 'Choose one -- \n\tCounter target spell.\n\tYou may choose new targets for target spell.\n\tCopy target instant or sorcery spell.  You may choose new targets for the copy.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417625&type=card',
          flavor: '"We meet again, pyromancer." --Baral, Chief of Compliance'
        },
        {
          name: 'Janjeet Sentry',
          set: 'Kaladesh',
          cost: '3',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Vedalken Soldier',
          rarity: 'Uncommon',
          effects: 'When Janjeet Sentry enters the battlefield, you get (E)(E) (two energy counters).\n(T), Pay (E)(E): You may tap or untap target artifact or creature.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417626&type=card',
          power: '2',
          toughness: '3',
          flavor: 'Janjeet Observatory is open to the public, but access to the adjoining laboratories is restricted.'
        },
        {
          name: 'Long-Finned Skywhale',
          set: 'Kaladesh',
          cost: '4',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Whale',
          rarity: 'Uncommon',
          effects: 'Flying\nLong-Finned Skywhale can block only creatures with flying.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417627&type=card',
          power: '4',
          toughness: '3',
          flavor: 'The aethersphere is home to the most wonderful beings on all of Kaladesh, although the dangers of traversing it mean that not much is known of them.'
        },
        {
          name: 'Malfunction',
          set: 'Kaladesh',
          cost: '4',
          color: 'Blue',
          supertype: 'Enchantment',
          subtype: 'Aura',
          rarity: 'Common',
          effects: 'Enchant artifact or creature\nWhen Malfunction enters the battlefield, tap enchanted permanent.\nEnchanted permanent doesn\'t untap during its controller\'s untap step.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417628&type=card',
          flavor: '"They don\'t make them like they used to."'
        },
        {
          name: 'Metallurgic Summonings',
          set: 'Kaladesh',
          cost: '5',
          color: 'Blue',
          supertype: 'Enchantment',
          rarity: 'Mythic',
          effects: 'Whenever you cast an instant or sorcery spell, create an X/X colorless Construct artifact creature token, where X is that spell\'s converted mana cost.\n(3UU), Exile Metallurgic Summonings: Return all instant and sorcery spells from your graveyard to your hand.  Activate this ability only if you control six or more artifacts.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417629&type=card'
        },
        {
          name: 'Minister of Inquiries',
          set: 'Kaladesh',
          cost: '1',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Vedalken Advisor',
          rarity: 'Uncommon',
          effects: 'When Minister of Inquiries enters the battlefield, you get (E)(E) (two energy counters).\n(T), Pay (E): Target player puts the top three cards of his or her library into his or her graveyard.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417630&type=card',
          power: '1',
          toughness: '2',
          flavor: '"This research violates Consulate law."'
        },
        {
          name: 'Nimble Innovator',
          set: 'Kaladesh',
          cost: '4',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Vedalken Artificer',
          rarity: 'Common',
          effects: 'When Nimble Innovator enters the battlefield, draw a card.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417631&type=card',
          power: '2',
          toughness: '2',
          flavor: '"A failure is simply another opportunity for improvement.  Just wait until you see what I come up with next."'
        },
        {
          name: 'Padeem, Consul of Innovation',
          set: 'Kaladesh',
          cost: '4',
          color: 'Blue',
          supertype: 'Legendary Creature',
          subtype: 'Vedalken Artificer',
          rarity: 'Rare',
          effects: 'Artifacts you control have hexproof.\nAt the beginning of your upkeep, if you control the artifact with the highest converted mana cost or tied for the highest converted mana cost, draw a card.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417632&type=card',
          power: '1',
          toughness: '4',
          flavor: '"Impress me."'
        },
        {
          name: 'Paradoxical Outcome',
          set: 'Kaladesh',
          cost: '4',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Rare',
          effects: 'Return any number of target nonland, nontoken permanents you control to their owners\' hands.  Draw a card for each card returned to your hand this way.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417633&type=card',
          flavor: 'The results of Rashmi\'s experimentation forced her to consider the possibility that multitudinous realities existed beyond her own.'
        },
        {
          name: 'Revolutionary Rebuff',
          set: 'Kaladesh',
          cost: '2',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Counter target nonartifact spell unless its controller pays (2).',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417634&type=card',
          flavor: 'By the time a Consulate sanction becomes official, the renegade quicksmiths have already found a way to circumvent it.'
        },
        {
          name: 'Saheeli\'s Artistry',
          set: 'Kaladesh',
          cost: '6',
          color: 'Blue',
          supertype: 'Sorcery',
          rarity: 'Rare',
          effects: 'Choose one or both -- \n\tCreate a token that\'s a copy of target artifact.\n\tCreate a token that\'s a copy of target creature, except it\'s an artifact in addition to its other types.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417635&type=card',
          flavor: '"From the first touch, I know exactly what the metal wants to be."'
        },
        {
          name: 'Select for Inspection',
          set: 'Kaladesh',
          cost: '1',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Return target tapped creature to its owner\'s hand.  Scry 1. (Look at the top card of your library. You may put that card on the bottom of your library.)',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417636&type=card'
        },
        {
          name: 'Shrewd Negotiation',
          set: 'Kaladesh',
          cost: '5',
          color: 'Blue',
          supertype: 'Sorcery',
          rarity: 'Uncommon',
          effects: 'Exchange control of target artifact you control and target artifact or creature you don\'t control.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417637&type=card',
          flavor: '"Pleasure doing business with you."'
        },
        {
          name: 'Tezzeret\'s Ambition',
          set: 'Kaladesh',
          cost: '5',
          color: 'Blue',
          supertype: 'Sorcery',
          rarity: 'Common',
          effects: 'Draw three cards.  If you control no artifacts, discard a card.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417638&type=card',
          flavor: '"To achieve what none have achieved before, one must dare what none have dared before."'
        },
        {
          name: 'Thriving Turtle',
          set: 'Kaladesh',
          cost: '1',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Turtle',
          rarity: 'Common',
          effects: 'When Thriving Turtle enters the battlefield, you get (E)(E) (two energy counters).\nWhenever Thriving Turtle attacks, you may pay (E)(E).  If you do, put a +1/+1 counter on it.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417639&type=card',
          power: '0',
          toughness: '3',
          flavor: 'Aether shapes everything on Kaladesh, from the sky to the sea.'
        },
        {
          name: 'Torrential Gearhulk',
          set: 'Kaladesh',
          cost: '6',
          color: 'Blue',
          supertype: 'Artifact Creature',
          subtype: 'Construct',
          rarity: 'Mythic',
          effects: 'Flash\nWhen Torrential Gearhulk enters the battlefield, you may cast target instant or sorcery spell from your graveyard without paying its mana cost.  If that card would be put into your graveyard this turn, exile it instead.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417640&type=card',
          power: '5',
          toughness: '6'
        },
        {
          name: 'Vedalken Blademaster',
          set: 'Kaladesh',
          cost: '3',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Vedalken Soldier',
          rarity: 'Common',
          effects: 'Prowess (Whenever you cast a noncreature spell, this creature gets +1/+1 until end of turn.)',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417641&type=card',
          power: '2',
          toughness: '3',
          flavor: 'Vedalken have six thin, agile fingers on each hand, giving them unparalleled dexterity.'
        },
        {
          name: 'Weldfast Wingsmith',
          set: 'Kaladesh',
          cost: '4',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Human Artificer',
          rarity: 'Common',
          effects: 'When an artifact enters the battlefield under your control, Weldfast Wingsmith gains flying until end of turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417642&type=card',
          power: '3',
          toughness: '3',
          flavor: '"Airships are too confining.  If I\'m in the sky, I want to feel the wind in my hair and taste the aether."'
        },
        {
          name: 'Wind Drake',
          set: 'Kaladesh',
          cost: '3',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Drake',
          rarity: 'Common',
          effects: 'Flying',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417643&type=card',
          power: '2',
          toughness: '2',
          flavor: 'Drakes prowl the skies of Kaladesh, waiting for the perfect moment to strike.'
        },
        /*End Blues*/
        /*BLACKS*/
        {
          name: 'Aetherborn Marauder',
          set: 'Kaladesh',
          cost: '4',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Aetherborn Rogue',
          rarity: 'Uncommon',
          effects: 'Flying, lifelink\nWhen Aetherborn Marauder enters the battlefield, move any number of +1/+1 counters from other permanents you control onto Aetherborn Marauder.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417644&type=card',
          power: '2',
          toughness: '2',
          flavor: '"I don\'t know what that is or who it belongs to, but it\'s shiny and I want it."'
        },
        {
          name: 'Ambitious Aetherborn',
          set: 'Kaladesh',
          cost: '5',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Aetherborn Artificer',
          rarity: 'Common',
          effects: 'Fabricate 1 (When this creature enters the battlefield, put a +1/+1 counter on it or create a 1/1 colorless Servo artifact creature token.)',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417645&type=card',
          power: '4',
          toughness: '3',
          flavor: 'Aetherborn who are unwilling to accept the decomposition of their bodies invent ways to preserve and augment themselves.'
        },
        {
          name: 'Demon of Dark Schemes',
          set: 'Kaladesh',
          cost: '6',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Demon',
          rarity: 'Mythic',
          effects: 'Flying\nWhen Demon of Dark Schemes enters the battlefield, all other creatures get -2/-2 until end of turn.\nWhenever another creature dies, you get (E) (one energy counter).\n(2B), Pay (E)(E)(E)(E): Put target creature card from a graveyard onto the battlefield under your control tapped.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417646&type=card',
          power: '5',
          toughness: '5'
        },
        {
          name: 'Dhund Operative',
          set: 'Kaladesh',
          cost: '2',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Human Rogue',
          rarity: 'Common',
          effects: 'As long as you control an artifact, Dhund Operative gets +1/+0 and has deathtouch. (Any amount of damage it deals to a creature is enough to destroy it.)',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417647&type=card',
          power: '2',
          toughness: '2',
          flavor: 'Baral\'s spies always have the latest technology.'
        },
        {
          name: 'Diabolic Tutor',
          set: 'Kaladesh',
          cost: '4',
          color: 'Black',
          supertype: 'Sorcery',
          rarity: 'Uncommon',
          effects: 'Search your library for a card and put that card into your hand.  Then shuffle your library.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417648&type=card',
          flavor: '"Show them how hot your fire can burn." --Liliana Vess, to Chandra Nalaar'
        },
        {
          name: 'Die Young',
          set: 'Kaladesh',
          cost: '2',
          color: 'Black',
          supertype: 'Sorcery',
          rarity: 'Common',
          effects: 'Choose target creature.  You get (E)(E) (two energy counters), then you may pay any amount of (E).  The creature gets -1/-1 until end of turn for each (E) paid this way.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417649&type=card',
          flavor: '"When the time comes, let go.  Nothing lasts forever."'
        },
        {
          name: 'Dukhara Scavenger',
          set: 'Kaladesh',
          cost: '6',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Crocodile',
          rarity: 'Common',
          effects: 'When Dukhara Scavenger enters the battlefield, you may put target artifact or creature card from your graveyard on top of your library.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417650&type=card',
          power: '4',
          toughness: '6',
          flavor: 'The teeth marks add character.'
        },
        {
          name: 'Eliminate the Competition',
          set: 'Kaladesh',
          cost: '5',
          color: 'Black',
          supertype: 'Sorcery',
          rarity: 'Rare',
          effects: 'As an additional cost to cast Eliminate the Competition, sacrifice X creatures.\nDestroy X target creatures.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417651&type=card',
          flavor: 'Open hostilities are strictly forbidden at the Inventors\' Fair, but "accidents" still happen.'
        },
        {
          name: 'Embraal Bruiser',
          set: 'Kaladesh',
          cost: '2',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Human Warrior',
          rarity: 'Uncommon',
          effects: 'Embraal Bruiser enters the battlefield tapped.\nEmbraal Bruiser has menace as long as you control an artifact.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417652&type=card',
          power: '3',
          toughness: '1',
          flavor: 'In Embraal, inventor gangs defend their turf with ingenious devices and blunt objects.'
        },
        {
          name: 'Essence Extraction',
          set: 'Kaladesh',
          cost: '3',
          color: 'Black',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Essence Extraction deals 3 damage to target creature and you gain 3 life.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417653&type=card',
          flavor: 'The "gifted" among the aetherborn can draw the life essence of other living beings into themselves.'
        },
        {
          name: 'Fortuitous Find',
          set: 'Kaladesh',
          cost: '3',
          color: 'Black',
          supertype: 'Sorcery',
          rarity: 'Common',
          effects: 'Choose one or both -- \n\tReturn target artifact card from your graveyard to your hand.\n\tReturn target creature card from your graveyard to your hand.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417654&type=card',
          flavor: 'An aetherborn wastes neither time nor treasure.'
        },
        {
          name: 'Foundry Screecher',
          set: 'Kaladesh',
          cost: '3',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Bat',
          rarity: 'Common',
          effects: 'Flying\nFoundry Screecher gets +1/+0 as long as you control an artifact.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417655&type=card',
          power: '2',
          toughness: '1',
          flavor: '"My creations still can\'t match the dive speed of those floppy-winged mammals.  Maybe I should enter one of them in the Fair." --Viprikti, thopterist'
        },
        {
          name: 'Fretwork Colony',
          set: 'Kaladesh',
          cost: '2',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Insect',
          rarity: 'Uncommon',
          effects: 'Fretwork Colony can\'t block.\nAt the beginning of your upkeep, put a +1/+1 counter on Fretwork Colony and you lose 1 life.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417656&type=card',
          power: '1',
          toughness: '1',
          flavor: 'The swarm leaves behind a flawless pattern that only occasionally threatens the structural integrity of the wood.'
        },
        {
          name: 'Gonti, Lord of Luxury',
          set: 'Kaladesh',
          cost: '4',
          color: 'Black',
          supertype: 'Legendary Creature',
          subtype: 'Aetherborn Rogue',
          rarity: 'Rare',
          effects: 'Deathtouch\nWhen Gonti, Lord of Luxury enters the battlefield, look at the top four cards of target opponent\'s library, exile one of them face down, then put the rest on the bottom of that library in a random order.  For as long as that card remains exiled, you may look at it, you may cast it, and you may pay mana as though it were mana of any type to cast it.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417657&type=card',
          power: '2',
          toughness: '3'
        },
        {
          name: 'Harsh Scrutiny',
          set: 'Kaladesh',
          cost: '1',
          color: 'Black',
          supertype: 'Sorcery',
          rarity: 'Uncommon',
          effects: 'Target opponent reveals his or her hand.  You choose a creature card from it.  That player discards that card.  Scry 1.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417658&type=card',
          flavor: '"If you\'ve done nothing wrong, you have nothing to fear." --Enforcer-Chief Ranaj'
        },
        {
          name: 'Lawless Broker',
          set: 'Kaladesh',
          cost: '3',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Aetherborn Rogue',
          rarity: 'Common',
          effects: 'When Lawless Broker dies, put a +1/+1 counter on target creature you control.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417659&type=card',
          power: '3',
          toughness: '2',
          flavor: 'Kaladesh\'s illicit marketplaces are known as "night markets," but if you know who to ask, you can find what you\'re looking for at any time of the day.'
        },
        {
          name: 'Live Fast',
          set: 'Kaladesh',
          cost: '3',
          color: 'Black',
          supertype: 'Sorcery',
          rarity: 'Common',
          effects: 'You draw two cards, lose 2 life, and get (E)(E) (two energy counters).',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417660&type=card',
          flavor: '"When you have the chance, take it.  Laugh, sing, dance.  Don\'t allow the night to end."'
        },
        {
          name: 'Lost Legacy',
          set: 'Kaladesh',
          cost: '3',
          color: 'Black',
          supertype: 'Sorcery',
          rarity: 'Rare',
          effects: 'Name a nonartifact, nonland card.  Search target player\'s graveyard, hand, and library for any number of cards with that name and exile them.  That player shuffles his or her library, then draws a card for each card exiled from their hand this way.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417661&type=card',
          flavor: '"That name shall not be spoken." --Baral, Chief of Compliance'
        },
        {
          name: 'Make Obsolete',
          set: 'Kaladesh',
          cost: '3',
          color: 'Black',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Creatures your opponents control get -1/-1 until end of turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417662&type=card',
          flavor: 'Yesterday\'s marvels are today\'s antiquities.'
        },
        {
          name: 'Marionette Master',
          set: 'Kaladesh',
          cost: '6',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Human Artificer',
          rarity: 'Rare',
          effects: 'Fabricate 3 (When this creature enters the battlefield, put three +1/+1 counters on it or create three 1/1 colorless Servo artifact creature tokens.)\nWhenever an artifact you control is put into a graveyard from the battlefield, target opponent loses life equal to Marionette Master\'s power.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417663&type=card',
          power: '1',
          toughness: '3'
        },
        {
          name: 'Maulfist Squad',
          set: 'Kaladesh',
          cost: '4',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Human Artificer',
          rarity: 'Common',
          effects: 'Menace\nFabricate 1 (When this creature enters the battlefield, put a +1/+1 counter on it or create a 1/1 colorless Servo artifact creature token.)',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417664&type=card',
          power: '3',
          toughness: '1',
          flavor: '"Nice invention there.  Looks real fragile."'
        },
        {
          name: 'Midnight Oil',
          set: 'Kaladesh',
          cost: '4',
          color: 'Black',
          supertype: 'Enchantment',
          rarity: 'Rare',
          effects: 'Midnight Oil enters the battlefield with seven hour counters on it.\nAt the beginning of your draw step, draw an additional card and remove two hour counters from Midnight Oil.\nYour maximum hand size is equal to the number of hour counters on Midnight Oil.\nWhenever you discard a card, you lose 1 life.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417665&type=card'
        },
        {
          name: 'Mind Rot',
          set: 'Kaladesh',
          cost: '3',
          color: 'Black',
          supertype: 'Sorcery',
          rarity: 'Common',
          effects: 'Target player discards two cards.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417666&type=card',
          flavor: 'Many an inventor has collapsed under the pressure to create a flawless design.'
        },
        {
          name: 'Morbid Curiosity',
          set: 'Kaladesh',
          cost: '3',
          color: 'Black',
          supertype: 'Sorcery',
          rarity: 'Uncommon',
          effects: 'As an additional cost to cast Morbid Curiosity, sacrifice an artifact or creature.\nDraw cards equal to the converted mana cost of the sacrificed permanent.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417667&type=card',
          flavor: '"Every creation carries a piece of its creators.  Their knowledge, their dreams, their soul.  That is the best part."'
        },
        {
          name: 'Night Market Lookout',
          set: 'Kaladesh',
          cost: '1',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Human Rogue',
          rarity: 'Common',
          effects: 'Whenever Night Market Lookout becomes tapped, each opponent loses 1 life and you gain 1 life.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417668&type=card',
          power: '1',
          toughness: '1',
          flavor: 'The Consulate rarely cracks the encoded announcement of a night market\'s location before dawn, and enforcers are taken care of if they wander too close.'
        },
        {
          name: 'Noxious Gearhulk',
          set: 'Kaladesh',
          cost: '6',
          color: 'Black',
          supertype: 'Artifact Creature',
          subtype: 'Construct',
          rarity: 'Mythic',
          effects: 'Menace\nWhen Noxious Gearhulk enters the battlefield, you may destroy another target creature.  If a creature is destroyed this way, you gain life equal to its toughness.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417669&type=card',
          power: '5',
          toughness: '4'
        },
        {
          name: 'Ovalchase Daredevil',
          set: 'Kaladesh',
          cost: '4',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Human Pilot',
          rarity: 'Uncommon',
          effects: 'Whenever an artifact enters the battlefield under your control, you may return Ovalchase Daredevil from your graveyard to your hand.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417670&type=card',
          power: '4',
          toughness: '2',
          flavor: '"Let me guess.  You thought I was dead."'
        },
        {
          name: 'Prakhata Club Security',
          set: 'Kaladesh',
          cost: '4',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Aetherborn Warrior',
          rarity: 'Common',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417671&type=card',
          power: '3',
          toughness: '4',
          flavor: 'It\'s rare that the Prakhata Club closes its doors.  It\'s also true that Lord Gonti meets with Consul Kambal.  What are the odds the two would occur in the same day?'
        },
        {
          name: 'Rush of Vitality',
          set: 'Kaladesh',
          cost: '2',
          color: 'Black',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Target creature gets +1/+0 and gains lifelink and indestructible until end of turn. (Damage dealt by that creature also causes its controller to gain that much life, and it can\'t be destroyed by damage or effects that say "destroy.")',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417672&type=card',
          flavor: 'Short lives lead to forbidden choices.'
        },
        {
          name: 'Subtle Strike',
          set: 'Kaladesh',
          cost: '2',
          color: 'Black',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Choose one or both -- \n\tTarget creature gets -1/-1 until end of turn.\n\tPut a +1/+1 counter on target creature.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417673&type=card',
          flavor: 'Renegades do some of their best work right under the Consulate\'s nose.'
        },
        {
          name: 'Syndicate Trafficker',
          set: 'Kaladesh',
          cost: '2',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Aetherborn Rogue',
          rarity: 'Rare',
          effects: '(1), Sacrifice an artifact: Put a +1/+1 counter on Syndicate Trafficker.  It gains indestructible until end of turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417674&type=card',
          power: '3',
          toughness: '1',
          flavor: '"The price isn\'t negotiable, but I\'m sure you\'ll agree it\'s fair."'
        },
        {
          name: 'Thriving Rats',
          set: 'Kaladesh',
          cost: '2',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Rat',
          rarity: 'Common',
          effects: 'When Thriving Rats enters the battlefield, you get (E)(E) (two energy counters).\nWhenever Thriving Rats attacks, you may pay (E)(E).  If you do, put a +1/+1 counter on it.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417675&type=card',
          power: '1',
          toughness: '2',
          flavor: 'In Ghirapur, even the lowliest residents live in lavish surroundings.'
        },
        {
          name: 'Tidy Conclusion',
          set: 'Kaladesh',
          cost: '5',
          color: 'Black',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Destroy target creature.  You gain 1 life for each artifact you control.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417676&type=card',
          flavor: 'Aetherborn matrons use any means necessary to secure victory for their protégés.'
        },
        {
          name: 'Underhanded Designs',
          set: 'Kaladesh',
          cost: '2',
          color: 'Black',
          supertype: 'Enchantment',
          rarity: 'Uncommon',
          effects: 'Whenever an artifact enters the battlefield under your control, you may pay (1).  If you do, each opponent loses 1 life and you gain 1 life.\n(1B), Sacrifice Underhanded Designs: Destroy target creature.  Activate this ability only if you control two or more artifacts.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417677&type=card'
        },
        {
          name: 'Weaponcraft Enthusiast',
          set: 'Kaladesh',
          cost: '3',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Aetherborn Artificer',
          rarity: 'Uncommon',
          effects: 'Fabricate 2 (When this creature enters the battlefield, put two +1/+1 counters on it or create two 1/1 colorless Servo artifact creature tokens.)',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417678&type=card',
          power: '0',
          toughness: '1',
          flavor: '"No, I don\'t believe they have the proper permits for those, but I\'m not going to be the one to ask." --Caru, Consulate warden'
        },
        /*End Blacks*/

        /*REDS*/
        {
          name: 'Aethertorch Renegade',
          set: 'Kaladesh',
          cost: '3',
          color: 'Red',
          supertype: 'Creature',
          subtype: 'Human Rogue',
          rarity: 'Uncommon',
          effects: 'When Aethertorch Renegade enters the battlefield, you get (E)(E)(E)(E) (four energy counters).\n(T), Pay (E)(E): Aethertorch Renegade deals 1 damage to target creature.\n(T), Pay (E)(E)(E)(E)(E)(E)(E)(E): Aethertorch Renegade deals 6 damage to target player.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417679&type=card',
          power: '1',
          toughness: '2'
        },
        {
          name: 'Brazen Scourge',
          set: 'Kaladesh',
          cost: '3',
          color: 'Red',
          supertype: 'Creature',
          subtype: 'Gremlin',
          rarity: 'Uncommon',
          effects: 'Haste',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417680&type=card',
          power: '3',
          toughness: '3',
          flavor: 'Driven by an insatiable hunger, gremlins never cease feeding.  They can destroy a lifetime of work in just a few moments.'
        },
        {
          name: 'Built to Smash',
          set: 'Kaladesh',
          cost: '1',
          color: 'Red',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Target attacking creature gets +3/+3 until end of turn.  If it\'s an artifact creature, it gains trample until end of turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417681&type=card',
          flavor: 'Free from Consulate regulations, renegade-built automatons push performance to the limit.'
        },
        {
          name: 'Cathartic Reunion',
          set: 'Kaladesh',
          cost: '2',
          color: 'Red',
          supertype: 'Sorcery',
          rarity: 'Common',
          effects: 'As an additional cost to cast Cathartic Reunion, discard two cards.\nDraw three cards.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417682&type=card',
          flavor: 'The chasm of years and worlds collapsed under the power of their embrace.'
        },
        {
          name: 'Chandra, Torch of Defiance',
          set: 'Kaladesh',
          cost: '4',
          color: 'Red',
          supertype: 'Planeswalker',
          subtype: 'Chandra',
          rarity: 'Mythic',
          effects: '+1: Exile the top card of your library.  You may cast it.  If you don\'t, Chandra, Torch of Defiance deals 2 damage to each opponent.\n+1: Add (RR) to your mana pool.\n-3: Chandra, Pyrogenius deals 4 damage to target creature.\n-7: You get an emblem with "Whenever you cast a spell, this emblem deals 5 damage to target creature or player."',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417683&type=card',
          loyalty: '4'
        },
        {
          name: 'Chandra\'s Pyrohelix',
          set: 'Kaladesh',
          cost: '2',
          color: 'Red',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Chandra\'s Pyrohelix deals 2 damage divided as you choose among one or two target creatures and/or players.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417684&type=card',
          flavor: '"This one\'s for my mom, and this one\'s for me."'
        },
        {
          name: 'Combustible Gearhulk',
          set: 'Kaladesh',
          cost: '6',
          color: 'Red',
          supertype: 'Artifact Creature',
          subtype: 'Construct',
          rarity: 'Mythic',
          effects: 'First strike\nWhen Combustible Gearhulk enters the battlefield, target opponent may have you draw three cards.  If the player doesn\'t, put the top three cards of your library into your graveyard, then Combustible Gearhulk deals damage to that player equal to the total converted mana cost of those cards.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417685&type=card',
          power: '6',
          toughness: '6'
        },
        {
          name: 'Demolish',
          set: 'Kaladesh',
          cost: '4',
          color: 'Red',
          supertype: 'Sorcery',
          rarity: 'Common',
          effects: 'Destroy target artifact or land.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417686&type=card',
          flavor: 'Most came to Ghirapur for the Fair.  Gremlins came for the feast.'
        },
        {
          name: 'Fateful Showdown',
          set: 'Kaladesh',
          cost: '4',
          color: 'Red',
          supertype: 'Instant',
          rarity: 'Rare',
          effects: 'Fateful Showdown deals damage to target creature or player equal to the number of cards in your hand.  Discard all the cards in your hand, then draw that many cards.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417687&type=card',
          flavor: 'Tonight at the Grand Exhibition, witness Head Judge Tezzeret face off against the infamous renegade Pia Nalaar.'
        },
        {
          name: 'Flame Lash',
          set: 'Kaladesh',
          cost: '4',
          color: 'Red',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Flame Lash deals 4 damage to target creature or player.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=420479&type=card',
          flavor: '"This is just my warm-up."'
        },
        {
          name: 'Furious Reprisal',
          set: 'Kaladesh',
          cost: '4',
          color: 'Red',
          supertype: 'Sorcery',
          rarity: 'Uncommon',
          effects: 'Furious Reprisal deals 2 damage to each of two target creatures and/or players.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417688&type=card',
          flavor: '"Now that\'s the Chandra I\'ve been waiting to see." --Liliana Vess'
        },
        {
          name: 'Giant Spectacle',
          set: 'Kaladesh',
          cost: '2',
          color: 'Red',
          supertype: 'Enchantment',
          subtype: 'Aura',
          rarity: 'Common',
          effects: 'Enchant creature\nEnchanted creature gets +2/+1 and has menace.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417689&type=card',
          flavor: 'The giant-decorating contest at the migration festival is a tradition that may have started as a dare.'
        },
        {
          name: 'Harnessed Lightning',
          set: 'Kaladesh',
          cost: '2',
          color: 'Red',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Choose target creature.  You get (E)(E)(E) (three energy counters), then you may pay any amount of (E).  Harnessed Lightning deals that much damage to that creature.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417690&type=card'
        },
        {
          name: 'Hijack',
          set: 'Kaladesh',
          cost: '3',
          color: 'Red',
          supertype: 'Sorcery',
          rarity: 'Common',
          effects: 'Gain control of target artifact or creature until end of turn.  Untap it.  It gains haste until end of turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417691&type=card',
          flavor: '"Whoa there.  Easy.  We\'re just going to take a little detour."'
        },
        {
          name: 'Incendiary Sabotage',
          set: 'Kaladesh',
          cost: '4',
          color: 'Red',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'As an additional cost to cast Incendiary Sabotage, sacrifice an artifact.\nIncendiary Sabotage deals 3 damage to each creature.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417692&type=card',
          flavor: '"All of those Consulate safety measures undone with one simple tweak."'
        },
        {
          name: 'Inventor\'s Apprentice',
          set: 'Kaladesh',
          cost: '1',
          color: 'Red',
          supertype: 'Creature',
          subtype: 'Human Artificer',
          rarity: 'Uncommon',
          effects: 'Inventor\'s Apprentice gets +1/+1 as long as you control an artifact.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417693&type=card',
          power: '1',
          toughness: '2',
          flavor: '"Everyone starts off making garbage.  If you finally make something halfway decent, it\'ll be the best day of your life." --Nehra, inventor'
        },
        {
          name: 'Lathnu Hellion',
          set: 'Kaladesh',
          cost: '3',
          color: 'Red',
          supertype: 'Creature',
          subtype: 'Hellion',
          rarity: 'Rare',
          effects: 'Haste\nWhen Lathnu Hellion enters the battlefield, you get (E)(E) (two energy counters).\nAt the beginning of your end step, sacrifice Lathnu Hellion unless you pay (E)(E).',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417694&type=card',
          power: '4',
          toughness: '4'
        },
        {
          name: 'Madcap Experiment',
          set: 'Kaladesh',
          cost: '4',
          color: 'Red',
          supertype: 'Sorcery',
          rarity: 'Rare',
          effects: 'Reveal cards from the top of your library until you reveal an artifact card.  Put that card onto the battlefield and the rest on the bottom of your library in a random order.  Madcap Experiment deals damage to you equal to the number of cards revealed this way.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417695&type=card'
        },
        {
          name: 'Maulfist Doorbuster',
          set: 'Kaladesh',
          cost: '4',
          color: 'Red',
          supertype: 'Creature',
          subtype: 'Human Warrior',
          rarity: 'Uncommon',
          effects: 'When Maulfist Doorbuster enters the battlefield, you get (E)(E) (two energy counters).\nWhenever Maulfist Doorbuster attacks, you may pay (E).  If you do, target creature can\'t block this turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417696&type=card',
          power: '4',
          toughness: '2',
          flavor: '"Knock, knock... too late."'
        },
        {
          name: 'Pia Nalaar',
          set: 'Kaladesh',
          cost: '3',
          color: 'Red',
          supertype: 'Legendary Creature',
          subtype: 'Human Artificer',
          rarity: 'Rare',
          effects: 'When Pia Nalaar enters the battlefield, create a 1/1 colorless Thopter artifact creature token with flying.\n(1R): Target creature gets +1/+0 until end of turn.\n(1), Sacrifice an artifact: Target creature can\'t block this turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417697&type=card',
          power: '2',
          toughness: '2'
        },
        {
          name: 'Quicksmith Genius',
          set: 'Kaladesh',
          cost: '3',
          color: 'Red',
          supertype: 'Creature',
          subtype: 'Human Artificer',
          rarity: 'Uncommon',
          effects: 'Whenever an artifact enters the battlefield under your control, you may discard a card.  If you do, draw a card.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417698&type=card',
          power: '3',
          toughness: '2',
          flavor: 'Quicksmiths are eager to jump from one project to the next, relying on flashes of inspiration rather than careful research.'
        },
        {
          name: 'Reckless Fireweaver',
          set: 'Kaladesh',
          cost: '2',
          color: 'Red',
          supertype: 'Creature',
          subtype: 'Human Artificer',
          rarity: 'Common',
          effects: 'Whenever an artifact enters the battlefield under your control, Reckless Fireweaver deals 1 damage to each opponent.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417699&type=card',
          power: '1',
          toughness: '3',
          flavor: 'Architects find inspiration in the dragon\'s beauty of form, while artificers are influenced by the function of its fire.'
        },
        {
          name: 'Renegade Tactics',
          set: 'Kaladesh',
          cost: '1',
          color: 'Red',
          supertype: 'Sorcery',
          rarity: 'Common',
          effects: 'Target creature can\'t block this turn.\nDraw a card.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417700&type=card',
          flavor: '"Nothing against you.  It\'s just that waiting for Consulate clearance was never really my thing."'
        },
        {
          name: 'Ruinous Gremlin',
          set: 'Kaladesh',
          cost: '1',
          color: 'Red',
          supertype: 'Creature',
          subtype: 'Gremlin',
          rarity: 'Common',
          effects: '(2R), Sacrifice Ruinous Gremlin: Destroy target artifact.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417701&type=card',
          power: '1',
          toughness: '1',
          flavor: 'City officials once sent twenty gleaming automatons to exterminate a nest of gremlins.  They soon saw the error of their ways.'
        },
        {
          name: 'Salivating Gremlins',
          set: 'Kaladesh',
          cost: '3',
          color: 'Red',
          supertype: 'Creature',
          subtype: 'Gremlin',
          rarity: 'Common',
          effects: 'Whenever an artifact enters the battlefield under your control, Salivating Gremlins gets +2/+0 and gains trample until end of turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417702&type=card',
          power: '2',
          toughness: '3',
          flavor: 'If an elf can dream it, a dwarf can build it, and a gremlin can eat it.'
        },
        {
          name: 'Skyship Stalker',
          set: 'Kaladesh',
          cost: '4',
          color: 'Red',
          supertype: 'Creature',
          subtype: 'Dragon',
          rarity: 'Rare',
          effects: 'Flying\n(R): Skyship Stalker gets +1/+0 until end of turn.\n(R): Skyship Stalker gains first strike until end of turn.\n(R): Skyship Stalker gains haste until end of turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417703&type=card',
          power: '3',
          toughness: '3'
        },
        {
          name: 'Spark of Creativity',
          set: 'Kaladesh',
          cost: '1',
          color: 'Red',
          supertype: 'Sorcery',
          rarity: 'Uncommon',
          effects: 'Choose target creature.  Exile the top card of your library.  You may have Spark of Creativity deal damage to that creature equal to the exiled card\'s converted mana cost.  If you don\'t, you may play that card until end of turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417704&type=card',
          flavor: '"To invent is to rebel." --Pia Nalaar'
        },
        {
          name: 'Speedway Fanatic',
          set: 'Kaladesh',
          cost: '2',
          color: 'Red',
          supertype: 'Creature',
          subtype: 'Human Pilot',
          rarity: 'Uncommon',
          effects: 'Haste\nWhenever Speedway Fanatic crews a Vehicle, that Vehicle gains haste until end of turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417705&type=card',
          power: '2',
          toughness: '1',
          flavor: 'If her vehicle even has a brake, she couldn\'t tell you which pedal it is.'
        },
        {
          name: 'Spireside Infiltrator',
          set: 'Kaladesh',
          cost: '3',
          color: 'Red',
          supertype: 'Creature',
          subtype: 'Human Rogue',
          rarity: 'Common',
          effects: 'Whenever Spireside Infiltrator becomes tapped, it deals 1 damage to each opponent.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417706&type=card',
          power: '3',
          toughness: '2',
          flavor: '"The Consulate promised that we would all have access to aether.  I\'m just keeping them honest."'
        },
        {
          name: 'Spontaneous Artist',
          set: 'Kaladesh',
          cost: '4',
          color: 'Red',
          supertype: 'Creature',
          subtype: 'Human Rogue',
          rarity: 'Common',
          effects: 'When Spontaneous Artist enters the battlefield, you get (E) (one energy counter).\nPay (E): Target creature gains haste until end of turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417707&type=card',
          power: '3',
          toughness: '3',
          flavor: 'Graffiti of the "leaking spire" symbol is found wherever the renegades have been.'
        },
        {
          name: 'Start Your Engines',
          set: 'Kaladesh',
          cost: '4',
          color: 'Red',
          supertype: 'Sorcery',
          rarity: 'Uncommon',
          effects: 'Vehicles you control become artifact creatures until end of turn.  Creatures you control get +2/+0 until end of turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417708&type=card',
          flavor: 'Inventors from around the world have come to the Fair hoping their creations will fly, drive, or sail their way to a top prize.'
        },
        {
          name: 'Territorial Gorger',
          set: 'Kaladesh',
          cost: '4',
          color: 'Red',
          supertype: 'Creature',
          subtype: 'Gremlin',
          rarity: 'Rare',
          effects: 'Trample\nWhenever you get one or more (E) (energy counters), Territorial Gorger gets +2/+2 until end of turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417709&type=card',
          power: '2',
          toughness: '2',
          flavor: 'Inventors have been known to capture gremlins with the intent to release them in a rival\'s workshop.  More often than not, that plan backfires.'
        },
        {
          name: 'Terror of the Fairgrounds',
          set: 'Kaladesh',
          cost: '4',
          color: 'Red',
          supertype: 'Creature',
          subtype: 'Gremlin',
          rarity: 'Common',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417710&type=card',
          power: '5',
          toughness: '2',
          flavor: '"Consider this a high alert, people.  Permission to destroy on sight.  Either we take it down or it\'ll take down the whole Fair." --Pav, gremlin watch'
        },
        {
          name: 'Thriving Grubs',
          set: 'Kaladesh',
          cost: '2',
          color: 'Red',
          supertype: 'Creature',
          subtype: 'Gremlin',
          rarity: 'Common',
          effects: 'When Thriving Grubs enters the battlefield, you get (E)(E) (two energy counters).\nWhenever Thriving Grubs attacks, you may pay (E)(E).  If you do, put a +1/+1 counter on it.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417711&type=card',
          power: '2',
          toughness: '1',
          flavor: 'Some passengers ride without tickets.'
        },
        {
          name: 'Wayward Giant',
          set: 'Kaladesh',
          cost: '5',
          color: 'Red',
          supertype: 'Creature',
          subtype: 'Giant',
          rarity: 'Common',
          effects: 'Menace',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417712&type=card',
          power: '4',
          toughness: '5',
          flavor: '"The giants follow the flow of aether, and twice a year it leads them through here.  Lesson learned.  More clearance is needed." --Sram, senior edificer'
        },
        {
          name: 'Welding Sparks',
          set: 'Kaladesh',
          cost: '3',
          color: 'Red',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Welding Sparks deals X damage to target creature, where X is 3 plus the number of artifacts you control.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417713&type=card',
          flavor: '"The fires of invention burn in all of us.  I fight for the freedom to unleash those flames." --Pia Nalaar'
        },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // 178
        // {
        //   name: 'Depala, Pilot Exemplar',
        //   set: 'Kaladesh',
        //   cost: '3',
        //   color: 'Boros (Red/White)',
        //   supertype: 'Legendary Creature',
        //   subtype: 'Dwarf Pilot',
        //   rarity: 'Rare',
        //   effects: 'Other Dwarves you control get +1/+1.\nEach Vehicle you control gets +1/+1 as long as it\'s a creature.\nWhenever Depala, Pilot Exemplar becomes tapped, you may pay (X).  If you do, reveal the top X cards of your library, put all Dwarf and Vehicle cards from among them into your hand, then put the rest on the bottom of your library in a random order.',
        //   art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417751&type=card',
        //   power: '3',
        //   toughness: '3'
        // },
        // 186-190
        // {
        //   name: 'Saheeli Rai',
        //   set: 'Kaladesh',
        //   cost: '3',
        //   color: 'Izzet (Blue/Red)',
        //   supertype: 'Planeswalker',
        //   subtype: 'Saheeli',
        //   rarity: 'Mythic',
        //   effects: '+1: Saheeli Rai deals 1 damage to each opponent.\n-2: Create a token that\'s a copy of target artifact or creature you control, except it\'s an artifact in addition to its other types.  That token gains haste.  Exile it at the beginning of the next end step.\n-7: Search your library for up to three artifact cards with different names, put them on the battlefield, then shuffle your library.',
        //   art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417759&type=card',
        //   loyalty: '3'
        // },
        // {
        //   name: 'Unlicensed Disintegration',
        //   set: 'Kaladesh',
        //   cost: '3',
        //   color: 'Rakdos (Black/Red)',
        //   supertype: 'Instant',
        //   rarity: 'Uncommon',
        //   effects: 'Destroy target creature.  If you control an artifact, Unlicensed Disintegration deals 3 damage to that creature\'s controller.',
        //   art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417760&type=card',
        //   flavor: '"I\'d stand back if I were you."'
        // },
        // {
        //   name: 'Veteran Motorist',
        //   set: 'Kaladesh',
        //   cost: '2',
        //   color: 'Boros (Red/White)',
        //   supertype: 'Creature',
        //   subtype: 'Dwarf Pilot',
        //   rarity: 'Uncommon',
        //   effects: 'When Veteran Motorist enters the battlefield, scry 2.\nWhenever Veteran Motorist crews a Vehicle, that Vehicle gets +1/+1 until end of turn.',
        //   art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417761&type=card',
        //   power: '3',
        //   toughness: '1',
        //   flavor: 'He\'s set to compete in every race at the Fair, and he plans to win them all.'
        // },
        // {
        //   name: 'Voltaic Brawler',
        //   set: 'Kaladesh',
        //   cost: '2',
        //   color: 'Gruul (Red/Green)',
        //   supertype: 'Creature',
        //   subtype: 'Human Warrior',
        //   rarity: 'Uncommon',
        //   effects: 'When Voltaic Brawler enters the battlefield, you get (E)(E) (two energy counters).\nWhenever Voltaic Brawler attacks, you may pay (E).  If you do, it gets +1/+1 and gains trample until end of turn.',
        //   art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417762&type=card',
        //   power: '3',
        //   toughness: '2'
        // },
        // {
        //   name: 'Whirler Virtuoso',
        //   set: 'Kaladesh',
        //   cost: '3',
        //   color: 'Izzet (Blue/Red)',
        //   supertype: 'Creature',
        //   subtype: 'Vedalken Artificer',
        //   rarity: 'Uncommon',
        //   effects: 'When Whirler Virtuoso enters the battlefield, you get (E)(E)(E) (three energy counters).\nPay (E)(E)(E): Create a 1/1 colorless Thopter artifact creature token with flying.',
        //   art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417763&type=card',
        //   power: '2',
        //   toughness: '3',
        //   flavor: 'The first tentative flaps are like a song to his soul.'
        // },
      ]);
    });
};
