exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('Card_List').del()
  .then(function () {
    // Inserts seed entries
    return knex('Card_List').insert([
      {
        name: 'Animate Wall',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'White',
        supertype: 'Enchant Wall',
        effects: 'Enchanted Wall can now attack.  Enchanted Wall\'s power and toughness are unchanged, even if its power is 0.',
        art: 'http://mythicspoiler.com/lea/cards/animatewall.jpg'
      },
      {
        name: 'Armageddon',
        set: 'Limited Edition Alpha',
        cost: '4',
        color: 'White',
        supertype: 'Sorcery',
        effects: 'All lands in play are destroyed.',
        art: 'http://mythicspoiler.com/lea/cards/armageddon.jpg'
      },
      {
        name: 'Balance',
        set: 'Limited Edition Alpha',
        cost: '2',
        color: 'White',
        supertype: 'Sorcery',
        effects: 'Whichever player has more lands in play must sacrifice enough lands of that player\'s choice to equalize the number of lands both players have in play.  Cards in hand and creatures on the battlefield must be equalized this way.  Creatures destroyed this way can\'t be regenerated.',
        art: 'http://mythicspoiler.com/lea/cards/balance.jpg'
      },
      {
        name: 'Benalish Hero',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'White',
        supertype: 'Summon Hero',
        effects: 'Bands',
        flavor: 'Benalia has a complex caste system that changes with the lunar year.  No matter what the seasons, the only caste that cannot be attained by heredity or money is that of the hero.',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/lea/cards/benalishhero.jpg'
      },
      {
        name: 'Black Ward',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'White',
        supertype: 'Enchant Creature',
        effects: 'Enchanted creature gains protection from black.',
        art: 'http://mythicspoiler.com/lea/cards/blackward.jpg'
      },
      {
        name: 'Blaze of Glory',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'White',
        supertype: 'Instant',
        effects: 'Target defending creature can and must block all attacking creatures it can legally block.  For example, a normal non-flying defender can and must block all normal non-flying attackers at once, but it cannot block any flying attackers.  Target defender\'s controller may distribute damage among attackers as desired.  Play before defense is chosen.',
        art: 'http://mythicspoiler.com/lea/cards/blazeofglory.jpg'
      },
      {
        name: 'Blessing',
        set: 'Limited Edition Alpha',
        cost: '2',
        color: 'White',
        supertype: 'Enchant Creature',
        effects: '{W}: Enchanted creature gets +1/+1 until end of turn.',
        art: 'http://mythicspoiler.com/lea/cards/blessing.jpg'
      },
      {
        name: 'Blue Ward',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'White',
        supertype: 'Enchant Creature',
        effects: 'Enchanted creature gains protection from blue.',
        art: 'http://mythicspoiler.com/lea/cards/blueward.jpg'
      },
      {
        name: 'Castle',
        set: 'Limited Edition Alpha',
        cost: '4',
        color: 'White',
        supertype: 'Enchantment',
        effects: 'Untapped creatures you control get +0/+2.  Attacking creatures you control lose this bonus.',
        art: 'http://mythicspoiler.com/lea/cards/castle.jpg'
      },
      {
        name: 'Circle of Protection: Black',
        set: 'Limited Edition Alpha',
        cost: '2',
        color: 'White',
        supertype: 'Enchantment',
        effects: '{1}: Prevent all damage against you from one black source.  If a source deals damage to you more than once in a turn, you must pay {1} each time to prevent the damage.',
        art: 'http://mythicspoiler.com/lea/cards/circleofprotectionblack.jpg'
      },
      {
        name: 'Circle of Protection: Blue',
        set: 'Limited Edition Alpha',
        cost: '2',
        color: 'White',
        supertype: 'Enchantment',
        effects: '{1}: Prevent all damage against you from one blue source.  If a source deals damage to you more than once in a turn, you must pay {1} each time to prevent the damage.',
        art: 'http://mythicspoiler.com/lea/cards/circleofprotectionblue.jpg'
      },
      {
        name: 'Circle of Protection: Green',
        set: 'Limited Edition Alpha',
        cost: '2',
        color: 'White',
        supertype: 'Enchantment',
        effects: '{1}: Prevent all damage against you from one green source.  If a source deals damage to you more than once in a turn, you must pay {1} each time to prevent the damage.',
        art: 'http://mythicspoiler.com/lea/cards/circleofprotectiongreen.jpg'
      },
      {
        name: 'Circle of Protection: Red',
        set: 'Limited Edition Alpha',
        cost: '2',
        color: 'White',
        supertype: 'Enchantment',
        effects: '{1}: Prevent all damage against you from one red source.  If a source deals damage to you more than once in a turn, you must pay {1} each time to prevent the damage.',
        art: 'http://mythicspoiler.com/lea/cards/circleofprotectionred.jpg'
      },
      {
        name: 'Circle of Protection: White',
        set: 'Limited Edition Alpha',
        cost: '2',
        color: 'White',
        supertype: 'Enchantment',
        effects: '{1}: Prevent all damage against you from one white source.  If a source deals damage to you more than once in a turn, you must pay {1} each time to prevent the damage.',
        art: 'http://mythicspoiler.com/lea/cards/circleofprotectionwhite.jpg'
      },
      {
        name: 'Consecrate Land',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'White',
        supertype: 'Enchant Land',
        effects: 'All enchantments on enchanted land are destroyed.  Enchanted land cannot be destroyed or further enchanted until this enchantment is destroyed.',
        art: 'http://mythicspoiler.com/lea/cards/consecrateland.jpg'
      },
      {
        name: 'Conversion',
        set: 'Limited Edition Alpha',
        cost: '4',
        color: 'White',
        supertype: 'Enchantment',
        effects: 'All Mountains are considered Plains.  At the beginning of each of your upkeeps, sacrifice Conversion unless you pay {WW}.',
        art: 'http://mythicspoiler.com/lea/cards/conversion.jpg'
      },
      {
        name: 'Crusade',
        set: 'Limited Edition Alpha',
        cost: '2',
        color: 'White',
        supertype: 'Enchantment',
        effects: 'All white creatures get +1/+1.',
        art: 'http://mythicspoiler.com/lea/cards/crusade.jpg'
      },
      {
        name: 'Death Ward',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'White',
        supertype: 'Instant',
        effects: 'Regenerate target creature.',
        art: 'http://mythicspoiler.com/lea/cards/deathward.jpg'
      },
      {
        name: 'Disenchant',
        set: 'Limited Edition Alpha',
        cost: '2',
        color: 'White',
        supertype: 'Instant',
        effects: 'Destroy target artifact or enchantment.',
        art: 'http://mythicspoiler.com/lea/cards/disenchant.jpg'
      },
      {
        name: 'Farmstead',
        set: 'Limited Edition Alpha',
        cost: '3',
        color: 'White',
        supertype: 'Enchant Land',
        effects: 'Enchanted land\'s controller gains 1 life each upkeep if {WW} is spent.  Enchanted land can still generate mana as usual.',
        art: 'http://mythicspoiler.com/lea/cards/farmstead.jpg'
      },
      {
        name: 'Green Ward',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'White',
        supertype: 'Enchant Creature',
        effects: 'Enchanted creature gains protection from green.',
        art: 'http://mythicspoiler.com/lea/cards/greenward.jpg'
      },
      {
        name: 'Guardian Angel',
        set: 'Limited Edition Alpha',
        cost: '2+',
        color: 'White',
        supertype: 'Instant',
        effects: 'Prevent the next X damage dealt to any target.  Any further damage dealt to that target this turn can be cancelled by paying {1} for each 1 damage dealt.',
        art: 'http://mythicspoiler.com/lea/cards/guardianangel.jpg'
      },
      {
        name: 'Healing Salve',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'White',
        supertype: 'Instant',
        effects: 'Choose one --\n\tYou gain 3 life.\n\tPrevent the next 3 damage dealt to any target.',
        art: 'http://mythicspoiler.com/lea/cards/healingsalve.jpg'
      },
      {
        name: 'Holy Armor',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'White',
        supertype: 'Enchant Creature',
        effects: 'Enchanted creature gets +0/+2.\n{W}: Enchanted creature gets +0/+1 until end of turn.',
        art: 'http://mythicspoiler.com/lea/cards/holyarmor.jpg'
      },
      {
        name: 'Holy Strength',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'White',
        supertype: 'Enchant Creature',
        effects: 'Enchanted creature gets +1/+2.',
        art: 'http://mythicspoiler.com/lea/cards/holystrength.jpg'
      },
      {
        name: 'Island Sanctuary',
        set: 'Limited Edition Alpha',
        cost: '2',
        color: 'White',
        supertype: 'Enchantment',
        effects: 'You may decline your draw step each turn.  If you do, until your next turn, creatures without flying or islandwalk cannot attack you.',
        art: 'http://mythicspoiler.com/lea/cards/islandsanctuary.jpg'
      },
      {
        name: 'Karma',
        set: 'Limited Edition Alpha',
        cost: '4',
        color: 'White',
        supertype: 'Enchantment',
        effects: 'For each Swamp on the battlefield, it deals 1 damage to its controller at the beginning of that player\'s upkeep.',
        art: 'http://mythicspoiler.com/lea/cards/karma.jpg'
      },
      {
        name: 'Lance',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'White',
        supertype: 'Enchant Creature',
        effects: 'Enchanted creature gains first strike.',
        art: 'http://mythicspoiler.com/lea/cards/lance.jpg'
      },
      {
        name: 'Mesa Pegasus',
        set: 'Limited Edition Alpha',
        cost: '2',
        color: 'White',
        supertype: 'Summon Pegasus',
        effects: 'Flying, bands',
        flavor: 'Before a woman marries in the village of Sursi, she must visit the land of the Mesa Pegasus.  Legend has it that if the woman is pure of heart and her love is true, a Mesa Pegasus will appear, blessing her family with long life and good fortune.',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/lea/cards/mesapegasus.jpg'
      },
      {
        name: 'Northern Paladin',
        set: 'Limited Edition Alpha',
        cost: '4',
        color: 'White',
        supertype: 'Summon Paladin',
        effects: '{WW}, {T}: Destroy target black permanent.',
        flavor: '"Look to the north; there you will find aid and comfort."\n--The Book of Tal',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/lea/cards/northernpaladin.jpg'
      },
      {
        name: 'Pearled Unicorn',
        set: 'Limited Edition Alpha',
        cost: '3',
        color: 'White',
        supertype: 'Summmon Unicorn',
        flavor: '"\'Do you know, I always thought Unicorns were fabulous monsters too?  I never saw one alive before!\'  \'Well, now that we have seen each other,\' said the Unicorn, \'if you\'ll believe in me, I\'ll believe in you.\'"\n--Lewis Carroll',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/lea/cards/pearledunicorn.jpg'
      },
      {
        name: 'Personal Incarnation',
        set: 'Limited Edition Alpha',
        cost: '6',
        color: 'White',
        supertype: 'Summon Avatar',
        effects: 'Caster can redirect any or all damage dealt to Personal Incarnation to themself instead.  The source of the damage is unchanged.  If Personal Incarnation is destroyed, its controller loses half their life, rounded up.',
        power: '6',
        toughness: '6',
        art: 'http://mythicspoiler.com/lea/cards/personalincarnation.jpg'
      },
      {
        name: 'Purelace',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'White',
        supertype: 'Interrupt',
        effects: 'Change the color of one card being played or on the battlefield to white.  Cost to cast, tap, maintain, or activate an ability remain unchanged.',
        art: 'http://mythicspoiler.com/lea/cards/purelace.jpg'
      },
      {
        name: 'Red Ward',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'White',
        supertype: 'Enchant Creature',
        effects: 'Enchanted creature gains protection from red.',
        art: 'http://mythicspoiler.com/lea/cards/redward.jpg'
      },
      {
        name: 'Resurrection',
        set: 'Limited Edition Alpha',
        cost: '4',
        color: 'White',
        supertype: 'Sorcery',
        effects: 'Return target creature card from your graveyard to the battlefield.',
        art: 'http://mythicspoiler.com/lea/cards/resurrection.jpg'
      },
      {
        name: 'Reverse Damage',
        set: 'Limited Edition Alpha',
        cost: '3',
        color: 'White',
        supertype: 'Instant',
        effects: 'All damage dealt to you this turn from a source of your choice is added to your life total instead of subtracted from it.',
        art: 'http://mythicspoiler.com/lea/cards/reversedamage.jpg'
      },
      {
        name: 'Righteousness',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'White',
        supertype: 'Instant',
        effects: 'Target blocking creature gets +7/+7 until end of turn.',
        art: 'http://mythicspoiler.com/lea/cards/righteousness.jpg'
      },
      {
        name: 'Samite Healer',
        set: 'Limited Edition Alpha',
        cost: '2',
        color: 'White',
        supertype: 'Summon Cleric',
        effects: '{T}: Prevent 1 damage to target creature or player.',
        flavor: 'Healers ultimately acquire the divine gifts of spiritual and physical wholeness.  The most devout are also granted the ability to pass physical wholeness on to others.',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/lea/cards/samitehealer.jpg'
      },
      {
        name: 'Savannah Lions',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'White',
        supertype: 'Summon Lions',
        flavor: 'The traditional kings of the jungle command a healthy respect in other climates as well.  Relying mainly on their stealth and speed, Savannah Lions can take a victim by surprise, even in the endless flat plains of their homeland.',
        power: '2',
        toughness: '1',
        art: 'http://mythicspoiler.com/lea/cards/savannahlions.jpg'
      },
      {
        name: 'Serra Angel',
        set: 'Limited Edition Alpha',
        cost: '5',
        color: 'White',
        supertype: 'Summon Angel',
        effects: 'Flying, vigilance',
        flavor: 'Born with wings of light and a sword of faith, this heavenly incarnation embodies both fury and purity.',
        power: '4',
        toughness: '4',
        art: 'http://mythicspoiler.com/lea/cards/serraangel.jpg'
      },
      {
        name: 'Swords to Plowshares',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'White',
        supertype: 'Instant',
        effects: 'Exile target creature.  Its controller gains life equal to its power.',
        art: 'http://mythicspoiler.com/lea/cards/swordstoplowshares.jpg'
      },
      {
        name: 'Veteran Bodyguard',
        set: 'Limited Edition Alpha',
        cost: '5',
        color: 'White',
        supertype: 'Summon Bodyguard',
        effects: 'As long as Veteran Bodyguard is untapped, all damage dealt to you by unblocked creatures is dealt to Veteran Bodyguard instead.  This damage may be prevented normally.',
        power: '2',
        toughness: '5',
        art: 'http://mythicspoiler.com/lea/cards/veteranbodyguard.jpg'
      },
      {
        name: 'Wall of Swords',
        set: 'Limited Edition Alpha',
        cost: '4',
        color: 'White',
        supertype: 'Summon Wall',
        effects: 'Flying',
        flavor: 'Just as the evil ones approached to slay Justina, she cast a great spell, imbuing her weapons with her own life force.  Thus she fulfilled the prophecy: "In the death of your savior will you find salvation."',
        power: '3',
        toughness: '5',
        art: 'http://mythicspoiler.com/lea/cards/wallofswords.jpg'
      },
      {
        name: 'White Knight',
        set: 'Limited Edition Alpha',
        cost: '2',
        color: 'White',
        supertype: 'Summon Knight',
        effects: 'Protection from black, first strike',
        flavor: 'Out of the blackness and stench of the engulfing swamp emerged a shimmering figure.  Only the splattered armor and ichor-stained sword hinted at the unfathomable evil the knight had just laid waste.',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/lea/cards/whiteknight.jpg'
      },
      {
        name: 'White Ward',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'White',
        supertype: 'Enchant Creature',
        effects: 'Enchanted creature gains protection from white.',
        art: 'http://mythicspoiler.com/lea/cards/whiteward.jpg'
      },
      {
        name: 'Wrath of God',
        set: 'Limited Edition Alpha',
        cost: '4',
        color: 'White',
        supertype: 'Sorcery',
        effects: 'Destroy all creatures.',
        art: 'http://mythicspoiler.com/lea/cards/wrathofgod.jpg'
      },
      {
        name: 'Air Elemental',
        set: 'Limited Edition Alpha',
        cost: '5',
        color: 'Blue',
        supertype: 'Summon Elemental',
        effects: 'Flying',
        flavor: 'These spirits of the air are winsome and wild, and cannot be truly contained.  Only marginally intelligent, they often substitude whimsy for strategy, delighting in mischief and mayhem.',
        power: '4',
        toughness: '4',
        art: 'http://mythicspoiler.com/lea/cards/airelemental.jpg'
      },
      {
        name: 'Ancestral Recall',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'Blue',
        supertype: 'Instant',
        effects: 'Target player draws three cards.',
        art: 'http://mythicspoiler.com/lea/cards/ancestralrecall.jpg'
      },
      {
        name: 'Animate Artifact',
        set: 'Limited Edition Alpha',
        cost: '4',
        color: 'Blue',
        supertype: 'Enchant Non-Creature Artifact',
        effects: 'Enchanted artifact is a creature in addition to its other types with power and toughness each equal to its converted mana cost.',
        art: 'http://mythicspoiler.com/lea/cards/animateartifact.jpg'
      },
      {
        name: 'Blue Elemental Blast',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'Blue',
        supertype: 'Interrupt',
        effects: 'Choose one --\n\tCounter target red spell.\n\tDestroy target red permanent.',
        art: 'http://mythicspoiler.com/lea/cards/blueelementalblast.jpg'
      },
      {
        name: 'Braingeyser',
        set: 'Limited Edition Alpha',
        cost: '3+',
        color: 'Blue',
        supertype: 'Sorcery',
        effects: 'Target player draws X cards.',
        art: 'http://mythicspoiler.com/lea/cards/braingeyser.jpg'
      },
      {
        name: 'Clone',
        set: 'Limited Edition Alpha',
        cost: '4',
        color: 'Blue',
        supertype: 'Summon Clone',
        effects: 'Clone enters the battlefield as a copy of any creature on the battlefield.',
        power: '*',
        toughness: '*',
        art: 'http://mythicspoiler.com/lea/cards/clone.jpg'
      },
      {
        name: 'Control Magic',
        set: 'Limited Edition Alpha',
        cost: '4',
        color: 'Blue',
        supertype: 'Enchant Creature',
        effects: 'You control enchanted creature.',
        art: 'http://mythicspoiler.com/lea/cards/controlmagic.jpg'
      },
      {
        name: 'Copy Artifact',
        set: 'Limited Edition Alpha',
        cost: '2',
        color: 'Blue',
        supertype: 'Enchantment',
        effects: 'Copy Artifact enters the battlefield as a copy of any artifact on the battlefield.',
        art: 'http://mythicspoiler.com/lea/cards/copyartifact.jpg'
      },
      {
        name: 'Counterspell',
        set: 'Limited Edition Alpha',
        cost: '2',
        color: 'Blue',
        supertype: 'Interrupt',
        effects: 'Counter target spell.',
        art: 'http://mythicspoiler.com/lea/cards/counterspell.jpg'
      },
      {
        name: 'Creature Bond',
        set: 'Limited Edition Alpha',
        cost: '2',
        color: 'Blue',
        supertype: 'Enchant Creature',
        effects: 'When enchanted creature dies, Creature Bond deals damage equal to enchanted creature\'s toughness to that creature\'s controller.',
        art: 'http://mythicspoiler.com/lea/cards/creaturebond.jpg'
      },
      {
        name: 'Drain Power',
        set: 'Limited Edition Alpha',
        cost: '2',
        color: 'Blue',
        supertype: 'Sorcery',
        effects: 'Tap all opponent\'s lands.  You add that mana to your mana pool.',
        art: 'http://mythicspoiler.com/lea/cards/drainpower.jpg'
      },
      {
        name: 'Feedback',
        set: 'Limited Edition Alpha',
        cost: '3',
        color: 'Blue',
        supertype: 'Enchant Enchantment',
        effects: 'At the beginning of each upkeep, Feedback deals 1 damage to enchanted permanent\'s controller.',
        art: 'http://mythicspoiler.com/lea/cards/feedback.jpg'
      },
      {
        name: 'Flight',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'Blue',
        supertype: 'Enchant Creature',
        effects: 'Enchanted creature has flying.',
        art: 'http://mythicspoiler.com/lea/cards/flight.jpg'
      },
      {
        name: 'Invisibility',
        set: 'Limited Edition Alpha',
        cost: '2',
        color: 'Blue',
        supertype: 'Enchant Creature',
        effects: 'Enchanted creature can\'t be blocked except by Walls.',
        art: 'http://mythicspoiler.com/lea/cards/invisibility.jpg'
      },
      {
        name: 'Jump',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'Blue',
        supertype: 'Instant',
        effects: 'Target creature gains flying until end of turn.',
        art: 'http://mythicspoiler.com/lea/cards/jump.jpg'
      },
      {
        name: 'Lifetap',
        set: 'Limited Edition Alpha',
        cost: '2',
        color: 'Blue',
        supertype: 'Enchantment',
        effects: 'Whenever an opponent taps a Forest, you gain 1 life.',
        art: 'http://mythicspoiler.com/lea/cards/lifetap.jpg'
      },
      {
        name: 'Lord of Atlantis',
        set: 'Limited Edition Alpha',
        cost: '2',
        color: 'Blue',
        supertype: 'Summon Lord of Atlantis',
        effects: 'All Merfolk get +1/+1 and have islandwalk.',
        flavor: 'A master of tactics, the Lord of Atlantis makes his people bold in battle merely by arriving to lead them.',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/lea/cards/lordofatlantis.jpg'
      },
      {
        name: 'Magical Hack',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'Blue',
        supertype: 'Interrupt',
        effects: 'Change the text of any one card by replacing one basic land type with another.  For example, you can change "swampwalk" to "plainswalk."',
        art: 'http://mythicspoiler.com/lea/cards/magicalhack.jpg'
      },
      {
        name: 'Mahamoti Djinn',
        set: 'Limited Edition Alpha',
        cost: '6',
        color: 'Blue',
        supertype: 'Summon Djinn',
        effects: 'Flying',
        flavor: 'Of royal blood among the spirits of the air, the Mahamoti Djinn rides on the wings of the winds.  As dangerous in a gambling hall as he is in battle, he is a master of trickery and misdirection.',
        power: '5',
        toughness: '6',
        art: 'http://mythicspoiler.com/lea/cards/mahamotidjinn.jpg'
      },
      {
        name: 'Mana Short',
        set: 'Limited Edition Alpha',
        cost: '3',
        color: 'Blue',
        supertype: 'Instant',
        effects: 'Tap all lands target opponent controls, and empty that player\'s mana pool.',
        art: 'http://mythicspoiler.com/lea/cards/manashort.jpg'
      },
      {
        name: 'Merfolk of the Pearl Trident',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'Blue',
        supertype: 'Summon Merfolk',
        flavor: 'Most human scholars believe that Merfolk are the survivors of sunken Atlantis, humans adapted to the water.  Merfolk, however, believe that humans sprang forth from Merfolk who adapted themselves in order to explore their last frontier.',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/lea/cards/merfolkofthepearltrident.jpg'
      },
      {
        name: 'Phantasmal Forces',
        set: 'Limited Edition Alpha',
        cost: '4',
        color: 'Blue',
        supertype: 'Summon Phantasm',
        effects: 'Flying\nPhantasmal Forces\'s controller must pay {U} at the beginning of each upkeep or sacrifice Phantasmal Forces.',
        flavor: 'These beings embody the essence of true heroes long dead.  Summoned from the dreamrealms, they rise to meet their enemies.',
        power: '4',
        toughness: '1',
        art: 'http://mythicspoiler.com/lea/cards/phantasmalforces.jpg'
      },
      {
        name: 'Phantasmal Terrain',
        set: 'Limited Edition Alpha',
        cost: '2',
        color: 'Blue',
        supertype: 'Enchant Land',
        effects: 'Enchanted land becomes a basic land type of the caster\'s choice.',
        art: 'http://mythicspoiler.com/lea/cards/phantasmalterrain.jpg'
      },
      {
        name: 'Phantom Monster',
        set: 'Limited Edition Alpha',
        cost: '4',
        color: 'Blue',
        supertype: 'Summon Phantasm',
        effects: 'Flying',
        flavor: '"While, like a ghastly rapid river,\nThrough the pale door,\nA hideous throng rush out forever,\nAnd laugh--but smile no more."\n--Edgar Allan Poe, "The Haunted House"',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/lea/cards/phantommonster.jpg'
      },
      {
        name: 'Pirate Ship',
        set: 'Limited Edition Alpha',
        cost: '5',
        color: 'Blue',
        supertype: 'Summon Ship',
        effects: '{T}: Pirate Ship deals 1 damage to target creature or player.\nPirate Ship can\'t attack unless defending player controls an Island.\nIf there are no Islands in play, sacrifice Pirate Ship.',
        power: '4',
        toughness: '3',
        art: 'http://mythicspoiler.com/lea/cards/pirateship.jpg'
      },
      {
        name: 'Power Leak',
        set: 'Limited Edition Alpha',
        cost: '2',
        color: 'Blue',
        supertype: 'Enchant Enchantment',
        effects: 'Enchanted permanent has an upkeep cost of {2}.  If enchanted permanent\'s controller cannot pay this upkeep cost, Power Leak deals 1 damage to them for each {1} unpaid.',
        art: 'http://mythicspoiler.com/lea/cards/powerleak.jpg'
      },
      {
        name: 'Power Sink',
        set: 'Limited Edition Alpha',
        cost: '2+',
        color: 'Blue',
        supertype: 'Interrupt',
        effects: 'Counter target spell unless its controller pays {X}.  If that spell\'s controller can\'t, they must pay with whatever land they have, and the spell is still countered.',
        art: 'http://mythicspoiler.com/lea/cards/powersink.jpg'
      },
      {
        name: 'Prodigal Sorcerer',
        set: 'Limited Edition Alpha',
        cost: '3',
        color: 'Blue',
        supertype: 'Summon Wizard',
        effects: '{T}: Prodigal Sorcerer deals 1 damage to target creature or player.',
        flavor: 'Occasionally a member of the Institute of Arcane Study acquires a taste for worldly pleasures.  Seldom do they have trouble finding employment.',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/lea/cards/prodigalsorcerer.jpg'
      },
      {
        name: 'Psionic Blast',
        set: 'Limited Edition Alpha',
        cost: '3',
        color: 'Blue',
        supertype: 'Instant',
        effects: 'Psionic Blast deals 4 damage to target creature or player and 2 damage to you.',
        art: 'http://mythicspoiler.com/lea/cards/psionicblast.jpg'
      },
      {
        name: 'Psychic Venom',
        set: 'Limited Edition Alpha',
        cost: '2',
        color: 'Blue',
        supertype: 'Enchant Land',
        effects: 'Whenever enchanted land becomes tapped, Psychic Venom deals 2 damage to that land\'s controller.',
        art: 'http://mythicspoiler.com/lea/cards/psychicvenom.jpg'
      },
      {
        name: 'Sea Serpent',
        set: 'Limited Edition Alpha',
        cost: '6',
        color: 'Blue',
        supertype: 'Summon Serpent',
        effects: 'Sea Serpent can\'t attack unless defending player controls an Island.\nAt the beginning of your upkeep, if there are no Islands in play, sacrifice Sea Serpent.',
        flavor: 'Legend has it that serpents used to be bigger, but how could that be?',
        power: '5',
        toughness: '5',
        art: 'http://mythicspoiler.com/lea/cards/seaserpent.jpg'
      },
      {
        name: 'Siren\'s Call',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'Blue',
        supertype: 'Instant',
        effects: 'All creatures target opponent controls attack this turn if able.  At end of combat, destroy all non-Wall creatures that didn\'t attack.  Creatures with summoning sickness are not affected.',
        art: 'http://mythicspoiler.com/lea/cards/sirenscall.jpg'
      },
      {
        name: 'Sleight of Mind',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'Blue',
        supertype: 'Interrupt',
        effects: 'Change the text of one card by replacing a color word with another.  For example, change "Counter target red spell" to "Counter target black spell."  This does not change the target spell\'s color.',
        art: 'http://mythicspoiler.com/lea/cards/sleightofmind.jpg'
      },
      {
        name: 'Spell Blast',
        set: 'Limited Edition Alpha',
        cost: '2+',
        color: 'Blue',
        supertype: 'Interrupt',
        effects: 'Counter target spell with converted mana cost X.',
        art: 'http://mythicspoiler.com/lea/cards/spellblast.jpg'
      },
      {
        name: 'Stasis',
        set: 'Limited Edition Alpha',
        cost: '2',
        color: 'Blue',
        supertype: 'Enchantment',
        effects: 'Players do not untap during their untap steps.  At the beginning of your upkeep, pay {U} or sacrifice Stasis.',
        art: 'http://mythicspoiler.com/lea/cards/stasis.jpg'
      },
      {
        name: 'Steal Artifact',
        set: 'Limited Edition Alpha',
        cost: '4',
        color: 'Blue',
        supertype: 'Enchant Artifact',
        effects: 'You control enchanted artifact.',
        art: 'http://mythicspoiler.com/lea/cards/stealartifact.jpg'
      },
      {
        name: 'Thoughtlace',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'Blue',
        supertype: 'Interrupt',
        effects: 'Change the color of any card to blue.',
        art: 'http://mythicspoiler.com/lea/cards/thoughtlace.jpg'
      },
      {
        name: 'Time Walk',
        set: 'Limited Edition Alpha',
        cost: '2',
        color: 'Blue',
        supertype: 'Sorcery',
        effects: 'Take an extra turn after this one.',
        art: 'http://mythicspoiler.com/lea/cards/timewalk.jpg'
      },
      {
        name: 'Timetwister',
        set: 'Limited Edition Alpha',
        cost: '3',
        color: 'Blue',
        supertype: 'Sorcery',
        effects: 'Each player shuffles their hand and graveyard into their library, then draws seven cards.  Exile Timetwister.',
        art: 'http://mythicspoiler.com/lea/cards/timetwister.jpg'
      },
      {
        name: 'Twiddle',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'Blue',
        supertype: 'Instant',
        effects: 'Tap or untap target artifact, creature, or land.',
        art: 'http://mythicspoiler.com/lea/cards/twiddle.jpg'
      },
      {
        name: 'Unsummon',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'Blue',
        supertype: 'Instant',
        effects: 'Return target creature to its owner\'s hand.',
        art: 'http://mythicspoiler.com/lea/cards/unsummon.jpg'
      },
      {
        name: 'Vesuvian Doppelganger',
        set: 'Limited Edition Alpha',
        cost: '5',
        color: 'Blue',
        supertype: 'Summon Doppelganger',
        effects: 'Vesuvian Doppelganger enters the battlefield as a copy of any creature on the battlefield.\nAt the beginning of your upkeep, you may have Vesuvian Doppelganger become a copy of target creature.',
        power: '*',
        toughness: '*',
        art: 'http://mythicspoiler.com/lea/cards/vesuviandoppelganger.jpg'
      },
      {
        name: 'Volcanic Eruption',
        set: 'Limited Edition Alpha',
        cost: '4+',
        color: 'Blue',
        supertype: 'Sorcery',
        effects: 'Destroy X target Mountains.  Volcanic Eruption deals X damage to each creature and each player.',
        art: 'http://mythicspoiler.com/lea/cards/volcaniceruption.jpg'
      },
      {
        name: 'Wall of Air',
        set: 'Limited Edition Alpha',
        cost: '3',
        color: 'Blue',
        supertype: 'Summon Wall',
        effects: 'Flying',
        flavor: '"This \'standing windstorm\' can hold us off indefinitely?  Ridiculous!"  Saying nothing, she put a pinch of salt on the table.  With a bang, she clapped her hands, and the salt disappeared, blown away.',
        power: '1',
        toughness: '5',
        art: 'http://mythicspoiler.com/lea/cards/wallofair.jpg'
      },
      {
        name: 'Wall of Water',
        set: 'Limited Edition Alpha',
        cost: '3',
        color: 'Blue',
        supertype: 'Summon Wall',
        effects: '{U}: Wall of Water gets +1/+0 until end of turn.',
        flavor: 'A deafening roar arose as the fury of an enormous vertical river supplanted our serenity.  Eddies turned into whirling geysers, leveling everything in their path.',
        power: '0',
        toughness: '5',
        art: 'http://mythicspoiler.com/lea/cards/wallofwater.jpg'
      },
      {
        name: 'Water Elemental',
        set: 'Limited Edition Alpha',
        cost: '5',
        color: 'Blue',
        supertype: 'Summon Elemental',
        flavor: 'Unpredictable as the sea itself, Water Elementals shift without warning from tranquility to tempest.  Capricious and fickle, they flow restlessly from one shape to another, expressing their moods with their physical forms.',
        power: '5',
        toughness: '4',
        art: 'http://mythicspoiler.com/lea/cards/waterelemental.jpg'
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      }
    ]);
  });
};