exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('Card_List').del()
  .then(function () {
    // Inserts seed entries
    return knex('Card_List').insert([
      {
        name: 'Animate Wall',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'White',
        supertype: 'Enchant Wall',
        effects: 'Enchanted Wall can now attack.  Enchanted Wall\'s power and toughness are unchanged, even if its power is 0.',
        art: 'http://mythicspoiler.com/lea/cards/animatewall.jpg'
      },
      {
        name: 'Armageddon',
        set: 'Limited Edition Alpha',
        cost: '4',
        color: 'White',
        supertype: 'Sorcery',
        effects: 'All lands in play are destroyed.',
        art: 'http://mythicspoiler.com/lea/cards/armageddon.jpg'
      },
      {
        name: 'Balance',
        set: 'Limited Edition Alpha',
        cost: '2',
        color: 'White',
        supertype: 'Sorcery',
        effects: 'Whichever player has more lands in play must sacrifice enough lands of that player\'s choice to equalize the number of lands both players have in play.  Cards in hand and creatures on the battlefield must be equalized this way.  Creatures destroyed this way can\'t be regenerated.',
        art: 'http://mythicspoiler.com/lea/cards/balance.jpg'
      },
      {
        name: 'Benalish Hero',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'White',
        supertype: 'Summon Hero',
        effects: 'Bands',
        flavor: 'Benalia has a complex caste system that changes with the lunar year.  No matter what the seasons, the only caste that cannot be attained by heredity or money is that of the hero.',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/lea/cards/benalishhero.jpg'
      },
      {
        name: 'Black Ward',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'White',
        supertype: 'Enchant Creature',
        effects: 'Enchanted creature gains protection from black.',
        art: 'http://mythicspoiler.com/lea/cards/blackward.jpg'
      },
      {
        name: 'Blaze of Glory',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'White',
        supertype: 'Instant',
        effects: 'Target defending creature can and must block all attacking creatures it can legally block.  For example, a normal non-flying defender can and must block all normal non-flying attackers at once, but it cannot block any flying attackers.  Target defender\'s controller may distribute damage among attackers as desired.  Play before defense is chosen.',
        art: 'http://mythicspoiler.com/lea/cards/blazeofglory.jpg'
      },
      {
        name: 'Blessing',
        set: 'Limited Edition Alpha',
        cost: '2',
        color: 'White',
        supertype: 'Enchant Creature',
        effects: '{W}: Enchanted creature gets +1/+1 until end of turn.',
        art: 'http://mythicspoiler.com/lea/cards/blessing.jpg'
      },
      {
        name: 'Blue Ward',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'White',
        supertype: 'Enchant Creature',
        effects: 'Enchanted creature gains protection from blue.',
        art: 'http://mythicspoiler.com/lea/cards/blueward.jpg'
      },
      {
        name: 'Castle',
        set: 'Limited Edition Alpha',
        cost: '4',
        color: 'White',
        supertype: 'Enchantment',
        effects: 'Untapped creatures you control get +0/+2.  Attacking creatures you control lose this bonus.',
        art: 'http://mythicspoiler.com/lea/cards/castle.jpg'
      },
      {
        name: 'Circle of Protection: Black',
        set: 'Limited Edition Alpha',
        cost: '2',
        color: 'White',
        supertype: 'Enchantment',
        effects: '{1}: Prevent all damage against you from one black source.  If a source deals damage to you more than once in a turn, you must pay {1} each time to prevent the damage.',
        art: 'http://mythicspoiler.com/lea/cards/circleofprotectionblack.jpg'
      },
      {
        name: 'Circle of Protection: Blue',
        set: 'Limited Edition Alpha',
        cost: '2',
        color: 'White',
        supertype: 'Enchantment',
        effects: '{1}: Prevent all damage against you from one blue source.  If a source deals damage to you more than once in a turn, you must pay {1} each time to prevent the damage.',
        art: 'http://mythicspoiler.com/lea/cards/circleofprotectionblue.jpg'
      },
      {
        name: 'Circle of Protection: Green',
        set: 'Limited Edition Alpha',
        cost: '2',
        color: 'White',
        supertype: 'Enchantment',
        effects: '{1}: Prevent all damage against you from one green source.  If a source deals damage to you more than once in a turn, you must pay {1} each time to prevent the damage.',
        art: 'http://mythicspoiler.com/lea/cards/circleofprotectiongreen.jpg'
      },
      {
        name: 'Circle of Protection: Red',
        set: 'Limited Edition Alpha',
        cost: '2',
        color: 'White',
        supertype: 'Enchantment',
        effects: '{1}: Prevent all damage against you from one red source.  If a source deals damage to you more than once in a turn, you must pay {1} each time to prevent the damage.',
        art: 'http://mythicspoiler.com/lea/cards/circleofprotectionred.jpg'
      },
      {
        name: 'Circle of Protection: White',
        set: 'Limited Edition Alpha',
        cost: '2',
        color: 'White',
        supertype: 'Enchantment',
        effects: '{1}: Prevent all damage against you from one white source.  If a source deals damage to you more than once in a turn, you must pay {1} each time to prevent the damage.',
        art: 'http://mythicspoiler.com/lea/cards/circleofprotectionwhite.jpg'
      },
      {
        name: 'Consecrate Land',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'White',
        supertype: 'Enchant Land',
        effects: 'All enchantments on enchanted land are destroyed.  Enchanted land cannot be destroyed or further enchanted until this enchantment is destroyed.',
        art: 'http://mythicspoiler.com/lea/cards/consecrateland.jpg'
      },
      {
        name: 'Conversion',
        set: 'Limited Edition Alpha',
        cost: '4',
        color: 'White',
        supertype: 'Enchantment',
        effects: 'All Mountains are considered Plains.  At the beginning of each of your upkeeps, sacrifice Conversion unless you pay {WW}.',
        art: 'http://mythicspoiler.com/lea/cards/conversion.jpg'
      },
      {
        name: 'Crusade',
        set: 'Limited Edition Alpha',
        cost: '2',
        color: 'White',
        supertype: 'Enchantment',
        effects: 'All white creatures get +1/+1.',
        art: 'http://mythicspoiler.com/lea/cards/crusade.jpg'
      },
      {
        name: 'Death Ward',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'White',
        supertype: 'Instant',
        effects: 'Regenerate target creature.',
        art: 'http://mythicspoiler.com/lea/cards/deathward.jpg'
      },
      {
        name: 'Disenchant',
        set: 'Limited Edition Alpha',
        cost: '2',
        color: 'White',
        supertype: 'Instant',
        effects: 'Destroy target artifact or enchantment.',
        art: 'http://mythicspoiler.com/lea/cards/disenchant.jpg'
      },
      {
        name: 'Farmstead',
        set: 'Limited Edition Alpha',
        cost: '3',
        color: 'White',
        supertype: 'Enchant Land',
        effects: 'Enchanted land\'s controller gains 1 life each upkeep if {WW} is spent.  Enchanted land can still generate mana as usual.',
        art: 'http://mythicspoiler.com/lea/cards/farmstead.jpg'
      },
      {
        name: 'Green Ward',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'White',
        supertype: 'Enchant Creature',
        effects: 'Enchanted creature gains protection from green.',
        art: 'http://mythicspoiler.com/lea/cards/greenward.jpg'
      },
      {
        name: 'Guardian Angel',
        set: 'Limited Edition Alpha',
        cost: '2+',
        color: 'White',
        supertype: 'Instant',
        effects: 'Prevent the next X damage dealt to any target.  Any further damage dealt to that target this turn can be cancelled by paying {1} for each 1 damage dealt.',
        art: 'http://mythicspoiler.com/lea/cards/guardianangel.jpg'
      },
      {
        name: 'Healing Salve',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'White',
        supertype: 'Instant',
        effects: 'Choose one --\n\tYou gain 3 life.\n\tPrevent the next 3 damage dealt to any target.',
        art: 'http://mythicspoiler.com/lea/cards/healingsalve.jpg'
      },
      {
        name: 'Holy Armor',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'White',
        supertype: 'Enchant Creature',
        effects: 'Enchanted creature gets +0/+2.\n{W}: Enchanted creature gets +0/+1 until end of turn.',
        art: 'http://mythicspoiler.com/lea/cards/holyarmor.jpg'
      },
      {
        name: 'Holy Strength',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'White',
        supertype: 'Enchant Creature',
        effects: 'Enchanted creature gets +1/+2.',
        art: 'http://mythicspoiler.com/lea/cards/holystrength.jpg'
      },
      {
        name: 'Island Sanctuary',
        set: 'Limited Edition Alpha',
        cost: '2',
        color: 'White',
        supertype: 'Enchantment',
        effects: 'You may decline your draw step each turn.  If you do, until your next turn, creatures without flying or islandwalk cannot attack you.',
        art: 'http://mythicspoiler.com/lea/cards/islandsanctuary.jpg'
      },
      {
        name: 'Karma',
        set: 'Limited Edition Alpha',
        cost: '4',
        color: 'White',
        supertype: 'Enchantment',
        effects: 'For each Swamp on the battlefield, it deals 1 damage to its controller at the beginning of that player\'s upkeep.',
        art: 'http://mythicspoiler.com/lea/cards/karma.jpg'
      },
      {
        name: 'Lance',
        set: 'Limited Edition Alpha',
        cost: '1',
        color: 'White',
        supertype: 'Enchant Creature',
        effects: 'Enchanted creature gains first strike.',
        art: 'http://mythicspoiler.com/lea/cards/lance.jpg'
      },
      {
        name: 'Mesa Pegasus',
        set: 'Limited Edition Alpha',
        cost: '2',
        color: 'White',
        supertype: 'Summon Pegasus',
        effects: 'Flying, bands',
        flavor: 'Before a woman marries in the village of Sursi, she must visit the land of the Mesa Pegasus.  Legend has it that if the woman is pure of heart and her love is true, a Mesa Pegasus will appear, blessing her family with long life and good fortune.',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/lea/cards/mesapegasus.jpg'
      },
      {
        name: 'Northern Paladin',
        set: 'Limited Edition Alpha',
        cost: '4',
        color: 'White',
        supertype: 'Summon Paladin',
        effects: '{WW}, {T}: Destroy target black permanent.',
        flavor: '"Look to the north; there you will find aid and comfort."\n--The Book of Tal',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/lea/cards/northernpaladin.jpg'
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Limited Edition Alpha',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      }
    ]);
  });
};