exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('card-list').del()
    .then(function () {
      // Inserts seed entries
      return knex('card-list').insert([
        {
          name: 'Aerial Modification',
          set: 'Aether Revolt',
          cost: '5',
          color: 'White',
          supertype: 'Enchantment',
          subtype: 'Aura',
          rarity: 'Uncommon',
          effects: 'Enchant creature or Vehicle\nAs long as enchanted permanent is a Vehicle, it\'s a creature in addition to its other types.\nEnchanted creature gets +2/+2 and has flying.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423668&type=card'
        },
        {
          name: 'Aeronaut Admiral',
          set: 'Aether Revolt',
          cost: '4',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Human Pilot',
          rarity: 'Uncommon',
          effects: 'Flying\nVehicles you control have flying.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423669&type=card',
          power: '3',
          toughness: '1',
          flavor: 'The Consulate recruits its best pilots from the League of Aeronauts.  Many go on to command entire fleets.'
        },
        {
          name: 'Aether Inspector',
          set: 'Aether Revolt',
          cost: '4',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Artificer',
          rarity: 'Common',
          effects: 'Vigilance\nWhen Aether Inspector enters the battlefield, you get (E)(E) (two energy counters).\nWhenever Aether Inspector attacks, you may pay (E)(E).  If you do, create a 1/1 colorless Servo artifact creature token.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423670&type=card',
          power: '2',
          toughness: '3'
        },
        {
          name: 'Aethergeode Miner',
          set: 'Aether Revolt',
          cost: '2',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Scout',
          rarity: 'Rare',
          effects: 'Whenever Aethergeode Miner attacks, you get (E)(E) (two energy counters).\nPay (E)(E): Exile Aethergeode Miner, then return it to the battlefield under its owner\'s control.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423671&type=card',
          power: '3',
          toughness: '1',
          flavor: 'Gremlins in the wild feed on nodules of pure aether, which are also prized by miners.'
        },
        {
          name: 'Airdrop Aeronauts',
          set: 'Aether Revolt',
          cost: '5',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Scout',
          rarity: 'Uncommon',
          effects: 'Flying\nRevolt--When Airdrop Aeronauts enters the battlefield, if a permanent you controlled left the battlefield this turn, you gain 5 life.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423672&type=card',
          power: '4',
          toughness: '3',
          flavor: '"Supplies inbound.  Keep that pressure on."'
        },
        {
          name: 'Alley Evasion',
          set: 'Aether Revolt',
          cost: '1',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Choose one -- \n\tTarget creature gets +1/+2 until end of turn.\n\tReturn target creature you control to its owner\'s hand.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423673&type=card',
          flavor: '"Sure, you know the law.  But I know the streets."'
        },
        {
          name: 'Audacious Infiltrator',
          set: 'Aether Revolt',
          cost: '2',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Rogue',
          rarity: 'Common',
          effects: 'Audacious Infiltrator can\'t be blocked by artifact creatures.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423674&type=card',
          power: '3',
          toughness: '1',
          flavor: '"This little critter can turn all of you to scrap in under thirty seconds!  Come on, who wants to be the first to go?  Try and stop me!"'
        },
        {
          name: 'Bastion Enforcer',
          set: 'Aether Revolt',
          cost: '3',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Soldier',
          rarity: 'Common',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423675&type=card',
          power: '3',
          toughness: '2',
          flavor: 'Headquartered at the Bastion of the Honorable, the Consulate\'s enforcers are charged with the impossible task of keeping the peace.'
        },
        {
          name: 'Call for Unity',
          set: 'Aether Revolt',
          cost: '5',
          color: 'White',
          supertype: 'Enchantment',
          rarity: 'Rare',
          effects: 'Revolt--At the beginning of your end step, if a permanent you controlled left the battlefield this turn, put a unity counter on Call for Unity.\nCreatures you control get +1/+1 for each unity counter on Call for Unity.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423676&type=card',
          flavor: 'The "leaking spire" stands for liberation from Consulate control.'
        },
        {
          name: 'Caught in the Brights',
          set: 'Aether Revolt',
          cost: '3',
          color: 'White',
          supertype: 'Enchantment',
          subtype: 'Aura',
          rarity: 'Common',
          effects: 'Enchant creature\nEnchanted creature can\'t attack or block.\nWhen a Vehicle you control attacks, exile enchanted creature.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423677&type=card',
          flavor: 'While hunting aether, a gremlin may ignore other stimuli, including threats to its own life.'
        },
        {
          name: 'Consulate Crackdown',
          set: 'Aether Revolt',
          cost: '5',
          color: 'White',
          supertype: 'Enchantment',
          rarity: 'Rare',
          effects: 'When Consulate Crackdown enters the battlefield, exile all artifacts your opponents control until Consulate Crackdown leaves the battlefield.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423678&type=card',
          flavor: '"The workshops are silent.  Our creations have been seized.  They have killed what made us alive." --Pia Nalaar'
        },
        {
          name: 'Conviction',
          set: 'Aether Revolt',
          cost: '2',
          color: 'White',
          supertype: 'Enchantment',
          subtype: 'Aura',
          rarity: 'Common',
          effects: 'Enchant creature\nEnchanted creature gets +1/+3.\n(W): Return Conviction to its owner\'s hand.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423679&type=card',
          flavor: '"There is no greater coward than one who believes in nothing."'
        },
        {
          name: 'Countless Gears Renegade',
          set: 'Aether Revolt',
          cost: '2',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Artificer',
          rarity: 'Common',
          effects: 'Revolt--When Countless Gears Renegade enters the battlefield, if a permanent you controlled left the battlefield this turn, create a 1/1 colorless Servo artifact creature token.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423680&type=card',
          power: '2',
          toughness: '2',
          flavor: '"Go forth and cause trouble, my little one!"'
        },
        {
          name: 'Dawnfeather Eagle',
          set: 'Aether Revolt',
          cost: '5',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Bird',
          rarity: 'Common',
          effects: 'Flying\nWhen Dawnfeather Eagle enters the battlefield, creatures you control get +1/+1 and vigilance until end of turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423681&type=card',
          power: '3',
          toughness: '3',
          flavor: '"It came to rest on the angel\'s arm, and then the weight of their gazes fell upon me." --Aeronaut\'s journal'
        },
        {
          name: 'Deadeye Harpooner',
          set: 'Aether Revolt',
          cost: '3',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Warrior',
          rarity: 'Uncommon',
          effects: 'Revolt--When Deadeye Harpooner enters the battlefield, if a permanent you controlled left the battlefield this turn, destroy target tapped creature an opponent controls.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423682&type=card',
          power: '2',
          toughness: '2',
          flavor: '"It seems there\'s even better hunting down here."'
        },
        {
          name: 'Decommission',
          set: 'Aether Revolt',
          cost: '3',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Destroy target artifact or enchantment.\nRevolt--If a permanent you controlled left the battlefield this turn, you gain 3 life.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423683&type=card',
          flavor: '"A key weakness in the design is its vulnerability to repeated, forceful blows."'
        },
        {
          name: 'Deft Dismissal',
          set: 'Aether Revolt',
          cost: '4',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Deft Dismissal deals 3 damage divided how you choose among one, two, or three target attacking or blocking creatures.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423684&type=card',
          flavor: '"With spy thopters all around, how can the consuls be so blind to Tezzeret\'s manipulations?" --Gideon Jura'
        },
        {
          name: 'Exquisite Archangel',
          set: 'Aether Revolt',
          cost: '7',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Angel',
          rarity: 'Mythic',
          effects: 'Flying\nIf you would lose the game, instead exile Exquisite Archangel and your life total becomes your starting life total.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423685&type=card',
          power: '5',
          toughness: '5',
          flavor: 'A living invention born of a grand design.'
        },
        {
          name: 'Felidar Guardian',
          set: 'Aether Revolt',
          cost: '4',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Cat Beast',
          rarity: 'Uncommon',
          effects: 'When Felidar Guardian enters the battlefield, you may exile target permanent you control, then return that card to the battlefield under its owner\'s control.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423686&type=card',
          power: '1',
          toughness: '4',
          flavor: 'The loyalty of a felidar is hard won but worth the effort.'
        },
        {
          name: 'Ghirapur Osprey',
          set: 'Aether Revolt',
          cost: '3',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Bird',
          rarity: 'Common',
          effects: 'Flying',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423687&type=card',
          power: '2',
          toughness: '2',
          flavor: 'Many airship captains keep pets that share their love of the sky.'
        },
        {
          name: 'Restoration Specialist',
          set: 'Aether Revolt',
          cost: '2',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Artificer',
          rarity: 'Uncommon',
          effects: '(W), Sacrifice Restoration Specialist: Return up to one target artifact card and up to one target enchantment card from your graveyard to your hand.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423688&type=card',
          power: '2',
          toughness: '1',
          flavor: 'Dwarves\' tools are priceless heirlooms handed down through generations.'
        },
        {
          name: 'Solemn Recruit',
          set: 'Aether Revolt',
          cost: '3',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Warrior',
          rarity: 'Rare',
          effects: 'Double strike\nRevolt--At the beginning of your end step, if a permanent you controlled left the battlefield this turn, put a +1/+1 counter on Solemn Recruit.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423689&type=card',
          power: '2',
          toughness: '2',
          flavor: '"I can no longer sit in my workshop and ignore the events outside.  My hammers strike for the people of Ghirapur."'
        },
        {
          name: 'Sram, Senior Edificer',
          set: 'Aether Revolt',
          cost: '2',
          color: 'White',
          supertype: 'Legendary Creature',
          subtype: 'Dwarf Advisor',
          rarity: 'Rare',
          effects: 'Whenever you cast an Aura, Equipment, or Vehicle spell, draw a card.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423690&type=card',
          power: '2',
          toughness: '2',
          flavor: '"As this conflict grows, it gets harder to prevent the city from breaking down.  How much longer can we keep this machinery balanced?"'
        },
        {
          name: 'Sram\'s Expertise',
          set: 'Aether Revolt',
          cost: '3',
          color: 'White',
          supertype: 'Sorcery',
          rarity: 'Rare',
          effects: 'Create three 1/1 colorless Servo artifact creature tokens.\nYou may cast a card with converted mana cost 3 or less from your hand without paying its mana cost.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423691&type=card',
          flavor: '"It\'s important to always have the right tool for the job.  This one is for picking my teeth."'
        },
        {
          name: 'Thopter Arrest',
          set: 'Aether Revolt',
          cost: '3',
          color: 'White',
          supertype: 'Enchantment',
          rarity: 'Uncommon',
          effects: 'When Thopter Arrest enters the battlefield, exile target artifact or creature an opponent controls until Thopter Arrest leaves the battlefield.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423692&type=card',
          flavor: 'The Consulate\'s eyes--unblinking, unsleeping--are everywhere.'
        },
        // {
        //   name: '',
        //   set: 'Aether Revolt',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Aether Revolt',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Aether Revolt',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Aether Revolt',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Aether Revolt',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Aether Revolt',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Aether Revolt',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Aether Revolt',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Aether Revolt',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Aether Revolt',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Aether Revolt',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Aether Revolt',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Aether Revolt',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Aether Revolt',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Aether Revolt',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
      ]);
    });
};
