exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('card-list').del()
    .then(function () {
      // Inserts seed entries
      return knex('card-list').insert([
        {
          name: 'Aerial Modification',
          set: 'Aether Revolt',
          cost: '5',
          color: 'White',
          supertype: 'Enchantment',
          subtype: 'Aura',
          rarity: 'Uncommon',
          effects: 'Enchant creature or Vehicle\nAs long as enchanted permanent is a Vehicle, it\'s a creature in addition to its other types.\nEnchanted creature gets +2/+2 and has flying.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423668&type=card'
        },
        {
          name: 'Aeronaut Admiral',
          set: 'Aether Revolt',
          cost: '4',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Human Pilot',
          rarity: 'Uncommon',
          effects: 'Flying\nVehicles you control have flying.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423669&type=card',
          power: '3',
          toughness: '1',
          flavor: 'The Consulate recruits its best pilots from the League of Aeronauts.  Many go on to command entire fleets.'
        },
        {
          name: 'Aether Inspector',
          set: 'Aether Revolt',
          cost: '4',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Artificer',
          rarity: 'Common',
          effects: 'Vigilance\nWhen Aether Inspector enters the battlefield, you get (E)(E) (two energy counters).\nWhenever Aether Inspector attacks, you may pay (E)(E).  If you do, create a 1/1 colorless Servo artifact creature token.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423670&type=card',
          power: '2',
          toughness: '3'
        },
        {
          name: 'Aethergeode Miner',
          set: 'Aether Revolt',
          cost: '2',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Scout',
          rarity: 'Rare',
          effects: 'Whenever Aethergeode Miner attacks, you get (E)(E) (two energy counters).\nPay (E)(E): Exile Aethergeode Miner, then return it to the battlefield under its owner\'s control.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423671&type=card',
          power: '3',
          toughness: '1',
          flavor: 'Gremlins in the wild feed on nodules of pure aether, which are also prized by miners.'
        },
        {
          name: 'Airdrop Aeronauts',
          set: 'Aether Revolt',
          cost: '5',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Scout',
          rarity: 'Uncommon',
          effects: 'Flying\nRevolt--When Airdrop Aeronauts enters the battlefield, if a permanent you controlled left the battlefield this turn, you gain 5 life.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423672&type=card',
          power: '4',
          toughness: '3',
          flavor: '"Supplies inbound.  Keep that pressure on."'
        },
        {
          name: 'Alley Evasion',
          set: 'Aether Revolt',
          cost: '1',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Choose one -- \n\tTarget creature gets +1/+2 until end of turn.\n\tReturn target creature you control to its owner\'s hand.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423673&type=card',
          flavor: '"Sure, you know the law.  But I know the streets."'
        },
        {
          name: 'Audacious Infiltrator',
          set: 'Aether Revolt',
          cost: '2',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Rogue',
          rarity: 'Common',
          effects: 'Audacious Infiltrator can\'t be blocked by artifact creatures.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423674&type=card',
          power: '3',
          toughness: '1',
          flavor: '"This little critter can turn all of you to scrap in under thirty seconds!  Come on, who wants to be the first to go?  Try and stop me!"'
        },
        {
          name: 'Bastion Enforcer',
          set: 'Aether Revolt',
          cost: '3',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Soldier',
          rarity: 'Common',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423675&type=card',
          power: '3',
          toughness: '2',
          flavor: 'Headquartered at the Bastion of the Honorable, the Consulate\'s enforcers are charged with the impossible task of keeping the peace.'
        },
        {
          name: 'Call for Unity',
          set: 'Aether Revolt',
          cost: '5',
          color: 'White',
          supertype: 'Enchantment',
          rarity: 'Rare',
          effects: 'Revolt--At the beginning of your end step, if a permanent you controlled left the battlefield this turn, put a unity counter on Call for Unity.\nCreatures you control get +1/+1 for each unity counter on Call for Unity.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423676&type=card',
          flavor: 'The "leaking spire" stands for liberation from Consulate control.'
        },
        {
          name: 'Caught in the Brights',
          set: 'Aether Revolt',
          cost: '3',
          color: 'White',
          supertype: 'Enchantment',
          subtype: 'Aura',
          rarity: 'Common',
          effects: 'Enchant creature\nEnchanted creature can\'t attack or block.\nWhen a Vehicle you control attacks, exile enchanted creature.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423677&type=card',
          flavor: 'While hunting aether, a gremlin may ignore other stimuli, including threats to its own life.'
        },
        {
          name: 'Consulate Crackdown',
          set: 'Aether Revolt',
          cost: '5',
          color: 'White',
          supertype: 'Enchantment',
          rarity: 'Rare',
          effects: 'When Consulate Crackdown enters the battlefield, exile all artifacts your opponents control until Consulate Crackdown leaves the battlefield.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423678&type=card',
          flavor: '"The workshops are silent.  Our creations have been seized.  They have killed what made us alive." --Pia Nalaar'
        },
        {
          name: 'Conviction',
          set: 'Aether Revolt',
          cost: '2',
          color: 'White',
          supertype: 'Enchantment',
          subtype: 'Aura',
          rarity: 'Common',
          effects: 'Enchant creature\nEnchanted creature gets +1/+3.\n(W): Return Conviction to its owner\'s hand.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423679&type=card',
          flavor: '"There is no greater coward than one who believes in nothing."'
        },
        {
          name: 'Countless Gears Renegade',
          set: 'Aether Revolt',
          cost: '2',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Artificer',
          rarity: 'Common',
          effects: 'Revolt--When Countless Gears Renegade enters the battlefield, if a permanent you controlled left the battlefield this turn, create a 1/1 colorless Servo artifact creature token.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423680&type=card',
          power: '2',
          toughness: '2',
          flavor: '"Go forth and cause trouble, my little one!"'
        },
        {
          name: 'Dawnfeather Eagle',
          set: 'Aether Revolt',
          cost: '5',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Bird',
          rarity: 'Common',
          effects: 'Flying\nWhen Dawnfeather Eagle enters the battlefield, creatures you control get +1/+1 and vigilance until end of turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423681&type=card',
          power: '3',
          toughness: '3',
          flavor: '"It came to rest on the angel\'s arm, and then the weight of their gazes fell upon me." --Aeronaut\'s journal'
        },
        {
          name: 'Deadeye Harpooner',
          set: 'Aether Revolt',
          cost: '3',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Warrior',
          rarity: 'Uncommon',
          effects: 'Revolt--When Deadeye Harpooner enters the battlefield, if a permanent you controlled left the battlefield this turn, destroy target tapped creature an opponent controls.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423682&type=card',
          power: '2',
          toughness: '2',
          flavor: '"It seems there\'s even better hunting down here."'
        },
        {
          name: 'Decommission',
          set: 'Aether Revolt',
          cost: '3',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Destroy target artifact or enchantment.\nRevolt--If a permanent you controlled left the battlefield this turn, you gain 3 life.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423683&type=card',
          flavor: '"A key weakness in the design is its vulnerability to repeated, forceful blows."'
        },
        {
          name: 'Deft Dismissal',
          set: 'Aether Revolt',
          cost: '4',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Deft Dismissal deals 3 damage divided how you choose among one, two, or three target attacking or blocking creatures.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423684&type=card',
          flavor: '"With spy thopters all around, how can the consuls be so blind to Tezzeret\'s manipulations?" --Gideon Jura'
        },
        {
          name: 'Exquisite Archangel',
          set: 'Aether Revolt',
          cost: '7',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Angel',
          rarity: 'Mythic',
          effects: 'Flying\nIf you would lose the game, instead exile Exquisite Archangel and your life total becomes your starting life total.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423685&type=card',
          power: '5',
          toughness: '5',
          flavor: 'A living invention born of a grand design.'
        },
        {
          name: 'Felidar Guardian',
          set: 'Aether Revolt',
          cost: '4',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Cat Beast',
          rarity: 'Uncommon',
          effects: 'When Felidar Guardian enters the battlefield, you may exile target permanent you control, then return that card to the battlefield under its owner\'s control.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423686&type=card',
          power: '1',
          toughness: '4',
          flavor: 'The loyalty of a felidar is hard won but worth the effort.'
        },
        {
          name: 'Ghirapur Osprey',
          set: 'Aether Revolt',
          cost: '3',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Bird',
          rarity: 'Common',
          effects: 'Flying',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423687&type=card',
          power: '2',
          toughness: '2',
          flavor: 'Many airship captains keep pets that share their love of the sky.'
        },
        {
          name: 'Restoration Specialist',
          set: 'Aether Revolt',
          cost: '2',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Artificer',
          rarity: 'Uncommon',
          effects: '(W), Sacrifice Restoration Specialist: Return up to one target artifact card and up to one target enchantment card from your graveyard to your hand.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423688&type=card',
          power: '2',
          toughness: '1',
          flavor: 'Dwarves\' tools are priceless heirlooms handed down through generations.'
        },
        {
          name: 'Solemn Recruit',
          set: 'Aether Revolt',
          cost: '3',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Warrior',
          rarity: 'Rare',
          effects: 'Double strike\nRevolt--At the beginning of your end step, if a permanent you controlled left the battlefield this turn, put a +1/+1 counter on Solemn Recruit.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423689&type=card',
          power: '2',
          toughness: '2',
          flavor: '"I can no longer sit in my workshop and ignore the events outside.  My hammers strike for the people of Ghirapur."'
        },
        {
          name: 'Sram, Senior Edificer',
          set: 'Aether Revolt',
          cost: '2',
          color: 'White',
          supertype: 'Legendary Creature',
          subtype: 'Dwarf Advisor',
          rarity: 'Rare',
          effects: 'Whenever you cast an Aura, Equipment, or Vehicle spell, draw a card.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423690&type=card',
          power: '2',
          toughness: '2',
          flavor: '"As this conflict grows, it gets harder to prevent the city from breaking down.  How much longer can we keep this machinery balanced?"'
        },
        {
          name: 'Sram\'s Expertise',
          set: 'Aether Revolt',
          cost: '3',
          color: 'White',
          supertype: 'Sorcery',
          rarity: 'Rare',
          effects: 'Create three 1/1 colorless Servo artifact creature tokens.\nYou may cast a card with converted mana cost 3 or less from your hand without paying its mana cost.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423691&type=card',
          flavor: '"It\'s important to always have the right tool for the job.  This one is for picking my teeth."'
        },
        {
          name: 'Thopter Arrest',
          set: 'Aether Revolt',
          cost: '3',
          color: 'White',
          supertype: 'Enchantment',
          rarity: 'Uncommon',
          effects: 'When Thopter Arrest enters the battlefield, exile target artifact or creature an opponent controls until Thopter Arrest leaves the battlefield.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423692&type=card',
          flavor: 'The Consulate\'s eyes--unblinking, unsleeping--are everywhere.'
        },
        {
          name: 'Aether Swooper',
          set: 'Aether Revolt',
          cost: '2',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Vedalken Artificer',
          rarity: 'Common',
          effects: 'Flying\nWhen Aether Swooper enters the battlefield, you get (E)(E) (two energy counters).\nWhenever Aether Swooper attacks, you may pay (E)(E).  If you do, create a 1/1 colorless Servo artifact creature token.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423693&type=card',
          power: '1',
          toughness: '2'
        },
        {
          name: 'Aethertide Whale',
          set: 'Aether Revolt',
          cost: '6',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Whale',
          rarity: 'Rare',
          effects: 'Flying\nWhen Aethertide Whale enters the battlefield, you get (E)(E)(E)(E)(E)(E) (six energy counters).\nPay (E)(E)(E)(E): Return Aethertide Whale to its owner\'s hand.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423694&type=card',
          power: '6',
          toughness: '4',
          flavor: '"To survive up here, I\'ve learned when to use my harpoon and when to just enjoy the view." --Kadhu, skywhaler'
        },
        {
          name: 'Baral, Chief of Compliance',
          set: 'Aether Revolt',
          cost: '2',
          color: 'Blue',
          supertype: 'Legendary Creature',
          subtype: 'Human Wizard',
          rarity: 'Rare',
          effects: 'Instant and sorcery spells you cast cost (1) less to cast.\nWhenever a spell or ability you control counters a spell, you may draw a card.  If you do, discard a card.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423695&type=card',
          power: '1',
          toughness: '3',
          flavor: '"The echo of silence is music to my ears."'
        },
        {
          name: 'Baral\'s Expertise',
          set: 'Aether Revolt',
          cost: '5',
          color: 'Blue',
          supertype: 'Sorcery',
          rarity: 'Rare',
          effects: 'Return up to three target artifacts and/or creatures to their owners\' hands.\nYou may cast a spell with converted mana cost 4 or less from your hand without paying its mana cost.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423696&type=card',
          flavor: '"Get out of my way."'
        },
        {
          name: 'Bastion Inventor',
          set: 'Aether Revolt',
          cost: '6',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Vedalken Artificer',
          rarity: 'Common',
          effects: 'Improvise (Your artifacts can help cast this spell.  Each artifact you tap after you\'re done activating mana abilities pays for (1).)\nHexproof (This creature can\'t be the target of spells or abilities your opponents control.)',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423697&type=card',
          power: '4',
          toughness: '4',
          flavor: '"This armor transcends the the limitations of mere flesh and bone."'
        },
        {
          name: 'Disallow',
          set: 'Aether Revolt',
          cost: '3',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Rare',
          effects: 'Counter target spell, activated ability, or triggered ability. (Mana abilities can\'t be targeted.)',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423698&type=card',
          flavor: '"How easily your flames are quenched." --Baral, Chief of Compliance'
        },
        {
          name: 'Dispersal Technician',
          set: 'Aether Revolt',
          cost: '5',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Vedalken Artificer',
          rarity: 'Common',
          effects: 'When Dispersal Technician enters the battlefield, you may return target artifact to its owner\'s hand.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423699&type=card',
          power: '3',
          toughness: '2',
          flavor: 'As renegade forces closed in on the Aether Spire, Consulate blockades failed one by one.'
        },
        {
          name: 'Efficient Construction',
          set: 'Aether Revolt',
          cost: '4',
          color: 'Blue',
          supertype: 'Enchantment',
          rarity: 'Uncommon',
          effects: 'Whenever you cast an artifact spell, create a 1/1 colorless Thopter artifact creature token with flying.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423700&type=card',
          flavor: 'For some of Ghirapur\'s aerowrights, building thopters is a byproduct of larger construction efforts.'
        },
        {
          name: 'Hinterland Drake',
          set: 'Aether Revolt',
          cost: '3',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Drake',
          rarity: 'Common',
          effects: 'Flying\nHinterland Drake can\'t block artifact creatures.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423701&type=card',
          power: '2',
          toughness: '3',
          flavor: '"As a kid, I dreamed of flying on those wild drakes.  They inspired me to build wings of my own." --Nadja Cloudtoucher, aerowright'
        },
        {
          name: 'Ice Over',
          set: 'Aether Revolt',
          cost: '2',
          color: 'Blue',
          supertype: 'Enchantment',
          subtype: 'Aura',
          rarity: 'Common',
          effects: 'Enchant artifact or creature\nEnchanted permanent doesn\'t untap during its controller\'s untap step.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423702&type=card',
          flavor: '"Slow the Consulate with whatever you\'ve got!" --Jasi Ganin, master siphoner'
        },
        {
          name: 'Illusionist\'s Stratagem',
          set: 'Aether Revolt',
          cost: '4',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Exile up to two target creatures you control, then return those cards to the battlefield under their owner\'s control.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423703&type=card',
          flavor: '"When everything hangs on a single moment, be sure to choose the right moment." --Jace Beleren'
        },
        {
          name: 'Leave in the Dust',
          set: 'Aether Revolt',
          cost: '4',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Return target nonland permanent to its owner\'s hand.\nDraw a card.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423704&type=card',
          flavor: 'The daredevil racers of the Derby Crows, long at odds with the Consulate, were quick to join the renegades in open revolt.'
        },
        {
          name: 'Mechanized Production',
          set: 'Aether Revolt',
          cost: '4',
          color: 'Blue',
          supertype: 'Enchantment',
          subtype: 'Aura',
          rarity: 'Mythic',
          effects: 'Enchant artifact you control\nAt the beginning of your upkeep, create a token that\'s a copy of enchanted artifact.  Then if you control eight or more artifacts with the same name as one another, you win the game.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423705&type=card',
          flavor: '"Give me eight walkers, I\'ll give you the city." --Dovin Baan'
        },
        {
          name: 'Metallic Rebuke',
          set: 'Aether Revolt',
          cost: '3',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Improvise (Your artifacts can help cast this spell.  Each artifact you tap after you\'re done activating mana abilities pays for (1).)\nCounter target spell unless its controller pays (3).',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423706&type=card',
          flavor: '"Too little, too late.  The machine is in motion." --Tezzeret'
        },
        {
          name: 'Negate',
          set: 'Aether Revolt',
          cost: '2',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Counter target noncreature spell.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423707&type=card',
          flavor: '"It is fascinating to see how the people of this plane replicate magical techniques without a natural gift.  Also frustrating." --Jace Beleren'
        },
        {
          name: 'Quicksmith Spy',
          set: 'Aether Revolt',
          cost: '4',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Human Artificer',
          rarity: 'Rare',
          effects: 'When Quicksmith Spy enters the battlefield, target artifact gets "(T): Draw a card" for as long as you control Quicksmith Spy.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423708&type=card',
          power: '2',
          toughness: '3',
          flavor: '"Let\'s just broaden its surveillance lens."'
        },
        {
          name: 'Reverse Engineer',
          set: 'Aether Revolt',
          cost: '5',
          color: 'Blue',
          supertype: 'Sorcery',
          rarity: 'Uncommon',
          effects: 'Improvise (Your artifacts can help cast this spell.  Each artifact you tap after you\'re done activating mana abilities pays for (1).)\nDraw three cards.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423709&type=card',
          flavor: 'The Hold, an illegal research facility in a derelict merchant ship, became a wellspring of renegade intelligence.'
        },
        {
          name: 'Salvage Scuttler',
          set: 'Aether Revolt',
          cost: '5',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Crab',
          rarity: 'Uncommon',
          effects: 'Whenever Salvage Scuttler attacks, return an artifact you control to its owner\'s hand.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423710&type=card',
          power: '4',
          toughness: '4',
          flavor: 'A hermit crab goes through many shells in its lifetime, and not all are natural in origin.'
        },
        {
          name: 'Shielded Aether Thief',
          set: 'Aether Revolt',
          cost: '2',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Vedalken Rogue',
          rarity: 'Uncommon',
          effects: 'Flash (You may cast this spell anytime you could cast an instant.)\nWhenever Shielded Aether Thief blocks, you get (E) (an energy counter).\n(T), Pay (E)(E)(E): Draw a card.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423711&type=card',
          power: '0',
          toughness: '4',
          flavor: 'Conflict breeds opportunity.'
        },
        {
          name: 'Shipwreck Moray',
          set: 'Aether Revolt',
          cost: '4',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Fish',
          rarity: 'Common',
          effects: 'When Shipwreck Moray enters the battlefield, you get (E)(E)(E)(E) (four energy counters).\nPay (E): Shipwreck Moray gets +2/-2 until end of turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423712&type=card',
          power: '0',
          toughness: '5',
          flavor: 'Shipwrecks do wonders for the local fauna, providing both shelter and aether.'
        },
        {
          name: 'Skyship Plunderer',
          set: 'Aether Revolt',
          cost: '2',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Human Pirate',
          rarity: 'Uncommon',
          effects: 'Flying\nWhenever Skyship Plunderer deals combat damage to a player, for each kind of counter on target permanent or player, give that permanent or player another counter of that kind.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423713&type=card',
          power: '2',
          toughness: '1',
          flavor: 'Escapes should always be daring.'
        },
        {
          name: 'Take into Custody',
          set: 'Aether Revolt',
          cost: '1',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Tap target creature.  It doesn\'t untap during its controller\'s next untap step.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423714&type=card',
          flavor: '"You can tell me what I want to know, or you can talk to the Chief of Compliance.  Why don\'t you make it easy on yourself?"'
        },
        {
          name: 'Trophy Mage',
          set: 'Aether Revolt',
          cost: '3',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Human Wizard',
          rarity: 'Uncommon',
          effects: 'When Trophy Mage enters the battlefield, you may search your library for an artifact card with converted mana cost 3, reveal it, put it into your hand, then shuffle your library.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423715&type=card',
          power: '2',
          toughness: '2',
          flavor: '"The tools of the past will help us forge the future."'
        },
        {
          name: 'Whir of Invention',
          set: 'Aether Revolt',
          cost: '4+',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Rare',
          effects: 'Improvise (Your artifacts can help cast this spell.  Each artifact you tap after you\'re done activating mana abilities pays for (1).)\nSearch your library for converted mana cost X or less, put it onto the battlefield, then shuffle your library.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423716&type=card'
        },
        {
          name: 'Wind-Kin Raiders',
          set: 'Aether Revolt',
          cost: '6',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Human Artificer',
          rarity: 'Uncommon',
          effects: 'Improvise (Your artifacts can help cast this spell.  Each artifact you tap after you\'re done activating mana abilities pays for (1).)\nFlying',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423717&type=card',
          power: '4',
          toughness: '3',
          flavor: 'Small aeronaut societies like the Wind-Kin had little to lose by siding with the renegades, and much to gain.'
        },
        {
          name: 'Aether Poisoner',
          set: 'Aether Revolt',
          cost: '2',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Human Artificer',
          rarity: 'Common',
          effects: 'Deathtouch (Any amount of damage this deals to a creature is enough to destroy it.)\nWhen Aether Poisoner enters the battlefield, you get (E)(E) (two energy counters).\nWhenever Aether Poisoner attacks, you may pay (E)(E).  If you do, create a 1/1 colorless Servo artifact creature token.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423718&type=card',
          power: '1',
          toughness: '1'
        },
        {
          name: 'Alley Strangler',
          set: 'Aether Revolt',
          cost: '3',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Aetherborn Rogue',
          rarity: 'Common',
          effects: 'Menace',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423719&type=card',
          power: '2',
          toughness: '3',
          flavor: '"You never know what day might be your last."'
        },
        {
          name: 'Battle at the Bridge',
          set: 'Aether Revolt',
          cost: '2+',
          color: 'Black',
          supertype: 'Sorcery',
          rarity: 'Rare',
          effects: 'Improvise (Your artifacts can help cast this spell.  Each artifact you tap after you\'re done activating mana abilities pays for (1).)\nTarget creature gets -X/-X until end of turn.  You gain X life.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423720&type=card',
          flavor: '"This is bigger than you.  All of you." --Tezzeret'
        },
        {
          name: 'Cruel Finality',
          set: 'Aether Revolt',
          cost: '3',
          color: 'Black',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Target creature gets -2/-2 until end of turn.  Scry 1. (Look at the top card of your library.  You may put that card on the bottom of your library.)',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423721&type=card',
          flavor: 'Bitter the bite of a demon\'s steel, and deep the abyss it opens.'
        },
        {
          name: 'Daring Demolition',
          set: 'Aether Revolt',
          cost: '4',
          color: 'Black',
          supertype: 'Sorcery',
          rarity: 'Common',
          effects: 'Destroy target creature or Vehicle.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423722&type=card',
          flavor: 'Living so close to death gives the aetherborn an unusual perspective on risk.'
        },
        {
          name: 'Defiant Salvager',
          set: 'Aether Revolt',
          cost: '3',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Aetherborn Artificer',
          rarity: 'Common',
          effects: 'Sacrifice an artifact or creature: Put a +1/+1 counter on Defiant Salvager.  Activate this ability only any time you could cast a sorcery.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423723&type=card',
          power: '2',
          toughness: '2',
          flavor: '"I didn\'t survive that crash just so I could fall to the likes of you."'
        },
        {
          name: 'Fatal Push',
          set: 'Aether Revolt',
          cost: '1',
          color: 'Black',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Destroy target creature with converted mana cost 2 or less.\nRevolt--Destroy that creature if it has converted mana cost 4 or less if a permanent you controlled left the battlefield this turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423724&type=card'
        },
        {
          name: 'Fen Hauler',
          set: 'Aether Revolt',
          cost: '7',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Insect',
          rarity: 'Common',
          effects: 'Improvise (Your artifacts can help cast this spell.  Each artifact you tap after you\'re done activating mana abilities pays for (1).)\nFen Hauler can\'t be blocked by artifact creatures.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423725&type=card',
          power: '5',
          toughness: '5',
          flavor: '"Success is found where others fear to look." --Ara, renegade smuggler'
        },
        {
          name: 'Foundry Hornet',
          set: 'Aether Revolt',
          cost: '4',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Insect',
          rarity: 'Uncommon',
          effects: 'Flying\nWhen Foundry Hornet enters the battlefield, if you control a creature with a +1/+1 counter on it, creatures your opponents control get -1/-1 until end of turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423726&type=card',
          power: '2',
          toughness: '3',
          flavor: 'Its buzzing is easily mistaken for the hum of a thopter\'s wings.'
        },
        {
          name: 'Fourth Bridge Prowler',
          set: 'Aether Revolt',
          cost: '1',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Human Rogue',
          rarity: 'Common',
          effects: 'When Fourth Bridge Prowler enters the battlefield, you may have target creature get -1/-1 until end of turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423727&type=card',
          power: '1',
          toughness: '1',
          flavor: 'Renegades run the gamut from lofty sages to petty thieves.'
        },
        {
          name: 'Gifted Aetherborn',
          set: 'Aether Revolt',
          cost: '2',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Aetherborn Vampire',
          rarity: 'Uncommon',
          effects: 'Deathtouch, lifelink',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423728&type=card',
          power: '2',
          toughness: '3',
          flavor: 'A few aetherborn have discovered a way to sustain their own existences at the cost of an insatiable hunger for the life essence of other beings.'
        },
        {
          name: 'Glint-Sleeve Siphoner',
          set: 'Aether Revolt',
          cost: '2',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Human Rogue',
          rarity: 'Rare',
          effects: 'Menace\nWhen Glint-Sleeve Siphoner enters the battlefield or attacks, you get (E) (an energy counter).\nAt the beginning of your upkeep, you may pay (E)(E).  If you do, you draw a card and you lose 1 life.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423729&type=card',
          power: '2',
          toughness: '1'
        },
        {
          name: 'Gonti\'s Machinations',
          set: 'Aether Revolt',
          cost: '1',
          color: 'Black',
          supertype: 'Enchantment',
          rarity: 'Uncommon',
          effects: 'Whenever you lose life for the first time each turn, you get (E). (You get an energy counter.  Damage causes loss of life.)\nPay (E)(E), Sacrifice Gonti\'s Machinations: Each opponent loses 3 life.  You gain life equal to the life lost this way.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423730&type=card',
          flavor: '"I am confident that all our enterprises can benefit from this little revolution."'
        },
        {
          name: 'Herald of Anguish',
          set: 'Aether Revolt',
          cost: '7',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Demon',
          rarity: 'Mythic',
          effects: 'Improvise (Your artifacts can help cast this spell.  Each artifact you tap after you\'re done activating mana abilities pays for (1).)\nFlying\nAt the beginning of your end step, each opponent discards a card.\n(1B), Sacrifice an artifact: Target creature gets -2/-2 until end of turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423731&type=card',
          power: '5',
          toughness: '5'
        },
        {
          name: 'Ironclad Revolutionary',
          set: 'Aether Revolt',
          cost: '6',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Aetherborn Artificer',
          rarity: 'Uncommon',
          effects: 'When Ironclad Revolutionary enters the battlefield, you may sacrifice an artifact.  If you do, put two +1/+1 counters on Ironclad Revolutionary and each opponent loses 2 life.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423732&type=card',
          power: '4',
          toughness: '4',
          flavor: 'As the rebellion spread, renegade ingenuity outpaced the Consulate\'s greatest fears.'
        },
        {
          name: 'Midnight Entourage',
          set: 'Aether Revolt',
          cost: '4',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Aetherborn Rogue',
          rarity: 'Rare',
          effects: 'Other Aetherborn you control get +1/+1.\nWhenever Midnight Aetherborn or another Aetherborn you control dies, you draw a card and you lose 1 life.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423733&type=card',
          power: '3',
          toughness: '3'
        },
        {
          name: 'Night Market Aeronaut',
          set: 'Aether Revolt',
          cost: '4',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Aetherborn Warrior',
          rarity: 'Common',
          effects: 'Flying\nRevolt--Night Market Aeronaut enters the battlefield with a +1/+1 counter on it if a permanent you controlled left the battlefield this turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423734&type=card',
          power: '2',
          toughness: '2',
          flavor: '"Death might come tomorrow, but today--today I am alive."'
        },
        {
          name: 'Perilous Predicament',
          set: 'Aether Revolt',
          cost: '5',
          color: 'Black',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Each opponent sacrifices an artifact creature and a nonartifact creature.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423735&type=card',
          flavor: 'Comrades in life.  Comrades in death.'
        },
        {
          name: 'Renegade\'s Getaway',
          set: 'Aether Revolt',
          cost: '3',
          color: 'Black',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Target permanent gains indestructible until end of turn.  Create a 1/1 colorless Servo artifact creature token. (Effects that say "destroy" don\'t destroy a permanent with indestructible, and if it\'s a creature, it can\'t be destroyed by damage.)',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423736&type=card',
          flavor: 'You can\'t fight what you can\'t find.'
        },
        {
          name: 'Resourceful Return',
          set: 'Aether Revolt',
          cost: '2',
          color: 'Black',
          supertype: 'Sorcery',
          rarity: 'Common',
          effects: 'Return target creature card from your graveyard to your hand.  If you control an artifact, draw a card.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423737&type=card',
          flavor: 'When the salvage team brought in the shattered gearhulk, a wave of excitement swept through the renegade foundry.'
        },
        {
          name: 'Secret Salvage',
          set: 'Aether Revolt',
          cost: '5',
          color: 'Black',
          supertype: 'Sorcery',
          rarity: 'Rare',
          effects: 'Exile target nonland card from your graveyard.  Search your library for any number of cards with the same name as that card, reveal them, and put them into your hand.  Then shuffle your library.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423738&type=card',
          flavor: 'There is no shortage of illegal salvage in Ghirapur, nor of those who are willing to profit from it.'
        },
        {
          name: 'Sly Requisitioner',
          set: 'Aether Revolt',
          cost: '5',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Human Artificer',
          rarity: 'Uncommon',
          effects: 'Improvise (Your artifacts can help cast this spell.  Each artifact you tap after you\'re done activating mana abilities pays for (1).)\nWhenever a nontoken artifact you control is put into a graveyard from the battlefield, create a 1/1 colorless Servo artifact creature token.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423739&type=card',
          power: '2',
          toughness: '2'
        },
        {
          name: 'Vengeful Rebel',
          set: 'Aether Revolt',
          cost: '3',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Aetherborn Warrior',
          rarity: 'Uncommon',
          effects: 'Revolt--When Vengeful Rebel enters the battlefield, if a permanent you controlled left the battlefield this turn, target creature an opponent controls gets -3/-3 until end of turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423740&type=card',
          power: '3',
          toughness: '2',
          flavor: 'Some aetherborn joined the rebellion for profit, others for the sake of their freedom, still others for revenge.'
        },
        {
          name: 'Yahenni, Undying Partisan',
          set: 'Aether Revolt',
          cost: '3',
          color: 'Black',
          supertype: 'Legendary Creature',
          subtype: 'Aetherborn Vampire',
          rarity: 'Rare',
          effects: 'Haste\nWhenever a creature an opponent controls dies, put a +1/+1 counter on Yahenni, Undying Partisan.\nSacrifice another creature: Yahenni, Undying Partisan gains indestructible until end of turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423741&type=card',
          power: '2',
          toughness: '2',
          flavor: '"The time for subtlety is over, darling."'
        },
        {
          name: 'Yahenni\'s Expertise',
          set: 'Aether Revolt',
          cost: '4',
          color: 'Black',
          supertype: 'Sorcery',
          rarity: 'Rare',
          effects: 'All creatures get -3/-3 until end of turn.\nYou may cast a card with converted mana cost 3 or less from your hand without paying its mana cost.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=423742&type=card',
          flavor: '"The Consulate pushed me to my limit, darling, and this is the result."'
        },
        // {
        //   name: '',
        //   set: 'Aether Revolt',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
      ]);
    });
};
