
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('card-list').del()
    .then(function () {
      // Inserts seed entries
      return knex('card-list').insert([
        {
          name: 'Act of Heroism',
          set: 'Hour of Devastation',
          cost: '2 (1W)',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Untap target creature.  It gets +2/+2 and can block an additional creature this turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Act-of-Heroism-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"On every plane, there are those who run toward danger." --Gideon Jura'
        },
        {
          name: 'Adorned Pouncer',
          set: 'Hour of Devastation',
          cost: '2 (1W)',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Cat',
          rarity: 'Rare',
          effects: 'Double strike\nEternalize (3WW) ((3WW), Exile this card from your graveyard: Create a token that\'s a copy of it, except it\'s a 4/4 black Zombie Cat with no mana cost.  Eternalize only as a sorcery.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Adorned-Pouncer-Hour-of-Devastation-Spoiler-216x302.png',
          power: '1',
          toughness: '1'
        },
        {
          name: 'Angel of Condemnation',
          set: 'Hour of Devastation',
          cost: '4 (2WW)',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Angel',
          rarity: 'Rare',
          effects: 'Flying, vigilance\n(2W), (T): Exile another target creature.  Return that card to the battlefield under its owner\'s control at the beginning of the next end step.\n(2W), (T), Exert Angel of Condemnation: Exile another target creature until Angel of Condemnation leaves the battlefield. (An exerted creature won\'t untap during your next untap step.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Angel-of-Condemnation-216x302.png',
          power: '3',
          toughness: '3'
        },
        {
          name: 'Angel of the God-Pharoah',
          set: 'Hour of Devastation',
          cost: '6 (4WW)',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Angel',
          rarity: 'Uncommon',
          effects: 'Flying\nCycling (2) ((2), Discard this card: Draw a card.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Angel-of-the-God-Pharaoh-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'The angels did not deceive.  From the start, they were clear their allegiance was to the God-Pharoah and to him alone.',
          power: '4',
          toughness: '4'
        },
        {
          name: 'Aven of Enduring Hope',
          set: 'Hour of Devastation',
          cost: '5 (4W)',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Bird Cleric',
          rarity: 'Common',
          effects: 'Flying\nWhen Aven of Enduring Hope enters the battlefield, you gain 3 life.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Aven-of-Enduring-Hope-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"This storm will calm.  We must believe that."',
          power: '3',
          toughness: '3'
        },
        {
          name: 'Crested Sunmare',
          set: 'Hour of Devastation',
          cost: '5 (3WW)',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Horse',
          rarity: 'Mythic',
          effects: 'Other Horses you control have indestructible.\nAt the beginning of each end step, if you gained life this turn, create a 5/5 white Horse creature token.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Crested-Sunmare-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"It is evidence that some pure corner of the world must still exist." --Djeru, former Tah-crop initiate',
          power: '5',
          toughness: '5'
        },
        {
          name: 'Dauntless Aven',
          set: 'Hour of Devastation',
          cost: '3 (2W)',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Bird Warrior',
          rarity: 'Common',
          effects: 'Flying\nWhenever Dauntless Aven attacks, untap target creature you control.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Dauntless-Aven-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'In the chaos brought by the new gods, swift-winged aven served as pathfinders, leading the last of the people away from the ruins of Naktamun.',
          power: '2',
          toughness: '1'
        },
        {
          name: 'Desert\'s Hold',
          set: 'Hour of Devastation',
          cost: '3 (2W)',
          color: 'White',
          supertype: 'Enchantment',
          subtype: 'Aura',
          rarity: 'Uncommon',
          effects: 'Enchant creature\nWhen Desert\'s Hold enters the battlefield, if you control a Desert or there is a Desert card in your graveyard, you gain 3 life.\nEnchanted creature can\'t attack or block, and its activated abilities can\'t be activated.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Deserts-Hold-216x302.png'
        },
        {
          name: 'Disposal Mummy',
          set: 'Hour of Devastation',
          cost: '3 (2W)',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Zombie Jackal',
          rarity: 'Common',
          effects: 'When Disposal Mummy enters the battlefield, exile target card from an opponent\'s graveyard.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Disposal-Mummy-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'Without the viziers to oversee their actions, some anointed went to extreme lengths to fulfill their directives.',
          power: '2',
          toughness: '3'
        },
        {
          name: 'Djeru, With Eyes Open',
          set: 'Hour of Devastation',
          cost: '5 (3WW)',
          color: 'White',
          supertype: 'Legendary Creature',
          subtype: 'Human Warrior',
          rarity: 'Rare',
          effects: 'Vigilance\nWhen Djeru, With Eyes Open enters the battlefield, you may search your library for a planeswalker card, reveal it, put it into your hand, then shuffle your library.\nIf a source would deal damage to a planeswalker you control, prevent 1 of that damage.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Djeru-With-Eyes-Open-Hour-of-Devastation-Spoiler-216x302.png',
          power: '4',
          toughness: '3'
        },
        {
          name: 'Djeru\'s Renunciation',
          set: 'Hour of Devastation',
          cost: '2 (1W)',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Tap up to two target creatures.\nCycling (W) ((W), Discard this card: Draw a card.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Djeru%E2%80%99s-Renunciation-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"I was promised an afterlife, not this.  Samut was right.  The God-Pharoah lied." --Djeru, former Tah-crop initiate'
        },
        {
          name: 'Dutiful Servants',
          set: 'Hour of Devastation',
          cost: '4 (3W)',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Zombie',
          rarity: 'Rare',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Dutiful-Servants-216x302.jpg',
          flavor: 'Buildings crumbled and monuments fell.  The river bled and the sky wept tears of fire.  All the while, servants silently continued their work, oblivious to it all.',
          power: '2',
          toughness: '5'
        },
        {
          name: 'Gideon\'s Defeat',
          set: 'Hour of Devastation',
          cost: '1 (W)',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Exile target white creature that\'s attacking or blocking.  If it was a Gideon planeswalker, you gain 5 life.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Gideon%E2%80%99s-Defeat-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"Gideon, how easy it must be to play the protector when you think yourself untouchable.  How wrong you are." --Nicol Bolas'
        },
        {
          name: 'God-Pharaoh\'s Faithful',
          set: 'Hour of Devastation',
          cost: '1 (W)',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Human Wizard',
          rarity: 'Common',
          effects: 'Whenever you cast a blue, black, or red spell, you gain 1 life.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/God-Pharaoh%E2%80%99s-Faithful-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"This is the final trial!  Rejoice, for the God-Pharaoh soars among us!"',
          power: '0',
          toughness: '4'
        },
        {
          name: 'Hour of Revelation',
          set: 'Hour of Devastation',
          cost: '6 (3WWW)',
          color: 'White',
          supertype: 'Sorcery',
          rarity: 'Rare',
          effects: 'Hour of Revelation costs (3) less to cast if there are ten or more nonland permanents on the battlefield.\nDestroy all nonland permanents.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Hour-of-Revelation-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'In the first moments, the gate to the afterlife opened, and the people were prostrate in the light of the God-Pharaoh.'
        },
        {
          name: 'Mummy Paramount',
          set: 'Hour of Devastation',
          cost: '2 (1W)',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Zombie',
          rarity: 'Common',
          effects: 'Whenever another Zombie enters the battlefield under your control, Mummy Paramount gets +1/+1 until end of turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Mummy-Paramount-216x302.png',
          flavor: '"It appears some mummies have begun to observe a hierarchy all their own." --Elekh, vizier of embalming',
          power: '2',
          toughness: '2'
        },
        {
          name: 'Oketra\'s Avenger',
          set: 'Hour of Devastation',
          cost: '2 (1W)',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Human Warrior',
          rarity: 'Common',
          effects: 'You may exert Oketra\'s Avenger as it attacks.  When you do, prevent all combat damage that would be dealt to it this turn. (An exerted creature won\'t untap during your next untap step.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Oketra%E2%80%99s-Avenger-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"Oketra\'s arrow is my spear, and her love my shield."',
          power: '3',
          toughness: '1'
        },
        {
          name: 'Oketra\'s Last Mercy',
          set: 'Hour of Devastation',
          cost: '3 (1WW)',
          color: 'White',
          supertype: 'Sorcery',
          rarity: 'Rare',
          effects: 'Your life total becomes your starting life total.  Lands you control don\'t untap during your next untap step.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Oketras-Last-Mercy-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'To the end, all Oketra did was for others.'
        },
        {
          name: 'Overwhelming Splendor',
          set: 'Hour of Devastation',
          cost: '8 (6WW)',
          color: 'White',
          supertype: 'Enchantment',
          subtype: 'Aura Curse',
          rarity: 'Mythic',
          effects: 'Enchant player\nCreatures enchanted player controls lose all abilities and have base power and toughness 1/1.\nEnchanted player can\'t activate abilites that aren\'t mana abilities or loyalty abilities.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Overwhelming-Splendor-Hour-of-Devastation-Spoiler-216x302.png'
        },
        {
          name: 'Sandblast',
          set: 'Hour of Devastation',
          cost: '3 (2W)',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Sandblast deals 5 damage to target attacking or blocking creature.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Sandblast-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'The sands of Amonkhet can be a boon as much as a bane.  It depends entirely on which way the wind blows.'
        },
        {
          name: 'Saving Grace',
          set: 'Hour of Devastation',
          cost: '2 (1W)',
          color: 'White',
          supertype: 'Enchantment',
          subtype: 'Aura',
          rarity: 'Uncommon',
          effects: 'Flash\hEnchant creature you control\nWhen Saving Grace enters the battlefield, all damage that would be dealt to you and permanents you control is dealt to enchanted creature instead.\nEnchanted creature gets +0/+3.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Saving-Grace-Hour-of-Devastation-Spoiler-216x302.png'
        },
        {
          name: 'Solemnity',
          set: 'Hour of Devastation',
          cost: '3 (2W)',
          color: 'White',
          supertype: 'Enchantment',
          rarity: 'Rare',
          effects: 'Players can\'t get counters.\nCounters can\'t be put on artifacts, creatures, enchantments, or land.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Solemnity-216x302.png',
          flavor: 'The arrival of the God-Pharaoh marked the betrayal of both gods and mortals.'
        },
        {
          name: 'Solitary Camel',
          set: 'Hour of Devastation',
          cost: '3 (2W)',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Camel',
          rarity: 'Common',
          effects: 'Solitary Camel has lifelink as long as you control a Desert or there is a Desert card in your graveyard. (Damage dealt by this creature also causes you to gain that much life.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Solitary-Camel-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'Deserts are inhospitable, not uninhabitable.',
          power: '3',
          toughness: '2'
        },
        {
          name: 'Steadfast Sentinel',
          set: 'Hour of Devastation',
          cost: '4 (3W)',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Human Cleric',
          rarity: 'Common',
          effects: 'Vigilance\nEternalize (4WW) ((4WW), Exile this card from your graveyard: Create a token that\'s a copy of it, except it\'s a 4/4 black Zombie Human Cleric with no mana cost.  Eternalize only as a sorcery.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Steadfast-Sentinel-Hour-of-Devastation-Spoiler-216x302.png',
          power: '2',
          toughness: '3'
        },
        {
          name: 'Steward of Solidarity',
          set: 'Hour of Devastation',
          cost: '2 (1W)',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Human Warrior',
          rarity: 'Uncommon',
          effects: '(T), Exert Steward of Solidarity: Create a 1/1 white Warrior creature token with vigilance. (An exerted creature won\t untap during your next untap step.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Steward-of-Solidarity-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'In the midst of disaster, heroic acts became almost ordinary, and ordinary warriors became heroes.',
          power: '2',
          toughness: '2'
        },
        {
          name: 'Sunscourge Champion',
          set: 'Hour of Devastation',
          cost: '3 (2W)',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Human Wizard',
          rarity: 'Uncommon',
          effects: 'When Sunscourge Champion enters the battlefield, you gain life equal to its power.\nEternalize (2WW) ((2WW), Exile this card from your graveyard: Create a token that\'s a copy of it, except it\'s a 4/4 black Zombie Human Wizard with no mana cost.  Eternalize only as a sorcery.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Sunscourge-Champion-214x302.jpg',
          power: '2',
          toughness: '3'
        },
        {
          name: 'Unconventional Tactics',
          set: 'Hour of Devastation',
          cost: '3 (2W)',
          color: 'White',
          supertype: 'Sorcery',
          rarity: 'Uncommon',
          effects: 'Target creature gets +3/+3 and gains flying until end of turn.\nWhenever a Zombie enters the battlefield under your control, you may pay (W).  If you do, return Unconventional Tactics from your graveyard to your hand.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Unconventional-Tactics-Hour-of-Devastation-Spoiler-216x302.png'
        },
        {
          name: 'Vizier of the True',
          set: 'Hour of Devastation',
          cost: '4 (3W)',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Human Cleric',
          rarity: 'Uncommon',
          effects: 'You may exert Vizier of the True as it attacks. (An exerted creature won\'t untap during your next untap step.)\nWhenever you exert a creature, tap target creature an opponent controls.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Vizier-of-the-True-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'Outnumbered, but not outmatched.',
          power: '3',
          toughness: '2'
        },
        {
          name: 'Aerial Guide',
          set: 'Hour of Devastation',
          cost: '3 (2U)',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Drake',
          rarity: 'Common',
          effects: 'Flying\nWhenever Aerial Guide attacks, another target attacking creature gains flying until end of turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Aerial-Guide-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"Kefnet taught us to turn obstacles into advantages." --Neponem, vizier of Kefnet',
          power: '2',
          toughness: '2'
        },
        {
          name: 'Aven Reedstalker',
          set: 'Hour of Devastation',
          cost: '4 (3U)',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Bird Warrior',
          rarity: 'Common',
          effects: 'Flash\nFlying',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Aven-Reedstalker-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"Our best chance against the Eternals will be tactics they\'ve never seen and styles they\'ve never trained in."',
          power: '2',
          toughness: '3'
        },
        {
          name: 'Champion of Wits',
          set: 'Hour of Devastation',
          cost: '3 (2U)',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Naga Wizard',
          rarity: 'Rare',
          effects: 'When Champion of Wits enters the battlefield, you may draw cards equal to its power.  If you do, discard two cards.\nEternalize (5UU) ((5UU), Exile this card from your graveyard: Create a token that\'s a copy of it, except it\'s a 4/4 black Zombie Naga Wizard with no mana cost.  Eternalize only as a sorcery.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Champion-of-Wits-Hour-of-Devastation-Spoiler-216x302.png'
        },
        {
          name: 'Countervailing Winds',
          set: 'Hour of Devastation',
          cost: '3 (2U)',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Counter target spell unless its controller pays (1) for each card in your graveyard.\nCycling (2) ((2), Discard this card: Draw a card.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Countervailing-Winds-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'The Eternals had long since mastered every technique taught during the trials.'
        },
        {
          name: 'Cunning Survivor',
          set: 'Hour of Devastation',
          cost: '2 (1U)',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Human Warrior',
          rarity: 'Common',
          effects: 'Whenever you cycle or discard a card, Cunning Survivor gets +1/+0 until end of turn and can\'t be blocked this turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Cunning-Survivor-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'Initiates who had been through the Trial of Knowledge learned to see everything as pieces of a larger puzzle.',
          power: '1',
          toughness: '3'
        },
        {
          name: 'Eternal of Harsh Truths',
          set: 'Hour of Devastation',
          cost: '3 (2U)',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Zombie Cleric',
          rarity: 'Uncommon',
          effects: 'Afflict 2 (Whenever this creature becomes blocked, defending player loses 2 life)\nWhenever Eternal of Harsh Truths attacks and isn\'t blocked, draw a card.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Eternal-of-Harsh-Truths-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"If creating the Eternals was Bolas\'s plan here, what is his plan for the Eternals?" --Jace Beleren',
          power: '1',
          toughness: '3'
        },
        {
          name: 'Fraying Sanity',
          set: 'Hour of Devastation',
          cost: '3 (2U)',
          color: 'Blue',
          supertype: 'Enchantment',
          subtype: 'Aura Curse',
          rarity: 'Rare',
          effects: 'Enchant player\nAt the beginning of each end step, enchanted player puts the top X cards of his or her library into his or her graveyard, where X is the number of cards put into that graveyard from anywhere this turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Fraying-Sanity-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'Those wound tightest are the first to unravel.'
        },
        {
          name: 'Hour of Eternity',
          set: 'Hour of Devastation',
          cost: '5+ (XXUUU)',
          color: 'Blue',
          supertype: 'Sorcery',
          rarity: 'Rare',
          effects: 'Exile X target creature cards from your graveyard.  For each card exiled this way, create a token that\'s a copy of that card, except it\'s a 4/4 black Zombie.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Hour-of-Eternity-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'To serve as an Eternal is the afterlife granted to the worthy.'
        },
        {
          name: 'Imaginary Threats',
          set: 'Hour of Devastation',
          cost: '4 (2UU)',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Creatures target opponent controls attack this turn if able.  During that opponent\'s next untap step, creatures he or she controls don\'t untap.\nCycling (2) ((2), Discard this card: Draw a card.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Imaginary-Threats-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'Liliana always knew Jace\'s illusions would come in handy.'
        },
        {
          name: 'Jace\'s Defeat',
          set: 'Hour of Devastation',
          cost: '2 (1U)',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Counter target blue spell.  If it was a Jace planeswalker spell, scry 2.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Jace%E2%80%99s-Defeat-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"I had hoped for more from you, Jace.  But I expected as much." --Nicol Bolas'
        },
        {
          name: 'Kefnet\'s Last Word',
          set: 'Hour of Devastation',
          cost: '4 (2UU)',
          color: 'Blue',
          supertype: 'Sorcery',
          rarity: 'Rare',
          effects: 'Gain control of target artifact, creature, or enchantment.  Lands you control don\'t untap during your next untap step.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Kefnets-Last-Word-216x302.png',
          flavor: 'In his final moments, Kefnet reached into the minds of those around him, desperate for logic within the consuming chaos.'
        },
        {
          name: 'Nimble Obstructionist',
          set: 'Hour of Devastation',
          cost: '3 (2U)',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Bird Wizard',
          rarity: 'Rare',
          effects: 'Flash\nFlying\nCycling (2U) ((2U), Discard this card: Draw a card.)\nWhen you cycle Nimble Obstructionist, counter target activated or triggered ability you don\'t control.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Nimble-Obstructionist-216x302.png',
          power: '3',
          toughness: '1'
        },
        {
          name: 'Ominous Sphinx',
          set: 'Hour of Devastation',
          cost: '5 (3UU)',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Sphinx',
          rarity: 'Uncommon',
          effects: 'Flying\nWhenever you cycle or discard a card, target creature an opponent controls gets -2/-0 until end of turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Ominous-Sphinx-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'The sphinxes began to speak only after the Second Sun aligned.  They whispered dire warnings, though no one listened.',
          power: '4',
          toughness: '4'
        },
        {
          name: 'Proven Combatant',
          set: 'Hour of Devastation',
          cost: '1 (U)',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Human Warrior',
          rarity: 'Common',
          effects: 'Eternalize (4UU) ((4UU), Exile this card from your graveyard: Create a token that\'s a copy of it, except it\'s a 4/4 black Zombie Human Warrior with no mana cost.  Eternalize only as a sorcery.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Proven-Combatant-216x302.png',
          flavor: '"It\'s not wise to keep glory waiting."',
          power: '1',
          toughness: '1'
        },
        {
          name: 'Riddleform',
          set: 'Hour of Devastation',
          cost: '2 (1U)',
          color: 'Blue',
          supertype: 'Enchantment',
          rarity: 'Uncommon',
          effects: 'Whenever you cast a noncreature spell, you may have Riddleform become a 3/3 Sphinx creature with flying in addition to its other types until end of turn.\n(2U): Scry 1.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Riddleform-Hour-of-Devastation-Spoiler-216x302.png'
        },
        {
          name: 'Seer of the Last Tomorrow',
          set: 'Hour of Devastation',
          cost: '3 (2U)',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Naga Cleric',
          rarity: 'Common',
          effects: '(U), (T), Discard a card: Target player puts the top three cards of his or her library into his or her graveyard.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Seer-of-the-Last-Tomorrow-216x302.png',
          flavor: '"The truth?  It\'s been here all along.  The Hours as we understood them are lies."',
          power: '1',
          toughness: '4'
        },
        {
          name: 'Sinuous Striker',
          set: 'Hour of Devastation',
          cost: '3 (2U)',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Naga Warrior',
          rarity: 'Uncommon',
          effects: '(U): Sinuous Striker gets +1/-1 until end of turn.\nEternalize (3UU) ((3UU), Discard a card, Exile this card from your graveyard: Create a token that\'s a copy of it, except it\'s a 4/4 black Zombie Naga Warrior with no mana cost.  Eternalize only as a sorcery.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Sinuous-Striker-216x300.jpg',
          power: '2',
          toughness: '2'
        },
        {
          name: 'Spellweaver Eternal',
          set: 'Hour of Devastation',
          cost: '2 (1U)',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Zombie Naga Wizard',
          rarity: 'Common',
          effects: 'Prowess (Whenever you cast a noncreature spell, this creature gets +1/+1 until end of turn.)\nAfflict 2 (Whenever this creature becomes blocked, defending player loses 2 life.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Spellweaver-Eternal-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"They were once our brothers and sisters." --Etha, former Rhet-crop initiate',
          power: '2',
          toughness: '1'
        },
        {
          name: 'Strategic Planning',
          set: 'Hour of Devastation',
          cost: '2 (1U)',
          color: 'Blue',
          supertype: 'Sorcery',
          rarity: 'Common',
          effects: 'Look at the top three cards of your library.  Put one into your hand and the rest into your graveyard.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Strategic-Planning1-216x302.png',
          flavor: '"Bolas remade this place in his image.  He has the advantage here.  We must approach carefully." --Jace Beleren'
        },
        {
          name: 'Striped Riverwinder',
          set: 'Hour of Devastation',
          cost: '7 (6U)',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Serpent',
          rarity: 'Common',
          effects: 'Hexproof (This creature can\'t be the target of spells or abilities your opponents control.)\nCycling (U) ((U), Discard this card: Draw a card.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Striped-Riverwinder-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'The denizens of the Luxa River woke angry on the currents of blood.',
          power: '5',
          toughness: '5'
        },
        {
          name: 'Supreme Will',
          set: 'Hour of Devastation',
          cost: '3 (2U)',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Choose one -- \n\tCounter target spell unless its controller pays (3).\n\tLook at the top four cards of your library.  Put one of them into your hand and the rest on the bottom of your library in any order.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Supreme-Will-Hour-of-Devastation-Spoiler-216x302.png'
        },
        {
          name: 'Swarm Intelligence',
          set: 'Hour of Devastation',
          cost: '7 (6U)',
          color: 'Blue',
          supertype: 'Enchantment',
          rarity: 'Rare',
          effects: 'Whenever you cast an instant or sorcery spell, you may copy that spell.  You may choose new targets for the copy.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Swarm-Intelligence-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'The Locust God\'s children were numberless, relentlessly eating away every trace of the city\'s protection.'
        },
        {
          name: 'Tragic Lesson',
          set: 'Hour of Devastation',
          cost: '3 (2U)',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Draw two cards.  Then discard a card unless you return a land you control to its owner\'s hand.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Tragic-Lesson-216x302.jpg',
          flavor: 'Though Kefnet\'s followers feverishly searched his last words for some final riddle, they only found the gurgles of a dying god.'
        },
        {
          name: 'Unesh, Criosphinx Sovereign',
          set: 'Hour of Devastation',
          cost: '6 (4UU)',
          color: 'Blue',
          supertype: 'Legendary Creature',
          subtype: 'Sphinx',
          rarity: 'Mythic',
          effects: 'Flying\nSphinx spells you cast cost (2) less to cast.\nWhenever Unesh, Criosphinx Sovereign or another Sphinx enters the battlefield under your control, reveal the top four cards of your library.  An opponent separates those cards into two piles.  Put one pile into your hand and the other into your graveyard.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Unesh-Criosphinx-Sovereign-Hour-of-Devastation-Spoiler-216x302.png',
          power: '4',
          toughness: '4'
        },
        {
          name: 'Unquenchable Thirst',
          set: 'Hour of Devastation',
          cost: '2 (1U)',
          color: 'Blue',
          supertype: 'Enchantment',
          subtype: 'Aura',
          rarity: 'Common',
          effects: 'Enchant creature\nWhen Unquenchable Thirst enters the battlefield, if you control a Desert or there is a Desert card in your graveyard, tap enchanted creature.\nEnchanted creature doesn\'t untap during its controller\'s untap step.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Unquenchable-Thirst-Hour-of-Devastation-Spoiler-216x302.png'
        },
        {
          name: 'Unsummon',
          set: 'Hour of Devastation',
          cost: '1 (U)',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Return target creature to its owner\'s hand.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Unsummon-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'Skills mastered by initiates are preserved within cartouches, so Eternals remain adept at their preferred combat styles.'
        },
        {
          name: 'Vizier of the Anointed',
          set: 'Hour of Devastation',
          cost: '4 (3U)',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Human Cleric',
          rarity: 'Uncommon',
          effects: 'When Vizier of the Anointed enters the battlefield, you may search your library for a creature card with eternalize or embalm, put that card into your graveyard, then shuffle your library.\nWhenever you activate an eternalize or embalm ability, draw a card.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Vizier-of-the-Anointed-Hour-of-Devastation-Spoiler-216x302.png',
          power: '2',
          toughness: '4'
        },
        {
          name: 'Accursed Horde',
          set: 'Hour of Devastation',
          cost: '4 (3B)',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Zombie',
          rarity: 'Uncommon',
          effects: '(1B): Target Zombie gains indestructible until end of turn. (Damage and effects that say "destroy" don\'t destroy it.  If its toughness is 0 or less, it\'s still put into its owner\'s graveyard.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Accursed-Horde-Hour-of-Devastation-Spoiler-216x302.png',
          power: '3',
          toughness: '3'
        },
        {
          name: 'Ammit Eternal',
          set: 'Hour of Devastation',
          cost: '3 (2B)',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Zombie Crocodile Demon',
          rarity: 'Rare',
          effects: 'Afflict 3 (Whenever this creature becomes blocked, defending player loses 3 life.)\nWhenever an opponent casts a spell, put a -1/-1 counter on Ammit Eternal.\nWhenever Ammit Eternal deals combat damage to a player, remove all -1/-1 counters from it.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Ammit-Eternal-Hour-of-Devastation-Spoiler-216x302.png',
          power: '5',
          toughness: '5'
        },
        {
          name: 'Apocalypse Demon',
          set: 'Hour of Devastation',
          cost: '6 (4BB)',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Demon',
          rarity: 'Rare',
          effects: 'Flying\nApocalypse Demon\'s power and toughness are each equal to the number of cards in your graveyard.\nAt the beginning of your upkeep, tap Apocalypse Demon unless you sacrifice another creature.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Apocalypse-Demon-Hour-of-Devastation-Spoiler-216x302.png',
          power: '*',
          toughness: '*'
        },
        {
          name: 'Banewhip Punisher',
          set: 'Hour of Devastation',
          cost: '3 (2B)',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Human Warrior',
          rarity: 'Uncommon',
          effects: 'When Banewhip Punisher enters the battlefield, put a -1/-1 counter on target creature.\n(B), Sacrifice Banewhip Punisher: Destroy target creature that has a -1/-1 counter on it.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Banewhip-Punisher-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"If I die, it will not be alone."',
          power: '2',
          toughness: '2'
        },
        {
          name: 'Bontu\'s Last Reckoning',
          set: 'Hour of Devastation',
          cost: '3 (1BB)',
          color: 'Black',
          supertype: 'Sorcery',
          rarity: 'Rare',
          effects: 'Destroy all creatures.  Lands you control don\'t untap during your next untap step.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Bontus-Last-Reckoning-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'To the last, Bontu wanted only to be first among the God-Pharaoh\'s disciples.'
        },
        {
          name: 'Carrion Screecher',
          set: 'Hour of Devastation',
          cost: '4 (3B)',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Zombie Bird',
          rarity: 'Common',
          effects: 'Flying',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Carrion-Screecher-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'The banished have come home to roost.',
          power: '3',
          toughness: '1'
        },
        {
          name: 'Doomfall',
          set: 'Hour of Devastation',
          cost: '3 (2B)',
          color: 'Black',
          supertype: 'Sorcery',
          rarity: 'Uncommon',
          effects: 'Choose one -- \n\tTarget opponent exiles a creature he or she controls.\n\tTarget opponent reveals his or her hand.  You choose a nonland card from it.  Exile that card.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Doomfall-216x302.png',
          flavor: '"This place has outlived its usefulness." --Nicol Bolas'
        },
        {
          name: 'Dreamstealer',
          set: 'Hour of Devastation',
          cost: '3 (2B)',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Human Wizard',
          rarity: 'Rare',
          effects: 'Menace\nWhenever Dreamstealer deals combat damage to a player, that player discards that many cards.\nEternalize (4BB) ((4BB), Exile this card from your graveyard: Create a token that\'s a copy of it, except it\'s a 4/4 black Zombie Human Wizard with no mana cost.  Eternalize only as a sorcery.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Dreamstealer-216x302.jpg',
          power: '1',
          toughness: '2'
        },
        {
          name: 'Grisly Survivor',
          set: 'Hour of Devastation',
          cost: '3 (2B)',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Minotaur Warrior',
          rarity: 'Common',
          effects: 'Whenever you cycle or discard a card, Grisly Survivor gets +2/+0 until end of turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Grisly-Survivor-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'No cartouches to earn.  No afterlife to enter.  Only the glory of a well-struck blow and the growing pile of felled enemies at her feet.',
          power: '2',
          toughness: '3'
        },
        {
          name: 'Hour of Glory',
          set: 'Hour of Devastation',
          cost: '4 (3B)',
          color: 'Black',
          supertype: 'Instant',
          rarity: 'Rare',
          effects: 'Exile target creature.  If that creature was a God, its controller reveals his or her hand and exiles from it with the same name as that creature.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Hour-of-Glory-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'The gods of the trials also faced the opportunity to prove themselves worthy.'
        },
        {
          name: 'Khenra Eternal',
          set: 'Hour of Devastation',
          cost: '2 (1B)',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Zombie Jackal Warrior',
          rarity: 'Common',
          effects: 'Afflict 1 (Whenever this creature becomes blocked, defending player loses 1 life.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Khenra-Eternal-216x302.png',
          flavor: 'For many years, servant mummies toiled in the mines to extract lazotep.  The emergence of the Eternals revealed the sacred substance\'s true purpose.',
          power: '2',
          toughness: '2'
        },
        {
          name: 'Lethal Sting',
          set: 'Hour of Devastation',
          cost: '3 (2B)',
          color: 'Black',
          supertype: 'Sorcery',
          rarity: 'Common',
          effects: 'As an additional cost to cast Lethal Sting, put a -1/-1 counter on target creature you control.\nDestroy target creature.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Lethal-Sting-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'Initiates once believed defeat was the worst fate possible--a sentiment they quickly abandoned.'
        },
        {
          name: 'Liliana\'s Defeat',
          set: 'Hour of Devastation',
          cost: '1 (B)',
          color: 'Black',
          supertype: 'Sorcery',
          rarity: 'Uncommon',
          effects: 'Destroy target black creature or black planeswalker.  If that permanent was a Liliana planeswalker, her controller loses 3 life.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Liliana%E2%80%99s-Defeat-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"All the power you have gathered for yourself, Liliana, I can take away." --Nicol Bolas'
        },
        {
          name: 'Lurching Rotbeast',
          set: 'Hour of Devastation',
          cost: '4 (3B)',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Zombie Beast',
          rarity: 'Common',
          effects: 'Cycling (B) ((B), Discard this card: Draw a card.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Lurching-Rotbeast-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'The dead that swept across Naktamun came in all shapes and sizes.',
          power: '4',
          toughness: '2'
        },
        {
          name: 'Marauding Boneslasher',
          set: 'Hour of Devastation',
          cost: '3 (2B)',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Zombie Minotaur',
          rarity: 'Common',
          effects: 'Marauding Boneslasher can\'t block unless you control another Zombie.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Marauding-Boneslasher-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'With the Hekma destroyed, the wandering dead that sought entrance to Naktamun had free rein to lay waste to the city.',
          power: '3',
          toughness: '3'
        },
        {
          name: 'Merciless Eternal',
          set: 'Hour of Devastation',
          cost: '3 (2B)',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Zombie Cleric',
          rarity: 'Uncommon',
          effects: 'Afflict 2 (Whenever this creature becomes blocked, defending player loses 2 life.)\n(2B), Discard a card: Merciless Eternal gets +2/+2 until end of turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Merciless-Eternal-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"My work here is done.  The people have done everything required of them." --Nicol Bolas',
          power: '2',
          toughness: '2'
        },
        {
          name: 'Moaning Wall',
          set: 'Hour of Devastation',
          cost: '3 (2B)',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Zombie Wall',
          rarity: 'Common',
          effects: 'Defender\nCycling (2) ((2), Discard this card: Draw a card.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Moaning-Wall-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'Before the monuments, before the first trials, before Naktamun itself, Bolas culled the plane of its adults in order to rebuild it for his own designs.',
          power: '0',
          toughness: '5'
        },
        {
          name: 'Razaketh, the Foulblooded',
          set: 'Hour of Devastation',
          cost: '8 (5BBB)',
          color: 'Black',
          supertype: 'Legendary Creature',
          subtype: 'Demon',
          rarity: 'Mythic',
          effects: 'Flying, trample\nPay 2 life, Sacrifice another creature: Search your library for a card and put that card into your hand.  Then shuffle your library.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Razaketh-the-Foulblooded-216x300.jpg',
          flavor: 'Liliana insisted on coming to Amonkhet to confront one of the two remaining demons to whom she is bound.',
          power: '8',
          toughness: '8'
        },
        {
          name: 'Razaketh\'s Rite',
          set: 'Hour of Devastation',
          cost: '5 (3BB)',
          color: 'Black',
          supertype: 'Sorcery',
          rarity: 'Uncommon',
          effects: 'Search your library for a card and put that card into your hand.  Then shuffle your library.\nCycling (B) ((B), Discard this card: Draw a card.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Razaketh%E2%80%99s-Rite-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"The blood ritual is complete.  The end approaches."'
        },
        {
          name: 'Ruin Rat',
          set: 'Hour of Devastation',
          cost: '2 (1B)',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Rat',
          rarity: 'Common',
          effects: 'Deathtouch\nWhen Ruin Rat dies, exile target card from an opponent\'s graveyard.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Ruin-Rat-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'From every shadow came the dull scratch of teeth on bones.',
          power: '1',
          toughness: '1'
        },
        {
          name: 'Scrounger of Souls',
          set: 'Hour of Devastation',
          cost: '5 (4B)',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Horror',
          rarity: 'Common',
          effects: 'Lifelink (Damage dealt by this creature also causes you to gain that much life.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Scrounger-of-Souls-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'Yell for help, and that may answer.',
          power: '3',
          toughness: '4'
        },
        {
          name: 'Torment of Hailfire',
          set: 'Hour of Devastation',
          cost: '3+ (XBB)',
          color: 'Black',
          supertype: 'Sorcery',
          rarity: 'Rare',
          effects: 'Repeat the following process X times.  Each opponent loses 3 life unless that player sacrifices a nonland permanent or discards a card.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Torment-of-Hailfire-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"Your God-Pharaoh has returned."'
        },
        {
          name: 'Torment of Scarabs',
          set: 'Hour of Devastation',
          cost: '4 (3B)',
          color: 'Black',
          supertype: 'Enchantment',
          subtype: 'Aura Curse',
          rarity: 'Uncommon',
          effects: 'Enchant player\nAt the beginning of enchanted player\'s upkeep, that player loses 3 life unless he or she sacrifices a nonland permanent or discards a card.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Torment-of-Scarabs-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'Like a carpet unrolling for their god, the scarabs poured out from the necropolis.'
        },
        {
          name: 'Torment of Venom',
          set: 'Hour of Devastation',
          cost: '4 (2BB)',
          color: 'Black',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Put three -1/-1 counters on target creature.  Its controller loses 3 life unless he or she sacrifices a nonland permanent or discards a card.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Torment-of-Venom-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'The Scorpion God\'s sting sends venom strong enough to poison blood, bone, and spirit.'
        },
        {
          name: 'Vile Manifestation',
          set: 'Hour of Devastation',
          cost: '2 (1B)',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Horror',
          rarity: 'Uncommon',
          effects: 'Vile Manifestation gets +1/+0 for each card with cycling in your graveyard.\nCycling (2) ((2), Discard this card: Draw a card.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Vile-Manifestation-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'The glyphs writhed and twisted, spewing out dark, vengeful magic.',
          power: '0',
          toughness: '4'
        },
        {
          name: 'Without Weakness',
          set: 'Hour of Devastation',
          cost: '2 (1B)',
          color: 'Black',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Target creature you control gains indestructible until end of turn.\nCycling (2) ((2), Discard this card: Draw a card.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Without-Weakness-Hour-of-Devastation-Spoiler-216x302.png'
        },
        {
          name: 'Wretched Camel',
          set: 'Hour of Devastation',
          cost: '2 (1B)',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Zombie Camel',
          rarity: 'Common',
          effects: 'When Wretched Camel dies, if you control a Desert or there is a Desert card in your graveyard, target player discards a card.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Wretched-Camel-216x302.jpg',
          flavor: 'Perfectly adapted to cross the wastes in life, they bring the wastes with them in death.',
          power: '2',
          toughness: '1'
        },
        {
          name: 'Abrade',
          set: 'Hour of Devastation',
          cost: '2 (1R)',
          color: 'Red',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Choose one --\n\tAbrade deals 3 damage to target creature.\n\tDestroy target artifact.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Abrade-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'The desert is a voracious beast, devouring both flesh and stone.'
        },
        {
          name: 'Blur of Blades',
          set: 'Hour of Devastation',
          cost: '2 (1R)',
          color: 'Red',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Put a -1/-1 counter on target creature.  Blur of Blades deals 2 damage to that creature\'s controller.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Blur-of-Blades-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'Samut battled her way through the hordes, shouting the names of those who\'d died in her crop and those she hoped yet to save.'
        },
        {
          name: 'Burning-Fist Minotaur',
          set: 'Hour of Devastation',
          cost: '2 (1R)',
          color: 'Red',
          supertype: 'Creature',
          subtype: 'Minotaur Wizard',
          rarity: 'Uncommon',
          effects: 'First strike\n(1R), Discard a card: Burning-Fist Minotaur gets +2/+0 until end of turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Burning-Fist-Minotaur-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"There is no afterlife.  Not for me, and not for you.  So think again before getting in my way."',
          power: '2',
          toughness: '1'
        },
        {
          name: 'Chandra\'s Defeat',
          set: 'Hour of Devastation',
          cost: '1 (R)',
          color: 'Red',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Chandra\'s Defeat deals 5 damage to target red creature or red planeswalker.  If that permanent is a Chandra planeswalker, you may discard a card.  If you do, draw a card.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Chandra%E2%80%99s-Defeat-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"Fire?  Is that your only trick, Chandra?" --Nicol Bolas'
        },
        {
          name: 'Chaos Maw',
          set: 'Hour of Devastation',
          cost: '7 (5RR)',
          color: 'Red',
          supertype: 'Creature',
          subtype: 'Hellion',
          rarity: 'Rare',
          effects: 'When Chaos Maw enters the battlefield, it deals 3 damage to each other creature.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Chaos-Maw-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'The food chain doesn\'t end at sandwurms.',
          power: '6',
          toughness: '6'
        },
        {
          name: 'Crash Through',
          set: 'Hour of Devastation',
          cost: '1 (R)',
          color: 'Red',
          supertype: 'Sorcery',
          rarity: 'Common',
          effects: 'Creatures you control gain trample until end of turn.\nDraw a card.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Crash-Through-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"We have to get out of the city, Djeru.  All of us!  Gather as many as you can." --Samut, former Tah-crop initiate'
        },
        {
          name: 'Defiant Khenra',
          set: 'Hour of Devastation',
          cost: '2 (1R)',
          color: 'Red',
          supertype: 'Creature',
          subtype: 'Jackal Warrior',
          rarity: 'Common',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Defiant-Khenra-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'There were those who saw the death of the gods and the city\'s collapse as a final test of worth.  Some believed it meant the God-Pharaoh had been killed.  Only a few realized they had been deceived.',
          power: '2',
          toughness: '2'
        },
        {
          name: 'Earthshaker Khenra',
          set: 'Hour of Devastation',
          cost: '2 (1R)',
          color: 'Red',
          supertype: 'Creature',
          subtype: 'Jackal Warrior',
          rarity: 'Rare',
          effects: 'Haste\nWhen Earthshaker Khenra enters the battlefield, target creature with power less than or equal to Earthshaker Khenra\'s power can\'t block this turn.\nEternalize (4RR) ((4RR), Exile this card from your graveyard: Create a token that\'s a copy of it, except it\'s a 4/4 black Zombie Jackal Warrior with no mana cost.  Eternalize only as a sorcery.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Earthshaker-Khenra-216x302.jpg',
          power: '2',
          toughness: '1'
        },
        {
          name: 'Fervent Paincaster',
          set: 'Hour of Devastation',
          cost: '3 (2R)',
          color: 'Red',
          supertype: 'Creature',
          subtype: 'Human Wizard',
          rarity: 'Uncommon',
          effects: '(T): Fervent Paincaster deals 1 damage to target player.\n(T), Exert Fervent Paincaster: It deals 1 damage to target creature. (An exerted creature won\'t untap during your next untap step.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Fervent-Paincaster-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"Everyone here is a honed fighter.  We will respond the only way we know how."',
          power: '3',
          toughness: '1'
        },
        {
          name: 'Firebrand Archer',
          set: 'Hour of Devastation',
          cost: '2 (1R)',
          color: 'Red',
          supertype: 'Creature',
          subtype: 'Human Archer',
          rarity: 'Common',
          effects: 'Whenever you cast a noncreature spell, Firebrand Archer deals 1 damage to each opponent.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Firebrand-Archer-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'A word of vengeance, and her arrows awaken in flame.',
          power: '2',
          toughness: '1'
        },
        {
          name: 'Frontline Devastator',
          set: 'Hour of Devastation',
          cost: '4 (3R)',
          color: 'Red',
          supertype: 'Creature',
          subtype: 'Zombie Minotaur Warrior',
          rarity: 'Common',
          effects: 'Afflict 2 (Whenever this creature becomes blocked, defending player loses 2 life.)\n(1R): Frontline Devastator gets +1/+0 until end of turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Frontline-Devastator-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'The God-Pharaoh\'s benevolence concealed the factory he created to produce an army of Eternals.',
          power: '3',
          toughness: '3'
        },
        {
          name: 'Gilded Cerodon',
          set: 'Hour of Devastation',
          cost: '5 (4R)',
          color: 'Red',
          supertype: 'Creature',
          subtype: 'Beast',
          rarity: 'Common',
          effects: 'Whenever Gilded Cerodon attacks, if you control a Desert or there is a Desert card in your graveyard, target creature can\'t block this turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Gilded-Cerodon-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'The plating on its horns is a token of honor from Hazoret, who favors creatures with great hearts.',
          power: '4',
          toughness: '4'
        },
        {
          name: 'Granitic Titan',
          set: 'Hour of Devastation',
          cost: '6 (4RR)',
          color: 'Red',
          supertype: 'Creature',
          subtype: 'Elemental',
          rarity: 'Common',
          effects: 'Menace\nCycling (2) ((2), Discard this card: Draw a card.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Granitic-Titan-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"That one\'s not mine.  Run!" --Nissa Revane',
          power: '5',
          toughness: '4'
        },
        {
          name: 'Hazoret\'s Undying Fury',
          set: 'Hour of Devastation',
          cost: '6 (4RR)',
          color: 'Red',
          supertype: 'Sorcery',
          rarity: 'Rare',
          effects: 'Shuffle your library, then exile the top four cards.  You may cast any number of nonland cards with converted mana cost 5 or less from among them without paying their mana costs.  Lands you control don\'t untap during your next untap step.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Hazoret%E2%80%99s-Undying-Fury-Hour-of-Devastation-Spoiler-216x302.png'
        },
        {
          name: 'Hour of Devastation',
          set: 'Hour of Devastation',
          cost: '5 (3RR)',
          color: 'Red',
          supertype: 'Sorcery',
          rarity: 'Rare',
          effects: 'All creatures lose indestructible until end of turn.  Hour of Devastation deals 5 damage to each creature and each non-Bolas planeswalker.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Hour-of-Devastation-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"Everything here exists or perishes at my whim.  Including you, Gatewatch." --Nicol Bolas'
        },
        {
          name: 'Imminent Doom',
          set: 'Hour of Devastation',
          cost: '3 (2R)',
          color: 'Red',
          supertype: 'Enchantment',
          rarity: 'Rare',
          effects: 'Imminent Doom enters the battlefield with a doom counter on it.\nWhenever you cast a spell with converted mana cost equal to the number of doom counters on Imminent Doom, Imminent Doom deals that much damage to target creature or player.  Then put a doom counter on Imminent Doom.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Imminent-Doom-Hour-of-Devastation-Spoiler-216x302.png'
        },
        {
          name: 'Inferno Jet',
          set: 'Hour of Devastation',
          cost: '6 (5R)',
          color: 'Red',
          supertype: 'Sorcery',
          rarity: 'Uncommon',
          effects: 'Inferno Jet deals 6 damage to target opponent.\nCycling (2) ((2), Discard this card: Draw a card.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Inferno-Jet-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"When the whole world is crazy, it\'s important to find something you can rely on."'
        },
        {
          name: 'Khenra Scrapper',
          set: 'Hour of Devastation',
          cost: '3 (2R)',
          color: 'Red',
          supertype: 'Creature',
          subtype: 'Jackal Warrior',
          rarity: 'Common',
          effects: 'Menace\nYou may exert Khenra Scrapper as it attacks.  When you do, it gets +2/+0 until end of turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Khenra-Scrapper-216x302.png',
          flavor: '"There is no tomorrow, so hold nothing back."',
          power: '2',
          toughness: '3'
        },
        {
          name: 'Kindled Fury',
          set: 'Hour of Devastation',
          cost: '1 (R)',
          color: 'Red',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Target creature gets +1/+0 and gains first strike until end of turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Kindled-Fury-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'The minotaur stared at the Eternal bearing down on him--the embodiment of deadly skill he had aspired to become.'
        },
        {
          name: 'Magmaroth',
          set: 'Hour of Devastation',
          cost: '4 (3R)',
          color: 'Red',
          supertype: 'Creature',
          subtype: 'Elemental',
          rarity: 'Uncommon',
          effects: 'At the beginning of your upkeep, put a -1/-1 counter on Magmaroth.\nWhenever you cast a noncreature spell, remove a -1/-1 counter from Magmaroth.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Magmaroth-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'Sand into glass and flesh into ash--such are the markers of its domain.',
          power: '5',
          toughness: '5'
        },
        {
          name: 'Manticore Eternal',
          set: 'Hour of Devastation',
          cost: '5 (3RR)',
          color: 'Red',
          supertype: 'Creature',
          subtype: 'Zombie Manticore',
          rarity: 'Uncommon',
          effects: 'Afflict 3 (Whenever this creature becomes blocked, defending player loses 3 life.)\nManticore Eternal attacks each combat if able.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Manticore-Eternal-216x302.jpg',
          flavor: 'While most Eternals were initiates who completed the trials, Bolas had plans for some of Amonkhet\'s other denizens.',
          power: '5',
          toughness: '4'
        },
        {
          name: 'Neheb, the Eternal',
          set: 'Hour of Devastation',
          cost: '5 (3RR)',
          color: 'Red',
          supertype: 'Legendary Creature',
          subtype: 'Zombie Minotaur Warrior',
          rarity: 'Mythic',
          effects: 'Afflict 3 (Whenever this creature becomes blocked, defending player loses 3 life.)\nAt the beginning of your postcombat main phase, add (R) to your mana pool for each 1 life your opponents have lost this turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Neheb-the-Eternal-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"This is what glory looks like." --Nicol Bolas',
          power: '4',
          toughness: '6'
        },
        {
          name: 'Open Fire',
          set: 'Hour of Devastation',
          cost: '3 (2R)',
          color: 'Red',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Open Fire deals 3 damage to target creature or player.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Open-Fire-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'Some khenra archers fashion their arrows with a personal touch.'
        },
        {
          name: 'Puncturing Blow',
          set: 'Hour of Devastation',
          cost: '4 (2RR)',
          color: 'Red',
          supertype: 'Sorcery',
          rarity: 'Common',
          effects: 'Puncturing Blow deals 5 damage to target creature.  If that creature would die this turn, exile it instead.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Puncturing-Blow-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"Neither the false God-Pharaoh nor his bugs will decide our fate." --Samut, former Tah-crop initiate'
        },
        {
          name: 'Sand Strangler',
          set: 'Hour of Devastation',
          cost: '4 (3R)',
          color: 'Red',
          supertype: 'Creature',
          subtype: 'Beast',
          rarity: 'Uncommon',
          effects: 'When Sand Strangler enters the battlefield, if you control a Desert or there is a Desert card in your graveyard, you may have Sand Strangler deal 3 damage to target creature.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Sand-Strangler-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'The bombardment of sand disorients, chokes, and ultimately tenderizes its prey.',
          power: '3',
          toughness: '3'
        },
        {
          name: 'Thorned Moloch',
          set: 'Hour of Devastation',
          cost: '3 (2R)',
          color: 'Red',
          supertype: 'Creature',
          subtype: 'Lizard',
          rarity: 'Common',
          effects: 'Prowess (Whenever you cast a noncreature spell, this creature gets +1/+1 until end of turn.)\nThorned Moloch has first strike as long as it\'s attacking.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Thorned-Moloch-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'Those who fled the destruction of the city stumbled into the territory of their prickly neighbors.',
          power: '2',
          toughness: '2'
        },
        {
          name: 'Wildfire Eternal',
          set: 'Hour of Devastation',
          cost: '4 (3R)',
          color: 'Red',
          supertype: 'Creature',
          subtype: 'Zombie Jackal Cleric',
          rarity: 'Rare',
          effects: 'Afflict 4 (Whenever this creature becomes blocked, defending player loses 4 life.)\nWhenever Wildfire Eternal attacks and isn\'t blocked, you may cast an instant or sorcery card from your hand without paying its mana cost.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Wildfire-Eternal-Hour-of-Devastation-Spoiler-216x302.png',
          power: '1',
          toughness: '4'
        },
        {
          name: 'Ambuscade',
          set: 'Hour of Devastation',
          cost: '3 (2G)',
          color: 'Green',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Target creature you control gets +1/+0 until end of turn.  It deals damage equal to its power to target creature an opponent controls.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Ambuscade-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"Spent a lifetime learning from predators.  Picked up a few tricks."'
        },
        {
          name: 'Beneath the Sands',
          set: 'Hour of Devastation',
          cost: '3 (2G)',
          color: 'Green',
          supertype: 'Sorcery',
          rarity: 'Common',
          effects: 'Search your library for a basic land card, put it onto the battlefield tapped, then shuffle your library.\nCycling (2) ((2), Discard this card: Draw a card.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Beneath-the-Sands-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'Though buried and muffled, nature\'s whisper still called to Nissa.'
        },
        {
          name: 'Bitterbow Sharpshooters',
          set: 'Hour of Devastation',
          cost: '5 (4G)',
          color: 'Green',
          supertype: 'Creature',
          subtype: 'Jackal Archer',
          rarity: 'Common',
          effects: 'Vigilance, reach',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Bitterbow-Sharpshooters-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"Remember, brother, the eyes are always vulnerable."\n"I never forgot."',
          power: '4',
          toughness: '4'
        },
        {
          name: 'Devotee of Strength',
          set: 'Hour of Devastation',
          cost: '3 (2G)',
          color: 'Green',
          supertype: 'Creature',
          subtype: 'Naga Wizard',
          rarity: 'Uncommon',
          effects: '(4G): Target creature gets +2/+2 until end of turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Devotee-of-Strength-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'When Rhonas fell, his followers stirred with newfound strength--a final gift from a god they thought indomitable.',
          power: '3',
          toughness: '2'
        },
        {
          name: 'Dune Diviner',
          set: 'Hour of Devastation',
          cost: '3 (2G)',
          color: 'Green',
          supertype: 'Creature',
          subtype: 'Naga Cleric',
          rarity: 'Uncommon',
          effects: '(1), Tap an untapped Desert you control: You gain 1 life.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Dune-Diviner-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'The desert had once been a place of endless horror.  It was now the last refuge as the city of Naktamun fell.',
          power: '2',
          toughness: '3'
        },
        {
          name: 'Feral Prowler',
          set: 'Hour of Devastation',
          cost: '2 (1G)',
          color: 'Green',
          supertype: 'Creature',
          subtype: 'Cat',
          rarity: 'Common',
          effects: 'When Feral Prowler dies, draw a card.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Feral-Prowler-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'Once favored companions, many cats were left to fend for themselves.',
          power: '1',
          toughness: '3'
        },
        {
          name: 'Frilled Sandwalla',
          set: 'Hour of Devastation',
          cost: '1 (G)',
          color: 'Green',
          supertype: 'Creature',
          subtype: 'Lizard',
          rarity: 'Common',
          effects: '(1G): Frilled Sandwalla gets +2/+2 until end of turn.  Activate this ability only once each turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Frilled-Sandwalla-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'It basks atop the rubble of Rhonas\'s monument, which still pulses with latent power.',
          power: '1',
          toughness: '1'
        },
        {
          name: 'Gift of Strength',
          set: 'Hour of Devastation',
          cost: '2 (1G)',
          color: 'Green',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Target creature gets +3/+3 and gains reach until end of turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Gift-of-Strength-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"What greater testament can there be to Rhonas\'s lessons?"'
        },
        {
          name: 'Harrier Naga',
          set: 'Hour of Devastation',
          cost: '3 (2G)',
          color: 'Green',
          supertype: 'Creature',
          subtype: 'Naga Warrior',
          rarity: 'Common',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Harrier-Naga-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'She trusts that the potent poisons of her darts will reach the enemy before the enemy reaches her.',
          power: '3',
          toughness: '3'
        },
        {
          name: 'Hope Tender',
          set: 'Hour of Devastation',
          cost: '2 (1G)',
          color: 'Green',
          supertype: 'Creature',
          subtype: 'Human Druid',
          rarity: 'Uncommon',
          effects: '(1), (T): Untap target land.\n(1), (T), Exert Hope Tender: Untap two target lands. (An exerted creature won\'t untap during your next untap step.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Hope-Tender-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'Some refused to leave their shattered homes, vowing to rebuild at any cost.',
          power: '2',
          toughness: '2'
        },
        {
          name: 'Hour of Promise',
          set: 'Hour of Devastation',
          cost: '5 (4G)',
          color: 'Green',
          supertype: 'Sorcery',
          rarity: 'Rare',
          effects: 'Search your library for up to two land cards, put them onto the battlefield tapped, then shuffle your library.  Then if you control three or more Deserts, create two 2/2 black Zombie creature tokens.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Hour-of-Promise-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'With the Hekma breached and its protection removed, the deserts swept in.'
        },
        {
          name: 'Life Goes On',
          set: 'Hour of Devastation',
          cost: '1 (G)',
          color: 'Green',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'You gain 4 life.  If a creature died this turn, you gain 8 life instead.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Life-Goes-On-216x302.jpg',
          flavor: '"If you believe the God-Pharaoh tests you, charge with me to prove yourself.  If you believe he betrayed us all, join with me to fight for tomorrow!" --Samut, former Tah-crop initiate'
        },
        {
          name: 'Majestic Myriarch',
          set: 'Hour of Devastation',
          cost: '5 (4G)',
          color: 'Green',
          supertype: 'Creature',
          subtype: 'Chimera',
          rarity: 'Mythic',
          effects: 'Majestic Myriarch\'s power and toughness are each equal to twice the number of creatures you control.\nAt the beginning of each combat, if you control a creature with flying,  Majestic Myriarch gains flying until end of turn.  The same is true for first strike, double strike, deathtouch, haste, hexproof, indestructible, lifelink, menace, reach, trample, and vigilance.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Majestic-Myriarch-Hour-of-Devastation-Spoiler-216x302.png',
          power: '*',
          toughness: '*'
        },
        {
          name: 'Nissa\'s Defeat',
          set: 'Hour of Devastation',
          cost: '3 (2G)',
          color: 'Green',
          supertype: 'Sorcery',
          rarity: 'Uncommon',
          effects: 'Destroy target Forest, green enchantment, or green planeswalker.  If that permanent is a Nissa planeswalker, draw a card.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Nissa%E2%80%99s-Defeat-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"The soul of this world is gone, Nissa, and I would gladly kill it again." --Nicol Bolas'
        },
        {
          name: 'Oasis Ritualist',
          set: 'Hour of Devastation',
          cost: '4 (3G)',
          color: 'Green',
          supertype: 'Creature',
          subtype: 'Naga Druid',
          rarity: 'Common',
          effects: '(T): Add one mana of any color to your mana pool.\n(T), Exert Oasis Ritualist: Add two mana of any one color to your mana pool. (An exerted creature won\'t untap during your next untap step.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Oasis-Ritualist-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"It\'s only the end if we allow it."',
          power: '2',
          toughness: '4'
        },
        {
          name: 'Overcome',
          set: 'Hour of Devastation',
          cost: '5 (3GG)',
          color: 'Green',
          supertype: 'Sorcery',
          rarity: 'Uncommon',
          effects: 'Creatures you control get +2/+2 and gain trample until end of turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Overcome-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"Forward!  Until the horizon is ours!" --Khemses, charioteer'
        },
        {
          name: 'Pride Sovereign',
          set: 'Hour of Devastation',
          cost: '3 (2G)',
          color: 'Green',
          supertype: 'Creature',
          subtype: 'Cat',
          rarity: 'Rare',
          effects: 'Pride Sovereign gets +1/+1 for each other Cat you control.\n(W), (T), Exert Pride Sovereign: Create two 1/1 white Cat creature tokens with lifelink. (An exerted creature won\'t untap during your next untap step/)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Pride-Sovereign-216x302.jpg',
          power: '2',
          toughness: '2'
        },
        {
          name: 'Quarry Beetle',
          set: 'Hour of Devastation',
          cost: '5 (4G)',
          color: 'Green',
          supertype: 'Creature',
          subtype: 'Insect',
          rarity: 'Uncommon',
          effects: 'When Quarry Beetle enters the battlefield, you may return target land card from your graveyard to the battlefield.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Quarry-Beetle-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"The ruin of the past is the topsoil of the future." --Sokar, former Nef-crop initiate',
          power: '4',
          toughness: '5'
        },
        {
          name: 'Rampaging Hippo',
          set: 'Hour of Devastation',
          cost: '6 (4GG)',
          color: 'Green',
          supertype: 'Creature',
          subtype: 'Hippo',
          rarity: 'Common',
          effects: 'Trample\nCycling (2) ((2), Discard this card: Draw a card.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Rampaging-Hippo-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"Respect is earned through deeds--or the capacity to bite someone in half." --Sana, former Ahn-crop initiate',
          power: '5',
          toughness: '6'
        },
        {
          name: 'Ramunap Excavator',
          set: 'Hour of Devastation',
          cost: '3 (2G)',
          color: 'Green',
          supertype: 'Creature',
          subtype: 'Naga Cleric',
          rarity: 'Rare',
          effects: 'You may play land cards from your graveyard.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Ramunap-Excavator-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"This world was once so much more than the confines of Naktamun."',
          power: '2',
          toughness: '3'
        },
        {
          name: 'Ramunap Hydra',
          set: 'Hour of Devastation',
          cost: '4 (3G)',
          color: 'Green',
          supertype: 'Creature',
          subtype: 'Snake Hydra',
          rarity: 'Rare',
          effects: 'Vigilance, reach, trample\nRamunap Hydra gets +1/+1 as long as you control a Desert.\nRamunap Hydra gets +1/+1 as long as there is a Desert card in your graveyard.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Ramunap-Hydra-Hour-of-Devastation-Spoiler-216x302.png',
          power: '3',
          toughness: '3'
        },
        {
          name: 'Resilient Khenra',
          set: 'Hour of Devastation',
          cost: '2 (1G)',
          color: 'Green',
          supertype: 'Creature',
          subtype: 'Jackal Wizard',
          rarity: 'Rare',
          effects: 'When Resilient Khenra enters the battlefield, you may have target creature get +X/+X until end of turn, where X is Resilient Khenra\'s power.\nEternalize (4GG) ((4GG), Exile this card from your graveyard: Create a token that\'s a copy of it, except it\'s a 4/4 black Zombie Jackal Wizard with no mana cost.  Eternalize only as a sorcery.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Resilient-Khenra-216x302.png',
          power: '2',
          toughness: '2'
        },
        {
          name: 'Rhonas\'s Last Stand',
          set: 'Hour of Devastation',
          cost: '2 (GG)',
          color: 'Green',
          supertype: 'Sorcery',
          rarity: 'Rare',
          effects: 'Create a 5/4 green Snake creature token.  Lands you control don\'t untap during your next untap step.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Rhonass-Last-Stand-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'Rhonas continued to fight until his last breath and even beyond.'
        },
        {
          name: 'Rhonas\'s Stalwart',
          set: 'Hour of Devastation',
          cost: '2 (1G)',
          color: 'Green',
          supertype: 'Creature',
          subtype: 'Human Warrior',
          rarity: 'Common',
          effects: 'You may exert Rhonas\'s Stalwart as it attacks.  When you do, it gets +1/+1 until end of turn and can\'t be blocked by creatures with power 2 or less this turn. (An exerted creature won\'t untap during your next untap step.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Rhonass-Stalwart-216x302.jpg',
          flavor: '"Give me some room."',
          power: '2',
          toughness: '2'
        },
        {
          name: 'Sidewinder Naga',
          set: 'Hour of Devastation',
          cost: '3 (2G)',
          color: 'Green',
          supertype: 'Creature',
          subtype: 'Naga Warrior',
          rarity: 'Common',
          effects: 'As long as you control a Desert or there is a Desert card in your graveyard, Sidewinder Naga gets +1/+0 and has trample.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Sidewinder-Naga-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"Those who embrace the harsh land rather than fight it find they have a powerful ally." --Nissa Revane',
          power: '3',
          toughness: '2'
        },
        {
          name: 'Sifter Wurm',
          set: 'Hour of Devastation',
          cost: '7 (5GG)',
          color: 'Green',
          supertype: 'Creature',
          subtype: 'Wurm',
          rarity: 'Uncommon',
          effects: 'Trample\nWhen Sifter Wurm enters the battlefield, scry 3, then reveal the top card of your library.  You gain life equal to that card\'s converted mana cost.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Sifter-Wurm-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"Rhonas\'s monument belongs to the wurms now.  Look elsewhere for refuge." --Arnun, vizier of the menagerie',
          power: '7',
          toughness: '7'
        },
        {
          name: 'Tenacious Hunter',
          set: 'Hour of Devastation',
          cost: '4 (2GG)',
          color: 'Green',
          supertype: 'Creature',
          subtype: 'Crocodile',
          rarity: 'Uncommon',
          effects: 'As long as a creature has a -1/-1 counter on it, Tenacious Hunter has vigilance and deathtouch.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Tenacious-Hunter-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'The crocodiles of the Broken Lands, long used to feeding on undead flesh, eagerly flooded into Naktamun for a taste of something fresher.',
          power: '4',
          toughness: '4'
        },
        {
          name: 'Uncage the Menagerie',
          set: 'Hour of Devastation',
          cost: '3+ (XGG)',
          color: 'Green',
          supertype: 'Sorcery',
          rarity: 'Mythic',
          effects: 'Search your library for X creature cards with different names that each have converted mana cost X, reveal them, put them into your hand, then shuffle your library.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Uncage-the-Menagerie-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'The destruction of Rhonas\'s monument released his collection upon the city.'
        },
      ]);
    });
};
