
exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('card-list').del()
    .then(function () {
      // Inserts seed entries
      return knex('card-list').insert([
        {
          name: 'Act of Heroism',
          set: 'Hour of Devastation',
          cost: '2 (1W)',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Untap target creature.  It gets +2/+2 and can block an additional creature this turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Act-of-Heroism-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"On every plane, there are those who run toward danger." --Gideon Jura'
        },
        {
          name: 'Adorned Pouncer',
          set: 'Hour of Devastation',
          cost: '2 (1W)',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Cat',
          rarity: 'Rare',
          effects: 'Double strike\nEternalize (3WW) ((3WW), Exile this card from your graveyard: Create a token that\'s a copy of it, except it\'s a 4/4 black Zombie Cat with no mana cost.  Eternalize only as a sorcery.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Adorned-Pouncer-Hour-of-Devastation-Spoiler-216x302.png',
          power: '1',
          toughness: '1'
        },
        {
          name: 'Angel of Condemnation',
          set: 'Hour of Devastation',
          cost: '4 (2WW)',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Angel',
          rarity: 'Rare',
          effects: 'Flying, vigilance\n(2W), (T): Exile another target creature.  Return that card to the battlefield under its owner\'s control at the beginning of the next end step.\n(2W), (T), Exert Angel of Condemnation: Exile another target creature until Angel of Condemnation leaves the battlefield. (An exerted creature won\'t untap during your next untap step.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Angel-of-Condemnation-216x302.png',
          power: '3',
          toughness: '3'
        },
        {
          name: 'Angel of the God-Pharoah',
          set: 'Hour of Devastation',
          cost: '6 (4WW)',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Angel',
          rarity: 'Uncommon',
          effects: 'Flying\nCycling (2) ((2), Discard this card: Draw a card.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Angel-of-the-God-Pharaoh-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'The angels did not deceive.  From the start, they were clear their allegiance was to the God-Pharoah and to him alone.',
          power: '4',
          toughness: '4'
        },
        {
          name: 'Aven of Enduring Hope',
          set: 'Hour of Devastation',
          cost: '5 (4W)',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Bird Cleric',
          rarity: 'Common',
          effects: 'Flying\nWhen Aven of Enduring Hope enters the battlefield, you gain 3 life.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Aven-of-Enduring-Hope-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"This storm will calm.  We must believe that."',
          power: '3',
          toughness: '3'
        },
        {
          name: 'Crested Sunmare',
          set: 'Hour of Devastation',
          cost: '5 (3WW)',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Horse',
          rarity: 'Mythic',
          effects: 'Other Horses you control have indestructible.\nAt the beginning of each end step, if you gained life this turn, create a 5/5 white Horse creature token.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Crested-Sunmare-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"It is evidence that some pure corner of the world must still exist." --Djeru, former Tah-crop initiate',
          power: '5',
          toughness: '5'
        },
        {
          name: 'Dauntless Aven',
          set: 'Hour of Devastation',
          cost: '3 (2W)',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Bird Warrior',
          rarity: 'Common',
          effects: 'Flying\nWhenever Dauntless Aven attacks, untap target creature you control.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Dauntless-Aven-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'In the chaos brought by the new gods, swift-winged aven served as pathfinders, leading the last of the people away from the ruins of Naktamun.',
          power: '2',
          toughness: '1'
        },
        {
          name: 'Desert\'s Hold',
          set: 'Hour of Devastation',
          cost: '3 (2W)',
          color: 'White',
          supertype: 'Enchantment',
          subtype: 'Aura',
          rarity: 'Uncommon',
          effects: 'Enchant creature\nWhen Desert\'s Hold enters the battlefield, if you control a Desert or there is a Desert card in your graveyard, you gain 3 life.\nEnchanted creature can\'t attack or block, and its activated abilities can\'t be activated.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Deserts-Hold-216x302.png'
        },
        {
          name: 'Disposal Mummy',
          set: 'Hour of Devastation',
          cost: '3 (2W)',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Zombie Jackal',
          rarity: 'Common',
          effects: 'When Disposal Mummy enters the battlefield, exile target card from an opponent\'s graveyard.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Disposal-Mummy-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'Without the viziers to oversee their actions, some anointed went to extreme lengths to fulfill their directives.',
          power: '2',
          toughness: '3'
        },
        {
          name: 'Djeru, With Eyes Open',
          set: 'Hour of Devastation',
          cost: '5 (3WW)',
          color: 'White',
          supertype: 'Legendary Creature',
          subtype: 'Human Warrior',
          rarity: 'Rare',
          effects: 'Vigilance\nWhen Djeru, With Eyes Open enters the battlefield, you may search your library for a planeswalker card, reveal it, put it into your hand, then shuffle your library.\nIf a source would deal damage to a planeswalker you control, prevent 1 of that damage.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Djeru-With-Eyes-Open-Hour-of-Devastation-Spoiler-216x302.png',
          power: '4',
          toughness: '3'
        },
        {
          name: 'Djeru\'s Renunciation',
          set: 'Hour of Devastation',
          cost: '2 (1W)',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Tap up to two target creatures.\nCycling (W) ((W), Discard this card: Draw a card.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Djeru%E2%80%99s-Renunciation-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"I was promised an afterlife, not this.  Samut was right.  The God-Pharoah lied." --Djeru, former Tah-crop initiate'
        },
        {
          name: 'Dutiful Servants',
          set: 'Hour of Devastation',
          cost: '4 (3W)',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Zombie',
          rarity: 'Rare',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Dutiful-Servants-216x302.jpg',
          flavor: 'Buildings crumbled and monuments fell.  The river bled and the sky wept tears of fire.  All the while, servants silently continued their work, oblivious to it all.',
          power: '2',
          toughness: '5'
        },
        {
          name: 'Gideon\'s Defeat',
          set: 'Hour of Devastation',
          cost: '1 (W)',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Exile target white creature that\'s attacking or blocking.  If it was a Gideon planeswalker, you gain 5 life.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Gideon%E2%80%99s-Defeat-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"Gideon, how easy it must be to play the protector when you think yourself untouchable.  How wrong you are." --Nicol Bolas'
        },
        {
          name: 'God-Pharaoh\'s Faithful',
          set: 'Hour of Devastation',
          cost: '1 (W)',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Human Wizard',
          rarity: 'Common',
          effects: 'Whenever you cast a blue, black, or red spell, you gain 1 life.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/God-Pharaoh%E2%80%99s-Faithful-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"This is the final trial!  Rejoice, for the God-Pharaoh soars among us!"',
          power: '0',
          toughness: '4'
        },
        {
          name: 'Hour of Revelation',
          set: 'Hour of Devastation',
          cost: '6 (3WWW)',
          color: 'White',
          supertype: 'Sorcery',
          rarity: 'Rare',
          effects: 'Hour of Revelation costs (3) less to cast if there are ten or more nonland permanents on the battlefield.\nDestroy all nonland permanents.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Hour-of-Revelation-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'In the first moments, the gate to the afterlife opened, and the people were prostrate in the light of the God-Pharaoh.'
        },
        {
          name: 'Mummy Paramount',
          set: 'Hour of Devastation',
          cost: '2 (1W)',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Zombie',
          rarity: 'Common',
          effects: 'Whenever another Zombie enters the battlefield under your control, Mummy Paramount gets +1/+1 until end of turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Mummy-Paramount-216x302.png',
          flavor: '"It appears some mummies have begun to observe a hierarchy all their own." --Elekh, vizier of embalming',
          power: '2',
          toughness: '2'
        },
        {
          name: 'Oketra\'s Avenger',
          set: 'Hour of Devastation',
          cost: '2 (1W)',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Human Warrior',
          rarity: 'Common',
          effects: 'You may exert Oketra\'s Avenger as it attacks.  When you do, prevent all combat damage that would be dealt to it this turn. (An exerted creature won\'t untap during your next untap step.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Oketra%E2%80%99s-Avenger-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"Oketra\'s arrow is my spear, and her love my shield."',
          power: '3',
          toughness: '1'
        },
        {
          name: 'Oketra\'s Last Mercy',
          set: 'Hour of Devastation',
          cost: '3 (1WW)',
          color: 'White',
          supertype: 'Sorcery',
          rarity: 'Rare',
          effects: 'Your life total becomes your starting life total.  Lands you control don\'t untap during your next untap step.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Oketras-Last-Mercy-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'To the end, all Oketra did was for others.'
        },
        {
          name: 'Overwhelming Splendor',
          set: 'Hour of Devastation',
          cost: '8 (6WW)',
          color: 'White',
          supertype: 'Enchantment',
          subtype: 'Aura Curse',
          rarity: 'Mythic',
          effects: 'Enchant player\nCreatures enchanted player controls lose all abilities and have base power and toughness 1/1.\nEnchanted player can\'t activate abilites that aren\'t mana abilities or loyalty abilities.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Overwhelming-Splendor-Hour-of-Devastation-Spoiler-216x302.png'
        },
        {
          name: 'Sandblast',
          set: 'Hour of Devastation',
          cost: '3 (2W)',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Sandblast deals 5 damage to target attacking or blocking creature.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Sandblast-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'The sands of Amonkhet can be a boon as much as a bane.  It depends entirely on which way the wind blows.'
        },
        {
          name: 'Saving Grace',
          set: 'Hour of Devastation',
          cost: '2 (1W)',
          color: 'White',
          supertype: 'Enchantment',
          subtype: 'Aura',
          rarity: 'Uncommon',
          effects: 'Flash\hEnchant creature you control\nWhen Saving Grace enters the battlefield, all damage that would be dealt to you and permanents you control is dealt to enchanted creature instead.\nEnchanted creature gets +0/+3.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Saving-Grace-Hour-of-Devastation-Spoiler-216x302.png'
        },
        {
          name: 'Solemnity',
          set: 'Hour of Devastation',
          cost: '3 (2W)',
          color: 'White',
          supertype: 'Enchantment',
          rarity: 'Rare',
          effects: 'Players can\'t get counters.\nCounters can\'t be put on artifacts, creatures, enchantments, or land.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Solemnity-216x302.png',
          flavor: 'The arrival of the God-Pharaoh marked the betrayal of both gods and mortals.'
        },
        {
          name: 'Solitary Camel',
          set: 'Hour of Devastation',
          cost: '3 (2W)',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Camel',
          rarity: 'Common',
          effects: 'Solitary Camel has lifelink as long as you control a Desert or there is a Desert card in your graveyard. (Damage dealt by this creature also causes you to gain that much life.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Solitary-Camel-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'Deserts are inhospitable, not uninhabitable.',
          power: '3',
          toughness: '2'
        },
        {
          name: 'Steadfast Sentinel',
          set: 'Hour of Devastation',
          cost: '4 (3W)',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Human Cleric',
          rarity: 'Common',
          effects: 'Vigilance\nEternalize (4WW) ((4WW), Exile this card from your graveyard: Create a token that\'s a copy of it, except it\'s a 4/4 black Zombie Human Cleric with no mana cost.  Eternalize only as a sorcery.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Steadfast-Sentinel-Hour-of-Devastation-Spoiler-216x302.png',
          power: '2',
          toughness: '3'
        },
        {
          name: 'Steward of Solidarity',
          set: 'Hour of Devastation',
          cost: '2 (1W)',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Human Warrior',
          rarity: 'Uncommon',
          effects: '(T), Exert Steward of Solidarity: Create a 1/1 white Warrior creature token with vigilance. (An exerted creature won\t untap during your next untap step.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Steward-of-Solidarity-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'In the midst of disaster, heroic acts became almost ordinary, and ordinary warriors became heroes.',
          power: '2',
          toughness: '2'
        },
        {
          name: 'Sunscourge Champion',
          set: 'Hour of Devastation',
          cost: '3 (2W)',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Human Wizard',
          rarity: 'Uncommon',
          effects: 'When Sunscourge Champion enters the battlefield, you gain life equal to its power.\nEternalize (2WW) ((2WW), Exile this card from your graveyard: Create a token that\'s a copy of it, except it\'s a 4/4 black Zombie Human Wizard with no mana cost.  Eternalize only as a sorcery.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Sunscourge-Champion-214x302.jpg',
          power: '2',
          toughness: '3'
        },
        {
          name: 'Unconventional Tactics',
          set: 'Hour of Devastation',
          cost: '3 (2W)',
          color: 'White',
          supertype: 'Sorcery',
          rarity: 'Uncommon',
          effects: 'Target creature gets +3/+3 and gains flying until end of turn.\nWhenever a Zombie enters the battlefield under your control, you may pay (W).  If you do, return Unconventional Tactics from your graveyard to your hand.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Unconventional-Tactics-Hour-of-Devastation-Spoiler-216x302.png'
        },
        {
          name: 'Vizier of the True',
          set: 'Hour of Devastation',
          cost: '4 (3W)',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Human Cleric',
          rarity: 'Uncommon',
          effects: 'You may exert Vizier of the True as it attacks. (An exerted creature won\'t untap during your next untap step.)\nWhenever you exert a creature, tap target creature an opponent controls.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Vizier-of-the-True-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'Outnumbered, but not outmatched.',
          power: '3',
          toughness: '2'
        },
        {
          name: 'Aerial Guide',
          set: 'Hour of Devastation',
          cost: '3 (2U)',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Drake',
          rarity: 'Common',
          effects: 'Flying\nWhenever Aerial Guide attacks, another target attacking creature gains flying until end of turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Aerial-Guide-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"Kefnet taught us to turn obstacles into advantages." --Neponem, vizier of Kefnet',
          power: '2',
          toughness: '2'
        },
        {
          name: 'Aven Reedstalker',
          set: 'Hour of Devastation',
          cost: '4 (3U)',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Bird Warrior',
          rarity: 'Common',
          effects: 'Flash\nFlying',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Aven-Reedstalker-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"Our best chance against the Eternals will be tactics they\'ve never seen and styles they\'ve never trained in."',
          power: '2',
          toughness: '3'
        },
        {
          name: 'Champion of Wits',
          set: 'Hour of Devastation',
          cost: '3 (2U)',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Naga Wizard',
          rarity: 'Rare',
          effects: 'When Champion of Wits enters the battlefield, you may draw cards equal to its power.  If you do, discard two cards.\nEternalize (5UU) ((5UU), Exile this card from your graveyard: Create a token that\'s a copy of it, except it\'s a 4/4 black Zombie Naga Wizard with no mana cost.  Eternalize only as a sorcery.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Champion-of-Wits-Hour-of-Devastation-Spoiler-216x302.png'
        },
        {
          name: 'Countervailing Winds',
          set: 'Hour of Devastation',
          cost: '3 (2U)',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Counter target spell unless its controller pays (1) for each card in your graveyard.\nCycling (2) ((2), Discard this card: Draw a card.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Countervailing-Winds-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'The Eternals had long since mastered every technique taught during the trials.'
        },
        {
          name: 'Cunning Survivor',
          set: 'Hour of Devastation',
          cost: '2 (1U)',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Human Warrior',
          rarity: 'Common',
          effects: 'Whenever you cycle or discard a card, Cunning Survivor gets +1/+0 until end of turn and can\'t be blocked this turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Cunning-Survivor-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'Initiates who had been through the Trial of Knowledge learned to see everything as pieces of a larger puzzle.',
          power: '1',
          toughness: '3'
        },
        {
          name: 'Eternal of Harsh Truths',
          set: 'Hour of Devastation',
          cost: '3 (2U)',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Zombie Cleric',
          rarity: 'Uncommon',
          effects: 'Afflict 2 (Whenever this creature becomes blocked, defending player loses 2 life)\nWhenever Eternal of Harsh Truths attacks and isn\'t blocked, draw a card.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Eternal-of-Harsh-Truths-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"If creating the Eternals was Bolas\'s plan here, what is his plan for the Eternals?" --Jace Beleren',
          power: '1',
          toughness: '3'
        },
        {
          name: 'Fraying Sanity',
          set: 'Hour of Devastation',
          cost: '3 (2U)',
          color: 'Blue',
          supertype: 'Enchantment',
          subtype: 'Aura Curse',
          rarity: 'Rare',
          effects: 'Enchant player\nAt the beginning of each end step, enchanted player puts the top X cards of his or her library into his or her graveyard, where X is the number of cards put into that graveyard from anywhere this turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Fraying-Sanity-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'Those wound tightest are the first to unravel.'
        },
        {
          name: 'Hour of Eternity',
          set: 'Hour of Devastation',
          cost: '5+ (XXUUU)',
          color: 'Blue',
          supertype: 'Sorcery',
          rarity: 'Rare',
          effects: 'Exile X target creature cards from your graveyard.  For each card exiled this way, create a token that\'s a copy of that card, except it\'s a 4/4 black Zombie.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Hour-of-Eternity-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'To serve as an Eternal is the afterlife granted to the worthy.'
        },
        {
          name: 'Imaginary Threats',
          set: 'Hour of Devastation',
          cost: '4 (2UU)',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Creatures target opponent controls attack this turn if able.  During that opponent\'s next untap step, creatures he or she controls don\'t untap.\nCycling (2) ((2), Discard this card: Draw a card.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Imaginary-Threats-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'Liliana always knew Jace\'s illusions would come in handy.'
        },
        {
          name: 'Jace\'s Defeat',
          set: 'Hour of Devastation',
          cost: '2 (1U)',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Counter target blue spell.  If it was a Jace planeswalker spell, scry 2.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Jace%E2%80%99s-Defeat-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"I had hoped for more from you, Jace.  But I expected as much." --Nicol Bolas'
        },
        {
          name: 'Kefnet\'s Last Word',
          set: 'Hour of Devastation',
          cost: '4 (2UU)',
          color: 'Blue',
          supertype: 'Sorcery',
          rarity: 'Rare',
          effects: 'Gain control of target artifact, creature, or enchantment.  Lands you control don\'t untap during your next untap step.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Kefnets-Last-Word-216x302.png',
          flavor: 'In his final moments, Kefnet reached into the minds of those around him, desperate for logic within the consuming chaos.'
        },
        {
          name: 'Nimble Obstructionist',
          set: 'Hour of Devastation',
          cost: '3 (2U)',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Bird Wizard',
          rarity: 'Rare',
          effects: 'Flash\nFlying\nCycling (2U) ((2U), Discard this card: Draw a card.)\nWhen you cycle Nimble Obstructionist, counter target activated or triggered ability you don\'t control.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Nimble-Obstructionist-216x302.png',
          power: '3',
          toughness: '1'
        },
        {
          name: 'Ominous Sphinx',
          set: 'Hour of Devastation',
          cost: '5 (3UU)',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Sphinx',
          rarity: 'Uncommon',
          effects: 'Flying\nWhenever you cycle or discard a card, target creature an opponent controls gets -2/-0 until end of turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Ominous-Sphinx-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'The sphinxes began to speak only after the Second Sun aligned.  They whispered dire warnings, though no one listened.',
          power: '4',
          toughness: '4'
        },
        {
          name: 'Proven Combatant',
          set: 'Hour of Devastation',
          cost: '1 (U)',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Human Warrior',
          rarity: 'Common',
          effects: 'Eternalize (4UU) ((4UU), Exile this card from your graveyard: Create a token that\'s a copy of it, except it\'s a 4/4 black Zombie Human Warrior with no mana cost.  Eternalize only as a sorcery.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Proven-Combatant-216x302.png',
          flavor: '"It\'s not wise to keep glory waiting."',
          power: '1',
          toughness: '1'
        },
        {
          name: 'Riddleform',
          set: 'Hour of Devastation',
          cost: '2 (1U)',
          color: 'Blue',
          supertype: 'Enchantment',
          rarity: 'Uncommon',
          effects: 'Whenever you cast a noncreature spell, you may have Riddleform become a 3/3 Sphinx creature with flying in addition to its other types until end of turn.\n(2U): Scry 1.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Riddleform-Hour-of-Devastation-Spoiler-216x302.png'
        },
        {
          name: 'Seer of the Last Tomorrow',
          set: 'Hour of Devastation',
          cost: '3 (2U)',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Naga Cleric',
          rarity: 'Common',
          effects: '(U), (T), Discard a card: Target player puts the top three cards of his or her library into his or her graveyard.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Seer-of-the-Last-Tomorrow-216x302.png',
          flavor: '"The truth?  It\'s been here all along.  The Hours as we understood them are lies."',
          power: '1',
          toughness: '4'
        },
        {
          name: 'Sinuous Striker',
          set: 'Hour of Devastation',
          cost: '3 (2U)',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Naga Warrior',
          rarity: 'Uncommon',
          effects: '(U): Sinuous Striker gets +1/-1 until end of turn.\nEternalize (3UU) ((3UU), Discard a card, Exile this card from your graveyard: Create a token that\'s a copy of it, except it\'s a 4/4 black Zombie Naga Warrior with no mana cost.  Eternalize only as a sorcery.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Sinuous-Striker-216x300.jpg',
          power: '2',
          toughness: '2'
        },
        {
          name: 'Spellweaver Eternal',
          set: 'Hour of Devastation',
          cost: '2 (1U)',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Zombie Naga Wizard',
          rarity: 'Common',
          effects: 'Prowess (Whenever you cast a noncreature spell, this creature gets +1/+1 until end of turn.)\nAfflict 2 (Whenever this creature becomes blocked, defending player loses 2 life.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Spellweaver-Eternal-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: '"They were once our brothers and sisters." --Etha, former Rhet-crop initiate',
          power: '2',
          toughness: '1'
        },
        {
          name: 'Strategic Planning',
          set: 'Hour of Devastation',
          cost: '2 (1U)',
          color: 'Blue',
          supertype: 'Sorcery',
          rarity: 'Common',
          effects: 'Look at the top three cards of your library.  Put one into your hand and the rest into your graveyard.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Strategic-Planning1-216x302.png',
          flavor: '"Bolas remade this place in his image.  He has the advantage here.  We must approach carefully." --Jace Beleren'
        },
        {
          name: 'Striped Riverwinder',
          set: 'Hour of Devastation',
          cost: '7 (6U)',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Serpent',
          rarity: 'Common',
          effects: 'Hexproof (This creature can\'t be the target of spells or abilities your opponents control.)\nCycling (U) ((U), Discard this card: Draw a card.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Striped-Riverwinder-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'The denizens of the Luxa River woke angry on the currents of blood.',
          power: '5',
          toughness: '5'
        },
        {
          name: 'Supreme Will',
          set: 'Hour of Devastation',
          cost: '3 (2U)',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Choose one -- \nCounter target spell unless its controller pays (3).\nLook at the top four cards of your library.  Put one of them into your hand and the rest on the bottom of your library in any order.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Supreme-Will-Hour-of-Devastation-Spoiler-216x302.png'
        },
        {
          name: 'Swarm Intelligence',
          set: 'Hour of Devastation',
          cost: '7 (6U)',
          color: 'Blue',
          supertype: 'Enchantment',
          rarity: 'Rare',
          effects: 'Whenever you cast an instant or sorcery spell, you may copy that spell.  You may choose new targets for the copy.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Swarm-Intelligence-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'The Locust God\'s children were numberless, relentlessly eating away every trace of the city\'s protection.'
        },
        {
          name: 'Tragic Lesson',
          set: 'Hour of Devastation',
          cost: '3 (2U)',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Draw two cards.  Then discard a card unless you return a land you control to its owner\'s hand.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Tragic-Lesson-216x302.jpg',
          flavor: 'Though Kefnet\'s followers feverishly searched his last words for some final riddle, they only found the gurgles of a dying god.'
        },
        {
          name: 'Unesh, Criosphinx Sovereign',
          set: 'Hour of Devastation',
          cost: '6 (4UU)',
          color: 'Blue',
          supertype: 'Legendary Creature',
          subtype: 'Sphinx',
          rarity: 'Mythic',
          effects: 'Flying\nSphinx spells you cast cost (2) less to cast.\nWhenever Unesh, Criosphinx Sovereign or another Sphinx enters the battlefield under your control, reveal the top four cards of your library.  An opponent separates those cards into two piles.  Put one pile into your hand and the other into your graveyard.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Unesh-Criosphinx-Sovereign-Hour-of-Devastation-Spoiler-216x302.png',
          power: '4',
          toughness: '4'
        },
        {
          name: 'Unquenchable Thirst',
          set: 'Hour of Devastation',
          cost: '2 (1U)',
          color: 'Blue',
          supertype: 'Enchantment',
          subtype: 'Aura',
          rarity: 'Common',
          effects: 'Enchant creature\nWhen Unquenchable Thirst enters the battlefield, if you control a Desert or there is a Desert card in your graveyard, tap enchanted creature.\nEnchanted creature doesn\'t untap during its controller\'s untap step.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Unquenchable-Thirst-Hour-of-Devastation-Spoiler-216x302.png'
        },
        {
          name: 'Unsummon',
          set: 'Hour of Devastation',
          cost: '1 (U)',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Return target creature to its owner\'s hand.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Unsummon-Hour-of-Devastation-Spoiler-216x302.png',
          flavor: 'Skills mastered by initiates are preserved within cartouches, so Eternals remain adept at their preferred combat styles.'
        },
        {
          name: 'Vizier of the Anointed',
          set: 'Hour of Devastation',
          cost: '4 (3U)',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Human Cleric',
          rarity: 'Uncommon',
          effects: 'When Vizier of the Anointed enters the battlefield, you may search your library for a creature card with eternalize or embalm, put that card into your graveyard, then shuffle your library.\nWhenever you activate an eternalize or embalm ability, draw a card.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Vizier-of-the-Anointed-Hour-of-Devastation-Spoiler-216x302.png',
          power: '2',
          toughness: '4'
        },
        {
          name: '',
          set: 'Hour of Devastation',
          cost: '',
          color: '',
          supertype: '',
          subtype: '',
          rarity: '',
          effects: '',
          art: '',
          flavor: '',
          power: '',
          toughness: '',
          loyalty: ''
        },
        {
          name: '',
          set: 'Hour of Devastation',
          cost: '',
          color: '',
          supertype: '',
          subtype: '',
          rarity: '',
          effects: '',
          art: '',
          flavor: '',
          power: '',
          toughness: '',
          loyalty: ''
        },
        {
          name: '',
          set: 'Hour of Devastation',
          cost: '',
          color: '',
          supertype: '',
          subtype: '',
          rarity: '',
          effects: '',
          art: '',
          flavor: '',
          power: '',
          toughness: '',
          loyalty: ''
        },
        {
          name: '',
          set: 'Hour of Devastation',
          cost: '',
          color: '',
          supertype: '',
          subtype: '',
          rarity: '',
          effects: '',
          art: '',
          flavor: '',
          power: '',
          toughness: '',
          loyalty: ''
        },
        {
          name: '',
          set: 'Hour of Devastation',
          cost: '',
          color: '',
          supertype: '',
          subtype: '',
          rarity: '',
          effects: '',
          art: '',
          flavor: '',
          power: '',
          toughness: '',
          loyalty: ''
        },
        {
          name: '',
          set: 'Hour of Devastation',
          cost: '',
          color: '',
          supertype: '',
          subtype: '',
          rarity: '',
          effects: '',
          art: '',
          flavor: '',
          power: '',
          toughness: '',
          loyalty: ''
        },
        {
          name: '',
          set: 'Hour of Devastation',
          cost: '',
          color: '',
          supertype: '',
          subtype: '',
          rarity: '',
          effects: '',
          art: '',
          flavor: '',
          power: '',
          toughness: '',
          loyalty: ''
        },
        {
          name: '',
          set: 'Hour of Devastation',
          cost: '',
          color: '',
          supertype: '',
          subtype: '',
          rarity: '',
          effects: '',
          art: '',
          flavor: '',
          power: '',
          toughness: '',
          loyalty: ''
        },
      ]);
    });
};
