exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('Card_List').del()
  .then(function () {
    // Inserts seed entries
    return knex('Card_List').insert([
      {
        name: 'Abu Jafar',
        set: 'Arabian Nights',
        cost: '1',
        color: 'White',
        supertype: 'Summon Leper',
        effects: 'If this creature dies from combat damage, destroy all creatures blocking or blocked by it.  They cannot be regenerated.',
        power: '0',
        toughness: '1',
        art: 'http://mythicspoiler.com/arn/cards/abujafar.jpg'
      },
      {
        name: 'Army of Allah',
        set: 'Arabian Nights',
        cost: '3',
        color: 'White',
        supertype: 'Instant',
        effects: 'Attacking creatures get +2/+0 until end of turn.',
        flavor: '"On the day of victory, no one is tired."\n--Arab proverb',
        art: 'http://mythicspoiler.com/arn/cards/armyofallah.jpg'
      },
      {
        name: 'Camel',
        set: 'Arabian Nights',
        cost: '1',
        color: 'White',
        supertype: 'Summon Camel',
        effects: 'Bands\nPrevent all damage dealt to this creature and all creatures in its band from Deserts.',
        flavor: 'Everyone knew Walid was a pious man, for he had been blessed with many sons, many jewels, and a great many camels.',
        power: '0',
        toughness: '1',
        art: 'http://mythicspoiler.com/arn/cards/camel.jpg'
      },
      {
        name: 'Eye for an Eye',
        set: 'Arabian Nights',
        cost: '2',
        color: 'White',
        supertype: 'Instant',
        effects: 'Can only be cast after you have received damage from any source.\nEye for an Eye deals damage equal to the damage dealt by the chosen source.  Any damage prevented from that source is not prevented from Eye for an Eye.',
        art: 'http://mythicspoiler.com/arn/cards/eyeforaneye.jpg'
      },
      {
        name: 'Jihad',
        set: 'Arabian Nights',
        cost: '3',
        color: 'White',
        supertype: 'Enchantment',
        effects: 'When Jihad enters the battlefield, choose a color.\nAs long as an opponent controls a permanent of the chosen color, all white creatures get +2/+1.  If an opponent has no permanents of the chosen color, sacrifice Jihad.',
        art: 'http://mythicspoiler.com/arn/cards/jihad.jpg'
      },
      {
        name: 'King Suleiman',
        set: 'Arabian Nights',
        cost: '2',
        color: 'White',
        supertype: 'Summon King',
        effects: '{T}: Destroy target Djinn or Efreet.',
        flavor: '"We made tempestuous winds obedient to Solomon... And many of the devils We also made obedient to him."\n--The Qur\'an, 21:81',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/arn/cards/kingsuleiman.jpg'
      },
      {
        name: 'Moorish Cavalry',
        set: 'Arabian Nights',
        cost: '4',
        color: 'White',
        supertype: 'Summon Cavalry',
        effects: 'Trample',
        flavor: 'Members of the elite Moorish Cavalry are very particular about their mounts, choosing only those whose bloodlines have been pure for generations.',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/arn/cards/moorishcavalry.jpg'
      },
      {
        name: 'Piety',
        set: 'Arabian Nights',
        cost: '3',
        color: 'White',
        supertype: 'Instant',
        effects: 'Defending creatures get +0/+3 until end of turn.',
        flavor: '"Whoever obeys God and His Prophet, fears God and does his duty to Him, will surely find success."\n--The Qur\'an, 24:52',
        art: 'http://mythicspoiler.com/arn/cards/piety.jpg'
      },
      {
        name: 'Repentant Blacksmith',
        set: 'Arabian Nights',
        cost: '2',
        color: 'White',
        supertype: 'Summon Smith',
        effects: 'Protection from red',
        flavor: '"For my confession they burned me with fire\nAnd found that I was for endurance made."\n--The Arabian Nights, translated by Haddawy',
        power: '1',
        toughness: '2',
        art: 'http://mythicspoiler.com/arn/cards/repentantblacksmith.jpg'
      },
      {
        name: 'Shahrazad',
        set: 'Arabian Nights',
        cost: '2',
        color: 'White',
        supertype: 'Sorcery',
        effects: 'Players must leave game in progress and use remaining cards in their libraries as decks for a subgame of Magic.  When that subgame is over, players shuffle those cards back into their libraries and return to the game in progress.  The loser of the subgame subtracts their life total by half, rounding down.',
        art: 'http://mythicspoiler.com/arn/cards/shahrazad.jpg'
      },
      {
        name: 'War Elephant',
        set: 'Arabian Nights',
        cost: '4',
        color: 'White',
        supertype: 'Summon Elephant',
        effects: 'Trample, bands',
        flavor: '"When elephants fight, it is the grass that suffers."\n--Kikuyu proverb',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/arn/cards/warelephant.jpg'
      },
      {
        name: 'Dandan',
        set: 'Arabian Nights',
        cost: '2',
        color: 'Blue',
        supertype: 'Summon Dandan',
        effects: 'Dandan can\'t attack unless an opponent controls an Island.\nIf you have no Islands in play, sacrifice Dandan.',
        power: '4',
        toughness: '1',
        art: 'http://mythicspoiler.com/arn/cards/dandan.jpg'
      },
      {
        name: 'Fishliver Oil',
        set: 'Arabian Nights',
        cost: '2',
        color: 'Blue',
        supertype: 'Enchant Creature',
        effects: 'Enchanted creature has islandwalk.',
        flavor: '"Then the maiden bade him cast off his robes and cover his body with fishliver oil, that he might safely follow her into the sea."',
        art: 'http://mythicspoiler.com/arn/cards/fishliveroil.jpg'
      },
      {
        name: 'Flying Men',
        set: 'Arabian Nights',
        cost: '1',
        color: 'Blue',
        supertype: 'Summon Flying Men',
        effects: 'Flying',
        flavor: '"Saffiyah clapped her hands, and twenty flying men appeared at her side, each well trained in the art of combat."',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/arn/cards/flyingmen.jpg'
      },
      {
        name: 'Giant Tortoise',
        set: 'Arabian Nights',
        cost: '2',
        color: 'Blue',
        supertype: 'Summon Tortoise',
        effects: 'Giant Tortoise gets +0/+3 as long as it\'s untapped.',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/arn/cards/gianttortoise.jpg'
      },
      {
        name: 'Island Fish Jasconius',
        set: 'Arabian Nights',
        cost: '4',
        color: 'Blue',
        supertype: 'Summon Island Fish',
        effects: 'You must pay {UUU} during your untap step to untap this creature.\nThis creature can\'t attack unless an opponent controls an Island.\nIf you have no Islands in play, sacrifice Island Fish.',
        power: '6',
        toughness: '8',
        art: 'http://mythicspoiler.com/arn/cards/islandfishjasconius.jpg'
      },
      {
        name: 'Merchant Ship',
        set: 'Arabian Nights',
        cost: '1',
        color: 'Blue',
        supertype: 'Summon Ship',
        effects: 'If Merchant Ship attacks and is not blocked, you gain 2 life.\nMerchant Ship can\'t attack unless an opponent controls an Island.\nIf you have no Islands in play, sacrifice Merchant Ship.',
        power: '0',
        toughness: '2',
        art: 'http://mythicspoiler.com/arn/cards/merchantship.jpg'
      },
      {
        name: 'Old Man of the Sea',
        set: 'Arabian Nights',
        cost: '3',
        color: 'Blue',
        supertype: 'Summon Marid',
        effects: '{T}: Gain control of target creature with power less than or equal to Old Man of the Sea\'s power.  You lose control of that creature if Old Man of the Sea becomes untapped or if that creature\'s power becomes greater than the Old Man\'s.\nYou may choose not to untap Old Man of the Sea during your untap step.',
        power: '2',
        toughness: '3',
        art: 'http://mythicspoiler.com/arn/cards/oldmanofthesea.jpg'
      },
      {
        name: 'Serendib Djinn',
        set: 'Arabian Nights',
        cost: '4',
        color: 'Blue',
        supertype: 'Summon Djinn',
        effects: 'Flying\nAt the beginning of your upkeep, sacrifice a land.  If an Island is sacrificed this way, Serendib Djinn deals 3 damage to you.  If you can\'t sacrifice a land, sacrifice Serendib Djinn instead.',
        power: '5',
        toughness: '6',
        art: 'http://mythicspoiler.com/arn/cards/serendibdjinn.jpg'
      },
      {
        name: 'Serendib Efreet',
        set: 'Arabian Nights',
        cost: '3',
        color: 'Blue',
        supertype: 'Summon Efreet',
        effects: 'Flying\nAt the beginning of your upkeep, Serendib Efreet deals 1 damage to you.',
        power: '3',
        toughness: '4',
        art: 'http://mythicspoiler.com/arn/cards/serendibefreet.jpg'
      },
      {
        name: 'Sindbad',
        set: 'Arabian Nights',
        cost: '2',
        color: 'Blue',
        supertype: 'Summon Sindbad',
        effects: '{T}: Draw a card.  If that card is not a land, discard a card.',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/arn/cards/sindbad.jpg'
      },
      {
        name: 'Unstable Mutation',
        set: 'Arabian Nights',
        cost: '1',
        color: 'Blue',
        supertype: 'Enchant Creature',
        effects: 'Enchanted creature gets +3/+3.\nAt the beginning of your upkeep, put a -1/-1 counter on enchanted creature.',
        art: 'http://mythicspoiler.com/arn/cards/unstablemutation.jpg'
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Arabian Nights',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      }
    ]);
  });
};