exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('card-list').del()
    .then(function () {
      // Inserts seed entries
      return knex('card-list').insert([

        /*WHITES*/
        {
          name: 'Acrobatic Maneuver',
          set: 'Kaladesh',
          cost: '3',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Exile target creature you control, then return that card to the battlefield under its owner\'s control.\nDraw a card.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417574&type=card',
          flavor: 'Renegades find ever more creative ways to work around the Consulate\'s aether regulations.'
        },
        {
          name: 'Aerial Responder',
          set: 'Kaladesh',
          cost: '3',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Soldier',
          rarity: 'Uncommon',
          effects: 'Flying, vigilance, lifelink',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417575&type=card',
          power: '2',
          toughness: '3',
          flavor: 'Dwarves have an instinct for repair, an inherent understanding of how systems work, and a reputation for fearlessness.  They\'re the perfect candidates for the Fair\'s emergency response team.'
        },
        {
          name: 'Aetherstorm Roc',
          set: 'Kaladesh',
          cost: '4',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Bird',
          rarity: 'Rare',
          effects: 'Whenever Aetherstorm Roc or another creature enters the battlefield under your control, you get (E) (an energy counter).\nWhenever Aetherstorm Roc attacks, you may pay (E)(E).  If you do, put a +1/+1 counter on it and tap up to one target creature defending player controls.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417576&type=card',
          power: '3',
          toughness: '3'
        },
        {
          name: 'Angel of Invention',
          set: 'Kaladesh',
          cost: '5',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Angel',
          rarity: 'Mythic',
          effects: 'Flying, vigilance, lifelink\nFabricate 2 (When this creature enters the battlefield, put two +1/+1 counters on it or create two 1/1 colorless Servo artifact creature tokens.)\nOther creatures you control get +1/+1.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417577&type=card',
          power: '2',
          toughness: '1'
        },
        {
          name: 'Authority of the Consuls',
          set: 'Kaladesh',
          cost: '1',
          color: 'White',
          supertype: 'Enchantment',
          rarity: 'Rare',
          effects: 'Creatures your opponents control enter the battlefield tapped.\nWhenever a creature enters the battlefield under an opponent\'s control, you gain 1 life.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417578&type=card',
          flavor: 'Citizens are free to do as they wish, within the confines of the Consulate\'s laws.'
        },
        {
          name: 'Aviary Mechanic',
          set: 'Kaladesh',
          cost: '2',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Artificer',
          rarity: 'Common',
          effects: 'When Aviary Mechanic enters the battlefield, you may return another permanent you control to its owner\'s hand.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417579&type=card',
          power: '2',
          toughness: '2',
          flavor: 'Pilots take crippled skyships to the Aviaries, trusting Ghirapur\'s most talented mechanics to get them back into the air.'
        },
        {
          name: 'Built to Last',
          set: 'Kaladesh',
          cost: '1',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Target creature gets +2/+2 until end of turn.  If it\'s an artifact creature, it gains indestructible until end of turn. (Damage and effects that say "destroy" don\'t destroy it.)',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417580&type=card',
          flavor: 'Consulate-built automatons have a lifetime warranty.'
        },
        {
          name: 'Captured by the Consulate',
          set: 'Kaladesh',
          cost: '4',
          color: 'White',
          supertype: 'Enchantment',
          subtype: 'Aura',
          rarity: 'Rare',
          effects: 'Enchant creature you don\'t control\nEnchanted creature can\'t attack.\nWhenever an opponent casts a spell, if it has a single target, change the target to enchanted creature if able.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417581&type=card',
          flavor: '"At last, the infamous Pia Nalaar." --Tezzeret'
        },
        {
          name: 'Cataclysmic Gearhulk',
          set: 'Kaladesh',
          cost: '5',
          color: 'White',
          supertype: 'Artifact Creature',
          subtype: 'Construct',
          rarity: 'Mythic',
          effects: 'Vigilance\nWhen Cataclysmic Gearhulk enters the battlefield, each player chooses an artifact, a creature, an enchantment, and a planeswalker from the nonland permanents he or she controls, then sacrifices the rest.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417582&type=card',
          power: '4',
          toughness: '5'
        },
        {
          name: 'Consulate Surveillance',
          set: 'Kaladesh',
          cost: '4',
          color: 'White',
          supertype: 'Enchantment',
          rarity: 'Uncommon',
          effects: 'When Consulate Surveillance enters the battlefield, you get (E)(E)(E)(E) (four energy counters).\nPay (E)(E): Prevent all damage that would be dealt to you this turn by a source of your choice.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417583&type=card'
        },
        {
          name: 'Consul\'s Shieldguard',
          set: 'Kaladesh',
          cost: '4',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Soldier',
          rarity: 'Uncommon',
          effects: 'When Consul\'s Shieldguard enters the battlefield, you get (E)(E) (two energy counters).\nWhenever Consul\'s Shieldguard attacks, you may pay (E).  If you do, another target attacking creature gains indestructible until end of turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417584&type=card',
          power: '3',
          toughness: '4'
        },
        {
          name: 'Eddytail Hawk',
          set: 'Kaladesh',
          cost: '2',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Bird',
          rarity: 'Common',
          effects: 'Flying\nWhen Eddytail Hawk enters the battlefield, you get (E)(E) (two energy counters).\nWhenever Eddytail Hawk attacks, you may pay (E).  If you do, another target attacking creature gains flying until end of turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417585&type=card',
          power: '1',
          toughness: '2'
        },
        {
          name: 'Fairgrounds Warden',
          set: 'Kaladesh',
          cost: '3',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Soldier',
          rarity: 'Uncommon',
          effects: 'When Fairgrounds Warden enters the battlefield, exile target creature an opponent controls until Fairgrounds Warden leaves the battlefield.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417586&type=card',
          power: '1',
          toughness: '3',
          flavor: '"You\'re coming with me."'
        },
        {
          name: 'Fragmentize',
          set: 'Kaladesh',
          cost: '1',
          color: 'White',
          supertype: 'Sorcery',
          rarity: 'Common',
          effects: 'Destroy target artifact or enchantment with converted mana cost 4 or less.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417587&type=card',
          flavor: '"Too much friction on your bearings, your countersink is inconsistent, and there are lines in your casting.  Dispose of it, and begin again." --Dovin Baan'
        },
        {
          name: 'Fumigate',
          set: 'Kaladesh',
          cost: '5',
          color: 'White',
          supertype: 'Sorcery',
          rarity: 'Rare',
          effects: 'Destroy all creatures.  You gain 1 life for each creature destroyed this way.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417588&type=card',
          flavor: '"Ghirapur\'s gremlin population poses a threat to the infrastructure of the fairgrounds.  Threats must be eliminated." --Sram, senior edificer'
        },
        {
          name: 'Gearshift Ace',
          set: 'Kaladesh',
          cost: '2',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Pilot',
          rarity: 'Uncommon',
          effects: 'First strike\nWhenever Gearshift Ace crews a Vehicle, that Vehicle gains first strike until end of turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417589&type=card',
          power: '2',
          toughness: '1',
          flavor: 'Some display their trophies at the Hall of Mechanists.  Others display their talent in the streets of Ghirapur.'
        },
        {
          name: 'Glint-Sleeve Artisan',
          set: 'Kaladesh',
          cost: '3',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Artificer',
          rarity: 'Common',
          effects: 'Fabricate 1 (When this creature enters the battlefield, put a +1/+1 counter on it or create a 1/1 colorless Servo artifact creature token.)',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417590&type=card',
          power: '2',
          toughness: '2',
          flavor: '"Shine bright, bolts tight."'
        },
        {
          name: 'Herald of the Fair',
          set: 'Kaladesh',
          cost: '3',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Human',
          rarity: 'Common',
          effects: 'When Herald of the Fair enters the battlefield, target creature you control gets +1/+1 until end of turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417591&type=card',
          power: '3',
          toughness: '2',
          flavor: '"Welcome, one and all!  Right this way!  Open your eyes, your ears, and your imaginations to the wonders of the Inventors\' Fair!"'
        },
        {
          name: 'Impeccable Timing',
          set: 'Kaladesh',
          cost: '2',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Impeccable Timing deals 3 damage to target attacking or blocking creature.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417592&type=card',
          flavor: 'When Baral constructed his trap for Chandra, he did not account for the arrival of an enormous leonin wielding a twin-headed axe.'
        },
        {
          name: 'Inspired Charge',
          set: 'Kaladesh',
          cost: '4',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Creatures you control get +2/+1 until end of turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417593&type=card',
          flavor: 'One dwarf on a build team ensures competence.  All dwarves on the team ensures brilliance.'
        },
        {
          name: 'Master Trinketeer',
          set: 'Kaladesh',
          cost: '3',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Artificer',
          rarity: 'Rare',
          effects: 'Servos and Thopters you control get +1/+1.\n(3W): Create a 1/1 colorless Servo artifact creature token.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417594&type=card',
          power: '3',
          toughness: '2',
          flavor: '"Let us never forget the joy that lies at the heart of invention."'
        },
        {
          name: 'Ninth Bridge Patrol',
          set: 'Kaladesh',
          cost: '2',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Soldier',
          rarity: 'Common',
          effects: 'Whenever another creature you control leaves the battlefield, put a +1/+1 counter on Ninth Bridge Patrol.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417595&type=card',
          power: '1',
          toughness: '1',
          flavor: 'The Consulate keeps watch at each of the eleven bridges to ensure that the market remains a haven for commerce, not for con artists.'
        },
        {
          name: 'Pressure Point',
          set: 'Kaladesh',
          cost: '2',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Tap target creature.\nDraw a card.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417596&type=card',
          flavor: 'Everything has an off switch.'
        },
        {
          name: 'Propeller Pioneer',
          set: 'Kaladesh',
          cost: '4',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Human Artificer',
          rarity: 'Common',
          effects: 'Flying\nFabricate 1 (When this creature enters the battlefield, put a +1/+1 counter on it or create a 1/1 colorless Servo artifact creature token.)',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417597&type=card',
          power: '2',
          toughness: '1',
          flavor: '"The sky isn\'t the limit.  It\'s the starting point."'
        },
        {
          name: 'Refurbish',
          set: 'Kaladesh',
          cost: '4',
          color: 'White',
          supertype: 'Sorcery',
          rarity: 'Uncommon',
          effects: 'Return target artifact card from your graveyard to the battlefield.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417598&type=card',
          flavor: '"There\'s no reason to buy a new one when I\'ve got the tools to fix the one you\'ve got." --Ripu, repair specialist'
        },
        {
          name: 'Revoke Privileges',
          set: 'Kaladesh',
          cost: '3',
          color: 'White',
          supertype: 'Enchantment',
          subtype: 'Aura',
          rarity: 'Common',
          effects: 'Enchant creature\nEnchanted creature can\'t attack, block, or crew Vehicles.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417599&type=card',
          flavor: '"By order of Consulate Mandate 482, I am required to detain you, citizen."'
        },
        {
          name: 'Servo Exhibition',
          set: 'Kaladesh',
          cost: '2',
          color: 'White',
          supertype: 'Sorcery',
          rarity: 'Uncommon',
          effects: 'Create two 1/1 colorless Servo artifact creature tokens.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417600&type=card',
          flavor: '"The judges really put them through their paces, but they prevailed.  I think they even impressed Head Judge Tezzeret." --Ritika, artificer'
        },
        {
          name: 'Skyswirl Harrier',
          set: 'Kaladesh',
          cost: '5',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Bird',
          rarity: 'Common',
          effects: 'Flying',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417601&type=card',
          power: '3',
          toughness: '4',
          flavor: 'The great birds dive through the sky, wings skimming the aether streams, to fall upon their unsuspecting prey.'
        },
        {
          name: 'Skywhaler\'s Shot',
          set: 'Kaladesh',
          cost: '3',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Destroy target creature with power 3 or greater.  Scry 1.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417602&type=card',
          flavor: 'In the moment of truth, it is as though time stands still, nd the whale waits, suspended in the sky.'
        },
        {
          name: 'Tasseled Dromedary',
          set: 'Kaladesh',
          cost: '1',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Camel',
          rarity: 'Common',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417603&type=card',
          power: '0',
          toughness: '4',
          flavor: 'There is no dress code for the Inventors\' Fair, but you\'ll be hard-pressed to find anyone or anything not done up in their finest.'
        },
        {
          name: 'Thriving Ibex',
          set: 'Kaladesh',
          cost: '4',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Goat',
          rarity: 'Common',
          effects: 'When Thriving Ibex enters the battlefield, you get (E)(E) (two energy counters).\nWhenever Thriving Ibex attacks, you may pay (E)(E).  If you do, put a +1/+1 counter on it.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417604&type=card',
          power: '2',
          toughness: '4',
          flavor: 'Textiles at the Inventors\' Fair feature threads from every corner of Kaladesh.'
        },
        {
          name: 'Toolcraft Exemplar',
          set: 'Kaladesh',
          cost: '1',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Artificer',
          rarity: 'Rare',
          effects: 'At the beginning of combat on your turn, if you control an artifact, Toolcraft Exemplar gets +2/+1 until end of turn. If you control three or more artifacts, it also gains first strike until end of turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417605&type=card',
          power: '1',
          toughness: '1',
          flavor: '"If you wish to produce the finest work, you must start with the finest tools."'
        },
        {
          name: 'Trusty Companion',
          set: 'Kaladesh',
          cost: '2',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Hyena',
          rarity: 'Uncommon',
          effects: 'Vigilance\nTrusty Companion can\'t attack alone.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417606&type=card',
          power: '3',
          toughness: '2',
          flavor: 'It shows affection an automaton never could.'
        },
        {
          name: 'Visionary Augmenter',
          set: 'Kaladesh',
          cost: '4',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dwarf Artificer',
          rarity: 'Uncommon',
          effects: 'Fabricate 2 (When this creature enters the battlefield, put two +1/+1 counters on it or create two 1/1 colorless Servo artifact creature tokens.)',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417607&type=card',
          power: '2',
          toughness: '1',
          flavor: '"It\'s a multifunctional radial extension system with superlateral, force-amplifying rigging.  Of course it will win."'
        },
        {
          name: 'Wispweaver Angel',
          set: 'Kaladesh',
          cost: '6',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Angel',
          rarity: 'Uncommon',
          effects: 'Flying\nWhen Wispweaver Angel enters the battlefield, you may exile another target creature you control, then return that card to the battlefield under its owner\'s control.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417608&type=card',
          power: '4',
          toughness: '4'
        },

        /*BLUES*/
        {
          name: 'Aether Meltdown',
          set: 'Kaladesh',
          cost: '2',
          color: 'Blue',
          supertype: 'Enchantment',
          subtype: 'Aura',
          rarity: 'Uncommon',
          effects: 'Flash (You may cast this spell anytime you could play an instant.)\nEnchant creature or Vehicle\nWhen Aether Meltdown enters the battlefield, you get (E)(E) (two energy counters).\nEnchanted permanent gets -4/-0.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417609&type=card'
        },
        {
          name: 'Aether Theorist',
          set: 'Kaladesh',
          cost: '2',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Vedalken Rogue',
          rarity: 'Common',
          effects: 'When Aether Theorist enters the battlefield, you get (E)(E)(E) (three energy counters).\n(T), Pay (E): Scry 1. (Look at the top card of your library.  You may put that card on the bottom of your library.)',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417610&type=card',
          power: '1',
          toughness: '3'
        },
        {
          name: 'Aether Tradewinds',
          set: 'Kaladesh',
          cost: '3',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Return target permanent you control and target permanent you don\'t control to their owner\'s hands.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417611&type=card',
          flavor: 'Consulate engineers have developed safe methods of harvesting aether, but renegades aren\'t always so careful.'
        },
        {
          name: 'Aethersquall Ancient',
          set: 'Kaladesh',
          cost: '7',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Leviathan',
          rarity: 'Rare',
          effects: 'At the beginning of your upkeep, you get (E)(E)(E) (three energy counters).\nPay (E)(E)(E)(E)(E)(E)(E)(E): Return all other creatures to their owners\' hands.  Activate this ability only any time you could cast a sorcery.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417612&type=card',
          power: '6',
          toughness: '6'
        },
        {
          name: 'Ceremonious Rejection',
          set: 'Kaladesh',
          cost: '1',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Counter target colorless spell.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417613&type=card',
          flavor: 'The judges at the Fair are held in such high esteem that a nod of recognition can inspire an inventor for a lifetime--and a wave of dismissal can end a career.'
        },
        {
          name: 'Confiscation Coup',
          set: 'Kaladesh',
          cost: '5',
          color: 'Blue',
          supertype: 'Sorcery',
          rarity: 'Rare',
          effects: 'Choose target artifact or creature.  You get (E)(E)(E)(E) (four energy counters), then you may pay an amount of (E) equal to that permanent\'s converted mana cost.  If you do, gain control of it.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417614&type=card',
          flavor: '"Citizens, do not resist.  This is for your safety.  Tezzeret bids you to surrender your inventions.  Now."'
        },
        {
          name: 'Curio Vendor',
          set: 'Kaladesh',
          cost: '2',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Vedalken',
          rarity: 'Common',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417615&type=card',
          power: '2',
          toughness: '1',
          flavor: '"Step right up!  Try your hand!  It\'ll thrill the senses and boggle the mind!"'
        },
        {
          name: 'Disappearing Act',
          set: 'Kaladesh',
          cost: '3',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'As an additional cost to cast Disappearing Act, return a permanent you control to its owner\'s hand.\nCounter target spell.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417616&type=card',
          flavor: '"Baral took my family from me back then.  I\'d do anything to face him now." --Chandra Nalaar'
        },
        {
          name: 'Dramatic Reversal',
          set: 'Kaladesh',
          cost: '2',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Untap all nonland permanents you control.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417617&type=card',
          flavor: '"Nobody asked you to butt in, Jace.  But thanks." --Chandra Nalaar'
        },
        {
          name: 'Era of Innovation',
          set: 'Kaladesh',
          cost: '2',
          color: 'Blue',
          supertype: 'Enchantment',
          rarity: 'Uncommon',
          effects: 'Whenever an artifact or Artificer enters the battlefield under your control, you may pay (1).  If you do, you get (E)(E) (two energy counters).\nPay (E)(E)(E)(E)(E)(E), Sacrifice Era of Innovation: Draw three cards.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417618&type=card'
        },
        {
          name: 'Experimental Aviator',
          set: 'Kaladesh',
          cost: '5',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Human Artificer',
          rarity: 'Uncommon',
          effects: 'Flying\nWhen Experimental Aviator enters the battlefield, create two 1/1 colorless Thopter artifact creature tokens with flying.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417619&type=card',
          power: '0',
          toughness: '3',
          flavor: '"The little thopters seemed lonely up here, so I thought I\'d join them."'
        },
        {
          name: 'Failed Inspection',
          set: 'Kaladesh',
          cost: '4',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Counter target spell.  Draw a card, then discard a card.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417620&type=card',
          flavor: 'The most dangerous thing an artificer can do is believe an invention is perfect.'
        },
        {
          name: 'Gearseeker Serpent',
          set: 'Kaladesh',
          cost: '7',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Serpent',
          rarity: 'Common',
          effects: 'Gearseeker Serpent costs (1) less to cast for each artifact you control.\n(5U): Gearseeker Serpent can\'t be blocked this turn.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417621&type=card',
          power: '5',
          toughness: '6',
          flavor: 'Its collection is vast, yet each ship has a special place in its heart.'
        },
        {
          name: 'Glimmer of Genius',
          set: 'Kaladesh',
          cost: '4',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Scry 2, then draw two cards.  You get (E)(E) (two energy counters).',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417622&type=card',
          flavor: 'Creators live for that moment of inspiration: precious, profound, perfect.'
        },
        {
          name: 'Glint-Nest Crane',
          set: 'Kaladesh',
          cost: '2',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Bird',
          rarity: 'Uncommon',
          effects: 'Flying\nWhen Glint-Nest Crane enters the battlefield, look at the top four cards of your library. You may reveal an artifact card from among them and put it into your hand. Put the rest on the bottom of your library in any order.',
          art: 'http://gatherer.wizards.com/Handlers/Image.ashx?multiverseid=417623&type=card',
          power: '1',
          toughness: '3'
        },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Kaladesh',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
      ]);
    });
};
