exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('Card_List').del()
  .then(function () {
    // Inserts seed entries
    return knex('Card_List').insert([
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'White',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        color: 'Colorless',
        supertype: 'Land',
        effects: '',
        flavor: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        color: 'Colorless',
        supertype: 'Land',
        effects: '',
        flavor: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        color: 'Colorless',
        supertype: 'Legendary Land',
        effects: '',
        flavor: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        color: 'Colorless',
        supertype: 'Legendary Land',
        effects: '',
        flavor: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        color: 'Colorless',
        supertype: 'Land',
        effects: '',
        flavor: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        color: 'Colorless',
        supertype: 'Legendary Land',
        effects: '',
        flavor: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        color: 'Colorless',
        supertype: 'Land',
        effects: '',
        flavor: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        color: 'Colorless',
        supertype: 'Legendary Land',
        effects: '',
        flavor: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        color: 'Colorless',
        supertype: 'Legendary Land',
        effects: '',
        flavor: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        color: 'Colorless',
        supertype: 'Land',
        effects: '',
        flavor: '',
        art: ''
      },
      {
        name: '',
        set: 'Legends',
        color: 'Colorless',
        supertype: 'Legendary Land',
        effects: '',
        flavor: '',
        art: ''
      }
    ]);
  });
};