exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('Card_List').del()
  .then(function () {
    // Inserts seed entries
    return knex('Card_List').insert([
      {
        name: 'Akron Legionnaire',
        set: 'Legends',
        cost: '8',
        color: 'White',
        supertype: 'Summon Legionnaire',
        effects: 'Other non-artifact creatures you control can\'t attack.',
        power: '8',
        toughness: '4',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: 'Alabaster Potion',
        set: 'Legends',
        cost: '3+',
        color: 'White',
        supertype: 'Instant',
        effects: 'Choose one--\n\t* Target player gains X life.\n\t* Prevent the next X damage to target creature or player.',
        flavor: '"Healing is a matter of time, but it is sometimes also a matter of opportunity."\n--D\'Avenant proverb',
        art: 'http://mythicspoiler.com/leg/cards/alabasterpotion.jpg'
      },
      {
        name: 'Amrou Kithkin',
        set: 'Legends',
        cost: '2',
        color: 'White',
        supertype: 'Summon Kithkin',
        effects: 'This creature can\'t be blocked by creatures with power 3 or greater.',
        flavor: 'Quick and agile, Amrou Kithkin can usually escape from even the most fearsome opponents.',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/leg/cards/amroukithkin.jpg'
      },
      {
        name: 'Angelic Voices',
        set: 'Legends',
        cost: '4',
        color: 'White',
        supertype: 'Enchantment',
        effects: 'As long as creatures you control are white or colorless, creatures you control get +1/+1.',
        art: 'http://mythicspoiler.com/leg/cards/angelicvoices.jpg'
      },
      {
        name: 'Cleanse',
        set: 'Legends',
        cost: '4',
        color: 'White',
        supertype: 'Sorcery',
        effects: 'Destroy all black creatures.',
        flavor: 'The clouds broke and the sun\'s rays burst forth; each foul beast in its turn faltered, and was gone.',
        art: 'http://mythicspoiler.com/leg/cards/cleanse.jpg'
      },
      {
        name: 'Clergy of the Holy Nimbus',
        set: 'Legends',
        cost: '1',
        color: 'White',
        supertype: 'Summon Priest',
        effects: 'Whenever Clergy of the Holy Nimbus would die, regenerate it unless an opponent pays {1}.',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/leg/cards/clergyoftheholynimbus.jpg'
      },
      {
        name: 'D\'Avenant Archer',
        set: 'Legends',
        cost: '3',
        color: 'White',
        supertype: 'Summon Archer',
        effects: '{T}: D\'Avenant Archer deals 1 damage to target attacking or blocking creature.',
        power: '1',
        toughness: '2',
        art: 'http://mythicspoiler.com/leg/cards/davenantarcher.jpg'
      },
      {
        name: 'Divine Intervention',
        set: 'Legends',
        cost: '8',
        color: 'White',
        supertype: 'Enchantment',
        effects: 'Divine Intervention enters the battlefield with two divinity counters on it.\nAt the beginning of your upkeep, remove a divinity counter from Divine Intervention.  Then, if there are no divinity counters on Divine Intervention, the game ends and is considered a draw.',
        art: 'http://mythicspoiler.com/leg/cards/divineintervention.jpg'
      },
      {
        name: 'Divine Offering',
        set: 'Legends',
        cost: '2',
        color: 'White',
        supertype: 'Instant',
        effects: 'Destroy target artifact.  You gain life equal to its converted mana cost.',
        flavor: 'D\'Haren stared at the twisted lump of metal that had been a prized artifact.  The fight was getting ugly.',
        art: 'http://mythicspoiler.com/leg/cards/divineoffering.jpg'
      },
      {
        name: 'Divine Transformation',
        set: 'Legends',
        cost: '4',
        color: 'White',
        supertype: 'Enchant Creature',
        effects: 'Enchanted creature gets +3/+3.',
        flavor: 'Glory surged through her and radiance surrounded her.  All things were possible with the blessing of the Divine.',
        art: 'http://mythicspoiler.com/leg/cards/divinetransformation.jpg'
      },
      {
        name: 'Elder Land Wurm',
        set: 'Legends',
        cost: '7',
        color: 'White',
        supertype: 'Summon Wurm',
        effects: 'Trample\nThis creature can\'t attack until it has blocked.',
        flavor: 'Sometimes it\'s best to let sleeping dragons lie.',
        power: '5',
        toughness: '5',
        art: 'http://mythicspoiler.com/leg/cards/elderlandwurm.jpg'
      },
      {
        name: 'Enchanted Being',
        set: 'Legends',
        cost: '3',
        color: 'White',
        supertype: 'Summon Being',
        effects: 'Prevent all damage dealt to Enchanted Being by enchanted creatures.',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/leg/cards/enchantedbeing.jpg'
      },
      {
        name: 'Equinox',
        set: 'Legends',
        cost: '1',
        color: 'White',
        supertype: 'Enchant Land',
        effects: 'Enchanted land has "{T}: Counter target spell that would destroy one or more of your lands."',
        art: 'http://mythicspoiler.com/leg/cards/equinox.jpg'
      },
      {
        name: 'Fortified Area',
        set: 'Legends',
        cost: '3',
        color: 'White',
        supertype: 'Enchantment',
        effects: 'Walls you control get +1/+0 and have banding.',
        art: 'http://mythicspoiler.com/leg/cards/fortifiedarea.jpg'
      },
      {
        name: 'Glyph of Life',
        set: 'Legends',
        cost: '1',
        color: 'White',
        supertype: 'Instant',
        effects: 'Until end of turn, whenever target Wall takes damage, you gain that much life.',
        flavor: 'Any wall can be battered down, but at what cost?',
        art: 'http://mythicspoiler.com/leg/cards/glyphoflife.jpg'
      },
      {
        name: 'Great Defender',
        set: 'Legends',
        cost: '1',
        color: 'White',
        supertype: 'Instant',
        effects: 'Target creature gets +0/+X, where X is its converted mana cost.',
        art: 'http://mythicspoiler.com/leg/cards/greatdefender.jpg'
      },
      {
        name: 'Great Wall',
        set: 'Legends',
        cost: '3',
        color: 'White',
        supertype: 'Enchantment',
        effects: 'Creatures with plainswalk may be blocked as if they didn\'t have plainswalk.',
        art: 'http://mythicspoiler.com/leg/cards/greatwall.jpg'
      },
      {
        name: 'Greater Realm of Preservation',
        set: 'Legends',
        cost: '2',
        color: 'White',
        supertype: 'Enchantment',
        effects: '{1W}: Prevent all damage dealt to you from a black or red source.  If that source would deal damage to you multiple times in a turn, you must pay this cost each time to prevent the damage.',
        art: 'http://mythicspoiler.com/leg/cards/greaterrealmofpreservation.jpg'
      },
      {
        name: 'Heaven\'s Gate',
        set: 'Legends',
        cost: '1',
        color: 'White',
        supertype: 'Instant',
        effects: 'Change the color of one or more target creatures to white until end of turn.',
        art: 'http://mythicspoiler.com/leg/cards/heavensgate.jpg'
      },
      {
        name: 'Holy Day',
        set: 'Legends',
        cost: '1',
        color: 'White',
        supertype: 'Instant',
        effects: 'Prevent all combat damage that would be dealt this turn.',
        flavor: '"The day of spirits; my soul\'s calm retreat / Which none disturb!"\n--Henry Vaughan, "Silex Scintillans"',
        art: 'http://mythicspoiler.com/leg/cards/holyday.jpg'
      },
      {
        name: 'Indestructible Aura',
        set: 'Legends',
        cost: '1',
        color: 'White',
        supertype: 'Instant',
        effects: 'Prevent all damage dealt to target creature until end of turn.',
        flavor: 'Theodar strode the battle lines, snatching swords with his bare hands and casting them aside until all cowered before him.',
        art: 'http://mythicspoiler.com/leg/cards/indestructibleaura.jpg'
      },
      {
        name: 'Infinite Authority',
        set: 'Legends',
        cost: '3',
        color: 'White',
        supertype: 'Enchant Creature',
        effects: 'All creatures with toughness 3 or less that are blocking or blocked by enchanted creature are destroyed at end of combat.  At the beginning of each end step, put a +1/+1 counter on enchanted creature for each creature destroyed this way.',
        art: 'http://mythicspoiler.com/leg/cards/infiniteauthority.jpg'
      },
      {
        name: 'Ivory Guardians',
        set: 'Legends',
        cost: '6',
        color: 'White',
        supertype: 'Summon Guardians',
        effects: 'Protection from red\nGuardians you control get +1/+1 if an opponent controls a red permanent.',
        flavor: 'The elite guard of the Mesa High Priests, the Ivory Guardians, were created to protect the innocent and faithful.  Some say their actions are above the law.',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/leg/cards/ivoryguardians.jpg'
      },
      {
        name: 'Keepers of the Faith',
        set: 'Legends',
        cost: '3',
        color: 'White',
        supertype: 'Summon Keepers',
        flavor: 'And then the Archangel Anthius spoke to them, saying, "Fear shall be vanquished by the Sword of Faith."',
        power: '2',
        toughness: '3',
        art: 'http://mythicspoiler.com/leg/cards/keepersofthefaith.jpg'
      },
      {
        name: 'Kismet',
        set: 'Legends',
        cost: '4',
        color: 'White',
        supertype: 'Enchantment',
        effects: 'Artifacts, creatures, and lands your opponents control enter the battlefield tapped.',
        art: 'http://mythicspoiler.com/leg/cards/kismet.jpg'
      },
      {
        name: 'Land Tax',
        set: 'Legends',
        cost: '1',
        color: 'White',
        supertype: 'Enchantment',
        effects: 'At the beginning of your upkeep, if an opponent controls more lands than you, you may search your library for up to three basic land cards and put them into your hand.  Then shuffle your library.',
        art: 'http://mythicspoiler.com/leg/cards/landtax.jpg'
      },
      {
        name: 'Lifeblood',
        set: 'Legends',
        cost: '4',
        color: 'White',
        supertype: 'Enchantment',
        effects: 'Whenever an opponent taps a Mountain, you gain 1 life.',
        flavor: '"Foolish wizard!  As you tap the power of your lofty keep, so grows my strength."\n--Malvern Xelionos, Letters',
        art: 'http://mythicspoiler.com/leg/cards/lifeblood.jpg'
      },
      {
        name: 'Moat',
        set: 'Legends',
        cost: '4',
        color: 'White',
        supertype: 'Enchantment',
        effects: 'Creatures without flying can\'t attack.',
        flavor: 'The purpose of any moat is to impede attack.  Some are filled with water, some with thistles.  Some are filled with things best left unseen.',
        art: 'http://mythicspoiler.com/leg/cards/moat.jpg'
      },
      {
        name: 'Osai Vultures',
        set: 'Legends',
        cost: '2',
        color: 'White',
        supertype: 'Summon Vultures',
        effects: 'Flying\nAt the beginning of each end step, if a creature died this turn, put a +1/+1 counter on Osai Vultures.\nRemove two +1/+1 counters from Osai Vultures: Osai Vultures gets +1/+1 until end of turn.',
        flavor: 'A sign of battle, the Vultures circle and wait for the victorious to depart.',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/leg/cards/osaivultures.jpg'
      },
      {
        name: 'Petra Sphinx',
        set: 'Legends',
        cost: '5',
        color: 'White',
        supertype: 'Summon Sphinx',
        effects: '{T}: Target player chooses a card name, then reveals the top card of their library.  If that card matches the chosen name, that player puts it into their hand.  Otherwise, put that card into the graveyard.',
        flavor: 'What walks on four legs in the morning, two legs in the afternoon, and three legs in the evening?',
        power: '3',
        toughness: '4',
        art: 'http://mythicspoiler.com/leg/cards/petrasphinx.jpg'
      },
      {
        name: 'Presence of the Master',
        set: 'Legends',
        cost: '4',
        color: 'White',
        supertype: 'Enchantment',
        effects: 'Counter all enchantment spells.',
        art: 'http://mythicspoiler.com/leg/cards/presenceofthemaster.jpg'
      },
      {
        name: 'Rapid Fire',
        set: 'Legends',
        cost: '4',
        color: 'White',
        supertype: 'Instant',
        effects: 'Target creature gains first strike until end of turn.  If that creature does not have rampage, it gains rampage 2 until end of turn.',
        art: 'http://mythicspoiler.com/leg/cards/rapidfire.jpg'
      },
      {
        name: 'Remove Enchantments',
        set: 'Legends',
        cost: '1',
        color: 'White',
        supertype: 'Instant',
        effects: 'Return all enchantments you control to your hand.  Destroy all other enchantments.',
        art: 'http://mythicspoiler.com/leg/cards/removeenchantments.jpg'
      },
      {
        name: 'Righteous Avengers',
        set: 'Legends',
        cost: '5',
        color: 'White',
        supertype: 'Summon Avengers',
        effects: 'Plainswalk',
        flavor: 'Few can withstand the wrath of the righteous.',
        power: '3',
        toughness: '1',
        art: 'http://mythicspoiler.com/leg/cards/righteousavengers.jpg'
      },
      {
        name: 'Seeker',
        set: 'Legends',
        cost: '4',
        color: 'White',
        supertype: 'Enchant Creature',
        effects: 'Enchanted creature can\'t be blocked except by white creatures or artifact creatures.',
        art: 'http://mythicspoiler.com/leg/cards/seeker.jpg'
      },
      {
        name: 'Shield Wall',
        set: 'Legends',
        cost: '2',
        color: 'White',
        supertype: 'Instant',
        effects: 'Creatures you control get +0/+2 until end of turn.',
        art: 'http://mythicspoiler.com/leg/cards/shieldwall.jpg'
      },
      {
        name: 'Spirit Link',
        set: 'Legends',
        cost: '1',
        color: 'White',
        supertype: 'Enchant Creature',
        effects: 'Enchanted creature has lifelink.',
        art: 'http://mythicspoiler.com/leg/cards/spiritlink.jpg'
      },
      {
        name: 'Spiritual Sanctuary',
        set: 'Legends',
        cost: '4',
        color: 'White',
        supertype: 'Enchantment',
        effects: 'All players who control a plains gain 1 life at the beginning of their upkeep.',
        art: 'http://mythicspoiler.com/leg/cards/spiritualsanctuary.jpg'
      },
      {
        name: 'Thunder Spirit',
        set: 'Legends',
        cost: '3',
        color: 'White',
        supertype: 'Summon Spirit',
        effects: 'First strike, flying',
        flavor: '"It was full of fire and smoke and light and... it drove between us and the Efrafans like a thousand thunderstorms with lightning."\n--Richard Adams, Watership Down',
        power: '2',
        toughness: '1',
        art: 'http://mythicspoiler.com/leg/cards/thunderspirit.jpg'
      },
      {
        name: 'Tundra Wolves',
        set: 'Legends',
        cost: '1',
        color: 'White',
        supertype: 'Summon Wolves',
        effects: 'First strike',
        flavor: 'I heard their eerie howling, the wolves calling their kindred across the frozen plains.',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/leg/cards/tundrawolves.jpg'
      },
      {
        name: 'Visions',
        set: 'Legends',
        cost: '1',
        color: 'White',
        supertype: 'Sorcery',
        effects: 'You may look at the top five cards of any library.  Then you may shuffle that library.',
        flavor: '"Visions of glory, spare my aching sight, / Ye unborn ages, crowd not upon my soul!"\n--Thomas Grey, The Bard',
        art: 'http://mythicspoiler.com/leg/cards/visions.jpg'
      },
      {
        name: 'Wall of Caltrops',
        set: 'Legends',
        cost: '2',
        color: 'White',
        supertype: 'Summon Wall',
        effects: 'If Wall of Caltrops and at least one other Wall block a creature and if there are no non-Wall creatures blocking that creature, Wall of Caltrops gains banding until end of turn.',
        flavor: '"Ow!  Ow ow ow!  Oooh, ow, OW!"',
        power: '2',
        toughness: '1',
        art: 'http://mythicspoiler.com/leg/cards/wallofcaltrops.jpg'
      },
      {
        name: 'Wall of Light',
        set: 'Legends',
        cost: '3',
        color: 'White',
        supertype: 'Summon Wall',
        effects: 'Protection from black',
        flavor: 'As many attackers were dazzled by the wall\'s beauty as were halted by its force.',
        power: '1',
        toughness: '5',
        art: 'http://mythicspoiler.com/leg/cards/walloflight.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Blue',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Black',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Red',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Green',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: '',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        cost: '',
        color: 'Colorless',
        supertype: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        color: 'Colorless',
        supertype: 'Land',
        effects: '',
        flavor: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        color: 'Colorless',
        supertype: 'Land',
        effects: '',
        flavor: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        color: 'Colorless',
        supertype: 'Legendary Land',
        effects: '',
        flavor: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        color: 'Colorless',
        supertype: 'Legendary Land',
        effects: '',
        flavor: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        color: 'Colorless',
        supertype: 'Land',
        effects: '',
        flavor: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        color: 'Colorless',
        supertype: 'Legendary Land',
        effects: '',
        flavor: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        color: 'Colorless',
        supertype: 'Land',
        effects: '',
        flavor: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        color: 'Colorless',
        supertype: 'Legendary Land',
        effects: '',
        flavor: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        color: 'Colorless',
        supertype: 'Legendary Land',
        effects: '',
        flavor: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        color: 'Colorless',
        supertype: 'Land',
        effects: '',
        flavor: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      },
      {
        name: '',
        set: 'Legends',
        color: 'Colorless',
        supertype: 'Legendary Land',
        effects: '',
        flavor: '',
        art: 'http://mythicspoiler.com/leg/cards/akronlegionnaire.jpg'
      }
    ]);
  });
};