exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('card-list').del()
    .then(function () {
      // Inserts seed entries
      return knex('card-list').insert([
        {
          name: 'Adanto Vanguard',
          set: 'Ixalan',
          cost: '2',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Vampire Soldier',
          rarity: 'Uncommon',
          effects: 'As long as Adanto Vanguard is attacking, it gets +2/+0 until end of turn.\nPay 4 life: Adanto Vanguard gains indestructible until end of turn. (Damage and effects that say "destroy" don\'t destroy it.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Adanto-Vanguard-Ixalan-Spoiler-216x302.png',
          power: '1',
          toughness: '1'
        },
        {
          name: 'Ashes of the Abhorrent',
          set: 'Ixalan',
          cost: '2',
          color: 'White',
          supertype: 'Enchantment',
          rarity: 'Rare',
          effects: 'Players can\'t cast spells from graveyards or activate abilities of cards in graveyards.\nWhenever a creature dies, you gain 1 life.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Ashes-of-the-Abhorrent-Ixalan-Spoiler-216x302.png',
          flavor: '"Let no trace of the vampires\' foulness remain."'
        },
        {
          name: 'Axis of Mortality',
          set: 'Ixalan',
          cost: '6',
          color: 'White',
          supertype: 'Enchantment',
          rarity: 'Mythic',
          effects: 'At the beginning of your upkeep, you may have two target players exchange life totals.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Axis-of-Mortality-216x302.png',
          flavor: 'The Church of Dusk teaches there is no gain without loss, no triumph without sacrifice, no drink of exquisite crimson without a dying gasp.'
        },
        {
          name: 'Bellowing Aegisaur',
          set: 'Ixalan',
          cost: '6',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dinosaur',
          rarity: 'Uncommon',
          effects: 'Enrage -- Whenever Bellowing Aegisaur is dealt damage, put a +1/+1 counter on each other creature you control.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/08/Bellowing-Aegisaur-216x302.png',
          power: '3',
          toughness: '5',
          flavor: 'Its roaring challenge is punctuated by the slam of its tail on the earth, rousing the herds of the plains.'
        },
        {
          name: 'Bishop of Rebirth',
          set: 'Ixalan',
          cost: '5',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Vampire Cleric',
          rarity: 'Rare',
          effects: 'Vigilance\nWhenever Bishop of Rebirth attacks, return target creature card with converted mana cost 3 or less from your graveyard to the battlefield.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Bishop-of-Rebirth-Ixalan-Spoiler-216x302.png',
          power: '3',
          toughness: '4',
          flavor: '"In the death of the foe lies the resurrection of the faithful."'
        },
        {
          name: 'Bishop\'s Soldier',
          set: 'Ixalan',
          cost: '2',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Vampire Soldier',
          rarity: 'Common',
          effects: 'Lifelink',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Bishop%E2%80%99s-Soldier-Ixalan-Spoiler-216x302.png',
          power: '2',
          toughness: '2',
          flavor: 'Vampires, the noble class of old Torrezon, are guided by their dual loyalties to church and crown.'
        },
        {
          name: 'Bright Reprisal',
          set: 'Ixalan',
          cost: '5',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Destroy target attacking creature.\nDraw a card.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Bright-Reprisal-Ixalan-Spoiler-216x302.png',
          flavor: 'Vampires know blood and the systems that carry it.  And they know exactly where to strike to set it free.'
        },
        {
          name: 'Demystify',
          set: 'Ixalan',
          cost: '1',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Destroy target enchantment.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Demystify-Ixalan-Spoiler-216x302.png',
          flavor: '"The River Heralds carve spells into jade, hoping to steer us from our course.  But what right do they have to keep us from that which once was ours?"'
        },
        {
          name: 'Duskborne Skymarcher',
          set: 'Ixalan',
          cost: '1',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Vampire Cleric',
          rarity: 'Uncommon',
          effects: 'Flying\n(W), (T): Target attacking Vampire gets +1/+1 until end of turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Duskborne-Skymarcher-Ixalan-Spoiler-216x302.png',
          power: '1',
          toughness: '1',
          flavor: '"The hour of Dusk is come."'
        },
        {
          name: 'Emissary of Sunrise',
          set: 'Ixalan',
          cost: '3',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Human Cleric',
          rarity: 'Uncommon',
          effects: 'First strike\nWhen Emissary of Sunrise enters the battlefield, it explores. (Reveal the top card of your library.  Put that card into your hand if it\'s a land.  Otherwise, put a +1/+1 counter on this creature, then put the card back or put it into your graveyard.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Emissary-of-Sunrise-Ixalan-Spoiler-216x302.png',
          power: '2',
          toughness: '1'
        },
        {
          name: 'Encampment Keeper',
          set: 'Ixalan',
          cost: '1',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Hound',
          rarity: 'Common',
          effects: 'First strike\n(7W), Sacrifice Encampment Keeper: Creatures you control get +2/+2 until end of turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Encampment-Keeper-Ixalan-Spoiler-216x302.png',
          power: '1',
          toughness: '1',
          flavor: 'Paladins of the Sanctum Seeker order are an adventurous lot, venturing into the wilds with monstrous mastiffs at their side.'
        },
        {
          name: 'Glorifier of Dusk',
          set: 'Ixalan',
          cost: '5',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Vampire Soldier',
          rarity: 'Uncommon',
          effects: 'Pay 2 life: Glorifier of Dusk gains flying until end of turn.\nPay 2 life: Glorifier of Dusk gains vigilance until end of turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Glorifier-of-Dusk-Ixalan-Spoiler-216x302.png',
          power: '4',
          toughness: '4',
          flavor: '"The blood of the enemy is a sacrament.  The strength it gives proves that our cause is just."'
        },
        {
          name: 'Goring Ceratops',
          set: 'Ixalan',
          cost: '7',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dinosaur',
          rarity: 'Rare',
          effects: 'Double strike\nWhenever Goring Ceratops attacks, other creatures you control gain double strike until end of turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Goring-Ceratops-Ixalan-Spoiler-216x302.png',
          power: '3',
          toughness: '3',
          flavor: '"Follow her footsteps and she will show you the way." --Itzama the Crested'
        },
        {
          name: 'Imperial Aerosaur',
          set: 'Ixalan',
          cost: '4',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dinosaur',
          rarity: 'Uncommon',
          effects: 'Flying\nWhen Imperial Aerosaur enters the battlefield, another target creature you control gets +1/+1 and gains flying until end of turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Imperial-Aerosaur-Ixalan-Spoiler-216x302.png',
          power: '3',
          toughness: '3',
          flavor: 'Its assistance is unnervingly similar to its hunting technique.'
        },
        {
          name: 'Imperial Lancer',
          set: 'Ixalan',
          cost: '1',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Human Knight',
          rarity: 'Uncommon',
          effects: 'Imperial Lancer has double strike as long as you control a Dinosaur.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Imperial-Lancer-Ixalan-Spoiler-216x302.png',
          power: '1',
          toughness: '1',
          flavor: '"Together my mount and I are stronger than either of us apart."'
        },
        {
          name: 'Inspiring Cleric',
          set: 'Ixalan',
          cost: '3',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Vampire Cleric',
          rarity: 'Uncommon',
          effects: 'When Inspiring Cleric enters the battlefield, you gain 4 life.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Inspiring-Cleric-Ixalan-Spoiler-216x302.png',
          power: '3',
          toughness: '2',
          flavor: '"The Immortal Sun will bring us true everlasting life to replace the everlasting shadow of undeath."'
        },
        {
          name: 'Ixalan\'s Binding',
          set: 'Ixalan',
          cost: '4',
          color: 'White',
          supertype: 'Enchantment',
          rarity: 'Uncommon',
          effects: 'When Ixalan\'s Binding enters the battlefield, exile target nonland permanent an opponent controls until Ixalan\'s Binding leaves the battlefield.\nYour opponents can\'t cast spells with the same name as the exiled card.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Ixalan%E2%80%99s-Binding-Ixalan-Spoiler-216x302.png',
          flavor: 'Jace awoke to the certainty that he was lost.'
        },
        {
          name: 'Kinjalli\'s Caller',
          set: 'Ixalan',
          cost: '1',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Human Cleric',
          rarity: 'Common',
          effects: 'Dinosaur spells you cast cost (1) less to cast.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Kinjalli%E2%80%99s-Caller-Ixalan-Spoiler-216x302.png',
          power: '0',
          toughness: '3',
          flavor: 'The people of the Sun Empire worship the sun in three aspects.  Kinjalli is the Wakening Sun, who created humans from clay and baked them in the sun\'s warmth.'
        },
        {
          name: 'Kinjalli\'s Sunwing',
          set: 'Ixalan',
          cost: '3',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dinosaur',
          rarity: 'Rare',
          effects: 'Flying\nCreatures your opponents control enter the battlefield tapped.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Kinjallis-Sunwing-Ixalan-Spoiler-216x302.png',
          power: '2',
          toughness: '3',
          flavor: '"There are moments when I feel I could fly like the sunwing.  Far away would I soar, but always a golden gale pushes me back." --Huatli'
        },
        {
          name: 'Legion Conquistador',
          set: 'Ixalan',
          cost: '3',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Vampire Soldier',
          rarity: 'Common',
          effects: 'When Legion Conquistador enters the battlefield, you may search your library for any number of cards named Legion Conquistador, reveal them, put them into your hand, then shuffle your library.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Legion-Conquistador-216x302.png',
          power: '2',
          toughness: '2',
          flavor: 'The Legion of Dusk sailed from Torrezon in search of glory, riches, and the Immortal Sun.'
        },
        {
          name: 'Legion\'s Judgement',
          set: 'Ixalan',
          cost: '3',
          color: 'White',
          supertype: 'Sorcery',
          rarity: 'Common',
          effects: 'Destroy target creature with power 4 or greater.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Legion%E2%80%99s-Judgment-Ixalan-Spoiler-216x302.png',
          flavor: '"My lance was once wielded by the Venerable Tarrian.  In his name and by his might, I cast you down!"'
        },
        {
          name: 'Legion\'s Landing',
          set: 'Ixalan',
          cost: '1',
          color: 'White',
          supertype: 'Legendary Enchantment',
          rarity: 'Mythic',
          effects: 'When Legion\'s Landing enters the battlefield, create a 1/1 white Vampire creature token with lifelink.\nWhen you attack with three or more creatures, transform Legion\'s Landing.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Legions-Landing-216x302.png',
          flavor: '"I claim this land in the name of the queen." --Adrian Adanto of Lujio'
        },
        {
          name: 'Adanto, the First Fort',
          set: 'Ixalan',
          cost: '0',
          color: 'Colorless',
          supertype: 'Legendary Land',
          rarity: 'Mythic',
          effects: '(Transforms from Legion\'s Landing.)\n(T): Add (W) to your mana pool.\n(2W), (T): Create a 1/1 white Vampire creature token with lifelink.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Adanto-the-First-Fort-216x302.png'
        },
        {
          name: 'Looming Altisaur',
          set: 'Ixalan',
          cost: '4',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dinosaur',
          rarity: 'Common',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Looming-Altisaur-216x300.jpg',
          power: '1',
          toughness: '7',
          flavor: 'Nature can\'t be tamed, but the Sun Empire believes that humans are made stronger when they test themselves against the wild strength of the dinosaurs.'
        },
        {
          name: 'Mavren Fein, Dusk Apostle',
          set: 'Ixalan',
          cost: '3',
          color: 'White',
          supertype: 'Legendary Creature',
          subtype: 'Vampire Cleric',
          rarity: 'Rare',
          effects: 'Whenever one or more nontoken Vampires you control attack, create a 1/1 white Vampire creature token with lifelink.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Mavren-Fein-Dusk-Apostle-Ixalan-Spoiler-216x302.png',
          power: '2',
          toughness: '2',
          flavor: 'In the rapture of his Blood Fast, he destroyed the navigator\'s tools and steered the ship to shore by faith alone.'
        },
        {
          name: 'Paladin of the Bloodstained',
          set: 'Ixalan',
          cost: '4',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Vampire Knight',
          rarity: 'Common',
          effects: 'When Paladin of the Bloodstained enters the battlefield, create a 1/1 white Vampire creature token with lifelink.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Paladin-of-the-Bloodstained-Ixalan-Spoiler-216x302.png',
          power: '3',
          toughness: '2',
          flavor: 'Closely linked to the Church of Dusk, the paladins of the Bloodstained order are devout to the point of fanaticism.'
        },
        {
          name: 'Pious Interdiction',
          set: 'Ixalan',
          cost: '4',
          color: 'White',
          supertype: 'Enchantment',
          subtype: 'Aura',
          rarity: 'Common',
          effects: 'Enchant creature\nWhen Pious Interdiction enters the battlefield, you gain 2 life.\nEnchanted creature can\'t attack or block.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Pious-Interdiction-Ixalan-Spoiler-216x302.png',
          flavor: '"Ours is the true and righteous path.  You will bow before our might."'
        },
        {
          name: 'Priest of the Wakening Sun',
          set: 'Ixalan',
          cost: '1',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Human Cleric',
          rarity: 'Rare',
          effects: 'At the beginning of your upkeep, you may reveal a Dinosaur card from your hand.  If you do, you gain 2 life.\n(3WW), Sacrifice Priest of the Wakening Sun: Search your library for a Dinosaur card, reveal it, put it into your hand, then shuffle your library.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Priest-of-the-Wakening-Sun-Ixalan-Spoiler-216x302.png',
          power: '1',
          toughness: '1'
        },
        {
          name: 'Pterodon Knight',
          set: 'Ixalan',
          cost: '4',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Human Knight',
          rarity: 'Common',
          effects: 'Pterodon Knight has flying as long as you control a Dinosaur.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Pterodon-Knight-Ixalan-Spoiler-216x302.png',
          power: '3',
          toughness: '3',
          flavor: '"To rise like the sun--there is no greater feeling."'
        },
        {
          name: 'Queen\'s Commission',
          set: 'Ixalan',
          cost: '3',
          color: 'White',
          supertype: 'Sorcery',
          rarity: 'Common',
          effects: 'Create two 1/1 white Vampire creature tokens with lifelink.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Queen%E2%80%99s-Commission-Ixalan-Spoiler-216x302.png',
          flavor: '"Let the blood of the impure flow through you.  Only the blessings of the golden city will purge its acrid taste from your mouth." --High Marshal Arguel'
        },
        {
          name: 'Rallying Roar',
          set: 'Ixalan',
          cost: '3',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Creatures you control get +1/+1 until end of turn.  Untap them.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Rallying-Roar-Ixalan-Spoiler-216x302.png',
          flavor: '"The sun\'s strength sings in our hearts!  I have never been more proud of my home and my people." --Huatli'
        },
        {
          name: 'Raptor Companion',
          set: 'Ixalan',
          cost: '2',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dinosaur',
          rarity: 'Common',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Raptor-Companion-Ixalan-Spoiler-216x302.png',
          power: '3',
          toughness: '1',
          flavor: 'A raptor will follow any order as long as that order is "hunt," "kill," or "go for the guts."'
        },
        {
          name: 'Ritual of Rejuvenation',
          set: 'Ixalan',
          cost: '3',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'You gain 4 life.\nDraw a card.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Ritual-of-Rejuvenation-Ixalan-Spoiler-216x302.png',
          flavor: '"Nothing is more sacred than the gift of blood.  Blessed is the vein that empties and the heart that is renewed."'
        },
        {
          name: 'Sanguine Sacrament',
          set: 'Ixalan',
          cost: '3+',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Rare',
          effects: 'You gain twice X life.  Put Sanguine Sacrament on the bottom of its owner\'s library.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Sanguine-Sacrement-Ixalan-Spoiler-216x302.png',
          flavor: '"As the sun sets to make way for dawn, so we turn to darkness to bring about the coming salvation."'
        },
        {
          name: 'Settle the Wreckage',
          set: 'Ixalan',
          cost: '4',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Rare',
          effects: 'Exile all attacking creatures target player controls.  That player searches his or her library for that many basic land cards, put those cards onto the battlefield tapped, then shuffle his or her library.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Settle-the-Wreckage-Ixalan-Spoiler-216x302.png'
        },
        {
          name: 'Sheltering Light',
          set: 'Ixalan',
          cost: '1',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Target creature gains indestructible until end of turn.  Scry 1. (Damage and effects that say "destroy" don\'t destroy the creature.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Sheltering-Light-Ixalan-Spoiler-216x302.png',
          flavor: 'Those who wield the power of the sun protect the Empire from darkness.'
        },
        {
          name: 'Shining Aerosaur',
          set: 'Ixalan',
          cost: '5',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dinosaur',
          rarity: 'Common',
          effects: 'Flying',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Shining-Aerosaur-Ixalan-Spoiler-216x302.png',
          power: '3',
          toughness: '4',
          flavor: '"The invaders cloak themselves in the shadows of dusk.  Aerosaurs hide in the brilliance of the noonday sun." --Caparocti Sunborn'
        },
        {
          name: 'Skyblade of the Legion',
          set: 'Ixalan',
          cost: '2',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Vampire Soldier',
          rarity: 'Common',
          effects: 'Flying',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Skyblade-of-the-Legion-Ixalan-Spoiler-216x302.png',
          power: '1',
          toughness: '3',
          flavor: 'Vampires call the gift of flight "exultation."  For their enemies, it brings only sorrow.'
        },
        {
          name: 'Slash of Talons',
          set: 'Ixalan',
          cost: '1',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Slash of Talons deals 2 damage to target attacking or blocking creature.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Slash-of-Talons-Ixalan-Spoiler-216x302.png',
          flavor: '"The amber sun smokes with fury, gazing on foes that gather like ants invading our home.  We are ready!  Blade and claw strike as one." --Huatli'
        },
        {
          name: 'Steadfast Armasaur',
          set: 'Ixalan',
          cost: '4',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dinosaur',
          rarity: 'Uncommon',
          effects: 'Vigilance\n(1W), (T): Steadfast Armasaur deals damage equal to its toughness to target creature blocking or blocked by it.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Steadfast-Armasaur-Ixalan-Spoiler-216x302.png',
          power: '2',
          toughness: '3',
          flavor: '"Like the mighty armasaur, we will defend against all who invade our shores." --Itzama the Crested'
        },
        {
          name: 'Sunrise Seeker',
          set: 'Ixalan',
          cost: '5',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Human Scout',
          rarity: 'Common',
          effects: 'Vigilance\nWhen Sunrise Seeker enters the battlefield, it explores. (Reveal the top card of your library.  Put that card into your hand if it\'s a land.  Otherwise, put a +1/+1 counter on this creature, then put the card back or put it into your graveyard.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Sunrise-Seeker-Ixalan-Spoiler-216x302.png',
          power: '3',
          toughness: '3'
        },
        {
          name: 'Territorial Hammerskull',
          set: 'Ixalan',
          cost: '3',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dinosaur',
          rarity: 'Common',
          effects: 'Whenever Territorial Hammerskull attacks, tap target creature an opponent controls.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Territorial-Hammerskull-Ixalan-Spoiler-216x302.png',
          power: '2',
          toughness: '3',
          flavor: 'From the eyes up, it\'s solid bone and stubbornness.'
        },
        {
          name: 'Tocatli Honor Guard',
          set: 'Ixalan',
          cost: '2',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Human Soldier',
          rarity: 'Rare',
          effects: 'Creatures entering the battlefield don\'t cause abilities to trigger.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Tocatli-Honor-Guard-Ixalan-Spoiler-216x302.png',
          power: '1',
          toughness: '3',
          flavor: 'The glorious city of Pachatupa is the center of the Sun Empire, and Tocatli, the emperor\'s palace, is its glowing heart.'
        },
        {
          name: 'Vampire\'s Zeal',
          set: 'Ixalan',
          cost: '1',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Target creature gets +2/+2 until end of turn.  If it\'s a Vampire, it gains first strike until end of turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Vampires-Zeal-Ixalan-Spoiler-216x302.png',
          flavor: 'The Feast of Blood sends new life essence flowing through the vampire who partakes, manifesting as even greater strength and speed.'
        },
        {
          name: 'Wakening Sun\'s Avatar',
          set: 'Ixalan',
          cost: '8',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dinosaur Avatar',
          rarity: 'Mythic',
          effects: 'When Wakening Sun\'s Avatar enters the battlefield, if you cast it from your hand, destroy all non-Dinosaur creatures.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Wakening-Suns-Avatar-Ixalan-Spoiler-216x302.png',
          power: '7',
          toughness: '7',
          flavor: '"Kinjalli\'s encompassing rays herald new life in the moment of the sun\'s dawning." --Chitlati, Lightning Rider'
        },
        {
          name: 'Air Elemental',
          set: 'Ixalan',
          cost: '5',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Elemental',
          rarity: 'Uncommon',
          effects: 'Flying',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Air-Elemental-Ixalan-Spoiler-216x302.png',
          power: '4',
          toughness: '4',
          flavor: 'As the ship approached, the jade totem rose high overhead.  Power rippled.  Eyes of stone glowed and crackled.  Out hissed a breath of the world, and a windstorm came alive.'
        },
        {
          name: 'Arcane Adaptation',
          set: 'Ixalan',
          cost: '3',
          color: 'Blue',
          supertype: 'Enchantment',
          rarity: 'Rare',
          effects: 'As Arcane Adaptation enters the battlefield, choose a creature type.\nCreatures you control are the chosen type in addition to their other types.  The same is true for creature spells you control and creature cards you own that aren\'t on the battlefield.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Arcane-Adaptation-Ixalan-Spoiler-216x302.png'
        },
        {
          name: 'Cancel',
          set: 'Ixalan',
          cost: '3',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Counter target spell.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Cancel-Ixalan-Spoiler-216x302.png',
          flavor: '"Hold your fire, obviously." --Captain Brandis Thorn'
        },
        {
          name: 'Chart a Course',
          set: 'Ixalan',
          cost: '2',
          color: 'Blue',
          supertype: 'Sorcery',
          rarity: 'Uncommon',
          effects: 'Draw two cards.  Then discard a card unless you attacked with a creature this turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Chart-a-Course-Ixalan-Spoiler-216x302.png',
          flavor: 'While other pirates prowl for treasure, Captain Parrish plunders secrets.'
        },
        {
          name: 'Daring Saboteur',
          set: 'Ixalan',
          cost: '2',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Human Pirate',
          rarity: 'Rare',
          effects: '(2U): Daring Saboteur can\'t be blocked this turn.\nWhenever Daring Saboteur deals combat damage to a player, you may draw a card.  If you do, discard a card.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Daring-Saboteur-Ixalan-Spoiler-216x302.png',
          power: '2',
          toughness: '1',
          flavor: '"They\'ll never see me coming."'
        },
        {
          name: 'Deadeye Quartermaster',
          set: 'Ixalan',
          cost: '4',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Human Pirate',
          rarity: 'Uncommon',
          effects: 'When Deadeye Quartermaster enters the battlefield, search your library for an Equipment or Vehicle card, reveal it, put it into your hand, then shuffle your library.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Deadeye-Quartermaster-Ixalan-Spoilers-216x302.png',
          power: '2',
          toughness: '2',
          flavor: '"Welcome aboard, mate!  You\'re going to need this."'
        },
        {
          name: 'Deeproot Waters',
          set: 'Ixalan',
          cost: '3',
          color: 'Blue',
          supertype: 'Enchantment',
          rarity: 'Uncommon',
          effects: 'Whenever you cast a Merfolk spell, create a 1/1 blue Merfolk creature token with hexproof. (A creature with hexproof can\'t be the target of spells or abilities your opponents control.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/08/Deeproot-Waters-Ixalan-Spoiler-216x302.png',
          flavor: 'A visit to the Deeproot Tree and its ancient spring replenishes a merfolk\'s connection to nature.'
        },
        {
          name: 'Depths of Desire',
          set: 'Ixalan',
          cost: '3',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Return target creature to its owners hand.  Create a colorless Treasure artifact token with "(T), Sacrifice this artifact: Add one mana of any color to your mana pool."',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Depths-of-Desire-Ixalan-Spoiler-216x302.png',
          flavor: 'Pockets full of gold, lungs full of brine.'
        },
        {
          name: 'Dive Down',
          set: 'Ixalan',
          cost: '1',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Target creature you control gets +0/+3 and gains hexproof until end of turn. (It can\'t be the target of spells or abilities your opponents control.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Dive-Down-Ixalan-Spoiler-216x302.png',
          flavor: '"Seeing the river is not the same as seeing the fish."'
        },
        {
          name: 'Dreamcaller Siren',
          set: 'Ixalan',
          cost: '4',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Siren Pirate',
          rarity: 'Rare',
          effects: 'Flash\nFlying\nDreamcaller Siren can block only creatures with flying.\nWhen Dreamcaller Siren enters the battlefield, if you control another Pirate, tap up to two target nonland permanents.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Dreamcaller-Siren-Ixalan-Spoiler-216x302.png',
          power: '3',
          toughness: '3'
        },
        {
          name: 'Entrancing Melody',
          set: 'Ixalan',
          cost: '3+',
          color: 'Blue',
          supertype: 'Sorcery',
          rarity: 'Rare',
          effects: 'Gain control of target creature with converted mana cost X.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/08/Entrancing-Melody-Ixalan-Spoiler-216x302.png',
          flavor: 'The stronger the will, the more bewitching the song.'
        },
        {
          name: 'Favorable Winds',
          set: 'Ixalan',
          cost: '2',
          color: 'Blue',
          supertype: 'Enchantment',
          rarity: 'Uncommon',
          effects: 'Creatures you control with flying get +1/+1.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Favorable-Winds-216x302.png',
          flavor: '"Like ribbons of wind and wisdom the coatls fly, twisting mystery into truth, shaping the clouds to suit their inscrutable will." --Huatli'
        },
        {
          name: 'Fleet Swallower',
          set: 'Ixalan',
          cost: '7',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Fish',
          rarity: 'Rare',
          effects: 'Whenever Fleet Swallower attacks, target opponent player puts the top half of his or her library into his or her graveyard, rounded up.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Fleet-Swallower.png',
          power: '6',
          toughness: '6',
          flavor: '"Captain, I think that island is following us."'
        },
        {
          name: 'Headwater Sentries',
          set: 'Ixalan',
          cost: '4',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Merfolk Warrior',
          rarity: 'Common',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Headwater-Sentries-Ixalan-Spoiler-216x302.png',
          power: '2',
          toughness: '5',
          flavor: '"The elders say that if the intruders discovered the secret of the golden city, it would mean an end to our people."'
        },
        {
          name: 'Herald of Secret Streams',
          set: 'Ixalan',
          cost: '4',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Merfolk Warrior',
          rarity: 'Rare',
          effects: 'Creatures you control with +1/+1 counters on them can\'t be blocked.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Herald-of-Secret-Streams-Ixalan-Spoiler-216x302.png',
          power: '2',
          toughness: '3',
          flavor: '"You might as well try to stop the waterfall."'
        },
        {
          name: 'Jace, Cunning Castaway',
          set: 'Ixalan',
          cost: '3',
          color: 'Blue',
          supertype: 'Legendary Planeswalker',
          subtype: 'Jace',
          rarity: 'Mythic',
          effects: '+1: Whenever one or more creatures you control deal combat damage to a player this turn, draw a card, then discard a card.\n-2: Create a 2/2 blue Illusion creature with "When this creature becomes the target of a spell, sacrifice it."\n-5: Create two tokens that are copies of Jace, Cunning Castaway, except they\'re not legendary.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/08/Jace-Cunning-Castaway-Ixalan-Spoiler-216x302.png',
          loyalty: '3'
        },
        {
          name: 'Kopala, Warden of Waves',
          set: 'Ixalan',
          cost: '3',
          color: 'Blue',
          supertype: 'Legendary Creature',
          subtype: 'Merfolk Wizard',
          rarity: 'Rare',
          effects: 'Spells your opponents cast that target a Merfolk you control cost (2) more to cast.\nAbilities your opponents activate that target a Merfolk you control cost (2) more to activate.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Kopala-Warden-of-Waves-Ixalan-Spoiler-216x302.png',
          power: '2',
          toughness: '2',
          flavor: '"I know these waters better than you know yourselves."'
        },
        {
          name: 'Lookout\'s Dispersal',
          set: 'Ixalan',
          cost: '3',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Lookout\'s Dispersal costs (1) less to cast if you control a Pirate.\nCounter target spell unless its controller pays (4).',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Lookouts-Dispersal-216x300.png',
          flavor: 'Her song plucks the strings of the storm, shifting wind and storm into a harmony that will carry her ship to safety.'
        },
        {
          name: 'Navigator\'s Ruin',
          set: 'Ixalan',
          cost: '3',
          color: 'Blue',
          supertype: 'Enchantment',
          rarity: 'Uncommon',
          effects: 'Raid -- At the beginning of your end step, if you attacked with a creature this turn, target opponent puts the top four cards of his or her library into his or her graveyard.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Navigator%E2%80%99s-Ruin-Ixalan-Spoiler-216x302.png',
          flavor: '"You won\'t be needing this.  Or this.  Or these..."'
        },
        {
          name: 'One With the Wind',
          set: 'Ixalan',
          cost: '2',
          color: 'Blue',
          supertype: 'Enchantment',
          subtype: 'Aura',
          rarity: 'Common',
          effects: 'Enchant creature\nEnchanted creature gets +2/+2 and has flying.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/One-With-the-Wind-Ixalan-Spoiler-216x302.png',
          flavor: '"River and sea, jungle and sky.  Water flows freely between the two halves of the world.  We are creatures of the water." --Shaper Tuvasa'
        },
        {
          name: 'Opt',
          set: 'Ixalan',
          cost: '1',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Scry 1. (Look at the top card of your library.  You may put that card on the bottom of your library.)\nDraw a card.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Opt-Ixalan-Spoiler-216x302.png',
          flavor: '"It\'s easy to anticipate Captain Storm\'s orders: take the more dangerous route."'
        },
        {
          name: 'Overflowing Insight',
          set: 'Ixalan',
          cost: '7',
          color: 'Blue',
          supertype: 'Sorcery',
          rarity: 'Mythic',
          effects: 'Target player draws seven cards.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Overflowing-Insight-Ixalan-Spoiler-216x302.png',
          flavor: 'The truth came to Kumena like the Great River\'s torrent: the only way to keep his enemies away from the hidden city was to claim its power for himself.'
        },
        {
          name: 'Perilous Voyage',
          set: 'Ixalan',
          cost: '2',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Return target nonland permanent you don\'t control to its owner\'s hand.  If its converted mana cost was 2 or less, scry 2.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Perilous-Voyage-216x302.jpg',
          flavor: 'For the first time in her life, Vraska tried to prevent death.'
        },
        {
          name: 'Pirate\'s Prize',
          set: 'Ixalan',
          cost: '4',
          color: 'Blue',
          supertype: 'Sorcery',
          rarity: 'Common',
          effects: 'Draw two cards.  Create a colorless Treasure token with "(T), Sacrifice this artifact: Add one mana of any color to your mana pool."',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Pirates-Prize-Ixalan-Spoiler-216x302.png',
          flavor: 'Nothing warms the heart like plunder.'
        },
        {
          name: 'Prosperous Pirates',
          set: 'Ixalan',
          cost: '5',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Human Pirate',
          rarity: 'Common',
          effects: 'When Prosperous Pirates enters the battlefield, create two colorless Treasure tokens with "(T), Sacrifice this artifact: Add one mana of any color to your mana pool."',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/08/Prosperous-Pirates-Ixalan-Spoiler-216x302.png',
          power: '3',
          toughness: '4',
          flavor: 'The floating city of High and Dry hasn\'t yet sunk under the weight of gold, but it\'s not for want of trying.'
        },
        {
          name: 'River Sneak',
          set: 'Ixalan',
          cost: '2',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Merfolk Warrior',
          rarity: 'Uncommon',
          effects: 'River Sneak can\'t be blocked.\nWhenever another Merfolk enters the battlefield under your control, River Sneak gets +1/+1 until end of turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/River-Sneak-Ixalan-Spoiler-216x302.png',
          power: '1',
          toughness: '1',
          flavor: 'No ripples, no splashes, no warning.'
        },
        {
          name: 'River\'s Rebuke',
          set: 'Ixalan',
          cost: '6',
          color: 'Blue',
          supertype: 'Sorcery',
          rarity: 'Rare',
          effects: 'Return all nonland permanents target player controls to their owner\'s hand.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Rivers-Rebuke-Ixalan-Spoiler-216x302.png',
          flavor: 'Carefully following the thaumatic compass Bolas had given her, Vraska blundered straight into the River Heralds\' trap.'
        },
        {
          name: 'Run Aground',
          set: 'Ixalan',
          cost: '4',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Put target artifact or creature on top of its owner\'s library.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Run-Aground-Ixalan-Spoiler-216x302.png',
          flavor: '"That\'s the first time I\'ve seen the ground do the running." --Captain Brinely Rage'
        },
        {
          name: 'Sailor of Means',
          set: 'Ixalan',
          cost: '3',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Human Pirate',
          rarity: 'Common',
          effects: 'When Sailor of Means enters the battlefield, create a colorless Treasure token with "(T), Sacrifice this artifact: Add one mana of any color to your mana pool."',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Sailor-of-Means-Ixalan-Spoiler-216x302.png',
          power: '1',
          toughness: '4',
          flavor: 'In the Brazen Coalition, the wheels of business are greased with plunder.'
        },
        {
          name: 'Search for Azcanta',
          set: 'Ixalan',
          cost: '2',
          color: 'Blue',
          supertype: 'Legendary Enchantment',
          rarity: 'Rare',
          effects: 'At the beginning of your upkeep, you may look at the top card of your library.  You may put it into your graveyard.  Then if you have seven or more cards in your graveyard, you may transform Search for Azcanta.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Search-for-Azcanta-Ixalan-Spoiler-216x302.png',
          flavor: 'The Sunken Ruin houses all the learning of a long-forgotten age.'
        },
        {
          name: 'Azcanta, the Sunken Ruin',
          set: 'Ixalan',
          cost: '0',
          color: 'Colorless',
          supertype: 'Legendary Land',
          rarity: 'Rare',
          effects: '(Transforms from Search for Azcanta)\n(T): Add (U) to your mana pool.\n(2U), (T): Look at the top four cards of your library.  You may reveal a noncreature, nonland card from among them and put it into your hand.  Put the rest on the bottom of your library in any order.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Azcanta-the-Sunken-Ruin-Ixalan-Spoiler-216x302.png'
        },
        {
          name: 'Shaper Apprentice',
          set: 'Ixalan',
          cost: '2',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Merfolk Wizard',
          rarity: 'Common',
          effects: 'Shaper Apprentice has flying as long as you control another Merfolk.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Shaper-Apprentice-Ixalan-Spoiler-216x302.png',
          power: '2',
          toughness: '1',
          flavor: 'The River Heralds would wreck a thousand ships to keep intruders from finding the golden city.'
        },
        {
          name: 'Shipwreck Looter',
          set: 'Ixalan',
          cost: '2',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Human Pirate',
          rarity: 'Common',
          effects: 'Raid -- When Shipwreck Looter enters the battlefield, if you attacked with a creature this turn, you may draw a card.  If you do, discard a card.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Shipwreck-Looter-Ixalan-Spoiler-216x302.png',
          power: '2',
          toughness: '1',
          flavor: 'One pirate\'s wreck is another\'s reward.'
        },
        {
          name: 'Shore Keeper',
          set: 'Ixalan',
          cost: '1',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Trilobite',
          rarity: 'Common',
          effects: '(7U), (T), Sacrifice Shore Keeper: Draw three cards.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Shore-Keeper-Ixalan-Spoiler-216x302.png',
          power: '0',
          toughness: '3',
          flavor: 'Over their long life spans, the larger trilobites accumulate vast treasure troves in their guts.'
        },
        {
          name: 'Siren Lookout',
          set: 'Ixalan',
          cost: '3',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Siren Pirate',
          rarity: 'Common',
          effects: 'Flying\nWhen Siren Lookout enters the battlefield, it explores. (Reveal the top card of your library.  Put that card into your hand if it\'s a land.  Otherwise, put a +1/+1 counter on this creature, then put the card back or put it into your graveyard.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Siren-Lookout-Ixalan-Spoiler-216x302.png',
          power: '1',
          toughness: '2'
        },
        {
          name: 'Siren Stormtamer',
          set: 'Ixalan',
          cost: '1',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Siren Pirate Wizard',
          rarity: 'Uncommon',
          effects: 'Flying\n(U), Sacrifice Siren Stormtamer: Counter target spell or ability that targets you or a creature you control.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Siren-Stormtamer-Ixalan-Spoilers-216x302.png',
          power: '1',
          toughness: '1',
          flavor: 'He\'s the calm that hides the coming storm.'
        },
        {
          name: 'Siren\'s Ruse',
          set: 'Ixalan',
          cost: '2',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Exile target creature you control, then return that card to the battlefield under its owner\'s control.  If a Pirate was exiled this way, draw a card.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Sirens-Ruse-Ixalan-Spoiler-216x302.png',
          flavor: 'Deception and misdirection are the heart of the pirate\'s arsenal.'
        },
        {
          name: 'Spell Pierce',
          set: 'Ixalan',
          cost: '1',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Counter target noncreature spell unless its controller pays (2).',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Spell-Pierce-216x302.png',
          flavor: '"A fool\'s fire is quickly quenched." --Shaper Kumena'
        },
        {
          name: 'Spell Swindle',
          set: 'Ixalan',
          cost: '5',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Rare',
          effects: 'Counter target spell.  Create X colorless Treasure tokens, where X is that spell\'s converted mana cost.  They have "(T), Sacrifice this artifact: Add one mana of any color to your mana pool."',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Spell-Swindle-Ixalan-Spoiler-216x302.png'
        },
        {
          name: 'Storm Fleet Aerialist',
          set: 'Ixalan',
          cost: '2',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Human Pirate',
          rarity: 'Uncommon',
          effects: 'Flying\nRaid -- Storm Fleet Aerialist enters the battlefield with a +1/+1 counter on it if you attacked with a creature this turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Storm-Fleet-Aerialist-Ixalan-Spoiler-216x302.png',
          power: '1',
          toughness: '2',
          flavor: '"Only one thing beats the freedom of the sea: the freedom of the sky."'
        },
        {
          name: 'Storm Fleet Spy',
          set: 'Ixalan',
          cost: '3',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Human Pirate',
          rarity: 'Uncommon',
          effects: 'Raid -- When Storm Fleet Spy enters the battlefield, if you attacked with a creature this turn, draw a card.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Storm-Fleet-Spy-Ixalan-Spoiler-216x302.png',
          power: '2',
          toughness: '2',
          flavor: '"They\'re searching in the same direction we are.  And for the same thing, I\'d wager."'
        },
        {
          name: 'Storm Sculptor',
          set: 'Ixalan',
          cost: '4',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Merfolk Wizard',
          rarity: 'Common',
          effects: 'Storm Sculptor can\'t be blocked.\nWhen Storm Sculptor enters the battlefield, return a creature you control to its owner\'s hand.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Storm-Sculptor-Ixalan-Spoiler-216x302.png',
          power: '3',
          toughness: '2',
          flavor: 'In his hands, the wind can become a weapon or a means of escape.'
        },
        {
          name: 'Tempest Caller',
          set: 'Ixalan',
          cost: '4',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Merfolk Wizard',
          rarity: 'Uncommon',
          effects: 'When Tempest Caller enters the battlefield, tap all creatures target opponent controls.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Tempest-Caller-Ixalan-Spoiler-216x302.png',
          power: '2',
          toughness: '3',
          flavor: '"I *am* the storm."'
        },
        {
          name: 'Watertrap Weaver',
          set: 'Ixalan',
          cost: '3',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Merfolk Wizard',
          rarity: 'Common',
          effects: 'When Watertrap Weaver enters the battlefield, tap target creature an opponent controls.  That creature doesn\'t untap during its controller\'s untap step.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Watertrap-Weaver-Ixalan-Spoiler-216x302.png',
          power: '2',
          toughness: '2',
          flavor: 'The river is a powerful friend.'
        },
        {
          name: 'Wind Strider',
          set: 'Ixalan',
          cost: '5',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Merfolk Wizard',
          rarity: 'Common',
          effects: 'Flash\nFlying',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Wind-Strider-Ixalan-Spoiler-216x302.png',
          power: '3',
          toughness: '3',
          flavor: '"Currents are currents, whether in sea or sky."'
        },
        {
          name: 'Anointed Deacon',
          set: 'Ixalan',
          cost: '5',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Vampire Cleric',
          rarity: 'Common',
          effects: 'At the beginning of combat on your turn, you may have target Vampire get +2/+0 until end of turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Anointed-Deacon-Ixalan-Spoiler-216x302.png',
          power: '3',
          toughness: '3',
          flavor: 'Inspiration is red as rubies, flowing like honeyed wine.'
        },
        {
          name: 'Arguel\'s Blood Fast',
          set: 'Ixalan',
          cost: '2',
          color: 'Black',
          supertype: 'Legendary Enchantment',
          rarity: 'Rare',
          effects: '(1B), Pay 2 life: Draw a card.\nAt the beginning of your upkeep, if you have 5 or less life, you may transform Arguel\'s Blood Fast.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Arguels-Blood-Fast-Ixalan-Spoiler-216x302.png',
          flavor: 'Arguel\'s vision led him into the jungles of Ixalan...'
        },
        {
          name: 'Temple of Aclazotz',
          set: 'Ixalan',
          cost: '0',
          color: 'Colorless',
          supertype: 'Legendary Land',
          rarity: 'Rare',
          effects: '(Transforms from Arguel\'s Blood Fast)\n(T): Add (B) to your mana pool.\n(T), Sacrifice a creature: You gain life equal to the sacrificed creature\'s toughness.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Temple-of-Aclazotz-Ixalan-Spoiler-216x302.png',
          flavor: '...to the lost temple of a bat-god of night, eternal enemy to the Threefold Sun.'
        },
        {
          name: 'Bishop of the Bloodstained',
          set: 'Ixalan',
          cost: '5',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Vampire Cleric',
          rarity: 'Uncommon',
          effects: 'When Bishop of the Bloodstained enters the battlefield, target opponent loses 1 life for each Vampire you control.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Bishop-of-the-Bloodstained-Ixalan-Spoiler-216x302.png',
          power: '3',
          toughness: '3',
          flavor: '"They shall give us all they have as penance for their resistance.  Their ships.  Their goods.  Their rebellious blood."'
        },
        {
          name: 'Blight Keeper',
          set: 'Ixalan',
          cost: '1',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Bat Imp',
          rarity: 'Common',
          effects: '(7B), (T), Sacrifice Blight Keeper: Target opponent loses 4 life and you gain 4 life.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Blight-Keeper-Ixalan-Spoiler-216x302.png',
          power: '1',
          toughness: '1',
          flavor: 'It withers fruit and flesh alike.'
        },
        {
          name: 'Bloodcrazed Paladin',
          set: 'Ixalan',
          cost: '2',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Vampire Knight',
          rarity: 'Rare',
          effects: 'Flash\nBloodcrazed Paladin enters the battlefield with a +1/+1 counter on it for each creature that died this turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Bloodcrazed-Paladin-Ixalan-Spoiler-216x302.png',
          power: '1',
          toughness: '1',
          flavor: 'When a paladin undertaking the Blood Fast finally gives in to hunger, the violence is sudden, explosive, and complete.'
        },
        {
          name: 'Boneyard Parley',
          set: 'Ixalan',
          cost: '7',
          color: 'Black',
          supertype: 'Sorcery',
          rarity: 'Mythic',
          effects: 'Exile up to five creature cards from graveyards.  An opponent separates those cards into two piles.  Put all cards from the pile of your choice on the battlefield under your control and the rest into their owners\' graveyards.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/08/Boneyard-Parley-Ixalan-Spoiler-216x302.png'
        },
        {
          name: 'Contract Killing',
          set: 'Ixalan',
          cost: '5',
          color: 'Black',
          supertype: 'Sorcery',
          rarity: 'Common',
          effects: 'Destroy target creature.  Create two colorless Treasure artifact tokens with "(T), Sacrifice this artifact: Add one mana of any color to your mana pool."',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Contract-Killing-Ixalan-Spoiler-216x302.png',
          flavor: 'For a price, the floating city of High and Dry offers all the amenities a pirate could want: rest, recreation, and revenge.'
        },
        {
          name: 'Costly Plunder',
          set: 'Ixalan',
          cost: '2',
          color: 'Black',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'As an additional cost to cast Costly Plunder, sacrifice an artifact or creature.\nDraw two cards.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Costly-Plunder-Ixalan-Spoiler-216x302.png',
          flavor: 'No lock of iron is a match for Vraska\'s will of stone.'
        },
        {
          name: 'Dark Nourishment',
          set: 'Ixalan',
          cost: '5',
          color: 'Black',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Dark Nourishment deals 3 damage to target creature or player.  You gain 3 life.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Dark-Nourishment-Ixalan-Spoiler-216x302.png',
          flavor: 'Demons lurk in the shadows of ancient ruins, spreading plague and corruption across the land.'
        },
        {
          name: 'Deadeye Tormentor',
          set: 'Ixalan',
          cost: '3',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Human Pirate',
          rarity: 'Common',
          effects: 'Raid -- When Deadeye Tormentor enters the battlefield, if you attacked with a creature this turn, target opponent discards a card.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/08/Deadeye-Tormentor-Ixalan-Spoiler-216x302.png',
          power: '2',
          toughness: '2',
          flavor: 'Despite their noble heritage, the pirates of the Deadeye Fleet are known for underhanded tactics and despicable trickery.'
        },
        {
          name: 'Deadeye Tracker',
          set: 'Ixalan',
          cost: '1',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Human Pirate',
          rarity: 'Rare',
          effects: '(1B), (T): Exile two cards from an opponent\'s graveyard.  Deadeye Tracker explores. (Reveal the top card of your library.  Put that card into your hand if it\'s a land.  Otherwise, put a +1/+1 counter on this creature, then put the card back or put it into your graveyard.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Deadeye-Tracker-Ixalan-Spoiler-216x302.png',
          power: '1',
          toughness: '1'
        },
        {
          name: 'Deathless Ancient',
          set: 'Ixalan',
          cost: '6',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Vampire Knight',
          rarity: 'Uncommon',
          effects: 'Flying\nTap three untapped Vampires you control: Return Deathless Ancient from your graveyard to your hand.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/08/Deathless-Ancient-Ixalan-Spoiler-216x302.png',
          power: '4',
          toughness: '4',
          flavor: '"Ancient one, we have reached the promised shore.  The Immortal Sun is near.  Drink and awake."'
        },
        {
          name: 'Desperate Castaways',
          set: 'Ixalan',
          cost: '2',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Human Pirate',
          rarity: 'Common',
          effects: 'Desperate Castaways can\'t attack unless you control an artifact.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Desperate-Castaways-216x302.png',
          power: '2',
          toughness: '3',
          flavor: 'A pirate crew without a ship is a crew that will do anything to get one.'
        },
        {
          name: 'Dire Fleet Hoarder',
          set: 'Ixalan',
          cost: '2',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Human Pirate',
          rarity: 'Common',
          effects: 'When Dire Fleet Hoarder dies, create a colorless Treasure artifact token with "(T), Sacrifice this artifact: Add one mana of any color to your mana pool."',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Dire-Fleet-Hoarder-216x302.png',
          power: '2',
          toughness: '1',
          flavor: 'Among the pirates of the Brazen Coalition, the only thing more dangerous than failure is success.'
        },
        {
          name: 'Dire Fleet Interloper',
          set: 'Ixalan',
          cost: '4',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Human Pirate',
          rarity: 'Common',
          effects: 'Menace\nWhen Dire Fleet Interloper enters the battlefield, it explores. (Reveal the top card of your library.  Put that card into your hand if it\'s a land.  Otherwise, put a +1/+1 counter on this creature, then put the card back or put it into your graveyard.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Dire-Fleet-Interloper-Ixalan-Spoiler-216x302.png',
          power: '2',
          toughness: '2'
        },
        {
          name: 'Dire Fleet Ravager',
          set: 'Ixalan',
          cost: '5',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Orc Pirate Wizard',
          rarity: 'Mythic',
          effects: 'Menace, deathtouch\nWhen Dire Fleet Ravager enters the battlefield, each player loses a third of his or her life, rounded up.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Dire-Fleet-Ravager-Ixalan-Spoiler-216x302.png',
          power: '4',
          toughness: '4',
          flavor: 'His fists fume with the decay of death, each strike a plague on the hearts of his enemies.'
        },
        {
          name: 'Duress',
          set: 'Ixalan',
          cost: '1',
          color: 'Black',
          supertype: 'Sorcery',
          rarity: 'Common',
          effects: 'Target opponent reveals his or her hand.  You choose a noncreature, nonland card from it.  That player discards that card.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Duress-Ixalan-Spoiler-216x302.png',
          flavor: 'Solitude and starvation are brutal punishments, but even worse is all that time to think.'
        },
        {
          name: 'Fathom Fleet Captain',
          set: 'Ixalan',
          cost: '2',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Human Pirate',
          rarity: 'Rare',
          effects: 'Menace\nWhenever Fathom Fleet Captain attacks, if you control another nontoken Pirate, you may pay (2).  If you do, create a 2/2 black Pirate creature token with menace.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Fathom-Fleet-Captain-Ixalan-Spoiler-216x302.png',
          power: '2',
          toughness: '1',
          flavor: '"Join me, and take the world for yourself!"'
        },
        {
          name: 'Fathom Fleet Cutthroat',
          set: 'Ixalan',
          cost: '4',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Human Pirate',
          rarity: 'Common',
          effects: 'When Fathom Fleet Cutthroat enters the battlefield, destroy target creature an opponent controls that was dealt damage this turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Fathom-Fleet-Cutthroat-Ixalan-Spoiler-216x302.png',
          power: '3',
          toughness: '3',
          flavor: '"It was a bad evening for you, mate.  Now it\'s chow time for the sharks."'
        },
        {
          name: 'Grim Captain\'s Call',
          set: 'Ixalan',
          cost: '3',
          color: 'Black',
          supertype: 'Sorcery',
          rarity: 'Uncommon',
          effects: 'Return a Pirate card from your graveyard to your hand, then do the same for Vampire, Dinosaur, and Merfolk.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Grim-Captains-Call-Ixalan-Spoiler-216x302.png',
          flavor: 'When the battle is over, the bitterest foes at last find common ground.'
        },
        {
          name: 'Heartless Pillage',
          set: 'Ixalan',
          cost: '3',
          color: 'Black',
          supertype: 'Sorcery',
          rarity: 'Uncommon',
          effects: 'Target opponent discards two cards.\nRaid -- If you attacked with a creature this turn, create a colorless Treasure artifact token with "(T), Sacrifice this artifact: Add one mana of any color to your mana pool."',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Heartless-Pillage-Ixalan-Spoiler-216x302.png'
        },
        {
          name: 'Kitesail Freebooter',
          set: 'Ixalan',
          cost: '2',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Human Pirate',
          rarity: 'Uncommon',
          effects: 'Flying\nWhen Kitesail Freebooter enters the battlefield, target opponent reveals his or her hand.  You choose a noncreature, nonland card from it.  Exile that card until Kitesail Freebooter leaves the battlefield.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Kitesail-Freebooter-Ixalan-Spoiler-216x302.png',
          power: '1',
          toughness: '2'
        },
        {
          name: 'Lurking Chupacabra',
          set: 'Ixalan',
          cost: '4',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Beast Horror',
          rarity: 'Uncommon',
          effects: 'Whenever a creature you control explores, target creature an opponent controls gets -2/-2 until end of turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Lurking-Chupacabra-Ixalan-Spoiler-216x302.png',
          power: '2',
          toughness: '3',
          flavor: '"Shadow birthed it.  The moon gave it eyes, and the jungle gave it teeth.  But it was Death that taught it cruelty." --Huatli'
        },
        {
          name: 'March of the Drowned',
          set: 'Ixalan',
          cost: '1',
          color: 'Black',
          supertype: 'Sorcery',
          rarity: 'Common',
          effects: 'Choose one -- \n\t* Return target creature card from your graveyard to your hand.\n\t* Return two target Pirate cards from your graveyard to your hand.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/March-of-the-Drowned-Ixalan-Spoiler-216x302.png'
        },
        {
          name: 'Mark of the Vampire',
          set: 'Ixalan',
          cost: '4',
          color: 'Black',
          supertype: 'Enchantment',
          subtype: 'Aura',
          rarity: 'Common',
          effects: 'Enchant creature\nEnchanted creature gets +2/+2 and has lifelink.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Mark-of-the-Vampire-Ixalan-Spoiler-216x302.png',
          flavor: '"Through your sacrifice of self, you become holy.  Through your strength, all will be saved." --From the Rite of Redemption'
        },
        {
          name: 'Queen\'s Agent',
          set: 'Ixalan',
          cost: '6',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Vampire Scout',
          rarity: 'Common',
          effects: 'Lifelink\nWhen Queen\'s Agent enters the battlefield, it explores. (Reveal the top card of your library.  Put that card into your hand if it\'s a land.  Otherwise, put a +1/+1 counter on this creature, then put the card back or put it into your graveyard.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Queen%E2%80%99s-Agent-Ixalan-Spoiler-216x302.png',
          power: '3',
          toughness: '3'
        },
        {
          name: 'Queen\'s Bay Soldier',
          set: 'Ixalan',
          cost: '2',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Vampire Soldier',
          rarity: 'Common',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Queen%E2%80%99s-Bay-Soldier-Ixalan-Spoiler-216x302.png',
          power: '2',
          toughness: '2',
          flavor: 'The soldiers of the Legion of Dusk have come to the colonies at Queen\'s Bay in search of glory and riches.  They are veterans of centuries of warfare, and they thirst for conquest.'
        },
        {
          name: 'Raider\'s Wake',
          set: 'Ixalan',
          cost: '4',
          color: 'Black',
          supertype: 'Enchantment',
          rarity: 'Uncommon',
          effects: 'Whenever an opponent discards a card, that player loses 2 life.\nRaid -- At the beginning of your end step, if you attacked with a creature this turn, target opponent discards a card.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Raiders%E2%80%99-Wake-Ixalan-Spoiler-216x302.png',
          flavor: 'One was spared to tell the gruesome tale.'
        },
        {
          name: 'Revel in Riches',
          set: 'Ixalan',
          cost: '5',
          color: 'Black',
          supertype: 'Enchantment',
          rarity: 'Rare',
          effects: 'Whenever a creature an opponent controls dies, create a colorless Treasure artifact token with "(T), Sacrifice this artifact: Add one mana of any color to your mana pool."\nAt the beginning of your upkeep, if you control ten or more Treasures, you win the game.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Revel-in-Riches-Ixalan-Spoiler-216x302.png'
        },
        {
          name: 'Ruin Raider',
          set: 'Ixalan',
          cost: '3',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Orc Pirate',
          rarity: 'Rare',
          effects: 'Raid -- At the beginning of your end step, if you attacked with a creature this turn, reveal the top card of your library and put that card into your hand.  You lose life equal to the card\'s converted mana cost.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Ruin-Raider-Ixalan-Spoiler-216x302.png',
          power: '3',
          toughness: '2'
        },
        {
          name: 'Ruthless Knave',
          set: 'Ixalan',
          cost: '3',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Orc Pirate',
          rarity: 'Uncommon',
          effects: '(2B), Sacrifice a creature: Create two colorless Treasure artifact tokens with "(T), Sacrifice this artifact: Add one mana of any color to your mana pool."\nSacrifice three Treasures: Draw a card.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Ruthless-Knave-Ixalan-Spoiler-216x302.png',
          power: '3',
          toughness: '2',
          flavor: '"This scum is barely worth the trouble."'
        },
        {
          name: 'Sanctum Seeker',
          set: 'Ixalan',
          cost: '4',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Vampire Knight',
          rarity: 'Rare',
          effects: 'Whenever a Vampire you control attacks, each opponent loses 1 life and you gain 1 life.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Sanctum-Seeker-Ixalan-Spoiler-216x302.png',
          power: '3',
          toughness: '4',
          flavor: 'The Sanctum Seekers were the first of the knightly orders to cross the sea and are still the most zealous.'
        },
        {
          name: 'Seekers\' Squire',
          set: 'Ixalan',
          cost: '2',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Human Scout',
          rarity: 'Uncommon',
          effects: 'When Seekers\' Squire enters the battlefield, it explores. (Reveal the top card of your library.  Put that card into your hand if it\'s a land.  Otherwise, put a +1/+1 counter on this creature, then put the card back or put it into your graveyard.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Seekers%E2%80%99-Squire-Ixalan-Spoiler-216x302.png',
          power: '1',
          toughness: '2',
          flavor: 'Dusk follows the light.'
        },
        {
          name: 'Skittering Heartstopper',
          set: 'Ixalan',
          cost: '1',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Insect',
          rarity: 'Common',
          effects: '(B): Skittering Heartstopper gains deathtouch until end of turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Skittering-Heartstopper-Ixalan-Spoiler-216x302.png',
          power: '1',
          toughness: '2',
          flavor: 'It flows like water over the forest floor, as deadly as the swiftest current.'
        },
        {
          name: 'Skulduggery',
          set: 'Ixalan',
          cost: '1',
          color: 'Black',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Until end of turn, target creature  you control gets +1/+1 and target creature an opponent controls gets -1/-1.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Skulduggery-216x302.png',
          flavor: '"They\'re so much more willing to parley once they\'re hanging from a boom by the ankle!"'
        },
        {
          name: 'Skymarch Bloodletter',
          set: 'Ixalan',
          cost: '3',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Vampire Soldier',
          rarity: 'Common',
          effects: 'Flying\nWhen Skymarch Bloodletter enters the battlefield, target opponent loses 1 life and you gain 1 life.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Skymarch-Bloodletter-Ixalan-Spoiler-216x302.png',
          power: '2',
          toughness: '2',
          flavor: 'From the perpetual shadowsmoke that hung over the ship, a silent form emerged, lips curled with malice and anticipation.'
        },
        {
          name: 'Spreading Rot',
          set: 'Ixalan',
          cost: '5',
          color: 'Black',
          supertype: 'Sorcery',
          rarity: 'Common',
          effects: 'Destroy target land.  Its controller loses 2 life.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Spreading-Rot-Ixalan-Spoiler-216x302.png',
          flavor: '"What is this foul presence that defies the sun\'s cleansing rays?" --Itzama the Crested'
        },
        {
          name: 'Sword-Point Diplomacy',
          set: 'Ixalan',
          cost: '3',
          color: 'Black',
          supertype: 'Sorcery',
          rarity: 'Rare',
          effects: 'Reveal the top three cards of your library.  For each of those cards, put it into your hand unless any opponent pays 3 life.  Then exile the rest.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Sword-Point-Diplomacy-Ixalan-Spoiler-216x302.png',
          flavor: '"Take my blood if you want.  Just don\'t take my gold!"'
        },
        {
          name: 'Vanquish the Weak',
          set: 'Ixalan',
          cost: '3',
          color: 'Black',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Destroy target creature with power 3 or less.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Vanquish-the-Weak-Ixalan-Spoiler-216x302.png',
          flavor: 'The clerics known as condemners punish those who do not recognize the righteous authority of the church.'
        },
        {
          name: 'Vicious Conquistador',
          set: 'Ixalan',
          cost: '1',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Vampire Soldier',
          rarity: 'Uncommon',
          effects: 'Whenever Vicious Conquistador attacks, each opponent loses 1 life.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Vicious-Conquistador-Ixalan-Spoiler-216x302.png',
          power: '1',
          toughness: '2',
          flavor: '"He is ambitions.  Tireless.  And utterly ruthless.  Ideal for the frontier." --Viceroy Elia Sotonores, report to the queen'
        },
        {
          name: 'Vraska\'s Contempt',
          set: 'Ixalan',
          cost: '4',
          color: 'Black',
          supertype: 'Instant',
          rarity: 'Rare',
          effects: 'Exile target creature or planeswalker.  You gain 2 life.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Vraskas-Contempt-Ixalan-Spoiler-216x302.png',
          flavor: 'It wasn\'t long before the taverns of High and Dry were full of whispers about the new captain who could turn a person to stone with a glance.'
        },
        {
          name: 'Walk the Plank',
          set: 'Ixalan',
          cost: '2',
          color: 'Black',
          supertype: 'Sorcery',
          rarity: 'Uncommon',
          effects: 'Destroy target non-Merfolk creature.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/08/Walk-the-Plank-Ixalan-Spoiler-216x302.png',
          flavor: 'When Captain Thorn adds a new ship to his fleet, he gives the crew a simple choice: follow me, or fall in the sea.'
        },
        {
          name: 'Wanted Scoundrels',
          set: 'Ixalan',
          cost: '2',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Human Pirate',
          rarity: 'Uncommon',
          effects: 'When Wanted Scoundrels dies, target opponent creates two colorless Treasure artifact tokens with "(T), Sacrifice this artifact: Add one mana of any color to your mana pool."',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Wanted-Scoundrels-216x302.png',
          power: '4',
          toughness: '3',
          flavor: '"Trust me.  The reward\'s not worth it."'
        },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
      ]);
    });
};
