exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('card-list').del()
    .then(function () {
      // Inserts seed entries
      return knex('card-list').insert([
        {
          name: 'Adanto Vanguard',
          set: 'Ixalan',
          cost: '2',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Vampire Soldier',
          rarity: 'Uncommon',
          effects: 'As long as Adanto Vanguard is attacking, it gets +2/+0 until end of turn.\nPay 4 life: Adanto Vanguard gains indestructible until end of turn. (Damage and effects that say "destroy" don\'t destroy it.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Adanto-Vanguard-Ixalan-Spoiler-216x302.png',
          power: '1',
          toughness: '1'
        },
        {
          name: 'Ashes of the Abhorrent',
          set: 'Ixalan',
          cost: '2',
          color: 'White',
          supertype: 'Enchantment',
          rarity: 'Rare',
          effects: 'Players can\'t cast spells from graveyards or activate abilities of cards in graveyards.\nWhenever a creature dies, you gain 1 life.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Ashes-of-the-Abhorrent-Ixalan-Spoiler-216x302.png',
          flavor: '"Let no trace of the vampires\' foulness remain."'
        },
        {
          name: 'Axis of Mortality',
          set: 'Ixalan',
          cost: '6',
          color: 'White',
          supertype: 'Enchantment',
          rarity: 'Mythic',
          effects: 'At the beginning of your upkeep, you may have two target players exchange life totals.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Axis-of-Mortality-216x302.png',
          flavor: 'The Church of Dusk teaches there is no gain without loss, no triumph without sacrifice, no drink of exquisite crimson without a dying gasp.'
        },
        {
          name: 'Bellowing Aegisaur',
          set: 'Ixalan',
          cost: '6',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dinosaur',
          rarity: 'Uncommon',
          effects: 'Enrage -- Whenever Bellowing Aegisaur is dealt damage, put a +1/+1 counter on each other creature you control.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/08/Bellowing-Aegisaur-216x302.png',
          power: '3',
          toughness: '5',
          flavor: 'Its roaring challenge is punctuated by the slam of its tail on the earth, rousing the herds of the plains.'
        },
        {
          name: 'Bishop of Rebirth',
          set: 'Ixalan',
          cost: '5',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Vampire Cleric',
          rarity: 'Rare',
          effects: 'Vigilance\nWhenever Bishop of Rebirth attacks, return target creature card with converted mana cost 3 or less from your graveyard to the battlefield.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Bishop-of-Rebirth-Ixalan-Spoiler-216x302.png',
          power: '3',
          toughness: '4',
          flavor: '"In the death of the foe lies the resurrection of the faithful."'
        },
        {
          name: 'Bishop\'s Soldier',
          set: 'Ixalan',
          cost: '2',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Vampire Soldier',
          rarity: 'Common',
          effects: 'Lifelink',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Bishop%E2%80%99s-Soldier-Ixalan-Spoiler-216x302.png',
          power: '2',
          toughness: '2',
          flavor: 'Vampires, the noble class of old Torrezon, are guided by their dual loyalties to church and crown.'
        },
        {
          name: 'Bright Reprisal',
          set: 'Ixalan',
          cost: '5',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Destroy target attacking creature.\nDraw a card.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Bright-Reprisal-Ixalan-Spoiler-216x302.png',
          flavor: 'Vampires know blood and the systems that carry it.  And they know exactly where to strike to set it free.'
        },
        {
          name: 'Demystify',
          set: 'Ixalan',
          cost: '1',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Destroy target enchantment.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Demystify-Ixalan-Spoiler-216x302.png',
          flavor: '"The River Heralds carve spells into jade, hoping to steer us from our course.  But what right do they have to keep us from that which once was ours?"'
        },
        {
          name: 'Duskborne Skymarcher',
          set: 'Ixalan',
          cost: '1',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Vampire Cleric',
          rarity: 'Uncommon',
          effects: 'Flying\n(W), (T): Target attacking Vampire gets +1/+1 until end of turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Duskborne-Skymarcher-Ixalan-Spoiler-216x302.png',
          power: '1',
          toughness: '1',
          flavor: '"The hour of Dusk is come."'
        },
        {
          name: 'Emissary of Sunrise',
          set: 'Ixalan',
          cost: '3',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Human Cleric',
          rarity: 'Uncommon',
          effects: 'First strike\nWhen Emissary of Sunrise enters the battlefield, it explores. (Reveal the top card of your library.  Put that card into your hand if it\'s a land.  Otherwise, put a +1/+1 counter on this creature, then put the card back or put it into your graveyard.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Emissary-of-Sunrise-Ixalan-Spoiler-216x302.png',
          power: '2',
          toughness: '1'
        },
        {
          name: 'Encampment Keeper',
          set: 'Ixalan',
          cost: '1',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Hound',
          rarity: 'Common',
          effects: 'First strike\n(7W), Sacrifice Encampment Keeper: Creatures you control get +2/+2 until end of turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Encampment-Keeper-Ixalan-Spoiler-216x302.png',
          power: '1',
          toughness: '1',
          flavor: 'Paladins of the Sanctum Seeker order are an adventurous lot, venturing into the wilds with monstrous mastiffs at their side.'
        },
        {
          name: 'Glorifier of Dusk',
          set: 'Ixalan',
          cost: '5',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Vampire Soldier',
          rarity: 'Uncommon',
          effects: 'Pay 2 life: Glorifier of Dusk gains flying until end of turn.\nPay 2 life: Glorifier of Dusk gains vigilance until end of turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Glorifier-of-Dusk-Ixalan-Spoiler-216x302.png',
          power: '4',
          toughness: '4',
          flavor: '"The blood of the enemy is a sacrament.  The strength it gives proves that our cause is just."'
        },
        {
          name: 'Goring Ceratops',
          set: 'Ixalan',
          cost: '7',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dinosaur',
          rarity: 'Rare',
          effects: 'Double strike\nWhenever Goring Ceratops attacks, other creatures you control gain double strike until end of turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Goring-Ceratops-Ixalan-Spoiler-216x302.png',
          power: '3',
          toughness: '3',
          flavor: '"Follow her footsteps and she will show you the way." --Itzama the Crested'
        },
        {
          name: 'Imperial Aerosaur',
          set: 'Ixalan',
          cost: '4',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dinosaur',
          rarity: 'Uncommon',
          effects: 'Flying\nWhen Imperial Aerosaur enters the battlefield, another target creature you control gets +1/+1 and gains flying until end of turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Imperial-Aerosaur-Ixalan-Spoiler-216x302.png',
          power: '3',
          toughness: '3',
          flavor: 'Its assistance is unnervingly similar to its hunting technique.'
        },
        {
          name: 'Imperial Lancer',
          set: 'Ixalan',
          cost: '1',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Human Knight',
          rarity: 'Uncommon',
          effects: 'Imperial Lancer has double strike as long as you control a Dinosaur.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Imperial-Lancer-Ixalan-Spoiler-216x302.png',
          power: '1',
          toughness: '1',
          flavor: '"Together my mount and I are stronger than either of us apart."'
        },
        {
          name: 'Inspiring Cleric',
          set: 'Ixalan',
          cost: '3',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Vampire Cleric',
          rarity: 'Uncommon',
          effects: 'When Inspiring Cleric enters the battlefield, you gain 4 life.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Inspiring-Cleric-Ixalan-Spoiler-216x302.png',
          power: '3',
          toughness: '2',
          flavor: '"The Immortal Sun will bring us true everlasting life to replace the everlasting shadow of undeath."'
        },
        {
          name: 'Ixalan\'s Binding',
          set: 'Ixalan',
          cost: '4',
          color: 'White',
          supertype: 'Enchantment',
          rarity: 'Uncommon',
          effects: 'When Ixalan\'s Binding enters the battlefield, exile target nonland permanent an opponent controls until Ixalan\'s Binding leaves the battlefield.\nYour opponents can\'t cast spells with the same name as the exiled card.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Ixalan%E2%80%99s-Binding-Ixalan-Spoiler-216x302.png',
          flavor: 'Jace awoke to the certainty that he was lost.'
        },
        {
          name: 'Kinjalli\'s Caller',
          set: 'Ixalan',
          cost: '1',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Human Cleric',
          rarity: 'Common',
          effects: 'Dinosaur spells you cast cost (1) less to cast.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Kinjalli%E2%80%99s-Caller-Ixalan-Spoiler-216x302.png',
          power: '0',
          toughness: '3',
          flavor: 'The people of the Sun Empire worship the sun in three aspects.  Kinjalli is the Wakening Sun, who created humans from clay and baked them in the sun\'s warmth.'
        },
        {
          name: 'Kinjalli\'s Sunwing',
          set: 'Ixalan',
          cost: '3',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dinosaur',
          rarity: 'Rare',
          effects: 'Flying\nCreatures your opponents control enter the battlefield tapped.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Kinjallis-Sunwing-Ixalan-Spoiler-216x302.png',
          power: '2',
          toughness: '3',
          flavor: '"There are moments when I feel I could fly like the sunwing.  Far away would I soar, but always a golden gale pushes me back." --Huatli'
        },
        {
          name: 'Legion Conquistador',
          set: 'Ixalan',
          cost: '3',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Vampire Soldier',
          rarity: 'Common',
          effects: 'When Legion Conquistador enters the battlefield, you may search your library for any number of cards named Legion Conquistador, reveal them, put them into your hand, then shuffle your library.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Legion-Conquistador-216x302.png',
          power: '2',
          toughness: '2',
          flavor: 'The Legion of Dusk sailed from Torrezon in search of glory, riches, and the Immortal Sun.'
        },
        {
          name: 'Legion\'s Judgement',
          set: 'Ixalan',
          cost: '3',
          color: 'White',
          supertype: 'Sorcery',
          rarity: 'Common',
          effects: 'Destroy target creature with power 4 or greater.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Legion%E2%80%99s-Judgment-Ixalan-Spoiler-216x302.png',
          flavor: '"My lance was once wielded by the Venerable Tarrian.  In his name and by his might, I cast you down!"'
        },
        {
          name: 'Legion\'s Landing',
          set: 'Ixalan',
          cost: '1',
          color: 'White',
          supertype: 'Legendary Enchantment',
          rarity: 'Mythic',
          effects: 'When Legion\'s Landing enters the battlefield, create a 1/1 white Vampire creature token with lifelink.\nWhen you attack with three or more creatures, transform Legion\'s Landing.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Legions-Landing-216x302.png',
          flavor: '"I claim this land in the name of the queen." --Adrian Adanto of Lujio'
        },
        {
          name: 'Adanto, the First Fort',
          set: 'Ixalan',
          cost: '0',
          color: 'Colorless',
          supertype: 'Legendary Land',
          rarity: 'Mythic',
          effects: '(Transforms from Legion\'s Landing.)\n(T): Add (W) to your mana pool.\n(2W), (T): Create a 1/1 white Vampire creature token with lifelink.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Adanto-the-First-Fort-216x302.png'
        },
        {
          name: 'Looming Altisaur',
          set: 'Ixalan',
          cost: '4',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dinosaur',
          rarity: 'Common',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Looming-Altisaur-216x300.jpg',
          power: '1',
          toughness: '7',
          flavor: 'Nature can\'t be tamed, but the Sun Empire believes that humans are made stronger when they test themselves against the wild strength of the dinosaurs.'
        },
        {
          name: 'Mavren Fein, Dusk Apostle',
          set: 'Ixalan',
          cost: '3',
          color: 'White',
          supertype: 'Legendary Creature',
          subtype: 'Vampire Cleric',
          rarity: 'Rare',
          effects: 'Whenever one or more nontoken Vampires you control attack, create a 1/1 white Vampire creature token with lifelink.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Mavren-Fein-Dusk-Apostle-Ixalan-Spoiler-216x302.png',
          power: '2',
          toughness: '2',
          flavor: 'In the rapture of his Blood Fast, he destroyed the navigator\'s tools and steered the ship to shore by faith alone.'
        },
        {
          name: 'Paladin of the Bloodstained',
          set: 'Ixalan',
          cost: '4',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Vampire Knight',
          rarity: 'Common',
          effects: 'When Paladin of the Bloodstained enters the battlefield, create a 1/1 white Vampire creature token with lifelink.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Paladin-of-the-Bloodstained-Ixalan-Spoiler-216x302.png',
          power: '3',
          toughness: '2',
          flavor: 'Closely linked to the Church of Dusk, the paladins of the Bloodstained order are devout to the point of fanaticism.'
        },
        {
          name: 'Pious Interdiction',
          set: 'Ixalan',
          cost: '4',
          color: 'White',
          supertype: 'Enchantment',
          subtype: 'Aura',
          rarity: 'Common',
          effects: 'Enchant creature\nWhen Pious Interdiction enters the battlefield, you gain 2 life.\nEnchanted creature can\'t attack or block.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Pious-Interdiction-Ixalan-Spoiler-216x302.png',
          flavor: '"Ours is the true and righteous path.  You will bow before our might."'
        },
        {
          name: 'Priest of the Wakening Sun',
          set: 'Ixalan',
          cost: '1',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Human Cleric',
          rarity: 'Rare',
          effects: 'At the beginning of your upkeep, you may reveal a Dinosaur card from your hand.  If you do, you gain 2 life.\n(3WW), Sacrifice Priest of the Wakening Sun: Search your library for a Dinosaur card, reveal it, put it into your hand, then shuffle your library.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Priest-of-the-Wakening-Sun-Ixalan-Spoiler-216x302.png',
          power: '1',
          toughness: '1'
        },
        {
          name: 'Pterodon Knight',
          set: 'Ixalan',
          cost: '4',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Human Knight',
          rarity: 'Common',
          effects: 'Pterodon Knight has flying as long as you control a Dinosaur.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Pterodon-Knight-Ixalan-Spoiler-216x302.png',
          power: '3',
          toughness: '3',
          flavor: '"To rise like the sun--there is no greater feeling."'
        },
        {
          name: 'Queen\'s Commission',
          set: 'Ixalan',
          cost: '3',
          color: 'White',
          supertype: 'Sorcery',
          rarity: 'Common',
          effects: 'Create two 1/1 white Vampire creature tokens with lifelink.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Queen%E2%80%99s-Commission-Ixalan-Spoiler-216x302.png',
          flavor: '"Let the blood of the impure flow through you.  Only the blessings of the golden city will purge its acrid taste from your mouth." --High Marshal Arguel'
        },
        {
          name: 'Rallying Roar',
          set: 'Ixalan',
          cost: '3',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Creatures you control get +1/+1 until end of turn.  Untap them.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Rallying-Roar-Ixalan-Spoiler-216x302.png',
          flavor: '"The sun\'s strength sings in our hearts!  I have never been more proud of my home and my people." --Huatli'
        },
        {
          name: 'Raptor Companion',
          set: 'Ixalan',
          cost: '2',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dinosaur',
          rarity: 'Common',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Raptor-Companion-Ixalan-Spoiler-216x302.png',
          power: '3',
          toughness: '1',
          flavor: 'A raptor will follow any order as long as that order is "hunt," "kill," or "go for the guts."'
        },
        {
          name: 'Ritual of Rejuvenation',
          set: 'Ixalan',
          cost: '3',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'You gain 4 life.\nDraw a card.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Ritual-of-Rejuvenation-Ixalan-Spoiler-216x302.png',
          flavor: '"Nothing is more sacred than the gift of blood.  Blessed is the vein that empties and the heart that is renewed."'
        },
        {
          name: 'Sanguine Sacrament',
          set: 'Ixalan',
          cost: '3+',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Rare',
          effects: 'You gain twice X life.  Put Sanguine Sacrament on the bottom of its owner\'s library.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Sanguine-Sacrement-Ixalan-Spoiler-216x302.png',
          flavor: '"As the sun sets to make way for dawn, so we turn to darkness to bring about the coming salvation."'
        },
        {
          name: 'Settle the Wreckage',
          set: 'Ixalan',
          cost: '4',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Rare',
          effects: 'Exile all attacking creatures target player controls.  That player searches his or her library for that many basic land cards, put those cards onto the battlefield tapped, then shuffle his or her library.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Settle-the-Wreckage-Ixalan-Spoiler-216x302.png'
        },
        {
          name: 'Sheltering Light',
          set: 'Ixalan',
          cost: '1',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Target creature gains indestructible until end of turn.  Scry 1. (Damage and effects that say "destroy" don\'t destroy the creature.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Sheltering-Light-Ixalan-Spoiler-216x302.png',
          flavor: 'Those who wield the power of the sun protect the Empire from darkness.'
        },
        {
          name: 'Shining Aerosaur',
          set: 'Ixalan',
          cost: '5',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dinosaur',
          rarity: 'Common',
          effects: 'Flying',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Shining-Aerosaur-Ixalan-Spoiler-216x302.png',
          power: '3',
          toughness: '4',
          flavor: '"The invaders cloak themselves in the shadows of dusk.  Aerosaurs hide in the brilliance of the noonday sun." --Caparocti Sunborn'
        },
        {
          name: 'Skyblade of the Legion',
          set: 'Ixalan',
          cost: '2',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Vampire Soldier',
          rarity: 'Common',
          effects: 'Flying',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Skyblade-of-the-Legion-Ixalan-Spoiler-216x302.png',
          power: '1',
          toughness: '3',
          flavor: 'Vampires call the gift of flight "exultation."  For their enemies, it brings only sorrow.'
        },
        {
          name: 'Slash of Talons',
          set: 'Ixalan',
          cost: '1',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Slash of Talons deals 2 damage to target attacking or blocking creature.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Slash-of-Talons-Ixalan-Spoiler-216x302.png',
          flavor: '"The amber sun smokes with fury, gazing on foes that gather like ants invading our home.  We are ready!  Blade and claw strike as one." --Huatli'
        },
        {
          name: 'Steadfast Armasaur',
          set: 'Ixalan',
          cost: '4',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dinosaur',
          rarity: 'Uncommon',
          effects: 'Vigilance\n(1W), (T): Steadfast Armasaur deals damage equal to its toughness to target creature blocking or blocked by it.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Steadfast-Armasaur-Ixalan-Spoiler-216x302.png',
          power: '2',
          toughness: '3',
          flavor: '"Like the mighty armasaur, we will defend against all who invade our shores." --Itzama the Crested'
        },
        {
          name: 'Sunrise Seeker',
          set: 'Ixalan',
          cost: '5',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Human Scout',
          rarity: 'Common',
          effects: 'Vigilance\nWhen Sunrise Seeker enters the battlefield, it explores. (Reveal the top card of your library.  Put that card into your hand if it\'s a land.  Otherwise, put a +1/+1 counter on this creature, then put the card back or put it into your graveyard.)',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Sunrise-Seeker-Ixalan-Spoiler-216x302.png',
          power: '3',
          toughness: '3'
        },
        {
          name: 'Territorial Hammerskull',
          set: 'Ixalan',
          cost: '3',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dinosaur',
          rarity: 'Common',
          effects: 'Whenever Territorial Hammerskull attacks, tap target creature an opponent controls.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Territorial-Hammerskull-Ixalan-Spoiler-216x302.png',
          power: '2',
          toughness: '3',
          flavor: 'From the eyes up, it\'s solid bone and stubbornness.'
        },
        {
          name: 'Tocatli Honor Guard',
          set: 'Ixalan',
          cost: '2',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Human Soldier',
          rarity: 'Rare',
          effects: 'Creatures entering the battlefield don\'t cause abilities to trigger.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/06/Tocatli-Honor-Guard-Ixalan-Spoiler-216x302.png',
          power: '1',
          toughness: '3',
          flavor: 'The glorious city of Pachatupa is the center of the Sun Empire, and Tocatli, the emperor\'s palace, is its glowing heart.'
        },
        {
          name: 'Vampire\'s Zeal',
          set: 'Ixalan',
          cost: '1',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Target creature gets +2/+2 until end of turn.  If it\'s a Vampire, it gains first strike until end of turn.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Vampires-Zeal-Ixalan-Spoiler-216x302.png',
          flavor: 'The Feast of Blood sends new life essence flowing through the vampire who partakes, manifesting as even greater strength and speed.'
        },
        {
          name: 'Wakening Sun\'s Avatar',
          set: 'Ixalan',
          cost: '8',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dinosaur Avatar',
          rarity: 'Mythic',
          effects: 'When Wakening Sun\'s Avatar enters the battlefield, if you cast it from your hand, destroy all non-Dinosaur creatures.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2017/09/Wakening-Suns-Avatar-Ixalan-Spoiler-216x302.png',
          power: '7',
          toughness: '7',
          flavor: '"Kinjalli\'s encompassing rays herald new life in the moment of the sun\'s dawning." --Chitlati, Lightning Rider'
        },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
        // {
        //   name: '',
        //   set: 'Ixalan',
        //   cost: '',
        //   color: '',
        //   supertype: '',
        //   subtype: '',
        //   rarity: '',
        //   effects: '',
        //   art: '',
        //   power: '',
        //   toughness: '',
        //   flavor: '',
        //   loyalty: ''
        // },
      ]);
    });
};
