exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('Card_List').del()
    .then(function () {
      // Inserts seed entries
      return knex('Card_List').insert([
        {
          name: 'Baffling End',
          set: 'Rivals of Ixalan',
          cost: '2',
          color: 'White',
          supertype: 'Enchantment',
          rarity: 'Uncommon',
          effects: 'When Baffling End enters the battlefield, exile target creature an opponent controls with converted mana cost 3 or less.\nWhen Baffling End leaves the battlefield, target opponent creates a 3/3 green Dinosaur creature token with trample.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2018/01/Baffling-End-Rivals-of-Ixalan-Spoiler-216x302.png'
        },
        {
          name: 'Bishop of Binding',
          set: 'Rivals of Ixalan',
          cost: '4',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Vampire Cleric',
          rarity: 'Rare',
          effects: 'When Bishop of Binding enters the battlefield, exile target creature an opponent controls until Bishop of Binding leaves the battlefield.\nWhenever Bishop of Binding attacks, target Vampire gets +X/+X until end of turn, where X is the power of the exiled card.',
          power: '1',
          toughness: '1',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2018/01/Bishop-of-Binding-Rivals-of-Ixalan-Spoiler-216x302.png'
        },
        {
          name: 'Blazing Hope',
          set: 'Rivals of Ixalan',
          cost: '1',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Exile target creature with power greater than or equal to your life total.',
          flavor: '"No shadow remains for you to hide in." --Caparocti Sunborn',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2018/01/Blazing-Hope-Rivals-of-Ixalan-Spoiler-216x302.png'
        },
        {
          name: 'Cleansing Ray',
          set: 'Rivals of Ixalan',
          cost: '2',
          color: 'White',
          supertype: 'Sorcery',
          rarity: 'Common',
          effects: 'Choose one --\n\tDestroy target Vampire.\n\tDestroy target enchantment.',
          flavor: '"The sun creates, sustains, and consumes so it can create again." --Caparocti Sunborn',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2018/01/Cleansing-Ray-Rivals-of-Ixalan-Spoiler-216x302.png'
        },
        {
          name: 'Divine Verdict',
          set: 'Rivals of Ixalan',
          cost: '4',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Destroy target attacking or blocking creature.',
          flavor: 'Cunning warriors and dim-witted beasts alike fall under the church\'s harsh judgment.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2018/01/Divine-Verdict-Rivals-of-Ixalan-Spoiler-216x302.png'
        },
        {
          name: 'Everdawn Champion',
          set: 'Rivals of Ixalan',
          cost: '3',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Human Soldier',
          rarity: 'Uncommon',
          effects: 'Prevent all combat damage that would be dealt to Everdawn Champion.',
          flavor: '"Undefeated in battle, she is the shining future that our empire deserves." --Huatli',
          power: '2',
          toughness: '2',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2018/01/Everdawn-Champion-Rivals-of-Ixalan-Spoiler-216x302.png'
        },
        {
          name: 'Exultant Skymarcher',
          set: 'Rivals of Ixalan',
          cost: '3',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Vampire Soldier',
          rarity: 'Common',
          effects: 'Flying',
          flavor: '"We have come at last to this holiest of holy places.  What was stolen from us long ago is ours once again."',
          power: '2',
          toughness: '3',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2018/01/Exultant-Skymarcher-Rivals-of-Ixalan-Spoiler-216x302.png'
        },
        {
          name: 'Famished Paladin',
          set: 'Rivals of Ixalan',
          cost: '2',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Vampire Knight',
          rarity: 'Uncommon',
          effects: 'Famished Paladin doesn\'t untap during your untap step.\nWhenever you gain life, untap Famished Paladin.',
          flavor: 'Loyal to his queen, slave to his thirst.',
          power: '3',
          toughness: '3',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2018/01/Famished-Paladin-Rivals-of-Ixalan-Spoiler-216x302.png'
        },
        {
          name: 'Forerunner of the Legion',
          set: 'Rivals of Ixalan',
          cost: '3',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Vampire Knight',
          rarity: 'Uncommon',
          effects: 'When Forerunner of the Legion enters the battlefield, you may search your library for a Vampire card, reveal it, then shuffle your library and put that card on top of it.\nWhenever another Vampire enters the battlefield under your control, target creature gets +1/+1 until end of turn.',
          power: '2',
          toughness: '2',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2018/01/Forerunner-of-the-Legion-216x302.png'
        },
        {
          name: 'Imperial Ceratops',
          set: 'Rivals of Ixalan',
          cost: '5',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dinosaur',
          rarity: 'Uncommon',
          effects: 'Enrage -- Whenever Imperial Ceratops is dealt damage, you gain 2 life.',
          flavor: '"The music of blades against its silver armor merely inspires it to bellow more full-throated melodies." --Huatli',
          power: '3',
          toughness: '5',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2018/01/Imperial-Ceratops-Rivals-of-Ixalan-Spoiler-216x302.png'
        },
        {
          name: 'Legion Conquistador',
          set: 'Rivals of Ixalan',
          cost: '3',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Vampire Soldier',
          rarity: 'Common',
          effects: 'When Legion Conquistador enters the battlefield, you may search your library for any number of cards named Legion Conquistador, reveal them, put them into your hand, then shuffle your library.',
          flavor: 'The Legion of Dusk sailed from Torrezon in search of glory, riches, and the Immortal Sun.',
          power: '2',
          toughness: '2',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2018/01/Legion-Conquistador-Rivals-of-Ixalan-Spoiler-216x302.png'
        },
        {
          name: 'Luminous Bonds',
          set: 'Rivals of Ixalan',
          cost: '3',
          color: 'White',
          supertype: 'Enchantment',
          subtype: 'Aura',
          rarity: 'Common',
          effects: 'Enchant creature\nEnchanted creature can\'t attack or block.',
          flavor: '"Your part in this fight is done, vampire.  Get used to your thirst."',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2018/01/Luminous-Bonds-Rivals-of-Ixalan-Spoiler-216x302.png'
        },
        {
          name: 'Majestic Heliopterus',
          set: 'Rivals of Ixalan',
          cost: '4',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dinosaur',
          rarity: 'Uncommon',
          effects: 'Flying\nWhenever Majestic Heliopterus attacks, another target Dinosaur you control gains flying until end of turn.',
          flavor: '"Its rise is like the sun\'s, a beautiful beginning.  Its descent is like the sun\'s, a frightful ending." --Huatli',
          power: '2',
          toughness: '2',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2018/01/Majestic-Heliopterus-216x302.png'
        },
        {
          name: 'Martyr of Dusk',
          set: 'Rivals of Ixalan',
          cost: '2',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Vampire Soldier',
          rarity: 'Common',
          effects: 'When Martyr of Dusk dies, create a 1/1 white Vampire creature token with lifelink.',
          flavor: '"Should I fall, take up our standard and carry on.  The Legion must always prevail."',
          power: '2',
          toughness: '1',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2018/01/Martyr-of-Dusk-Rivals-of-Ixalan-Spoiler-216x302.png'
        },
        {
          name: 'Moment of Triumph',
          set: 'Rivals of Ixalan',
          cost: '1',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Target creature gets +2/+2 until end of turn.  You gain 2 life.',
          flavor: '"The time of our salvation is at hand.  Dusk washes over the world, and the Legion will rise immortal!"',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2018/01/Moment-of-Triumph-Rivals-of-Ixalan-Spoiler-216x302.png'
        },
        {
          name: 'Paladin of Atonement',
          set: 'Rivals of Ixalan',
          cost: '2',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Vampire Knight',
          rarity: 'Rare',
          effects: 'At the beginning of each upkeep, if you lost life last turn, put a +1/+1 counter on Paladin of Atonement.\nWhen Paladin of Atonement dies, you gain life equal to its toughness.',
          flavor: 'For every wound there is a blessing; for every death, a reckoning.',
          power: '1',
          toughness: '1',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2018/01/Paladin-of-Atonement-216x302.png'
        },
        {
          name: 'Pride of Conquerors',
          set: 'Rivals of Ixalan',
          cost: '2',
          color: 'White',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Ascend (If you control ten or more permanents, you get the city\'s blessing for the rest of the game.)\nCreatures you control get +1/+1 until end of turn.  If you have the city\'s blessing, those creatures get +2/+2 instead.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2018/01/Pride-of-Conquerors-Rivals-of-Ixalan-Spoiler-216x302.png'
        },
        {
          name: 'Radiant Destiny',
          set: 'Rivals of Ixalan',
          cost: '3',
          color: 'White',
          supertype: 'Enchantment',
          rarity: 'Rare',
          effects: 'Ascend (If you control ten or more permanents, you get the city\'s blessing for the rest of the game.)\nAs Radiant Destiny enters the battlefield, choose a creature type.\nCreatures you control of the chosen type get +1/+1.  As long as you have the city\'s blessing, they also have vigilance.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2018/01/Radiant-Destiny-Rivals-of-Ixalan-Spoiler-216x302.png'
        },
        {
          name: 'Raptor Companion',
          set: 'Rivals of Ixalan',
          cost: '2',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dinosaur',
          rarity: 'Common',
          flavor: 'The abundance of foes in Orazca means the raptors no longer need any orders.',
          power: '3',
          toughness: '1',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2018/01/Raptor-Companion-Rivals-of-Ixalan-Spoiler-216x302.png'
        },
        {
          name: 'Sanguine Glorifier',
          set: 'Rivals of Ixalan',
          cost: '4',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Vampire Cleric',
          rarity: 'Common',
          effects: 'When Sanguine Glorifier enters the battlefield, put a +1/+1 counter on another target Vampire you control.',
          flavor: 'For the Legion of Dusk, the Immortal Sun is a source of eternal life.  When they reclaim it, they will no longer be forced to subsist on the blood of the wicked.',
          power: '3',
          toughness: '3',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2018/01/Sanguine-Glorifier-Rivals-of-Ixalan-Spoiler-216x302.png'
        },
        {
          name: 'Skymarcher Aspirant',
          set: 'Rivals of Ixalan',
          cost: '1',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Vampire Soldier',
          rarity: 'Uncommon',
          effects: 'Ascend (If you control ten or more permanents, you get the city\'s blessing for the rest of the game.)\nSkymarcher Aspirant has flying as long as you have the city\'s blessing.',
          flavor: '"I was born to glory."',
          power: '2',
          toughness: '1',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2018/01/Skymarcher-Aspirant-216x302.png'
        },
        {
          name: 'Slaughter the Strong',
          set: 'Rivals of Ixalan',
          cost: '3',
          color: 'White',
          supertype: 'Sorcery',
          rarity: 'Rare',
          effects: 'Each player chooses any number of creatures he or she controls with total power 4 or less, then sacrifices all other creatures he or she controls.',
          flavor: '"Cut the beasts out from under them and their strength is nothing." --Vona of Iedo, Butcher of Magan',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2018/01/Slaughter-the-Strong-Rivals-of-Ixalan-Spoiler-216x302.png'
        },
        {
          name: 'Snubhorn Sentry',
          set: 'Rivals of Ixalan',
          cost: '1',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dinosaur',
          rarity: 'Common',
          effects: 'Ascend (If you control ten or more permanents, you get the city\'s blessing for the rest of the game.)\nSnubhorn Sentry gets +3/+0 as long as you have the city\'s blessing.',
          flavor: 'They\'re fun to train -- if you like stubborn, aggressive, and fiercely territorial.',
          power: '0',
          toughness: '3',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2018/01/Snubhorn-Sentry-Rivals-of-Ixalan-Spoiler-216x302.png'
        },
        {
          name: 'Sphinx\'s Decree',
          set: 'Rivals of Ixalan',
          cost: '2',
          color: 'White',
          supertype: 'Sorcery',
          rarity: 'Rare',
          effects: 'Each opponent can\'t cast instant or sorcery spells during that player\'s next turn.',
          flavor: '"Be still." --Azor',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2018/01/Sphinxs-Decree-216x302.jpg'
        },
        {
          name: 'Squire\'s Devotion',
          set: 'Rivals of Ixalan',
          cost: '3',
          color: 'White',
          supertype: 'Enchantment',
          subtype: 'Aura',
          rarity: 'Common',
          effects: 'Enchant creature\nEnchanted creature gets +1/+1 and has lifelink.\nWhen Squire\'s Devotion enters the battlefield, create a 1/1 white Vampire creature token with lifelink.',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2018/01/Squire%E2%80%99s-Devotion-Rivals-of-Ixalan-Spoiler1-216x302.png'
        },
        {
          name: 'Sun Sentinel',
          set: 'Rivals of Ixalan',
          cost: '2',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Human Soldier',
          rarity: 'Common',
          effects: 'Vigilance',
          flavor: '"I will not sleep until Orazca is ours once more."',
          power: '2',
          toughness: '2',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2018/01/Sun-Sentinel-Rivals-of-Ixalan-Spoiler-216x302.png'
        },
        {
          name: 'Sun-Crested Pterodon',
          set: 'Rivals of Ixalan',
          cost: '5',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dinosaur',
          rarity: 'Common',
          effects: 'Flying\nSun-Crested Pterodon has vigilance as long as you control another Dinosaur.',
          flavor: '"Pterodons tolerate no intrusion into their skies.  Even the clouds must ask permission." --Mahuiz, Sun Empire archer',
          power: '2',
          toughness: '5',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2018/01/Sun-Crested-Prerodon-216x302.png'
        },
        {
          name: 'Temple Altisaur',
          set: 'Rivals of Ixalan',
          cost: '5',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dinosaur',
          rarity: 'Rare',
          effects: 'If a source would deal damage to another Dinosaur you control, prevent all but 1 of that damage.',
          flavor: '"Kinjalli sculpted humans from clay, but the dinosaurs were carved from unyielding stone." --Itzama the Crested',
          power: '3',
          toughness: '4',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2018/01/Temple-Altisaur-Rivals-of-Ixalan-Spoiler-216x302.png'
        },
        {
          name: 'Trapjaw Tyrant',
          set: 'Rivals of Ixalan',
          cost: '5',
          color: 'White',
          supertype: 'Creature',
          subtype: 'Dinosaur',
          rarity: 'Mythic',
          effects: 'Enrage -- Whenever Trapjaw Tyrant is dealt damage, exile target creature an opponent controls until Trapjaw Tyrant leaves the battlefield.',
          flavor: '"I would advise you not to struggle." --Huatli',
          power: '5',
          toughness: '5',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2018/01/Trapjaw-Tyrant-Rivals-of-Ixalan-Spoiler-216x302.png'
        },
        {
          name: 'Zetalpa, Primal Dawn',
          set: 'Rivals of Ixalan',
          cost: '8',
          color: 'White',
          supertype: 'Legendary Creature',
          subtype: 'Elder Dinosaur',
          rarity: 'Rare',
          effects: 'Flying, double strike, vigilance, trample, indestructible',
          flavor: 'The sky takes flight and the earth trembles.',
          power: '4',
          toughness: '8',
          art: 'http://www.magicspoiler.com/wp-content/uploads/2018/01/Zetalpa-Primal-Dawn-216x302.png'
        },
        {
          name: 'Admiral\'s Order',
          set: 'Rivals of Ixalan',
          cost: '3',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Rare',
          effects: 'Raid -- If you attacked with a creature this turn, you may pay {U} rather than pay this spell\'s mana cost.\nCounter target spell.',
          flavor: '"Damn the cannons, mates.  Charge!"',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/616/200/283/439688.full.jpg'
        },
        {
          name: 'Aquatic Incursion',
          set: 'Rivals of Ixalan',
          cost: '4',
          color: 'Blue',
          supertype: 'Enchantment',
          rarity: 'Uncommon',
          effects: 'When Aquatic Incursion enters the battlefield, create two 1/1 blue Merfolk creature tokens with hexproof. (They can\'t be the targets of spells or abilities your opponents control)\n{3U}: Target Merfolk can\'t be blocked this turn.',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/622/200/283/439689.full.jpg'
        },
        {
          name: 'Crafty Cutpurse',
          set: 'Rivals of Ixalan',
          cost: '4',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Human Pirate',
          rarity: 'Rare',
          effects: 'Flash\nWhen Crafty Cutpurse enters the battlefield, each token that would be created under an opponent\'s control this turn is created under your control instead.',
          flavor: 'Possession is eleven-tenths of the pirate code.',
          power: '2',
          toughness: '2',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/647/200/283/439690.full.jpg'
        },
        {
          name: 'Crashing Tide',
          set: 'Rivals of Ixalan',
          cost: '3',
          color: 'Blue',
          supertype: 'Sorcery',
          rarity: 'Common',
          effects: 'Crashing Tide has flash as long as you control a Merfolk.\nReturn target creature to its owner\'s hand.\nDraw a card.',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/648/200/283/439691.full.jpg'
        },
        {
          name: 'Curious Obsession',
          set: 'Rivals of Ixalan',
          cost: '1',
          color: 'Blue',
          supertype: 'Enchantment',
          subtype: 'Aura',
          rarity: 'Uncommon',
          effects: 'Enchant creature\nEnchanted creature gets +1/+1 and "Whenever this creature deals combat damage to a player, you may draw a card."\nAt the beginning of your next end step, if you didn\'t attack with a creature this turn, sacrifice Curious Obsession.',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/650/200/283/439692.full.jpg'
        },
        {
          name: 'Deadeye Rig-Hauler',
          set: 'Rivals of Ixalan',
          cost: '4',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Human Pirate',
          rarity: 'Common',
          effects: 'Raid -- When Deadeye Rig-Hauler enters the battlefield, if you attacked with a creature this turn, you may return target creature to its owner\'s hand.',
          flavor: '"Up you go, you soggy rat."',
          power: '3',
          toughness: '2',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/655/200/283/439693.full.jpg'
        },
        {
          name: 'Expel from Orazca',
          set: 'Rivals of Ixalan',
          cost: '2',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Ascend (If you control ten or more permanents, you get the city\'s blessing for the rest of the game.\nReturn target nonland permanent to its owner\'s hand.  If you have the city\'s blessing, you may put that permanent on top of its owner\'s library instead.',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/669/200/283/439694.full.jpg'
        },
        {
          name: 'Flood of Recollection',
          set: 'Rivals of Ixalan',
          cost: '2',
          color: 'Blue',
          supertype: 'Sorcery',
          rarity: 'Uncommon',
          effects: 'Return target instant or sorcery card from your graveyard to your hand.  Exile Flood of Recollection.',
          flavor: 'Jace tumbled down the waterfall and plunged deep into his past.',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/669/200/283/439695.full.jpg'
        },
        {
          name: 'Hornswoggle',
          set: 'Rivals of Ixalan',
          cost: '3',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Uncommon',
          effects: 'Counter target creature spell.  You create a colorless Treasure artifact token with "{T}, Sacrifice this artifact: Add one mana of any color to your mana pool."',
          flavor: 'Being a merciful pirate, she saved the vampire\'s gold from falling overboard.',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/669/200/283/439696.full.jpg'
        },
        {
          name: 'Induced Amnesia',
          set: 'Rivals of Ixalan',
          cost: '3',
          color: 'Blue',
          supertype: 'Enchantment',
          rarity: 'Rare',
          effects: 'When Induced Amnesia enters the battlefield, target player exiles all cards from his or her hand face down, then draws that many cards.\nWhen Induced Amnesia is put into a graveyard from the battlefield, return the exiled cards to their owner\'s hand.',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/669/200/283/439697.full.jpg'
        },
        {
          name: 'Kitesail Corsair',
          set: 'Rivals of Ixalan',
          cost: '2',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Human Pirate',
          rarity: 'Common',
          effects: 'Kitesail Corsair has flying as long as it\'s attacking.',
          flavor: '"Why perch in the crow\'s nest when I can fly like the crows?"',
          power: '2',
          toughness: '1',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/669/200/283/439698.full.jpg'
        },
        {
          name: 'Kumena\'s Awakening',
          set: 'Rivals of Ixalan',
          cost: '4',
          color: 'Blue',
          supertype: 'Enchantment',
          rarity: 'Rare',
          effects: 'Ascend (If you control ten or more permanents, you get the city\'s blessing for the rest of the game.)\nAt the beginning of your upkeep, each player draws a card.  If you have the city\'s blessing, instead only you draw a card.',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/669/200/283/439699.full.jpg'
        },
        {
          name: 'Mist-Cloaked Herald',
          set: 'Rivals of Ixalan',
          cost: '1',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Merfolk Warrior',
          rarity: 'Common',
          effects: 'Mist-Cloaked Herald can\'t be blocked.',
          flavor: 'With matchless stealth, the River Heralds fought a running battle against the three enemy forces.',
          power: '1',
          toughness: '1',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/669/200/283/439700.full.jpg'
        },
        {
          name: 'Negate',
          set: 'Rivals of Ixalan',
          cost: '2',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Counter target noncreature spell.',
          flavor: '"As one, nature lifts its voice to tell you this: \'No.\'"',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/669/200/283/439701.full.jpg'
        },
        {
          name: 'Nezehal, Primal Tide',
          set: 'Rivals of Ixalan',
          cost: '7',
          color: 'Blue',
          supertype: 'Legendary Creature',
          rarity: 'Elder Dinosaur',
          effects: 'Nezehal, Primal Tide can\'t be countered.\nYou have no maximum hand size.\nWhenever an opponent casts a noncreature spell, draw a card.\nDiscard three cards: Exile Nezehal.  Return it to the battlefield tapped under its owner\'s control at the beginning of the next end step.',
          power: '7',
          toughness: '7',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/669/200/283/439702.full.jpg'
        },
        {
          name: 'Release to the Wind',
          set: 'Rivals of Ixalan',
          cost: '3',
          color: 'Blue',
          supertype: 'Instant',
          rarity: 'Rare',
          effects: 'Exile target nonland permanent.  For as long as that card remains exiled, its owner may cast it without paying its mana cost.',
          flavor: '"Here and gone like a fleeting breeze."',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/669/200/283/439703.full.jpg'
        },
        {
          name: 'River Darter',
          set: 'Rivals of Ixalan',
          cost: '3',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Merfolk Warrior',
          rarity: 'Common',
          effects: 'River Darter can\'t be blocked by Dinosaurs.',
          flavor: '"Don\'t make splashes.  Make progress."\n--Tishana',
          power: '2',
          toughness: '3',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/669/200/283/439704.full.jpg'
        },
        {
          name: 'Riverwise Augur',
          set: 'Rivals of Ixalan',
          cost: '4',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Merfolk Wizard',
          rarity: 'Uncommon',
          effects: 'When Riverwise Augur enters the battlefield, draw three cards, then put two cards from your hand on top of your library in any order.',
          flavor: '"Time flows as the rivers do, toward an unknown sea.  The wise know to look downstream."',
          power: '2',
          toughness: '2',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/669/200/283/439705.full.jpg'
        },
        {
          name: 'Sailor of Means',
          set: 'Rivals of Ixalan',
          cost: '3',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Human Pirate',
          rarity: 'Common',
          effects: 'When Sailor of Means enters the battlefield, create a colorless Treasure artifact token with "{T}, Sacrifice this artifact: Add one mana of any color to your mana pool."',
          flavor: 'The rising tide of Orazca\'s plunder lifted all ships.',
          power: '1',
          toughness: '4',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/669/200/283/439706.full.jpg'
        },
        {
          name: 'Sea Legs',
          set: 'Rivals of Ixalan',
          cost: '1',
          color: 'Blue',
          supertype: 'Enchantment',
          subtype: 'Aura',
          rarity: 'Common',
          effects: 'Flash\nEnchant creature\nEnchanted creature gets +0/+2 as long as it\'s a Pirate.  Otherwise, it gets -2/-0.',
          flavor: '"When the waves pick up, either you find your feet or you lose your lunch."',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/669/200/283/439707.full.jpg'
        },
        {
          name: 'Seafloor Oracle',
          set: 'Rivals of Ixalan',
          cost: '4',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Merfolk Wizard',
          rarity: 'Rare',
          effects: 'Whenever a Merfolk you control deals damage to a player, draw a card.',
          flavor: 'Where the light falls dim and blue on broken ships, secrets lie unclaimed.',
          power: '2',
          toughness: '3',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/669/200/283/439708.full.jpg'
        },
        {
          name: 'Secrets of the Golden City',
          set: 'Rivals of Ixalan',
          cost: '3',
          color: 'Blue',
          supertype: 'Sorcery',
          rarity: 'Common',
          effects: 'Ascend (If you control ten or more permanents, you have the city\'s blessing for the rest of the game.)\nDraw two cards.  If you have the city\'s blessing, draw three cards instead',
          flavor: 'Stolen knowledge can never be stolen back.',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/669/200/283/439709.full.jpg'
        },
        {
          name: 'Silvergill Adept',
          set: 'Rivals of Ixalan',
          cost: '2',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Merfolk Wizard',
          rarity: 'Uncommon',
          effects: 'As an additional cost to cast Silvergill Adept, reveal a Merfolk card from your had or pay {3}.\nWhen Silvergill Adept enters the battlefield, draw a card.',
          flavor: '"If you keep to the shallows, you\'ll never learn the secrets of the depths."',
          power: '2',
          toughness: '1',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/669/200/283/439710.full.jpg'
        },
        {
          name: 'Siren Reaver',
          set: 'Rivals of Ixalan',
          cost: '4',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Siren Pirate',
          rarity: 'Uncommon',
          effects: 'Raid -- Siren Reaver costs {1} less to cast if you attacked with a creature this turn.\nFlying',
          flavor: '"Prepare to be boarded."',
          power: '3',
          toughness: '2',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/669/200/283/439711.full.jpg'
        },
        {
          name: 'Slippery Scoundrel',
          set: 'Rivals of Ixalan',
          cost: '3',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Human Pirate',
          rarity: 'Uncommon',
          effects: 'Ascend (If you control ten or more permanents, you have the city\'s blessing for the rest of the game.)\nAs long as you have the city\'s blessing, Slippery Scoundrel has hexproof and can\'t be blocked.',
          flavor: '"I\'d rather be caught red-handed than leave empty-handed!"',
          power: '2',
          toughness: '2',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/669/200/283/439712.full.jpg'
        },
        {
          name: 'Soul of the Rapids',
          set: 'Rivals of Ixalan',
          cost: '5',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Elemental',
          rarity: 'Common',
          effects: 'Flying\nHexproof (This creature can\'t be the target of spells or abilities your opponents control.)',
          flavor: 'With Kumena in control of the Immortal Sun, the rapids rose from their riverbeds and the waterfalls took flight.',
          power: '3',
          toughness: '2',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/669/200/283/439713.full.jpg'
        },
        {
          name: 'Sworn Guardian',
          set: 'Rivals of Ixalan',
          cost: '2',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Merfolk Warrior',
          rarity: 'Common',
          flavor: 'For the River Heralds, the Immortal Sun is an object of terror and devastation.  The idea that anyone would retrieve it for their own use is utterly abhorrent.',
          power: '1',
          toughness: '3',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/669/200/283/439714.full.jpg'
        },
        {
          name: 'Timestream Navigator',
          set: 'Rivals of Ixalan',
          cost: '2',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Human Pirate Wizard',
          rarity: 'Mythic',
          effects: 'Ascend (If you control ten or more permanents, you have the city\'s blessing for the rest of the game.)\n{2UU}, {T}, Put Timestream Navigator on the bottom of its owner\'s library: Take an extra turn after this one.  Activate this ability only if you have the city\'s blessing.',
          power: '1',
          toughness: '1',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/669/200/283/439715.full.jpg'
        },
        {
          name: 'Warkite Marauder',
          set: 'Rivals of Ixalan',
          cost: '2',
          color: 'Blue',
          supertype: 'Creature',
          subtype: 'Human Pirate',
          rarity: 'Rare',
          effects: 'Flying\nWhenever Warkite Marauder attacks, target creature defending player controls loses all abilities and has base power and toughness 0/1 until end of turn.',
          power: '2',
          toughness: '1',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/669/200/283/439716.full.jpg'
        },
        {
          name: 'Waterknot',
          set: 'Rivals of Ixalan',
          cost: '3',
          color: 'Blue',
          supertype: 'Enchantment',
          subtype: 'Aura',
          rarity: 'Common',
          effects: 'Enchant creature\nWhen Waterknot enters the battlefield, tap enchanted creature.\nEnchanted creature doesn\'t untap during its controller\'s untap step.',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/669/200/283/439717.full.jpg'
        },
        {
          name: 'Arterial Flow',
          set: 'Rivals of Ixalan',
          cost: '3',
          color: 'Black',
          supertype: 'Sorcery',
          rarity: 'Uncommon',
          effects: 'Each opponent discards two cards.  If you control a Vampire, each opponent loses 2 life and you gain 2 life.',
          flavor: '"It is impious to admit, but I do enjoy pirate blood.  Something in the salty tang of it, the spice of rebellion."',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/669/200/283/439718.full.jpg'
        },
        {
          name: 'Canal Monitor',
          set: 'Rivals of Ixalan',
          cost: '5',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Lizard',
          rarity: 'Common',
          flavor: 'The first goblin tried to swim the canal.  The second built a raft.  The last and craftiest goblin launched herself from a firecannon and soared over the canal, trailing smoke.  All were eaten, but only one was cooked.',
          power: '5',
          toughness: '3',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/669/200/283/439719.full.jpg'
        },
        {
          name: 'Champion of Dusk',
          set: 'Rivals of Ixalan',
          cost: '5',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Vampire Knight',
          rarity: 'Rare',
          effects: 'When Champion of Dusk enters the battlefield, you draw X cards and you lose X life, where X is the number of Vampires you control.',
          flavor: '"Drench these golden streets in the blood of our enemies."',
          power: '4',
          toughness: '4',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/669/200/283/439720.full.jpg'
        },
        {
          name: 'Dark Inquiry',
          set: 'Rivals of Ixalan',
          cost: '3',
          color: 'Black',
          supertype: 'Sorcery',
          rarity: 'Common',
          effects: 'Target opponent reveals his or her hand.  You choose a nonland card from it.  Tnat player discards that card.',
          flavor: '"Your mind is no longer yours to waste."',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/669/200/283/439721.full.jpg'
        },
        {
          name: 'Dead Man\'s Chest',
          set: 'Rivals of Ixalan',
          cost: '2',
          color: 'Black',
          supertype: 'Enchantment',
          subtype: 'Aura',
          rarity: 'Rare',
          effects: 'Enchant creature an opponent controls\nWhen enchanted creature dies, exile cards equal to its power from the top of its owner\'s library.  You may cast nonland cards from among them for as long as they remain exiled, and you may spend mana as though it were mana of any type to cast those spells.',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/669/200/283/439722.full.jpg'
        },
        {
          name: 'Dinosaur Hunter',
          set: 'Rivals of Ixalan',
          cost: '2',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Human Pirate',
          rarity: 'Common',
          effects: 'Whenever Dinosaur Hunter deals damage to a Dinosaur, destroy that creature.',
          flavor: '"Aye, the foul beast chomped me, but I got away.  You\'d best believe when I find it again, it won\'t get away so easy."',
          power: '2',
          toughness: '2',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/669/200/283/439723.full.jpg'
        },
        {
          name: 'Dire Fleet Poisoner',
          set: 'Rivals of Ixalan',
          cost: '2',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Human Pirate',
          rarity: 'Rare',
          effects: 'Flash\nDeathtouch\nWhen Dire Fleet Poisoner enters the battlefield, target attacking Pirate gets +1/+1 and has deathtouch until end of turn.',
          power: '2',
          toughness: '2',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/669/200/283/439724.full.jpg'
        },
        {
          name: 'Dusk Charger',
          set: 'Rivals of Ixalan',
          cost: '4',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Horse',
          rarity: 'Common',
          effects: 'Ascend (If you control ten or more permanents, you have the city\'s blessing for the rest of the game.)\nDusk Charger gets +2/+2 as long as you have the city\'s blessing.',
          flavor: 'Stories say demon blood runs in its veins, making it fearless and bloodthirsty.',
          power: '3',
          toughness: '3',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/669/200/283/439725.full.jpg'
        },
        {
          name: 'Dusk Legion Zealot',
          set: 'Rivals of Ixalan',
          cost: '2',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Vampire Soldier',
          rarity: 'Common',
          effects: 'When Dusk Legion Zealot enters the battlefield, you draw a card and you lose 1 life.',
          flavor: 'Once they reached Orazca, the Legion\'s explorers ransacked tombs and temples, hunting for the Immortal Sun.',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/669/200/283/439726.full.jpg'
        },
        {
          name: 'Fathom Fleet Boarder',
          set: 'Rivals of Ixalan',
          cost: '3',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Orc Pirate',
          rarity: 'Common',
          effects: 'When Fathom Fleet Boarder enters the battlefield, you lose 2 life unless you control another Pirate.',
          flavor: 'Without frequent raids, orcs sometimes get bored and plunder their own ships.',
          power: '3',
          toughness: '3',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/673/200/283/439728.full.jpg'
        },
        {
          name: 'Forerunner of the Coalition',
          set: 'Rivals of Ixalan',
          cost: '3',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Human Pirate',
          rarity: 'Uncommon',
          effects: 'When Forerunner of the Coalition enters the battlefield, you may search your library for a Pirate card, reveal it, then shuffle your library, and put that card on top of it.\nWhenever another Pirate enters the battlefield under your control, each opponent loses 1 life.',
          power: '2',
          toughness: '2',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/675/200/283/439729.full.jpg'
        },
        {
          name: 'Golden Demise',
          set: 'Rivals of Ixalan',
          cost: '3',
          color: 'Black',
          supertype: 'Sorcery',
          rarity: 'Uncommon',
          effects: 'Ascend (If you control ten or more permanents, you have the city\'s blessing for the rest of the game.)\nAll creatures get -2/-2 until end of turn.  If you have the city\'s blessing, instead only creatures your opponents control get -2/-2 until end of turn.',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/688/200/283/439730.full.jpg'
        },
        {
          name: 'Grasping Scoundrel',
          set: 'Rivals of Ixalan',
          cost: '1',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Human Pirate',
          rarity: 'Common',
          effects: 'Grasping Scoundrel gets +1/+0 as long as it\'s attacking.',
          flavor: '"I can hear the plunder calling.  It asks for me by name."',
          power: '1',
          toughness: '1',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/691/200/283/439731.full.jpg'
        },
        {
          name: 'Gruesome Fate',
          set: 'Rivals of Ixalan',
          cost: '3',
          color: 'Black',
          supertype: 'Sorcery',
          rarity: 'Common',
          effects: 'Each opponent loses 1 life for each creature you control.',
          flavor: '"You were keen enough to sink your fangs into us, vampire!  And now you\'re afraid of a few little nibbles?"\nUdvil "Ratty" Ratlock',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/692/200/283/439732.full.jpg'
        },
        {
          name: 'Impale',
          set: 'Rivals of Ixalan',
          cost: '4',
          color: 'Black',
          supertype: 'Sorcery',
          rarity: 'Common',
          effects: 'Destroy target creature.',
          flavor: 'Never let the glitter of gold distract you from the gleam of steel in the shadows.',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/699/200/283/439733.full.jpg'
        },
        {
          name: 'Mastermind\'s Acquisition',
          set: 'Rivals of Ixalan',
          cost: '4',
          color: 'Black',
          supertype: 'Sorcery',
          rarity: 'Rare',
          effects: 'Choose one -- \n\bSearch your library for a card, put it into your hand, then shuffle your library.\n\bChoose a card you own from outside the game and put it into your hand.',
          flavor: 'Another piece of a nefarious puzzle.',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/718/200/283/439734.full.jpg'
        },
        {
          name: 'Mausoleum Harpy',
          set: 'Rivals of Ixalan',
          cost: '5',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Harpy',
          rarity: 'Uncommon',
          effects: 'Flying\nAscend (If you control ten or more permanents, you have the city\'s blessing for the rest of the game.)\nWhenever another creature you control dies, if you have the city\'s blessing, put a +1/+1 counter on Mausoleum Harpy.',
          power: '3',
          toughness: '3',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/719/200/283/439735.full.jpg'
        },
        {
          name: 'Moment of Craving',
          set: 'Rivals of Ixalan',
          cost: '2',
          color: 'Black',
          supertype: 'Instant',
          rarity: 'Common',
          effects: 'Target creature gets -2/-2 until end of turn.  You gain 2 life.',
          flavor: '"The time of condemnation is at hand.  Dusk washes over the world, and I consign you to eternal darkness!"',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/723/200/283/439736.full.jpg'
        },
        {
          name: 'Oathsworn Vampire',
          set: 'Rivals of Ixalan',
          cost: '2',
          color: 'Black',
          supertype: 'Creature',
          subtype: 'Vampire Knight',
          rarity: 'Uncommon',
          effects: 'Oathsworn Vampire enters the battlefield tapped.\nYou may cast Oathsworn Vampire from your graveyard if you gained life this turn.',
          flavor: '"My conquistadors are never slain, merely laid to rest."\n--Queen Miralda the Pious',
          power: '2',
          toughness: '2',
          art: 'https://media-dominaria.cursecdn.com/avatars/thumbnails/265/731/200/283/439737.full.jpg'
        },
      ]);
    });
  };
