exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('Card_List').del()
  .then(function () {
    // Inserts seed entries
    return knex('Card_List').insert([
      {
        name: 'Karn, Scion of Urza',
        set: 'Dominaria',
        cost: '4',
        color: 'Colorless',
        supertype: 'Legendary Planeswalker',
        subtype: 'Karn',
        rarity: 'Mythic',
        effects: '+1: Reveal the top two cards of your library.  An opponent chooses one of them.  Put that card into your hand and exile the other with a silver counter on it.\n-1: Put a card you own with a silver counter on it from exile into your hand.\n-2: Create a 0/0 colorless Construct artifact creature with "This creature gets +1/+1 for each artifact you control.',
        loyalty: '5',
        art: 'http://mythicspoiler.com/dom/cards/karnscionofurza2.jpg'
      },
      {
        name: 'Adamant Will',
        set: 'Dominaria',
        cost: '2',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Target creature gets +2/+2 and gains indestructible until end of turn. (Damage and effects that say "destroy" don\'t destroy it.)',
        flavor: 'The shield took a year to craft, a month to enchant, and a decade to master -- all for one glorious moment.',
        art: 'http://mythicspoiler.com/dom/cards/adamantwill.jpg'
      },
      {
        name: 'Aven Sentry',
        set: 'Dominaria',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Bird Soldier',
        rarity: 'Common',
        effects: 'Flying',
        flavor: '"My flock flew from a distant continent ruined by cataclysm and war.  Benalia gave us shelter to end our exodus."',
        power: '3',
        toughness: '2',
        art: 'http://mythicspoiler.com/dom/cards/avensentry.jpg'
      },
      {
        name: 'Baird, Steward of Argive',
        set: 'Dominaria',
        cost: '4',
        color: 'White',
        supertype: 'Legendary Creature',
        subtype: 'Human Soldier',
        rarity: 'Uncommon',
        effects: 'Vigilance\nCreatures can\'t attack you or a planeswalker you control unless their controller pays {1} for each of those creatures.',
        flavor: '"The walls of Argive were built by a peaceful dynastic union that has guarded us against war for fifteen centuries.  The lesson is clear."',
        power: '2',
        toughness: '4',
        art: 'http://mythicspoiler.com/dom/cards/bairdstewardofargive2.jpg'
      },
      {
        name: 'Benalish Honor Guard',
        set: 'Dominaria',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Knight',
        rarity: 'Common',
        effects: 'Benalish Honor Guard gets +1/+0 for each legendary creature you control.',
        flavor: '"The true measure of all heroes is not what they achieve, but what they inspire."\n--Triumph of Gerrard',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/dom/cards/benalishhonorguard1.jpg'
      },
      {
        name: 'Benalish Marshal',
        set: 'Dominaria',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Knight',
        rarity: 'Rare',
        effects: 'Other creatures you control get +1/+1.',
        flavor: '"Some aspire to climb the mountain of Honor.  The Benalish are born upon its peak, and from there ascend among the stars."\n--History of Benalia',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/dom/cards/benalishmarshal3.jpg'
      },
      {
        name: 'Blessed Light',
        set: 'Dominaria',
        cost: '5',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Exile target artifact or enchantment.',
        flavor: 'Enchanted by mage-smiths and blessed by priests, Benalish windows let in light and cast out darkness.',
        art: 'http://mythicspoiler.com/dom/cards/blessedlight.jpg'
      },
      {
        name: 'Board the Weatherlight',
        set: 'Dominaria',
        cost: '2',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Uncommon',
        effects: 'Look at the top five cards of your library.  You may reveal a historic card from among them and put it into your hand.  Put the rest on the bottom of your library in a random order.  (Artifacts, legendaries, and Sagas are historic.)',
        flavor: 'A new gathering for a new age.',
        art: 'http://mythicspoiler.com/dom/cards/boardtheweatherlight.jpg'
      },
      {
        name: 'Call the Cavalry',
        set: 'Dominaria',
        cost: '4',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'Create two 2/2 white Knight creature tokens with vigilance.',
        flavor: 'Benalish citizens born under the same constellations share a star-clan.  Their loyalty to each other interlaces the Seven Houses.',
        art: 'http://mythicspoiler.com/dom/cards/callthecavalry.jpg'
      },
      {
        name: 'Charge',
        set: 'Dominaria',
        cost: '1',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Creatures you control get +1/+1 until end of turn.',
        flavor: '"Honor rides before us.  All we have to do is catch up."\n--Danitha Capashen',
        art: 'http://mythicspoiler.com/dom/cards/charge1.jpg'
      },
      {
        name: 'D\'Avenant Trapper',
        set: 'Dominaria',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Archer',
        rarity: 'Common',
        effects: 'Whenever you cast a historic spell, tap target creature an opponent controls.  (Artifacts, legendaries, and Sagas are historic.)',
        flavor: '"Go swiftly, clever arrow, and teach\nThe philosophy of stillness."\n--D\'Avenant verse',
        power: '3',
        toughness: '2',
        art: 'http://mythicspoiler.com/dom/cards/davenanttrapper.jpg'
      },
      {
        name: 'Danitha Capashen, Paragon',
        set: 'Dominaria',
        cost: '3',
        color: 'White',
        supertype: 'Legendary Creature',
        subtype: 'Human Knight',
        rarity: 'Uncommon',
        effects: 'First strike, vigilance, lifelink\nAura and equipment spells you cast cost {1} less to cast.',
        flavor: '"I will protect the less fortunate.  I will love bravely.  I will face despair and fight on.  As a Capashen, I can do no less."',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/dom/cards/danithacapashenparagon1.jpg'
      },
      {
        name: 'Daring Archaeologist',
        set: 'Dominaria',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Artificer',
        rarity: 'Rare',
        effects: 'When Daring Archaeologist enters the battlefield, you may return target artifact card from your graveyard to your hand.\nWhenever you cast a historic spell, put a +1/+1 counter on Daring Archaeologist.  (Artifacts, legendaries, and Sagas are historic.)',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/dom/cards/daringarchaeologist1.jpg'
      },
      {
        name: 'Dauntless Bodyguard',
        set: 'Dominaria',
        cost: '1',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Knight',
        rarity: 'Uncommon',
        effects: 'When Dauntless Bodyguard enters the battlefield, choose another creature you control.\nSacrifice Dauntless Bodyguard: The chosen creature gains indestructible until end of turn.',
        flavor: 'The Benalish aristocracy is hereditary, but the loyalty of its subjects is earned.',
        power: '2',
        toughness: '1',
        art: 'http://mythicspoiler.com/dom/cards/dauntlessbodyguard1.jpg'
      },
      {
        name: 'Dub',
        set: 'Dominaria',
        cost: '3',
        color: 'White',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Common',
        effects: 'Enchanted creature gets +2/+2, has first strike, and is a Knight in addition to its other types.',
        flavor: '"Rise, knight of New Benalia."',
        art: 'http://mythicspoiler.com/dom/cards/dub1.jpg'
      },
      {
        name: 'Evra, Halcyon Witness',
        set: 'Dominaria',
        cost: '6',
        color: 'White',
        supertype: 'Legendary Creature',
        subtype: 'Avatar',
        rarity: 'Rare',
        effects: 'Lifelink\n{4}: Exchange your life total with Evra, Halcyon Witness\'s power.',
        flavor: '"Light from the Null Moon took form--a mirage made real, alone in grandeur, isolated in a world that once had been its own."\n--Fall of the Thran',
        power: '4',
        toughness: '4',
        art: 'http://mythicspoiler.com/dom/cards/evrahalcyonwitness1.jpg'
      },
      {
        name: 'Excavation Elephant',
        set: 'Dominaria',
        cost: '5',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Elephant',
        rarity: 'Common',
        effects: 'Kicker {1W} (You may pay an additional {1W} as you cast this spell.)\nWhen Excavation Elephant enters the battlefield, if it was kicked, return target artifact card from your graveyard to your hand.',
        power: '3',
        toughness: '5',
        art: 'http://mythicspoiler.com/dom/cards/excavationelephant.jpg'
      },
      {
        name: 'Fall of the Thran',
        set: 'Dominaria',
        cost: '6',
        color: 'White',
        supertype: 'Enchantment',
        subtype: 'Saga',
        rarity: 'Rare',
        effects: '(As this Saga enters and after your draw step, add a lore counter.  Sacrifice after III.)\nI: Destroy all lands.\nII & III: Each player returns two lands from their graveyard to the battlefield.',
        art: 'http://mythicspoiler.com/dom/cards/fallofthethran.jpg'
      },
      {
        name: 'Gideon\'s Reproach',
        set: 'Dominaria',
        cost: '2',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Gideon\'s Reproach deals 4 damage to target attacking or blocking creature.',
        flavor: 'On Amonkhet, Gideon lost both his sural and his faith in himself.  But he can still throw a punch, and he still knows a bad guy when he sees one.',
        art: 'http://mythicspoiler.com/dom/cards/gideonsreproach.jpg'
      },
      {
        name: 'Healing Grace',
        set: 'Dominaria',
        cost: '1',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Prevent the next 3 damage that would be dealt to any target this turn by a source of your choice.  You gain 3 life.',
        flavor: '"Whatever faith you have in Serra, she has more in you."\n--Lyra Dawnbringer',
        art: 'http://mythicspoiler.com/dom/cards/healinggrace1.jpg'
      },
      {
        name: 'History of Benalia',
        set: 'Dominaria',
        cost: '3',
        color: 'White',
        supertype: 'Enchantment',
        subtype: 'Saga',
        rarity: 'Mythic',
        effects: '(As this Saga enters and after your draw step, add a lore counter.  Sacrifice after III.)\nI & II: Create a 2/2 white Knight creature token with vigilance.\nIII: Knights you control get +2/+1 until end of turn.',
        art: 'http://mythicspoiler.com/dom/cards/historyofbenalia1.jpg'
      },
      {
        name: 'Invoke the Divine',
        set: 'Dominaria',
        cost: '3',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Destroy target artifact or enchantment.  You gain 4 life.',
        flavor: '"Let go of all that harms you.  Cast your burdens into the darkness, and build for the faithful a house of light."\n--Song of All, canto 1008',
        art: 'http://mythicspoiler.com/dom/cards/invokethedivine1.jpg'
      },
      {
        name: 'Knight of Grace',
        set: 'Dominaria',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Knight',
        rarity: 'Uncommon',
        effects: 'First strike\nHexproof from black (This creature can\'t be the target of black spells or abilities your opponents control.)\nKnight of Grace gets +1/+0 as long as any player controls a black permanent.',
        flavor: 'A light to pierce the shadows.',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/dom/cards/knightofgrace2.jpg'
      },
      {
        name: 'Knight of New Benalia',
        set: 'Dominaria',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Knight',
        rarity: 'Common',
        flavor: 'The mage-smiths of New Benalia have perfected the art of blending fine steel and enchanted glass into weapons that are both beautiful and deadly.  Only elite knights are entrusted with these martial works of art.',
        power: '3',
        toughness: '1',
        art: 'http://mythicspoiler.com/dom/cards/knightofnewbenalia.jpg'
      },
      {
        name: 'Kwende, Pride of Femeref',
        set: 'Dominaria',
        cost: '4',
        color: 'White',
        supertype: 'Legendary Creature',
        subtype: 'Human Knight',
        rarity: 'Uncommon',
        effects: 'Double strike\nCreatures you control with first strike have double strike.',
        flavor: 'Descendant of a vanished land, student of a forgotten general, and master of blades no smith could forge anew.  He honors them all by living a life worthy of song.',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/dom/cards/kwendeprideoffemeref1.jpg'
      },
      {
        name: 'Lyra Dawnbringer',
        set: 'Dominaria',
        cost: '5',
        color: 'White',
        supertype: 'Legendary Creature',
        subtype: 'Angel',
        rarity: 'Mythic',
        effects: 'Flying, first strike, lifelink\nOther Angels you control get +1/+1 and lifelink.',
        flavor: '"You are not alone.  You never were."',
        power: '5',
        toughness: '5',
        art: 'http://mythicspoiler.com/dom/cards/lyradawnbringer1.jpg'
      },
      {
        name: 'Mesa Unicorn',
        set: 'Dominaria',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Unicorn',
        rarity: 'Common',
        effects: 'Lifelink',
        flavor: 'The unicorns of Sursi are a manifestation of Serra\'s joy and compassion.  They frolic and dance like children, offering blessings to anyone they encounter.',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/dom/cards/mesaunicorn.jpg'
      },
      {
        name: 'On Serra\'s Wings',
        set: 'Dominaria',
        cost: '4',
        color: 'White',
        supertype: 'Legendary Enchantment',
        subtype: 'Aura',
        rarity: 'Uncommon',
        effects: 'Enchant creature\nEnchanted creature is legendary, gets +1/+1, and has flying, vigilance, and lifelink.',
        flavor: '"The spirit of Serra raised Brindri high and commanded her to keep the balance."\nSong of All, canto 524',
        art: 'http://mythicspoiler.com/dom/cards/onserraswings2.jpg'
      },
      {
        name: 'Pegasus Courser',
        set: 'Dominaria',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Pegasus',
        rarity: 'Common',
        effects: 'Flying\nWhenever Pegasus Courser attacks, another target attacking creature gains flying until end of turn.',
        flavor: 'A pegasus chooses its rider, bearing the worthy into the clouds and tossing all others to the ground.',
        power: '1',
        toughness: '3',
        art: 'http://mythicspoiler.com/dom/cards/pegasuscourser.jpg'
      },
      {
        name: 'Sanctum Spirit',
        set: 'Dominaria',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Spirit',
        rarity: 'Uncommon',
        effects: 'Lifelink\nDiscard a historic card: Sanctum Spirit gains indestructible until end of turn. (Artifacts, legendaries, and Sagas are historic)',
        flavor: '"When history becomes too mournful, even good souls may choose to forget."\n--Shalai, voice of Plenty',
        power: '3',
        toughness: '2',
        art: 'http://mythicspoiler.com/dom/cards/sanctumspirit.jpg'
      },
      {
        name: 'Seal Away',
        set: 'Dominaria',
        cost: '2',
        color: 'White',
        supertype: 'Enchantment',
        rarity: 'Uncommon',
        effects: 'Flash\nWhen Seal Away enters the battlefield, exile target tapped creature an opponent controls until Seal Away leaves the battlefield.',
        flavor: 'An ancient nemesis rendered harmless long ago.',
        art: 'http://mythicspoiler.com/dom/cards/sealaway1.jpg'
      },
      {
        name: 'Sergeant-at-Arms',
        set: 'Dominaria',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Common',
        effects: 'Kicker {2W} (You may pay an additional {2W} as you cast this spell.)\nWhen Sergeant-at-Arms enters the battlefield, if it was kicked, create two 1/1 white Soldier creature tokens.',
        flavor: 'Knights get the glory.  Soldiers get things done.',
        power: '2',
        toughness: '3',
        art: 'http://mythicspoiler.com/dom/cards/sergeantatarms.jpg'
      },
      {
        name: 'Serra Angel',
        set: 'Dominaria',
        cost: '5',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Angel',
        rarity: 'Uncommon',
        effects: 'Flying, vigilance',
        flavor: 'The angel remembers her past lives like dreams.  Her song held up meadows.  Her blade drove back darkness.  Her wings carried her across the ages.',
        power: '4',
        toughness: '4',
        art: 'http://mythicspoiler.com/dom/cards/serraangel1.jpg'
      },
      {
        name: 'Serra Disciple',
        set: 'Dominaria',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Bird Cleric',
        rarity: 'Common',
        effects: 'Flying, first strike\nWhenever you cast a historic spell, Serra Disciple gets +1/+1 until end of turn. (Artifacts, legendaries, and Sagas are historic)',
        flavor: 'Theologians now believe that the Ancestor was another divine form of Serra.',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/dom/cards/serradisciple.jpg'
      },
      {
        name: 'Shalai, Voice of Plenty',
        set: 'Dominaria',
        cost: '4',
        color: 'White',
        supertype: 'Legendary Creature',
        subtype: 'Angel',
        rarity: 'Rare',
        effects: 'Flying\nYou, planeswalkers you control, and other creatures you control have hexproof.\n{4GG}: Put a +1/+1 counter on each creature you control.',
        power: '3',
        toughness: '4',
        art: 'http://mythicspoiler.com/dom/cards/shalaivoiceofplenty1.jpg'
      },
      {
        name: 'Teshar, Ancestor\'s Apostle',
        set: 'Dominaria',
        cost: '4',
        color: 'White',
        supertype: 'Legendary Creature',
        subtype: 'Bird Cleric',
        rarity: 'Rare',
        effects: 'Flying\nWhenever you cast a historic spell, return target creature card with converted mana cost 3 or less from your graveyard to the battlefield. (Artifacts, legendaries, and Sagas are historic)',
        flavor: '"The Ancestor saved us for a purpose."',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/dom/cards/tesharancestorsapostle3.jpg'
      },
      {
        name: 'Tragic Poet',
        set: 'Dominaria',
        cost: '1',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human',
        rarity: 'Common',
        effects: '{T}, Sacrifice Tragic Poet: Return target enchantment card from your graveyard to your hand.',
        flavor: '"In a healing world I write--I, who will never be healed.  Let my last gift be one of memory: from a thousand lost thoughts, choose one, and remember my name."',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/dom/cards/tragicpoet.jpg'
      },
      {
        name: 'Triumph of Gerrard',
        set: 'Dominaria',
        cost: '2',
        color: 'White',
        supertype: 'Enchantment',
        subtype: 'Saga',
        rarity: 'Uncommon',
        effects: '(As this Saga enters and after your draw step, add a lore counter.  Sacrifice after III.)\nI & II: Put a +1/+1 counter on target creature you control with the greatest power.\nIII: Target creature you control with the greatest power gains flying, first strike, and lifelink until end of turn.',
        art: 'http://mythicspoiler.com/dom/cards/triumphofgerrard1.jpg'
      },
      {
        name: 'Urza\'s Ruinous Blast',
        set: 'Dominaria',
        cost: '5',
        color: 'White',
        supertype: 'Legendary Sorcery',
        rarity: 'Rare',
        effects: '(You may cast a legendary sorcery only if you control a legendary creature or planeswalker.)\nExile all nonland permanents that aren\'t legendary.',
        flavor: 'Centuries ago, one man\'s vengeance plunged the world into ice and darkness.',
        art: 'http://mythicspoiler.com/dom/cards/urzasruinousblast3.jpg'
      },
      {
        name: 'Academy Drake',
        set: 'Dominaria',
        cost: '3',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Drake',
        rarity: 'Common',
        effects: 'Kicker {4} (You may pay an additional {4} as you cast this spell.)\nFlying\nIf Academy Drake was kicked, it enters the battlefield with two +1/+1 counters on it.',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/dom/cards/academydrake.jpg'
      },
      {
        name: 'Academy Journeymage',
        set: 'Dominaria',
        cost: '5',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Human Wizard',
        rarity: 'Common',
        effects: 'This spell costs {1} less to cast if you control a Wizard.\nWhen Academy Journeymage enters the battlefield, return target creature an opponent controls to its owner\'s hand.',
        flavor: 'We don\'t choose who comes here.  We choose how long they stay.',
        power: '3',
        toughness: '2',
        art: 'http://mythicspoiler.com/dom/cards/academyjourneymage1.jpg'
      },
      {
        name: 'The Antiquities War',
        set: 'Dominaria',
        cost: '4',
        color: 'Blue',
        supertype: 'Enchantment',
        subtype: 'Saga',
        rarity: 'Rare',
        effects: '(As this Saga enters and after your draw step, add a lore counter.  Sacrifice after III.)\nI & II: Look at the top five cards of your library.  You may reveal an artifact from among them and put it into your hand.  Put the rest on the bottom of your library in a random order.\nIII: Artifacts you control become artifact creatures with base power and toughness 5/5 until end of turn.',
        art: 'http://mythicspoiler.com/dom/cards/theantiquitieswar3.jpg'
      },
      {
        name: 'Arcane Flight',
        set: 'Dominaria',
        cost: '1',
        color: 'Blue',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Common',
        effects: 'Enchant creature\nEnchanted creature gets +1/+1 and has flying.',
        flavor: 'The Tolarian Academies are known for their magical research, powerful sorcerers, and accidental destruction of ecosystems.',
        art: 'http://mythicspoiler.com/dom/cards/arcaneflight.jpg'
      },
      {
        name: 'Artificer\'s Assistant',
        set: 'Dominaria',
        cost: '1',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Bird',
        rarity: 'Common',
        effects: 'Flying\nWhenever you cast a historic spell, scry 1. (Artifacts, legendaries, and Sagas are historic.  To scry 1, look at the top card of your library, then you may put that card on the bottom of your library.)',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/dom/cards/artificersassistant.jpg'
      },
      {
        name: 'Befuddle',
        set: 'Dominaria',
        cost: '3',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Target creature gets -4/-0 until end of turn.\nDraw a card.',
        flavor: '"The trick to talking sense into Keldons is getting them to hold still.  I learned that from Radha."\n--Jhoira',
        art: 'http://mythicspoiler.com/dom/cards/befuddle1.jpg'
      },
      {
        name: 'Blink of an Eye',
        set: 'Dominaria',
        cost: '2',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Kicker {1U} (You may pay an additional {1U} as you cast this spell.)\nReturn target nonland permanent to its owner\'s hand.  If this spell was kicked, draw a card.',
        art: 'http://mythicspoiler.com/dom/cards/blinkofaneye1.jpg'
      },
      {
        name: 'Cloudreader Sphinx',
        set: 'Dominaria',
        cost: '5',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Sphinx',
        rarity: 'Common',
        effects: 'Flying\nWhen Cloudreader Sphinx enters the battlefield, scry 2. (Look at the top two cards of your library, then put any number of them on the bottom of your library and the rest on top in any order.)',
        power: '3',
        toughness: '4',
        art: 'http://mythicspoiler.com/dom/cards/cloudreadersphinx.jpg'
      },
      {
        name: 'Cold-Water Snapper',
        set: 'Dominaria',
        cost: '6',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Turtle',
        rarity: 'Common',
        effects: 'Hexproof (This creature can\'t be the target of spells or abilities your opponents control.)',
        flavor: 'For generations, the inhabitants of Orvada have hungered for turtle soup.  For generations, the turtles have frustrated their ambitions.',
        power: '4',
        toughness: '5',
        art: 'http://mythicspoiler.com/dom/cards/coldwatersnapper.jpg'
      },
      {
        name: 'Curator\'s Ward',
        set: 'Dominaria',
        cost: '3',
        color: 'Blue',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Uncommon',
        effects: 'Enchant permanent\nEnchanted permanent has hexproof.\nWhen enchanted permanent leaves the battlefield, if it was historic, draw two cards. (Artifacts, legendaries, and Sagas are historic.)',
        art: 'http://mythicspoiler.com/dom/cards/curatorsward1.jpg'
      },
      {
        name: 'Deep Freeze',
        set: 'Dominaria',
        cost: '3',
        color: 'Blue',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Common',
        effects: 'Enchant creature\nEnchanted creature has base power and toughness 0/4, has defender, loses all other abilities, and is a blue Wall in addition to its other colors and types.',
        flavor: 'For cryomancers, studying the Ice Age isn\'t just an academic exercise.',
        art: 'http://mythicspoiler.com/dom/cards/deepfreeze1.jpg'
      },
      {
        name: 'Diligent Excavator',
        set: 'Dominaria',
        cost: '2',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Human Artificer',
        rarity: 'Uncommon',
        effects: 'Whenever you cast a historic spell, target player puts the top two cards of their library into their graveyard. (Artifacts, legendaries, and Sagas are historic.)',
        flavor: 'Archaeologists don\'t just dig in the dirt.  They excavate time, scraping off the years grain by grain.',
        power: '1',
        toughness: '3',
        art: 'http://mythicspoiler.com/dom/cards/diligentexcavator.jpg'
      },
      {
        name: 'Divination',
        set: 'Dominaria',
        cost: '3',
        color: 'Blue',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'Draw two cards.',
        flavor: '"Half your studies will be learning the laws of magic.  The other half will be bending them."\n--Naru Meha, master wizard',
        art: 'http://mythicspoiler.com/dom/cards/divination.jpg'
      },
      {
        name: 'Homarid Explorer',
        set: 'Dominaria',
        cost: '4',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Homarid Scout',
        rarity: 'Common',
        effects: 'When Homarid Explorer enters the battlefield, target player puts the top four cards of their graveyard into their library.',
        flavor: '"Homarids spread northward from Sarpadia as the climate cooled, raiding coastal settlements for supplies."\n--Time of Ice',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/dom/cards/homaridexplorer2.jpg'
      },
      {
        name: 'In Bolas\'s Clutches',
        set: 'Dominaria',
        cost: '6',
        color: 'Blue',
        supertype: 'Legendary Enchantment',
        subtype: 'Aura',
        rarity: 'Uncommon',
        effects: 'Enchant permanent\nYou control enchanted permanent.\nEnchanted permanent is legendary.',
        flavor: '"Your contract is in default.  You belong to me now.  Serve, or die."\n--Nicol Bolas',
        art: 'http://mythicspoiler.com/dom/cards/inbolassclutches1.jpg'
      },
      {
        name: 'Karn\'s Temporal Sundering',
        set: 'Dominaria',
        cost: '6',
        color: 'Blue',
        supertype: 'Legendary Sorcery',
        rarity: 'Rare',
        effects: '(You may cast a legendary sorcery only if you control a legendary creature or planeswalker.)\nTarget player takes an extra turn after this one.  Return up to one target nonland permanent to its owner\'s hand.  Exile Karn\'s Temporal Sundering.',
        flavor: 'Centuries ago, a quest to harness time became a spiral into chaos.',
        art: 'http://mythicspoiler.com/dom/cards/karnstemporalsundering2.jpg'
      },
      {
        name: 'Merfolk Trickster',
        set: 'Dominaria',
        cost: '2',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Merfolk Wizard',
        rarity: 'Uncommon',
        effects: 'Flash\nWhen Merfolk Trickster enters the battlefield, tap target creature an opponent controls.  It loses all abilities until end of turn.',
        flavor: 'Saved from destruction by one planeswalker\'s sacrifice, the Eliterate colony forswore the taking of life.',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/dom/cards/merfolktrickster2.jpg'
      },
      {
        name: 'The Mirari Conjecture',
        set: 'Dominaria',
        cost: '5',
        color: 'Blue',
        supertype: 'Enchantment',
        subtype: 'Saga',
        rarity: 'Rare',
        effects: '(As this Saga enters and after your draw step, add a lore counter.  Sacrifice after III.)\nI: Return target instant card from your graveyard to your hand.\nII: Return target sorcery card from your graveyard to your hand.\nIII: Until end of turn, whenever you cast an instant or sorcery spell, copy it.  You may choose new targets for the copy.',
        art: 'http://mythicspoiler.com/dom/cards/themirariconjecture1.jpg'
      },
      {
        name: 'Naban, Dean of Iteration',
        set: 'Dominaria',
        cost: '2',
        color: 'Blue',
        supertype: 'Legendary Creature',
        subtype: 'Human Wizard',
        rarity: 'Rare',
        effects: 'If a Wizard entering the battlefield under your control causes a triggered ability of a permanent you control to trigger, that ability triggers an additional time.',
        flavor: '"Perfect.  Now do it again."',
        power: '2',
        toughness: '1',
        art: 'http://mythicspoiler.com/dom/cards/nabandeanofiteration1.jpg'
      },
      {
        name: 'Naru Meha, Master Wizard',
        set: 'Dominaria',
        cost: '4',
        color: 'Blue',
        supertype: 'Legendary Creature',
        subtype: 'Human Wizard',
        rarity: 'Mythic',
        effects: 'Flash\nWhen Naru Meha, Master Wizard enters the battlefield, copy target instant or sorcery spell that you control.  You may choose new targets for the copy.\nOther Wizards you control get +1/+1.',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/dom/cards/narumehamasterwizard1.jpg'
      },
      {
        name: 'Opt',
        set: 'Dominaria',
        cost: '1',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Scry 1. (Look at the top card of your library.  You may put that card on the bottom of your library.)\nDraw a card.',
        flavor: 'The crystal pulsed with the power of Teferi\'s planeswalker spark.  Had Jhoira given him a blessing or a curse?',
        art: 'http://mythicspoiler.com/dom/cards/opt.jpg'
      },
      {
        name: 'Precognition Field',
        set: 'Dominaria',
        cost: '4',
        color: 'Blue',
        supertype: 'Enchantment',
        rarity: 'Rare',
        effects: 'You may look at the top card of your library. (You may do this at any time.)\nYou may cast the top card of your library if it\'s an instant or sorcery card.\n{3}: Exile the top card of your library.',
        art: 'http://mythicspoiler.com/dom/cards/precognitionfield2.jpg'
      },
      {
        name: 'Relic Runner',
        set: 'Dominaria',
        cost: '2',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Human Rogue',
        rarity: 'Common',
        effects: 'Relic Runner can\'t be blocked if you\'ve cast a historic spell this turn. (Artifacts, legendaries, and Sagas are historic.)',
        flavor: 'Her knack for tampering with wards got her kicked out of the academy, but they also got her back in.',
        power: '2',
        toughness: '1',
        art: 'http://mythicspoiler.com/dom/cards/relicrunner.jpg'
      },
      {
        name: 'Rescue',
        set: 'Dominaria',
        cost: '1',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Return target permanent you control to its owner\'s hand.',
        flavor: 'With just a few seconds to escape, Deryan saved Hurkyl\'s editions on restoring physical objects from ash.',
        art: 'http://mythicspoiler.com/dom/cards/rescue1.jpg'
      },
      {
        name: 'Sage of Lat-Nam',
        set: 'Dominaria',
        cost: '2',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Human Artificer',
        rarity: 'Uncommon',
        effects: '{T}, Sacrifice an artifact: Draw a card.',
        flavor: 'Though it was laid to waste by the brothers, many schools of magic trace their origins to the College of Lat-Nam, including the Tolarian Academy.',
        power: '1',
        toughness: '2',
        art: 'http://mythicspoiler.com/dom/cards/sageoflatnam1.jpg'
      },
      {
        name: 'Sentinel of the Pearl Trident',
        set: 'Dominaria',
        cost: '5',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Merfolk Soldier',
        rarity: 'Uncommon',
        effects: 'Flash\nWhen Sentinel of the Pearl Trident enters the battlefield, you may exile target historic permanent you control.  If you do, return that card to the battlefield under its owner\'s control at the beginning of the next end step. (Artifacts, legendaries, and Sagas are historic.)',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/dom/cards/sentinelofthepearltrident1.jpg'
      },
      {
        name: 'Slinn Voda, the Rising Deep',
        set: 'Dominaria',
        cost: '8',
        color: 'Blue',
        supertype: 'Legendary Creature',
        subtype: 'Leviathan',
        rarity: 'Uncommon',
        effects: 'Kicker {1U} (You may pay an additional {1U} as you cast this spell.)\nWhen Slinn Voda, the Rising Deep enters the battlefield, if it was kicked, return all creatures to their owners\' hands except for Merfolk, Krakens, Leviathans, Octopuses, and Serpents.',
        power: '8',
        toughness: '8',
        art: 'http://mythicspoiler.com/dom/cards/slinnvodatherisingdeep.jpg'
      },
      {
        name: 'Syncopate',
        set: 'Dominaria',
        cost: '2+',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Counter target spell unless its controller pays {X}.  If that spell is countered this way, exile it instead of putting it into its owner\'s graveyard.',
        flavor: 'The fire spell stuttered and broke.  Its pieces reached Teferi out of rythm, meaningless.',
        art: 'http://mythicspoiler.com/dom/cards/syncopate.jpg'
      },
      {
        name: 'Tempest Djinn',
        set: 'Dominaria',
        cost: '3',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Djinn',
        rarity: 'Rare',
        effects: 'Flying\nTempest Djinn gets +1/+0 for each basic Island you control.',
        flavor: 'The first to arrive on Dominaria from their distant home, the marids are the eldest tribe of djinn and the most respected by storm and sea.',
        power: '0',
        toughness: '4',
        art: 'http://mythicspoiler.com/dom/cards/tempestdjinn2.jpg'
      },
      {
        name: 'Tetsuko Umezawa, Fugitive',
        set: 'Dominaria',
        cost: '2',
        color: 'Blue',
        supertype: 'Legendary Creature',
        subtype: 'Human Rogue',
        rarity: 'Uncommon',
        effects: 'Creatures you control with power or toughness 1 or less can\'t be blocked.',
        flavor: '"My ancestor Toshiro used to say, \'Life is a series of choices between bad and worse.\'  I\'m a master of making great bad choices."',
        power: '1',
        toughness: '3',
        art: 'http://mythicspoiler.com/dom/cards/tetsukoumezawafugitive1.jpg'
      },
      {
        name: 'Time of Ice',
        set: 'Dominaria',
        cost: '4',
        color: 'Blue',
        supertype: 'Enchantment',
        subtype: 'Saga',
        rarity: 'Uncommon',
        effects: '(As this Saga enters and after your draw step, add a lore counter.  Sacrifice after III.)\nI & II: Tap target creature your opponent controls.  It doesn\'t untap during its controller\'s untap step for as long as you control Time of Ice.\nIII: Return all tapped creatures to their owner\'s hands.',
        art: 'http://mythicspoiler.com/dom/cards/timeofice1.jpg'
      },
      {
        name: 'Tolarian Scholar',
        set: 'Dominaria',
        cost: '3',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Human Wizard',
        rarity: 'Common',
        flavor: 'The Tolarian Academies embrace a tradition of study and research while discouraging the kinds of experiments that ruined the original island of Tolaria.',
        power: '2',
        toughness: '3',
        art: 'http://mythicspoiler.com/dom/cards/tolarianscholar1.jpg'
      },
      {
        name: 'Unwind',
        set: 'Dominaria',
        cost: '3',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Counter target noncreature spell.  Untap up to three lands.',
        flavor: '"A problem is only a problem if you don\'t have the tools to correct it."\n--Jhoira',
        art: 'http://mythicspoiler.com/dom/cards/unwind1.jpg'
      },
      {
        name: 'Vodalian Arcanist',
        set: 'Dominaria',
        cost: '2',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Merfolk Wizard',
        rarity: 'Common',
        effects: '{T}: Add {C}.  Use this mana only to cast an instant or sorcery spell.',
        flavor: 'The Vodalian Empire tends to be insular.  The scholarly Volshe caste are the exception, using education as an antidote to xenophobia.',
        power: '1',
        toughness: '3',
        art: 'http://mythicspoiler.com/dom/cards/vodalianarcanist.jpg'
      },
      {
        name: 'Weight of Memory',
        set: 'Dominaria',
        cost: '5',
        color: 'Blue',
        supertype: 'Sorcery',
        rarity: 'Uncommon',
        effects: 'Draw three cards.  Target player puts the top three cards of their library into their graveyard.',
        flavor: 'In lives that have stretched for centuries, there are bound to be a few awkward silences.',
        art: 'http://mythicspoiler.com/dom/cards/weightofmemory.jpg'
      },
      {
        name: 'Wizard\'s Retort',
        set: 'Dominaria',
        cost: '3',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'This spell costs {1} less to cast if you control a Wizard.\nCounter target spell.',
        flavor: '"The second mage learned to dissipate blasts of lightning.  Threat and response: thus did the study of magic progress."\n--Naban, dean of iteration',
        art: 'http://mythicspoiler.com/dom/cards/wizardsretort1.jpg'
      },
      {
        name: 'Zahid, Djinn of the Lamp',
        set: 'Dominaria',
        cost: '6',
        color: 'Blue',
        supertype: 'Legendary Creature',
        subtype: 'Djinn',
        rarity: 'Rare',
        effects: 'You may pay {3U} and tap an untapped artifact you control rather than pay this spell\'s mana cost.\nFlying',
        flavor: '"I do as I please, little mortal.  Do go on about your wishes, though--they amuse me to no end."',
        power: '5',
        toughness: '6',
        art: 'http://mythicspoiler.com/dom/cards/zahiddjinnofthelamp2.jpg'
      },
      {
        name: 'Blessing of Belzenlok',
        set: 'Dominaria',
        cost: '1',
        color: 'Black',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Target creature gets +2/+1 until end of turn.  If it\'s legendary, it also gains lifelink until end of turn.',
        flavor: '"My heart is not mine, it is Belzenlok\'s.  All hearts are his, and all blood."\n--"Rite of Belzenlok"',
        art: 'http://mythicspoiler.com/dom/cards/blessingofbelzenlok.jpg'
      },
      {
        name: 'Cabal Evangel',
        set: 'Dominaria',
        cost: '2',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Human Cleric',
        rarity: 'Common',
        flavor: '"All hail the Demonlord Belzenlok, Evincar of the Stronghold, Scion of Darkness, Doom of Fools, Lord of the Wastes, Master of the Ebon Hand, Eternal Patriarch of the Cabal..."',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/dom/cards/cabalevangel.jpg'
      },
      {
        name: 'Cabal Paladin',
        set: 'Dominaria',
        cost: '4',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Human Knight',
        rarity: 'Common',
        effects: 'Whenever you cast a historic spell, Cabal Paladin deals 2 damage to each opponent. (Artifacts, legendaries, and Sagas are historic.)',
        flavor: '"The Demonlord has ruled every age.  Every ruin, myth, and nightmare proves his power."\n--"Rite of Belzenlok"',
        power: '4',
        toughness: '2',
        art: 'http://mythicspoiler.com/dom/cards/cabalpaladin.jpg'
      },
      {
        name: 'Caligo Skin-Witch',
        set: 'Dominaria',
        cost: '2',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Human Wizard',
        rarity: 'Common',
        effects: 'Kicker {3B} (You may pay an additional {3B} as you cast this spell.)\nWhen Caligo Skin-Witch enters the battlefield, if it was kicked, each opponent discards two cards.',
        flavor: '"Take their faces.  The lips of these unbelievers may yet honor the Demonlord."',
        power: '1',
        toughness: '3',
        art: 'http://mythicspoiler.com/dom/cards/caligoskinwitch1.jpg'
      },
      {
        name: 'Cast Down',
        set: 'Dominaria',
        cost: '2',
        color: 'Black',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'Destroy target nonlegendary creature.',
        flavor: '"Your life is finished, your name lost, and your work forgotten.  It is as though Mazeura never existed."\n--Chainer\'s Torment',
        art: 'http://mythicspoiler.com/dom/cards/castdown.jpg'
      },
      {
        name: 'Chainer\'s Torment',
        set: 'Dominaria',
        cost: '4',
        color: 'Black',
        supertype: 'Enchantment',
        subtype: 'Saga',
        rarity: 'Uncommon',
        effects: 'I & II: Chainer\'s Torment deals 2 damage to each opponent and you gain 2 life.\nIII: Create an X/X black Nightmare Horror creature token, where X is half your life total, rounded up.  It deals X damage to you.',
        art: 'http://mythicspoiler.com/dom/cards/chainerstorment1.jpg'
      },
      {
        name: 'Dark Bargain',
        set: 'Dominaria',
        cost: '4',
        color: 'Black',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Look at the top three cards of your library, put two into your hand, and the other into your graveyard.  Dark Bargain deals 2 damage to you.',
        flavor: '"I have pustules of the great Ratadrabik, very cheap.  No?  Surely you\'ll want a tincture of Nevinyrral\'s pulverized remains.  Genuine!"',
        art: 'http://mythicspoiler.com/dom/cards/darkbargain1.jpg'
      },
      {
        name: 'Deathbloom Thallid',
        set: 'Dominaria',
        cost: '3',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Fungus',
        rarity: 'Common',
        effects: 'When Deathbloom Thallid dies, create a 1/1 green Saproling creature token.',
        flavor: '"Nature is not always gentle or kind, but all life begets life."\n--Marwyn of Llanowar',
        power: '3',
        toughness: '2',
        art: 'http://mythicspoiler.com/dom/cards/deathbloomthallid.jpg'
      },
      {
        name: 'Demonic Vigor',
        set: 'Dominaria',
        cost: '1',
        color: 'Black',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Common',
        effects: 'Enchant creature\nEnchanted creature gets +1/+1.\nWhen enchanted creature dies, return that card to its owner\'s hand.',
        flavor: 'In the Cabal, death is just another mark of devotion.',
        art: 'http://mythicspoiler.com/dom/cards/demonicvigor1.jpg'
      },
      {
        name: 'Demonlord Belzenlok',
        set: 'Dominaria',
        cost: '6',
        color: 'Black',
        supertype: 'Legendary Creature',
        subtype: 'Elder Demon',
        rarity: 'Mythic',
        effects: 'Flying, trample\nWhen Demonlord Belzenlok enters the battlefield, exile cards from the top of your library until you exile a nonland card, then put that card into your hand.  If the card\'s converted mana cost is 4 or greater, repeat this process.  Demonlord Belzenlok deals 1 damage to you for each card put into your hand in this way.',
        power: '6',
        toughness: '6',
        art: 'http://mythicspoiler.com/dom/cards/demonlordbelzenlok2.jpg'
      },
      {
        name: '',
        set: 'Dominaria',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Dominaria',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Dominaria',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Dominaria',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Dominaria',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Dominaria',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Dominaria',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Dominaria',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Dominaria',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Dominaria',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
      {
        name: '',
        set: 'Dominaria',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        art: ''
      },
    ]);
  });
};