exports.seed = (knex, Promise) => {
  // Deletes ALL existing entries
  return knex('Card_List').del()
  .then(() => {
    // Inserts seed entries
    return knex('Card_List').insert([
      {
        name: 'Aegis of the Heavens',
        set: 'Magic 2019 Core Set',
        cost: '2',
        color: 'White',
        supertype: 'Instant',
        effects: 'Target creature gets +1/+7 until end of turn.',
        flavor: 'Inner strength is never seen until it makes all the difference.',
        art: 'http://mythicspoiler.com/m19/cards/aegisoftheheavens1.jpg'
      },
      {
        name: 'Aethershield Harvester',
        set: 'Magic 2019 Core Set',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        rarity: 'Dwarf Artificer',
        effects: 'At the beginning of combat on your turn, target artifact creature you control gets +2/+2 and gains indestructible until end of turn. (Damage and effects that say "destroy" don\'t destroy it.)',
        flavor: 'Most smiths shape metal, but some prefer more delicate materials.',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/m19/cards/aethershieldartificer1.jpg'
      },
      {
        name: 'Ajani, Adversary of Tyrants',
        set: 'Magic 2019 Core Set',
        cost: '4',
        color: 'White',
        supertype: 'Legendary Planeswalker',
        subtype: 'Ajani',
        rarity: 'Mythic',
        effects: '+1: Put a +1/+1 counter on each of up to two target creatures.\n-2: Return target creature with converted mana cost 2 or less from your graveyard to the battlefield.\n-7: You get an emblem with, "At the beginning of your end step, create three 1/1 white Cat creature tokens with lifelink."',
        loyalty: '4',
        art: 'http://mythicspoiler.com/m19/cards/ajaniadversaryoftyrants1.jpg'
      },
      {
        name: 'Ajani\'s Last Stand',
        set: 'Magic 2019 Core Set',
        cost: '4',
        color: 'White',
        supertype: 'Enchantment',
        rarity: 'Rare',
        effects: 'Whenever a creature or planeswalker you control dies, you may sacrifice Ajani\'s Last Stand.  If you do, create a 4/4 white Avatar creature token with flying.\nWhen a spell or ability an opponent controls causes you to discard this card, if you control a Plains, create a 4/4 white Avatar creature token with flying.',
        art: 'http://mythicspoiler.com/m19/cards/ajanislaststand.jpg'
      },
      {
        name: 'Ajani\'s Pridemate',
        set: 'Magic 2019 Core Set',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Cat Warrior',
        rarity: 'Uncommon',
        effects: 'Whenever you gain life, you may put a +1/+1 counter on Ajani\'s Pridemate.',
        flavor: '"When one of us prospers, the pride prospers."\n--Jazal Goldmane',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/m19/cards/ajanispridemate.jpg'
      },
      {
        name: 'Ajani\'s Welcome',
        set: 'Magic 2019 Core Set',
        cost: '1',
        color: 'White',
        supertype: 'Enchantment',
        rarity: 'Uncommon',
        effects: 'Whenever a creature enters the battlefield under your control, you gain 1 life.',
        flavor: '"You cannot defend others if your own well-being is neglected."',
        art: 'http://mythicspoiler.com/m19/cards/ajaniswelcome.jpg'
      },
      {
        name: 'Angel of the Dawn',
        set: 'Magic 2019 Core Set',
        cost: '5',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Angel',
        rarity: 'Common',
        effects: 'Flying\nWhen Angel of the Dawn enters the battlefield, creatures you control get +1/+1 and gain vigilance until end of turn. (Attacking doesn\'t cause them to tap.)',
        flavor: 'She sings for all those who have been silenced.',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/m19/cards/angelofthedawn1.jpg'
      },
      {
        name: 'Cavalry Drillmaster',
        set: 'Magic 2019 Core Set',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Knight',
        rarity: 'Common',
        effects: 'When Cavalry Drillmaster enters the battlefield, target creature you control gets +2/+0 and gains first strike until end of turn. (It deals combat damage before creatures without first strike.)',
        power: '2',
        toughness: '1',
        art: 'http://mythicspoiler.com/m19/cards/cavalrydrillmaster.jpg'
      },
      {
        name: 'Cleansing Nova',
        set: 'Magic 2019 Core Set',
        cost: '5',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Rare',
        effects: 'Choose one --\n\tDestroy all creatures.\n\tDestroy all artifacts and enchantments.',
        flavor: 'In their final moments, the demons gazed upon grace in its purest form.',
        art: 'http://mythicspoiler.com/m19/cards/cleansingnova.jpg'
      },
      {
        name: 'Daybreak Chaplain',
        set: 'Magic 2019 Core Set',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Cleric',
        rarity: 'Common',
        effects: 'Lifelink (Damage dealt by this creature also causes you to gain that much life.)',
        flavor: '"May the light shine through me to guide the lost."',
        power: '1',
        toughness: '3',
        art: 'http://mythicspoiler.com/m19/cards/daybreakchaplain1.jpg'
      },
      {
        name: 'Dwarven Priest',
        set: 'Magic 2019 Core Set',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Dwarf Cleric',
        rarity: 'Common',
        effects: 'When Dwarven Priest enters the battlefield, you gain 1 life for each creature you control.',
        flavor: '"These storied halls are under my protection."',
        power: '2',
        toughness: '4',
        art: 'http://mythicspoiler.com/m19/cards/dwarvenpriest1.jpg'
      },
      {
        name: 'Gallant Cavalry',
        set: 'Magic 2019 Core Set',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Knight',
        rarity: 'Common',
        effects: 'Vigilance (Attacking doesn\'t cause this creature to tap.)\nWhen Gallant Cavalry enters the battlefield, create a 2/2 white Knight creature token with vigilance.',
        flavor: '"Our duty does not stop at our borders."',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/m19/cards/gallantcavalry1.jpg'
      },
      {
        name: 'Herald of Faith',
        set: 'Magic 2019 Core Set',
        cost: '5',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Angel',
        rarity: 'Uncommon',
        effects: 'Flying\nWhenever Herald of Faith attacks, you gain 2 life.',
        flavor: 'The clerics prayed for salvation.  The soldiers prayed for victory.  Both prayers were answered.',
        power: '4',
        toughness: '3',
        art: 'http://mythicspoiler.com/m19/cards/heraldoffaith.jpg'
      },
      {
        name: 'Hieromancer\'s Cage',
        set: 'Magic 2019 Core Set',
        cost: '4',
        color: 'White',
        supertype: 'Enchantment',
        rarity: 'Uncommon',
        effects: 'When Hieromancer\'s Cage enters the battlefield, exile target nonland permanent an opponent controls until Hieromancer\'s Cage leaves the battlefield.',
        flavor: 'Law protects but also contains.',
        art: 'http://mythicspoiler.com/m19/cards/hieromancerscage.jpg'
      },
      {
        name: 'Inspired Charge',
        set: 'Magic 2019 Core Set',
        cost: '4',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Creatures you control get +2/+1 until end of turn.',
        flavor: '"Impossible!  How could they overwhelm us?  We had barricades, war elephants... and they were hardly a tenth of our number!"\n--General Avitora',
        art: 'http://mythicspoiler.com/m19/cards/inspiredcharge1.jpg'
      },
      {
        name: 'Invoke the Divine',
        set: 'Magic 2019 Core Set',
        cost: '3',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Destroy target artifact or enchantment.  You gain 4 life.',
        flavor: '"Let go of all that harms you.  Cast your burdens into the darkness, and build for the faithful a house of light."\n--Song of All, canto 1008',
        art: 'http://mythicspoiler.com/m19/cards/invokethedivine1.jpg'
      },
      {
        name: 'Isolate',
        set: 'Magic 2019 Core Set',
        cost: '1',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Rare',
        effects: 'Exile target permanent with converted mana cost 1.',
        flavor: 'Threefold were his crimes, doubled were his pleas, singular was his fate.',
        art: 'http://mythicspoiler.com/m19/cards/isolate.jpg'
      },
      {
        name: 'Knight of the Tusk',
        set: 'Magic 2019 Core Set',
        cost: '6',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Knight',
        rarity: 'Common',
        effects: 'Vigilance (Attacking doesn\'t cause this creature to tap.)',
        flavor: '"Horse?  Who needs a horse?"',
        power: '3',
        toughness: '7',
        art: 'http://mythicspoiler.com/m19/cards/knightofthetusk1.jpg'
      },
      {
        name: 'Knight\'s Pledge',
        set: 'Magic 2019 Core Set',
        cost: '2',
        color: 'White',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Common',
        effects: 'Enchant creature\nEnchanted creature gets +2/+2.',
        flavor: '"As long as my faith persists, so shall I."',
        art: 'http://mythicspoiler.com/m19/cards/knightspledge1.jpg'
      },
      {
        name: 'Knightly Valor',
        set: 'Magic 2019 Core Set',
        cost: '5',
        color: 'White',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Uncommon',
        effects: 'When Knightly Valor enters the battlefield, create a 2/2 white Knight creature token with vigilance. (Attacking doesn\'t cause it to tap.)\nEnchanted creature gets +2/+2 and has vigilance.',
        art: 'http://mythicspoiler.com/m19/cards/knightlyvalor1.jpg'
      },
      {
        name: 'Lena, Selfless Champion',
        set: 'Magic 2019 Core Set',
        cost: '6',
        color: 'White',
        supertype: 'Legendary Creature',
        subtype: 'Human Knight',
        rarity: 'Rare',
        effects: 'When Lena, Selfless Champion enters the battlefield, create a 1/1 white Soldier creature token for each nontoken creature you control.\nSacrifice Lena: Creatures you control with power less than Lena\'s power gain indestructible until end of turn.',
        flavor: '"Those who do evil and those who do nothing are equally worthy of contempt."',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/m19/cards/lenaselflesschampion.jpg'
      },
      {
        name: 'Leonin Vanguard',
        set: 'Magic 2019 Core Set',
        cost: '1',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Cat Soldier',
        rarity: 'Uncommon',
        effects: 'At the beginning of combat on your turn, if you control three or more creatures, Leonin Vanguard gets +1/+1 until end of turn and you gain 1 life.',
        flavor: 'The best fighters are skilled in both harming and healing.',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/m19/cards/leoninvanguard.jpg'
      },
      {
        name: 'Leonin Warleader',
        set: 'Magic 2019 Core Set',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Cat Soldier',
        rarity: 'Rare',
        effects: 'Whenever Leonin Warleader attacks, create two 1/1 white Cat creature tokens with lifelink that are tapped and attacking.',
        flavor: 'When one leonin hunts, many more are surely nearby.',
        power: '4',
        toughness: '4',
        art: 'http://mythicspoiler.com/m19/cards/leoninwarleader.jpg'
      },
      {
        name: 'Loxodon Line Breaker',
        set: 'Magic 2019 Core Set',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Elephant Soldier',
        rarity: 'Common',
        flavor: 'Loxodons are firm in stature and spirit.  No matter the odds, they are always first into battle.',
        power: '3',
        toughness: '2',
        art: 'http://mythicspoiler.com/m19/cards/loxodonlinebreaker.jpg'
      },
      {
        name: 'Luminous Bonds',
        set: 'Magic 2019 Core Set',
        cost: '3',
        color: 'White',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Common',
        effects: 'Enchant creature\nEnchanted creature can\'t attack or block.',
        flavor: '"Your part in this fight is done, vampire.  Get used to your thirst."',
        art: 'http://mythicspoiler.com/m19/cards/luminousbonds.jpg'
      },
      {
        name: 'Make a Stand',
        set: 'Magic 2019 Core Set',
        cost: '3',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'Creatures you control get +1/+0 and gain indestructible until end of turn. (Damage and effects that say "destroy" don\'t destroy them.)',
        flavor: 'For a moment they stood tall, all fear forgotten.',
        art: 'http://mythicspoiler.com/m19/cards/makeastand.jpg'
      },
      {
        name: 'Mentor of the Meek',
        set: 'Magic 2019 Core Set',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Rare',
        effects: 'Whenever another creature with power 2 or less enters the battlefield under your control, you may pay {1}.  If you do, draw a card.',
        flavor: '"In these halls, there is no pass or fail.  Your true test comes with the first full moon."',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/m19/cards/mentorofthemeek.jpg'
      },
      {
        name: 'Mighty Leap',
        set: 'Magic 2019 Core Set',
        cost: '2',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Target creature gets +2/+2 and gains flying until end of turn.',
        flavor: '"I feel the presence of the God-Pharoah in the Second Sun, and I rise upon its rays."',
        art: 'http://mythicspoiler.com/m19/cards/mightyleap.jpg'
      },
      {
        name: 'Militia Bugler',
        set: 'Magic 2019 Core Set',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Uncommon',
        effects: 'Vigilance (Attacking doesn\'t cause this creature to tap.)\nWhen Militia Bugler enters the battlefield, look at the top four cards of your library.  You may reveal a creature card with power 2 or less from among them and put it into your hand.  Put the rest on the bottom of your library in a random order.',
        power: '2',
        toughness: '3',
        art: 'http://mythicspoiler.com/m19/cards/militiabugler.jpg'
      },
      {
        name: 'Novice Knight',
        set: 'Magic 2019 Core Set',
        cost: '1',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Knight',
        rarity: 'Uncommon',
        effects: 'Defender (This creature can\'t attack.)\nAs long as Novice Knight is enchanted or equipped, it can attack as though it didn\'t have defender.',
        flavor: 'Even the greatest hero begins with nothing.',
        power: '2',
        toughness: '3',
        art: 'http://mythicspoiler.com/m19/cards/noviceknight.jpg'
      },
      {
        name: 'Oreskos Swiftclaw',
        set: 'Magic 2019 Core Set',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Cat Warrior',
        rarity: 'Common',
        flavor: 'The leonin of Oreskos are swift to take offense -- not because they are thin-skinned, but because they are always ready for a fight.',
        power: '3',
        toughness: '1',
        art: 'http://mythicspoiler.com/m19/cards/oreskosswiftclaw.jpg'
      },
      {
        name: 'Pegasus Courser',
        set: 'Magic 2019 Core Set',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Pegasus',
        rarity: 'Common',
        effects: 'Flying\nWhenever Pegasus Courser attacks, another target attacking creature gains flying until end of turn.',
        flavor: 'A pegasus chooses its rider, bearing the worthy into the clouds and tossing all others to the ground.',
        power: '1',
        toughness: '3',
        art: 'http://mythicspoiler.com/m19/cards/pegasuscourser.jpg'
      },
      {
        name: 'Remorseful Cleric',
        set: 'Magic 2019 Core Set',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Spirit Cleric',
        rarity: 'Rare',
        effects: 'Flying\nSacrifice Remorseful Cleric: Exile all cards from target player\'s graveyard.',
        flavor: 'A lifetime of keeping up appearances is not enough to earn an eternity of rest.',
        power: '2',
        toughness: '1',
        art: 'http://mythicspoiler.com/m19/cards/remorsefulcleric.jpg'
      },
      {
        name: 'Resplendent Angel',
        set: 'Magic 2019 Core Set',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Angel',
        rarity: 'Mythic',
        effects: 'Flying\nAt the beginning of each end step, if you gained 5 or more life this turn, create a 4/4 white Angel creature token with flying and vigilance.\n{3WWW}: Until end of turn, Resplendent Angel gets +2/+2 and lifelink.',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/m19/cards/resplendentangel.jpg'
      },
      {
        name: 'Revitalize',
        set: 'Magic 2019 Core Set',
        cost: '2',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'You gain 3 life.\nDraw a card.',
        flavor: '"A potion is no substitute for a skilled surgeon, but it will hold your bits in."\n--Torricks, battlefield medic',
        art: 'http://mythicspoiler.com/m19/cards/revitalize.jpg'
      },
      {
        name: 'Rustwing Falcon',
        set: 'Magic 2019 Core Set',
        cost: '1',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Bird',
        rarity: 'Common',
        effects: 'Flying',
        flavor: 'Native to wide prairies and scrublands, falcons occasionally roost in dragon skeletons.',
        power: '1',
        toughness: '2',
        art: 'http://mythicspoiler.com/m19/cards/rustwingfalcon.jpg'
      },
      {
        name: 'Shield Mare',
        set: 'Magic 2019 Core Set',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Horse',
        rarity: 'Uncommon',
        effects: 'Shield Mare can\'t be blocked by red creatures.\nWhen Shield Mare enters the battlefield or becomes the target of a spell or ability an opponent controls, you gain 3 life.',
        flavor: 'When it passes, order defeats chaos.',
        power: '2',
        toughness: '3',
        art: 'http://mythicspoiler.com/m19/cards/shieldmare.jpg'
      },
      {
        name: 'Star-Crowned Stag',
        set: 'Magic 2019 Core Set',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Elk',
        rarity: 'Common',
        effects: 'Whenever Star-Crowned Stag attacks, tap target creature defending player controls.',
        flavor: 'White as starlight on snow, it appears only on the eve of the winter solstice.',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/m19/cards/starcrownedstag.jpg'
      },
      {
        name: 'Suncleanser',
        set: 'Magic 2019 Core Set',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Cleric',
        rarity: 'Rare',
        effects: 'When Suncleanser enters the battlefield, choose one --\n\tRemove all counters from target creature.  It can\'t have counters put on it for as long as Suncleanser remains on the battlefield.\n\tTarget opponent loses all counters.  That player can\'t get counters for as long as Suncleanser remains on the battlefield.',
        power: '1',
        toughness: '4',
        art: 'http://mythicspoiler.com/m19/cards/suncleanser.jpg'
      },
      {
        name: 'Take Vengeance',
        set: 'Magic 2019 Core Set',
        cost: '2',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'Destroy target tapped creature.',
        flavor: '"Your death will be a balm, your passing a welcome revision, and all will sigh with peace to know of your demise."',
        art: 'http://mythicspoiler.com/m19/cards/takevengeance.jpg'
      },
      {
        name: 'Trusty Packbeast',
        set: 'Magic 2019 Core Set',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Beast',
        rarity: 'Common',
        effects: 'When Trusty Packbeast enters the battlefield, return target artifact card from your graveyard to your hand.',
        flavor: '"Margaret has traveled with me to the end of the world and back."\n--Hewen Frit, merchant',
        power: '2',
        toughness: '3',
        art: 'http://mythicspoiler.com/m19/cards/trustypackbeast.jpg'
      },
      {
        name: 'Valiant Knight',
        set: 'Magic 2019 Core Set',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Knight',
        rarity: 'Rare',
        effects: 'Other Knights you control get +1/+1.\n{3WW}: Knights you control gain double strike until end of turn.',
        flavor: '"Defeat is no reason to retreat.  It is a sign we must redouble our efforts to win this fight."',
        power: '3',
        toughness: '4',
        art: 'http://mythicspoiler.com/m19/cards/valiantknight.jpg'
      },
      {
        name: 'Aether Tunnel',
        set: 'Magic 2019 Core Set',
        cost: '2',
        color: 'Blue',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Uncommon',
        effects: 'Enchant creature\nEnchanted creature gets +1/+0 and can\'t be blocked.',
        flavor: 'If you can\'t find a doorway, make one.',
        art: 'http://mythicspoiler.com/m19/cards/aethertunnel.jpg'
      },
      {
        name: 'Anticipate',
        set: 'Magic 2019 Core Set',
        cost: '2',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Look at the top three cards of your library.  Put one of them into your hand and the rest on the bottom of your library in any order.',
        flavor: 'Divining the future is easy when you hold the power to sway it.',
        art: 'http://mythicspoiler.com/m19/cards/anticipate.jpg'
      },
      {
        name: 'Aven Wind Mage',
        set: 'Magic 2019 Core Set',
        cost: '3',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Bird Wizard',
        rarity: 'Common',
        effects: 'Flying\nWhenever you cast an instant or sorcery spell, Aven Wind Mage gets +1/+1 until end of turn.',
        flavor: '"My skill sharpens with each beat of my wings."',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/m19/cards/avenwindmage.jpg'
      },
      {
        name: 'Aviation Pioneer',
        set: 'Magic 2019 Core Set',
        cost: '3',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Human Artificer',
        rarity: 'Common',
        effects: 'When Aviation Pioneer enters the battlefield, create a 1/1 colorless Thopter artifact creature token with flying.',
        flavor: '"They say perfection is unattainable, but they said that about flight too."',
        power: '1',
        toughness: '2',
        art: 'http://mythicspoiler.com/m19/cards/aviationpioneer.jpg'
      },
      {
        name: 'Bone to Ash',
        set: 'Magic 2019 Core Set',
        cost: '4',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'Counter target creature spell.\nDraw a card.',
        flavor: '"I can think of worse ways to go.  On second thought, maybe not."\n--Ludevic, necro-alchemist',
        art: 'http://mythicspoiler.com/m19/cards/bonetoash.jpg'
      },
      {
        name: 'Cancel',
        set: 'Magic 2019 Core Set',
        cost: '3',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Counter target spell.',
        flavor: '"I decide what stands in my way."',
        art: 'http://mythicspoiler.com/m19/cards/cancel.jpg'
      },
      {
        name: 'Departed Deckhand',
        set: 'Magic 2019 Core Set',
        cost: '2',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Spirit Pirate',
        rarity: 'Uncommon',
        effects: 'When Departed Deckhand becomes the target of a spell, sacrifice it.\nDeparted Deckhand can\'t be blocked except by Spirits.\n{3U}: Another target creature you control can\'t be blocked this turn except by Spirits.',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/m19/cards/departeddeckhand.jpg'
      },
      {
        name: 'Disperse',
        set: 'Magic 2019 Core Set',
        cost: '2',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Return target nonland permanent to its owner\'s hand.',
        flavor: 'It\'s pointless to hold on when you have nothing to hold on with.',
        art: 'http://mythicspoiler.com/m19/cards/disperse.jpg'
      },
      {
        name: 'Divination',
        set: 'Magic 2019 Core Set',
        cost: '3',
        color: 'Blue',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'Draw two cards.',
        flavor: '"The stars mark your destiny.  May you accept the fate thus divulged."',
        art: 'http://mythicspoiler.com/m19/cards/divination.jpg'
      },
      {
        name: 'Djinn of Wishes',
        set: 'Magic 2019 Core Set',
        cost: '5',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Djinn',
        rarity: 'Rare',
        effects: 'Flying\nDjinn of Wishes enters the battlefield with three wish counters on it.\n{2UU}, Remove a wish counter from Djinn of Wishes: Reveal the top card of your library.  You may play that card without paying its mana cost.  If you don\'t, exile it.',
        power: '4',
        toughness: '4',
        art: 'http://mythicspoiler.com/m19/cards/djinnofwishes.jpg'
      },
      {
        name: 'Dwindle',
        set: 'Magic 2019 Core Set',
        cost: '3',
        color: 'Blue',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Common',
        effects: 'Enchant creature\nEnchanted creature gets -6/-0.\nWhen enchanted creature blocks, destroy it. (The attacking creature remains blocked.)',
        flavor: 'The collection didn\'t have room to expand, so the wizard improvised a solution.',
        art: 'http://mythicspoiler.com/m19/cards/dwindle.jpg'
      },
      {
        name: 'Essence Scatter',
        set: 'Magic 2019 Core Set',
        cost: '2',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Counter target creature spell.',
        flavor: 'Dependence on luck is anathema to Kefnet\'s rigorous studies.  Those who hope to escape his maze by chance never succeed.',
        art: 'http://mythicspoiler.com/m19/cards/essencescatter.jpg'
      },
      {
        name: 'Exclusion Mage',
        set: 'Magic 2019 Core Set',
        cost: '3',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Human Wizard',
        rarity: 'Uncommon',
        effects: 'When Exclusion Mage enters the battlefield, return target creature an opponent controls to its owner\'s hand.',
        flavor: 'Successful battles start with knowing who\'s worth fighting.',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/m19/cards/exclusionmage.jpg'
      },
      {
        name: 'Frilled Sea Serpent',
        set: 'Magic 2019 Core Set',
        cost: '6',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Serpent',
        rarity: 'Common',
        effects: '{5UU}: Frilled Sea Serpent can\'t be blocked this turn.',
        flavor: '"Reel it in.  No, wait!  Throw it back!"\n--Gertrude, deep-sea angler',
        power: '4',
        toughness: '6',
        art: 'http://mythicspoiler.com/m19/cards/frilledseaserpent.jpg'
      },
      {
        name: 'Gearsmith Prodigy',
        set: 'Magic 2019 Core Set',
        cost: '1',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Human Artificer',
        rarity: 'Common',
        effects: 'Gearsmith Prodigy gets +1/+0 as long as you control an artifact.',
        flavor: 'Young artificers on Kaladesh let their imaginations run wild.',
        power: '1',
        toughness: '2',
        art: 'http://mythicspoiler.com/m19/cards/gearsmithprodigy.jpg'
      },
      {
        name: 'Ghostform',
        set: 'Magic 2019 Core Set',
        cost: '2',
        color: 'Blue',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'Up to two target creatures can\'t be blocked this turn.',
        flavor: '"Picking locks is for beginners."',
        art: 'http://mythicspoiler.com/m19/cards/ghostform.jpg'
      },
      {
        name: 'Horizon Scholar',
        set: 'Magic 2019 Core Set',
        cost: '6',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Sphinx',
        rarity: 'Uncommon',
        effects: 'Flying\nWhen Horizon Scholar enters the battlefield, scry 2. (Look at the top two cards of your library, then put any number of them on the bottom of your library and the rest on top in any order.)',
        power: '4',
        toughness: '4',
        art: 'http://mythicspoiler.com/m19/cards/horizonscholar.jpg'
      },
      {
        name: 'Metamorphic Alteration',
        set: 'Magic 2019 Core Set',
        cost: '2',
        color: 'Blue',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Rare',
        effects: 'As Metamorphic Alteration enters the battlefield, choose a creature.\n Enchanted creature is a copy of the chosen creature.',
        art: 'http://mythicspoiler.com/m19/cards/metamorphicalteration.jpg'
      },
      {
        name: 'Mirror Image',
        set: 'Magic 2019 Core Set',
        cost: '3',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Shapeshifter',
        rarity: 'Uncommon',
        effects: 'You may have Mirror Image enter the battlefield as a copy of any creature you control.',
        flavor: 'The life of a shapeshifter is one of constant change.',
        power: '0',
        toughness: '0',
        art: 'http://mythicspoiler.com/m19/cards/mirrorimage.jpg'
      },
      {
        name: 'Mistcaller',
        set: 'Magic 2019 Core Set',
        cost: '1',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Merfolk Wizard',
        rarity: 'Rare',
        effects: 'Sacrifice Mistcaller: Until end of turn, if a nontoken creature would enter the battlefield and it wasn\'t cast, exile it instead.',
        flavor: 'Hospitality is of little concern for those who do not wish to be disturbed.',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/m19/cards/mistcaller.jpg'
      },
      {
        name: 'Mystic Archaeologist',
        set: 'Magic 2019 Core Set',
        cost: '2',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Human Wizard',
        rarity: 'Rare',
        effects: '{3UU}: Draw two cards.',
        flavor: 'The delight of discovery drives the pursuit of knowledge.',
        power: '2',
        toughness: '1',
        art: 'http://mythicspoiler.com/m19/cards/mysticarchaeologist.jpg'
      },
      {
        name: 'Omenspeaker',
        set: 'Magic 2019 Core Set',
        cost: '2',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Human Wizard',
        rarity: 'Common',
        effects: 'When Omenspeaker enters the battlefield, scry 2. (Look at the top two cards of your library, then put any number of them on the bottom of your library and the rest on top in any order.)',
        flavor: 'Her prophecies amaze her even as she speaks them.',
        power: '1',
        toughness: '3',
        art: 'http://mythicspoiler.com/m19/cards/omenspeaker.jpg'
      },
      {
        name: 'Omniscience',
        set: 'Magic 2019 Core Set',
        cost: '10',
        color: 'Blue',
        supertype: 'Enchantment',
        rarity: 'Mythic',
        effects: 'You may cast spells from your hand without paying their mana costs.',
        flavor: '"The things I once imagined would be my greatest achievements were only the first steps toward a future I can only begin to fathom."\n--Jace Beleren',
        art: 'http://mythicspoiler.com/m19/cards/omniscience.jpg'
      },
      {
        name: 'One with the Machine',
        set: 'Magic 2019 Core Set',
        cost: '4',
        color: 'Blue',
        supertype: 'Sorcery',
        rarity: 'Rare',
        effects: 'Draw cards equal to the highest converted mana cost among artifacts you control.',
        flavor: '"When I grafted the Planar Bridge into myself, I felt my Planeswalker spark flare beyond my body.  The Multiverse was my plaything.  It felt... incredible."\n--Tezzeret',
        art: 'http://mythicspoiler.com/m19/cards/onewiththemachine.jpg'
      },
      {
        name: 'Patient Rebuilding',
        set: 'Magic 2019 Core Set',
        cost: '5',
        color: 'Blue',
        supertype: 'Enchantment',
        rarity: 'Rare',
        effects: 'At the beginning of your upkeep, target opponent puts the top three cards of their hand into their graveyard, then you draw cards for each land card put into that graveyard this way.',
        flavor: 'Nicol Bolas would not rest until he was restored to his former glory.',
        art: 'http://mythicspoiler.com/m19/cards/patientrebuilding.jpg'
      },
      {
        name: 'Psychic Corrosion',
        set: 'Magic 2019 Core Set',
        cost: '3',
        color: 'Blue',
        supertype: 'Enchantment',
        rarity: 'Uncommon',
        effects: 'Whenever you draw a card, each opponent puts the top two cards of their library into their graveyard.',
        flavor: '"To break another\'s mind is to deliver a fate worse than death.  It is a terrifying power."\n--Jace Beleren',
        art: 'http://mythicspoiler.com/m19/cards/psychiccorrosion.jpg'
      },
      {
        name: 'Sai, Master Thopterist',
        set: 'Magic 2019 Core Set',
        cost: '3',
        color: 'Blue',
        supertype: 'Legendary Creature',
        subtype: 'Human Artificer',
        rarity: 'Rare',
        effects: 'Whenever you cast an artifact spell, create a 1/1 colorless Thopter artifact creature token with flying.\n{1U}, Sacrifice two artifacts: Draw a card.',
        flavor: '"Industry without artistry is just a fancy way to fill a junkyard."',
        power: '1',
        toughness: '4',
        art: 'http://mythicspoiler.com/m19/cards/saimasterthopterist.jpg'
      },
      {
        name: 'Salvager of Secrets',
        set: 'Magic 2019 Core Set',
        cost: '5',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Merfolk Wizard',
        rarity: 'Common',
        effects: 'When Salvager of Secrets enters the battlefield, return target instant or sorcery card from your graveyard to your hand.',
        flavor: 'The greatest treasure of the deep is an echo from above.',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/m19/cards/salvagerofsecrets.jpg'
      },
      {
        name: 'Scholar of Stars',
        set: 'Magic 2019 Core Set',
        cost: '4',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Human Artificer',
        rarity: 'Common',
        effects: 'When Scholar of Stars enters the battlefield, if you control an artifact, draw a card.',
        flavor: '"The path of the stars is as reliable as the instruments that measure them."',
        power: '3',
        toughness: '2',
        art: 'http://mythicspoiler.com/m19/cards/scholarofstars.jpg'
      },
      {
        name: 'Sift',
        set: 'Magic 2019 Core Set',
        cost: '4',
        color: 'Blue',
        supertype: 'Sorcery',
        rarity: 'Uncommon',
        effects: 'Draw three cards, then discard one card.',
        flavor: 'Dwell longest on the thoughts that shine brightest.',
        art: 'http://mythicspoiler.com/m19/cards/sift.jpg'
      },
      {
        name: 'Skilled Animator',
        set: 'Magic 2019 Core Set',
        cost: '3',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Human Artificer',
        rarity: 'Uncommon',
        effects: 'When Skilled Animator enters the battlefield, target artifact you control becomes an artifact creature with base power and toughness 5/5 for as long as Skilled Animator remains on the battlefield.',
        power: '1',
        toughness: '3',
        art: 'http://mythicspoiler.com/m19/cards/skilledanimator.jpg'
      },
      {
        name: 'Sleep',
        set: 'Magic 2019 Core Set',
        cost: '4',
        color: 'Blue',
        supertype: 'Sorcery',
        rarity: 'Uncommon',
        effects: 'Tap all creatures target player controls.  Those creatures don\'t untap during that player\'s next untap step.',
        flavor: '"I give them dreams so wonderous that they hesitate to return to the realm of the conscious."\n--Garild, merfolk mage',
        art: 'http://mythicspoiler.com/m19/cards/sleep.jpg'
      },
      {
        name: 'Snapping Drake',
        set: 'Magic 2019 Core Set',
        cost: '4',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Drake',
        rarity: 'Common',
        effects: 'Flying',
        flavor: 'Foul-tempered, poorly trained, and mule-stubborn, the drake is the perfect test of the master\'s will.',
        power: '3',
        toughness: '2',
        art: 'http://mythicspoiler.com/m19/cards/snappingdrake.jpg'
      },
      {
        name: 'Supreme Phantom',
        set: 'Magic 2019 Core Set',
        cost: '2',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Spirit',
        rarity: 'Rare',
        effects: 'Flying\nOther Spirits you control get +1/+1.',
        flavor: 'A king\'s knowledge does not vanish when the heart stops beating.',
        power: '1',
        toughness: '3',
        art: 'http://mythicspoiler.com/m19/cards/supremephantom.jpg'
      },
      {
        name: 'Surge Mare',
        set: 'Magic 2019 Core Set',
        cost: '2',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Horse Fish',
        rarity: 'Uncommon',
        effects: 'Surge Mare can\'t be blocked by green creatures.\nWhenever Surge Mare deals damage to an opponent, you may draw a card.  If you do, discard a card.\n{1U}: Surge Mare gets +2/-2 until end of turn.',
        flavor: 'When it passes, waves touch the sky.',
        power: '0',
        toughness: '5',
        art: 'http://mythicspoiler.com/m19/cards/surgemare.jpg'
      },
      {
        name: 'Switcheroo',
        set: 'Magic 2019 Core Set',
        cost: '5',
        color: 'Blue',
        supertype: 'Sorcery',
        rarity: 'Uncommon',
        effects: 'Exchange control of two target creatures.',
        flavor: 'Say hello to your new friend.',
        art: 'http://mythicspoiler.com/m19/cards/switcheroo.jpg'
      },
      {
        name: 'Tezzeret, Artifice Master',
        set: 'Magic 2019 Core Set',
        cost: '5',
        color: 'Blue',
        supertype: 'Legendary Planeswalker',
        subtype: 'Tezzeret',
        rarity: 'Mythic',
        effects: '+1: Create a 1/1 colorless Thopter artifact creature token with flying.\n0: Draw a card.  If you control three or more artifacts, draw two cards instead.\n-9: You get an emblem with "At the beginning of your end step, search your library for a permanent card, put it onto the battlefield, then shuffle your library."',
        loyalty: '5',
        art: 'http://mythicspoiler.com/m19/cards/tezzeretartificemaster.jpg'
      },
      {
        name: 'Tolarian Scholar',
        set: 'Magic 2019 Core Set',
        cost: '3',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Human Wizard',
        rarity: 'Common',
        flavor: 'The Tolarian Academies embrace a tradition of study and research while discouraging the kinds of experiments that ruined the original island of Tolaria.',
        power: '2',
        toughness: '3',
        art: 'http://mythicspoiler.com/m19/cards/tolarianscholar.jpg'
      },
      {
        name: 'Totally Lost',
        set: 'Magic 2019 Core Set',
        cost: '5',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Put target nonland permanent on top of its owner\'s library.',
        flavor: 'Fblthp had always hated crowds.',
        art: 'http://mythicspoiler.com/m19/cards/totallylost.jpg'
      },
      {
        name: 'Uncomfortable Chill',
        set: 'Magic 2019 Core Set',
        cost: '3',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Creatures your opponents control get -2/-0 until end of turn.\nDraw a card.',
        flavor: 'The cold slowed their movements until only their panicked eyeballs swiveled beneath the ice.',
        art: 'http://mythicspoiler.com/m19/cards/uncomfortablechill.jpg'
      },
      {
        name: 'Windreader Sphinx',
        set: 'Magic 2019 Core Set',
        cost: '7',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Sphinx',
        rarity: 'Rare',
        effects: 'Flying\nWhenever a creature with flying attacks, you may draw a card.',
        flavor: '"Your mind is too filled with foolish concerns to hear the subtle whispers that the breeze brings."',
        power: '3',
        toughness: '7',
        art: 'http://mythicspoiler.com/m19/cards/windreadersphinx.jpg'
      },
      {
        name: 'Wall of Mist',
        set: 'Magic 2019 Core Set',
        cost: '2',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Wall',
        rarity: 'Common',
        effects: 'Defender (This creature can\'t attack.)',
        flavor: 'The seafloor is flecked with the bones of fools who dared to sail into the mist.',
        power: '0',
        toughness: '5',
        art: 'http://mythicspoiler.com/m19/cards/wallofmist.jpg'
      },
      {
        name: '',
        set: 'Magic 2019 Core Set',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
    ]);
  });
};
