exports.seed = (knex, Promise) => {
  // Deletes ALL existing entries
  return knex('Card_List').del()
  .then(() => {
    // Inserts seed entries
    return knex('Card_List').insert([
      {
        name: 'Blade Instructor',
        set: 'Guilds of Ravnica',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Common',
        effects: 'Mentor (Whenever this creature attacks, put a +1/+1 counter on target attacking creature with lesser power.)',
        flavor: '"Watch carefully.  The gap between death and victory is thinner than your blade."',
        power: '3',
        toughness: '1',
        art: 'http://mythicspoiler.com/grn/cards/bladeinstructor.jpg'
      },
      {
        name: 'Bounty Agent',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Rare',
        effects: 'Vigilance\n{T}, Sacrifice Bounty Agent: Destroy target legendary permanent that\'s an artifact, creature, or enchantment.',
        flavor: '"Lately I\'ve seen the biggest bounties of my career -- and for the biggest names."',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/grn/cards/bountyagent.jpg'
      },
      {
        name: 'Candlelight Vigil',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'White',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Common',
        effects: 'Enchant creature\nEnchanted creature gets +3/+2 and has vigilance.',
        flavor: 'Selesnya guildmages do not sleep so the rest of the Conclave can.',
        art: 'http://mythicspoiler.com/grn/cards/candlelightvigil.jpg'
      },
      {
        name: 'Citywide Bust',
        set: 'Guilds of Ravnica',
        cost: '3',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Rare',
        effects: 'Destroy all creatures with toughness 4 or greater.',
        flavor: '"Oh, you fellas are going to love the lockup.  Excellent gruel.  Very low ceilings."\n--Libuse, Boros sergeant',
        art: 'http://mythicspoiler.com/grn/cards/citywidebust.jpg'
      },
      {
        name: 'Collar the Culprit',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Destroy target creature with toughness 4 or greater.',
        flavor: '"Reports of Gruul rioters in four districts.  Start with the big ones and work your way up."\n--Libuse, Boros sergeant',
        art: 'http://mythicspoiler.com/grn/cards/collartheculprit.jpg'
      },
      {
        name: 'Conclave Tribunal',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'White',
        supertype: 'Enchantment',
        rarity: 'Uncommon',
        effects: 'Convoke (Your creatures can help cast this spell.  Each creature you tap while casting this spell pays for {1} or one mana of that creature\'s color.)\nWhen Conclave Tribunal enters the battlefield, exile target nonland permanent an opponent controls until Conclave Tribunal leaves the battlefield.',
        art: 'http://mythicspoiler.com/grn/cards/conclavetribunal.jpg'
      },
      {
        name: 'Crush Contraband',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'Choose one or both --\n\tExile target artifact.\n\tExile target enchantment.',
        flavor: 'The Izzet mage knew she would neither get her thermoinverter back nor have the satisfaction of exploding it herself.',
        art: 'http://mythicspoiler.com/grn/cards/crushcontraband.jpg'
      },
      {
        name: 'Dawn of Hope',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'White',
        supertype: 'Enchantment',
        rarity: 'Rare',
        effects: 'Whenever you gain life, you may pay {2}.  If you do, draw a card.\n{3W}: Create a 1/1 white Soldier creature token with lifelink.',
        flavor: '"To wage war, secure peace within yourself."\n--Emmara',
        art: 'http://mythicspoiler.com/grn/cards/dawnofhope.jpg'
      },
      {
        name: 'Demotion',
        set: 'Guilds of Ravnica',
        cost: '1',
        color: 'White',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Uncommon',
        effects: 'Enchant creature\nEnchanted creature can\'t block, and its activated abilities can\'t be activated.',
        flavor: 'There\'s no greater honor than joining your chosen guild, and no greater shame than failing it.',
        art: 'http://mythicspoiler.com/grn/cards/demotion.jpg'
      },
      {
        name: 'Divine Visitation',
        set: 'Guilds of Ravnica',
        cost: '5',
        color: 'White',
        supertype: 'Enchantment',
        rarity: 'Mythic',
        effects: 'If one or more creature tokens would be created under your control, that many 4/4 white Angel creature tokens with flying and vigilance are created instead.',
        flavor: 'The angels appreciated the offer but politely declined to eat any birdseed.',
        art: 'http://mythicspoiler.com/grn/cards/divinevisitation.jpg'
      },
      {
        name: 'Flight of Equenauts',
        set: 'Guilds of Ravnica',
        cost: '8',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Knight',
        rarity: 'Uncommon',
        effects: 'Convoke (Your creatures can help cast this spell.  Each creature you tap while casting this spell pays for {1} or one mana of that creature\'s color.)\nFlying',
        flavor: '"Yes, there\'s competition between our equenauts and the Boros skyjeks.  At least they think it\'s a competition."',
        power: '4',
        toughness: '5',
        art: 'http://mythicspoiler.com/grn/cards/flightofequenauts.jpg'
      },
      {
        name: 'Gird for Battle',
        set: 'Guilds of Ravnica',
        cost: '1',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Uncommon',
        effects: 'Put a +1/+1 counter on each of up to two target creatures.',
        flavor: '"You won\'t need the sword drills, your shields, or my blessing.  You\'ll fight for Sunhome with the truth in your heart."\n--Aurelia',
        art: 'http://mythicspoiler.com/grn/cards/girdforbattle.jpg'
      },
      {
        name: 'Haazda Marshal',
        set: 'Guilds of Ravnica',
        cost: '1',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Uncommon',
        effects: 'Whenever Haazda Marshal and at least two other creatures attack, create a 1/1 white Soldier creature token with lifelink.',
        flavor: 'Ravnica\'s convoluted power structure often boils down to who can muster the most swords on a given block.',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/grn/cards/haazdamarshal.jpg'
      },
      {
        name: 'Healer\'s Hawk',
        set: 'Guilds of Ravnica',
        cost: '1',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Bird',
        rarity: 'Common',
        effects: 'Flying, lifelink',
        flavor: 'The wounded see the glow of its vials long before they see its wings diving out of the clouds.',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/grn/cards/healershawk.jpg'
      },
      {
        name: 'Hunted Witness',
        set: 'Guilds of Ravnica',
        cost: '1',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human',
        rarity: 'Common',
        effects: 'When Hunted Witness dies, create a 1/1 white Soldier creature token with lifelink.',
        flavor: 'He ferried weapons, spells, exotic animals -- but his most dangerous cargo was the truth.',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/grn/cards/huntedwitness.jpg'
      },
      {
        name: 'Inspiring Unicorn',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Unicorn',
        rarity: 'Uncommon',
        effects: 'Whenever Inspiring Unicorn attacks, creatures you control get +1/+1 until end of turn.',
        flavor: 'There are two lives: the life you live before you see a unicorn, and the life you live after.',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/grn/cards/inspiringunicorn.jpg'
      },
      {
        name: 'Intrusive Packbeast',
        set: 'Guilds of Ravnica',
        cost: '5',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Beast',
        rarity: 'Common',
        effects: 'Vigilance\nWhen Intrusive Packbeast enters the battlefield, tap up to two target creatures your opponents control.',
        flavor: 'Good at carrying things.  Really good at knocking them down.',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/grn/cards/intrusivepackbeast.jpg'
      },
      {
        name: 'Ledev Guardian',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Knight',
        rarity: 'Common',
        effects: 'Convoke (Your creatures can help cast this spell.  Each creature you tap while casting this spell pays for  {1} or one mana of that creature\'s color.)',
        flavor: '"I\'ve raised her since she was a pup, and she\'s raised me since I was a recruit."',
        power: '2',
        toughness: '4',
        art: 'http://mythicspoiler.com/grn/cards/ledevguardian.jpg'
      },
      {
        name: 'Light of the Legion',
        set: 'Guilds of Ravnica',
        cost: '6',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Angel',
        rarity: 'Rare',
        effects: 'Flying\nMentor (Whenever this creature attacks, put a +1/+1 counter on target attacking creature with lesser power.)\nWhen Light of the Legion dies, put a +1/+1 counter on each white creature you control.',
        power: '5',
        toughness: '5',
        art: 'http://mythicspoiler.com/grn/cards/lightofthelegion.jpg'
      },
      {
        name: 'Loxodon Restorer',
        set: 'Guilds of Ravnica',
        cost: '6',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Elephant Cleric',
        rarity: 'Common',
        effects: 'Convoke (Your creatures can help cast this spell.  Each creature you tap while casting this spell pays for {1} or one mana of that creature\'s color.)\nWhen Loxodon Restorer enters the battlefield, you gain 4 life.',
        power: '3',
        toughness: '4',
        art: 'http://mythicspoiler.com/grn/cards/loxodonrestorer.jpg'
      },
      {
        name: 'Luminous Bonds',
        set: 'Guilds of Ravnica',
        cost: '3',
        color: 'White',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Common',
        effects: 'Enchant creature\nEnchanted creature can\'t attack or block.',
        flavor: '"Article 5.8.2. Ensure proper restraint of any and all arms, legs, claws, jaws, tails, tentacles, and tendrils as appropriate."\n--Azorius Arrester Procedure, appendix B',
        art: 'http://mythicspoiler.com/grn/cards/luminousbonds.jpg'
      },
      {
        name: 'Parhelion Patrol',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Knight',
        rarity: 'Common',
        effects: 'Flying, vigilance\nMentor (Whenever this creature attacks, put a +1/+1 counter on target attacking creature with lesser power.)',
        flavor: '"Too many have disappeared in these dark days.  I am the light that will lead them home."',
        power: '2',
        toughness: '3',
        art: 'http://mythicspoiler.com/grn/cards/parhelionpatrol.jpg'
      },
      {
        name: 'Righteous Blow',
        set: 'Guilds of Ravnica',
        cost: '1',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Righteous Blow deals 2 damage to target attacking or blocking creature.',
        flavor: '"The Golgari believe they should be given what they deserve.  On this we agree."\n--Tajic',
        art: 'http://mythicspoiler.com/grn/cards/righteousblow.jpg'
      },
      {
        name: 'Roc Charger',
        set: 'Guilds of Ravnica',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Bird',
        rarity: 'Uncommon',
        effects: 'Flying\nWhenever Roc Charger attacks, target attacking creature without flying gains flying until end of turn.',
        flavor: 'Rocs\' innate fearlessness makes them ideal mounts for emergency response.',
        power: '1',
        toughness: '3',
        art: 'http://mythicspoiler.com/grn/cards/roccharger.jpg'
      },
      {
        name: 'Skyline Scout',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Scout',
        rarity: 'Common',
        effects: 'Whenever Skyline Scout attacks, you may pay {1W}.  If you do, it gains flying until end of turn.',
        flavor: '"Sometimes an angel passes by and gives me a little nod, like, "You\'re a daring one!"  That always makes my day."',
        power: '2',
        toughness: '1',
        art: 'http://mythicspoiler.com/grn/cards/skylinescout.jpg'
      },
      {
        name: 'Sunhome Stalwart',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Uncommon',
        effects: 'First strike\nMentor (Whenever this creature attacks, put a +1/+1 counter on target attacking creature with lesser power.)',
        flavor: '"Before I let you wield one of these, let\'s see you dodge one!"',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/grn/cards/sunhomestalwart.jpg'
      },
      {
        name: 'Sworn Companions',
        set: 'Guilds of Ravnica',
        cost: '3',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'Create two 1/1 white Soldier creature tokens with lifelink.',
        flavor: '"The trouble with youths these days is that, in outright defiance of their elders, they refuse to be bought."\n--Karlov of the Ghost Council',
        art: 'http://mythicspoiler.com/grn/cards/sworncompanions.jpg'
      },
      {
        name: 'Take Heart',
        set: 'Guilds of Ravnica',
        cost: '1',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Target creature gets +1/+1 until end of turn.  You gain 1 life for each attacking creature you control.',
        flavor: 'In the quiet before a battle, Boros soldiers whisper prayers that steady their nerves and focus their minds.',
        art: 'http://mythicspoiler.com/grn/cards/takeheart.jpg'
      },
      {
        name: 'Tenth District Guard',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Common',
        effects: 'When Tenth District Guard enters the battlefield, target creature gets +0/+1 until end of turn.',
        flavor: '"The Tenth has always been my home.  This city is constantly embroiled in one crisis or another, but I\'m determined to protect my piece."',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/grn/cards/tenthdistrictguard.jpg'
      },
      {
        name: 'Venerated Loxodon',
        set: 'Guilds of Ravnica',
        cost: '5',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Elephant Cleric',
        rarity: 'Rare',
        effects: 'Convoke (Your creatures can help cast this spell.  Each creature you tap while casting this spell pays for {1} or one mana of that creature\'s color.)\nWhen Venerated Loxodon enters the battlefield, put a +1/+1 counter on each creature that convoked it.',
        power: '4',
        toughness: '4',
        art: 'http://mythicspoiler.com/grn/cards/veneratedloxodon.jpg'
      },
      {
        name: 'Capture Sphere',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'Blue',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Common',
        effects: 'Flash\nEnchant creature\nWhen Capture Sphere enters the battlefield, tap enchanted creature.\nEnchanted creature doesn\'t untap during its controller\'s untap step.',
        art: 'http://mythicspoiler.com/grn/cards/capturesphere.jpg'
      },
      {
        name: 'Chemister\'s Insight',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'Draw two cards.\nJump-start (You may cast this card from your graveyard by discarding a card in addition to paying its other costs.  Then exile this card.)',
        flavor: '"My specialty is theoretical universal limits and ways to circumvent them."',
        art: 'http://mythicspoiler.com/grn/cards/chemistersinsight.jpg'
      },
      {
        name: 'Citywatch Sphinx',
        set: 'Guilds of Ravnica',
        cost: '6',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Sphinx',
        rarity: 'Uncommon',
        effects: 'Flying\nWhen Citywatch Sphinx dies, surveil 2. (Look at the top two cards of your library, then put any number of them into your graveyard and the rest on top of your library in any order.)',
        flavor: 'All those who trade in questions must answer to the Dimir.',
        power: '5',
        toughness: '4',
        art: 'http://mythicspoiler.com/grn/cards/citywatchsphinx.jpg'
      },
      {
        name: 'Dazzling Lights',
        set: 'Guilds of Ravnica',
        cost: '1',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Target creature gets -3/-0 until end of turn.\nSurveil 2. (Look at the top two cards of your library, then put any number of them into your graveyard and the rest on top of your library in any order.)',
        art: 'http://mythicspoiler.com/grn/cards/dazzlinglights.jpg'
      },
      {
        name: 'Devious Cover-Up',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Counter target spell.  If a spell is countered this way, exile it instead of putting it into its owner\'s graveyard.  You may shuffle up to four target cards from your graveyard into your library.',
        flavor: 'First, dispose of the evidence.  Then dispose of your knowledge of its disposal.',
        art: 'http://mythicspoiler.com/grn/cards/deviouscoverup.jpg'
      },
      {
        name: 'Dimir Informant',
        set: 'Guilds of Ravnica',
        cost: '3',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Human Rogue',
        rarity: 'Common',
        effects: 'When Dimir Informant enters the battlefield, surveil 2. (Look at the top two cards of your library, then put any number of them into your graveyard and the rest on top of your library in any order.)',
        flavor: 'The letters arrive, all sealed and read.',
        power: '1',
        toughness: '4',
        art: 'http://mythicspoiler.com/grn/cards/dimirinformant.jpg'
      },
      {
        name: 'Disdainful Stroke',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Counter target spell with converted mana cost 4 or greater.',
        flavor: '"Laws apply only to those who lack the vision to see past them."',
        art: 'http://mythicspoiler.com/grn/cards/disdainfulstroke.jpg'
      },
      {
        name: 'Dream Eater',
        set: 'Guilds of Ravnica',
        cost: '6',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Nightmare Sphinx',
        rarity: 'Mythic',
        effects: 'Flash\nFlying\nWhen Dream Eater enters the battlefield, surveil 4.  When you do, you may return target nonland permanent an opponent controls to its owner\'s hand. (To surveil 4, look at the top four cards of your library, then put any number of them into your graveyard and the rest on top of your library in any order.)',
        power: '4',
        toughness: '3',
        art: 'http://mythicspoiler.com/grn/cards/dreameater.jpg'
      },
      {
        name: 'Drowned Secrets',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'Blue',
        supertype: 'Enchantment',
        rarity: 'Rare',
        effects: 'Whenever you cast a blue spell, target player puts the top two cards of their library into their graveyard.',
        flavor: 'Beneath Ravnica\'s streets runs a layer of tunnels, then caverns and waterways, then terrors and nightmares.',
        art: 'http://mythicspoiler.com/grn/cards/drownedsecrets.jpg'
      },
      {
        name: 'Enhanced Surveillance',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'Blue',
        supertype: 'Enchantment',
        rarity: 'Uncommon',
        effects: 'You may look at an additional two cards each time you surveil.\nExile Enhanced Surveillance: Shuffle your graveyard into your library.',
        flavor: '"Who are the agents of the Dimir?  No one and everyone."\n--Lazav',
        art: 'http://mythicspoiler.com/grn/cards/enhancedsurveillance.jpg'
      },
      {
        name: 'Guild Summit',
        set: 'Guilds of Ravnica',
        cost: '3',
        color: 'Blue',
        supertype: 'Enchantment',
        rarity: 'Uncommon',
        effects: 'When Guild Summit enters the battlefield, you may tap any number of untapped Gates you control.  Draw a card for each Gate tapped this way.\nWhenever a Gate enters the battlefield under your control, draw a card.',
        flavor: 'In a climate of suspicion, Isperia gathered the guilds to propose a radical idea: cooperation.',
        art: 'http://mythicspoiler.com/grn/cards/guildsummit.jpg'
      },
      {
        name: 'Leapfrog',
        set: 'Guilds of Ravnica',
        cost: '3',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Frog',
        rarity: 'Common',
        effects: 'Leapfrog has flying as long as you\'ve cast an instant or sorcery spell this turn.',
        flavor: '"Most compete for insects at street level.  Some dwell near Izzet laboratories and ride the thermal updrafts."\n--Yolov, Simic bioengineer',
        power: '3',
        toughness: '1',
        art: 'http://mythicspoiler.com/grn/cards/leapfrog.jpg'
      },
      {
        name: 'Maximize Altitude',
        set: 'Guilds of Ravnica',
        cost: '1',
        color: 'Blue',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'Target creature gets +1/+1 and gains flying until end of turn.\nJump-start (You may cast this card from your graveyard by discarding a card in addition to paying its other costs.  Then exile this card.)',
        art: 'http://mythicspoiler.com/grn/cards/maximizealtitude.jpg'
      },
      {
        name: 'Mission Briefing',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Rare',
        effects: 'Surveil 2, then choose an instant or sorcery card in your graveyard.  You may cast that card this turn.  If that card would be put into your graveyard this turn, exile it instead. (To surveil 2, look at the top two cards of your library, then put any number of them into your graveyard and the rest on top of your library in any order.)',
        art: 'http://mythicspoiler.com/grn/cards/missionbriefing.jpg'
      },
      {
        name: 'Murmuring Mystic',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Human Wizard',
        rarity: 'Uncommon',
        effects: 'Whenever you cast an instant or sorcery spell, create a 1/1 blue Bird Illusion creature token with flying.',
        flavor: 'Rumors float through the city like crows, alighting on citizens seemingly at random.',
        power: '1',
        toughness: '5',
        art: 'http://mythicspoiler.com/grn/cards/murmuringmystic.jpg'
      },
      {
        name: 'Muse Drake',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Drake',
        rarity: 'Common',
        effects: 'Flying\nWhen Muse Drake enters the battlefield, draw a card.',
        flavor: 'A composer wrote a symphony based on the drakes screeching outside her window.  Reviews were mixed -- except among the drakes.',
        power: '1',
        toughness: '3',
        art: 'http://mythicspoiler.com/grn/cards/musedrake.jpg'
      },
      {
        name: 'Narcomoeba',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Illusion',
        rarity: 'Rare',
        effects: 'Flying\nWhen Narcomoeba is put into your graveyard from your library, you may put it onto the battlefield.',
        flavor: '"What bait do you cast to catch a dream?"\n--Ravnican riddle',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/grn/cards/narcomoeba.jpg'
      },
      {
        name: 'Nightveil Sprite',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Faerie Rogue',
        rarity: 'Uncommon',
        effects: 'Flying\nWhenever Nightveil Sprite attacks, surveil 1. (Look at the top card of your library.  You may put that card into your graveyard.)',
        flavor: '"We\'re on the fortieth floor with one window, no balcony.  No one could possibly get in."\nMinosz, Orzhov chief of security',
        power: '1',
        toughness: '2',
        art: 'http://mythicspoiler.com/grn/cards/nightveilsprite.jpg'
      },
      {
        name: 'Omnispell Adept',
        set: 'Guilds of Ravnica',
        cost: '5',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Human Wizard',
        rarity: 'Rare',
        effects: '{2U}, {T}: You may cast an instant or sorcery card from your hand without paying its mana cost.',
        flavor: 'She memorized every arcane text in the Ismeri Library by the time she was sixteen.  Now she quizzes sphinxes in her spare time.',
        power: '3',
        toughness: '4',
        art: 'http://mythicspoiler.com/grn/cards/omnispelladept.jpg'
      },
      {
        name: 'Passwall Adept',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Human Wizard',
        rarity: 'Common',
        effects: '{2U}: Target creature can\'t be blocked this turn.',
        flavor: '"My doors are called trespassing, my signatures, forgeries.  They don\'t respect my talents, and I don\'t respect their labels."',
        power: '1',
        toughness: '3',
        art: 'http://mythicspoiler.com/grn/cards/passwalladept.jpg'
      },
      {
        name: '',
        set: 'Guilds of Ravnica',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Guilds of Ravnica',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Guilds of Ravnica',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Guilds of Ravnica',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Guilds of Ravnica',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Guilds of Ravnica',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Guilds of Ravnica',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Guilds of Ravnica',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Guilds of Ravnica',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Guilds of Ravnica',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Guilds of Ravnica',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
    ]);
  });
};