exports.seed = (knex, Promise) => {
  // Deletes ALL existing entries
  return knex('Card_List').del()
  .then(() => {
    // Inserts seed entries
    return knex('Card_List').insert([
      {
        name: 'Blade Instructor',
        set: 'Guilds of Ravnica',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Common',
        effects: 'Mentor (Whenever this creature attacks, put a +1/+1 counter on target attacking creature with lesser power.)',
        flavor: '"Watch carefully.  The gap between death and victory is thinner than your blade."',
        power: '3',
        toughness: '1',
        art: 'http://mythicspoiler.com/grn/cards/bladeinstructor.jpg'
      },
      {
        name: 'Bounty Agent',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Rare',
        effects: 'Vigilance\n{T}, Sacrifice Bounty Agent: Destroy target legendary permanent that\'s an artifact, creature, or enchantment.',
        flavor: '"Lately I\'ve seen the biggest bounties of my career -- and for the biggest names."',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/grn/cards/bountyagent.jpg'
      },
      {
        name: 'Candlelight Vigil',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'White',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Common',
        effects: 'Enchant creature\nEnchanted creature gets +3/+2 and has vigilance.',
        flavor: 'Selesnya guildmages do not sleep so the rest of the Conclave can.',
        art: 'http://mythicspoiler.com/grn/cards/candlelightvigil.jpg'
      },
      {
        name: 'Citywide Bust',
        set: 'Guilds of Ravnica',
        cost: '3',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Rare',
        effects: 'Destroy all creatures with toughness 4 or greater.',
        flavor: '"Oh, you fellas are going to love the lockup.  Excellent gruel.  Very low ceilings."\n--Libuse, Boros sergeant',
        art: 'http://mythicspoiler.com/grn/cards/citywidebust.jpg'
      },
      {
        name: 'Collar the Culprit',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Destroy target creature with toughness 4 or greater.',
        flavor: '"Reports of Gruul rioters in four districts.  Start with the big ones and work your way up."\n--Libuse, Boros sergeant',
        art: 'http://mythicspoiler.com/grn/cards/collartheculprit.jpg'
      },
      {
        name: 'Conclave Tribunal',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'White',
        supertype: 'Enchantment',
        rarity: 'Uncommon',
        effects: 'Convoke (Your creatures can help cast this spell.  Each creature you tap while casting this spell pays for {1} or one mana of that creature\'s color.)\nWhen Conclave Tribunal enters the battlefield, exile target nonland permanent an opponent controls until Conclave Tribunal leaves the battlefield.',
        art: 'http://mythicspoiler.com/grn/cards/conclavetribunal.jpg'
      },
      {
        name: 'Crush Contraband',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'Choose one or both --\n\tExile target artifact.\n\tExile target enchantment.',
        flavor: 'The Izzet mage knew she would neither get her thermoinverter back nor have the satisfaction of exploding it herself.',
        art: 'http://mythicspoiler.com/grn/cards/crushcontraband.jpg'
      },
      {
        name: 'Dawn of Hope',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'White',
        supertype: 'Enchantment',
        rarity: 'Rare',
        effects: 'Whenever you gain life, you may pay {2}.  If you do, draw a card.\n{3W}: Create a 1/1 white Soldier creature token with lifelink.',
        flavor: '"To wage war, secure peace within yourself."\n--Emmara',
        art: 'http://mythicspoiler.com/grn/cards/dawnofhope.jpg'
      },
      {
        name: 'Demotion',
        set: 'Guilds of Ravnica',
        cost: '1',
        color: 'White',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Uncommon',
        effects: 'Enchant creature\nEnchanted creature can\'t block, and its activated abilities can\'t be activated.',
        flavor: 'There\'s no greater honor than joining your chosen guild, and no greater shame than failing it.',
        art: 'http://mythicspoiler.com/grn/cards/demotion.jpg'
      },
      {
        name: 'Divine Visitation',
        set: 'Guilds of Ravnica',
        cost: '5',
        color: 'White',
        supertype: 'Enchantment',
        rarity: 'Mythic',
        effects: 'If one or more creature tokens would be created under your control, that many 4/4 white Angel creature tokens with flying and vigilance are created instead.',
        flavor: 'The angels appreciated the offer but politely declined to eat any birdseed.',
        art: 'http://mythicspoiler.com/grn/cards/divinevisitation.jpg'
      },
      {
        name: 'Flight of Equenauts',
        set: 'Guilds of Ravnica',
        cost: '8',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Knight',
        rarity: 'Uncommon',
        effects: 'Convoke (Your creatures can help cast this spell.  Each creature you tap while casting this spell pays for {1} or one mana of that creature\'s color.)\nFlying',
        flavor: '"Yes, there\'s competition between our equenauts and the Boros skyjeks.  At least they think it\'s a competition."',
        power: '4',
        toughness: '5',
        art: 'http://mythicspoiler.com/grn/cards/flightofequenauts.jpg'
      },
      {
        name: 'Gird for Battle',
        set: 'Guilds of Ravnica',
        cost: '1',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Uncommon',
        effects: 'Put a +1/+1 counter on each of up to two target creatures.',
        flavor: '"You won\'t need the sword drills, your shields, or my blessing.  You\'ll fight for Sunhome with the truth in your heart."\n--Aurelia',
        art: 'http://mythicspoiler.com/grn/cards/girdforbattle.jpg'
      },
      {
        name: 'Haazda Marshal',
        set: 'Guilds of Ravnica',
        cost: '1',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Uncommon',
        effects: 'Whenever Haazda Marshal and at least two other creatures attack, create a 1/1 white Soldier creature token with lifelink.',
        flavor: 'Ravnica\'s convoluted power structure often boils down to who can muster the most swords on a given block.',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/grn/cards/haazdamarshal.jpg'
      },
      {
        name: 'Healer\'s Hawk',
        set: 'Guilds of Ravnica',
        cost: '1',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Bird',
        rarity: 'Common',
        effects: 'Flying, lifelink',
        flavor: 'The wounded see the glow of its vials long before they see its wings diving out of the clouds.',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/grn/cards/healershawk.jpg'
      },
      {
        name: 'Hunted Witness',
        set: 'Guilds of Ravnica',
        cost: '1',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human',
        rarity: 'Common',
        effects: 'When Hunted Witness dies, create a 1/1 white Soldier creature token with lifelink.',
        flavor: 'He ferried weapons, spells, exotic animals -- but his most dangerous cargo was the truth.',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/grn/cards/huntedwitness.jpg'
      },
      {
        name: 'Inspiring Unicorn',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Unicorn',
        rarity: 'Uncommon',
        effects: 'Whenever Inspiring Unicorn attacks, creatures you control get +1/+1 until end of turn.',
        flavor: 'There are two lives: the life you live before you see a unicorn, and the life you live after.',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/grn/cards/inspiringunicorn.jpg'
      },
      {
        name: 'Intrusive Packbeast',
        set: 'Guilds of Ravnica',
        cost: '5',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Beast',
        rarity: 'Common',
        effects: 'Vigilance\nWhen Intrusive Packbeast enters the battlefield, tap up to two target creatures your opponents control.',
        flavor: 'Good at carrying things.  Really good at knocking them down.',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/grn/cards/intrusivepackbeast.jpg'
      },
      {
        name: 'Ledev Guardian',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Knight',
        rarity: 'Common',
        effects: 'Convoke (Your creatures can help cast this spell.  Each creature you tap while casting this spell pays for  {1} or one mana of that creature\'s color.)',
        flavor: '"I\'ve raised her since she was a pup, and she\'s raised me since I was a recruit."',
        power: '2',
        toughness: '4',
        art: 'http://mythicspoiler.com/grn/cards/ledevguardian.jpg'
      },
      {
        name: 'Light of the Legion',
        set: 'Guilds of Ravnica',
        cost: '6',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Angel',
        rarity: 'Rare',
        effects: 'Flying\nMentor (Whenever this creature attacks, put a +1/+1 counter on target attacking creature with lesser power.)\nWhen Light of the Legion dies, put a +1/+1 counter on each white creature you control.',
        power: '5',
        toughness: '5',
        art: 'http://mythicspoiler.com/grn/cards/lightofthelegion.jpg'
      },
      {
        name: 'Loxodon Restorer',
        set: 'Guilds of Ravnica',
        cost: '6',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Elephant Cleric',
        rarity: 'Common',
        effects: 'Convoke (Your creatures can help cast this spell.  Each creature you tap while casting this spell pays for {1} or one mana of that creature\'s color.)\nWhen Loxodon Restorer enters the battlefield, you gain 4 life.',
        power: '3',
        toughness: '4',
        art: 'http://mythicspoiler.com/grn/cards/loxodonrestorer.jpg'
      },
      {
        name: 'Luminous Bonds',
        set: 'Guilds of Ravnica',
        cost: '3',
        color: 'White',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Common',
        effects: 'Enchant creature\nEnchanted creature can\'t attack or block.',
        flavor: '"Article 5.8.2. Ensure proper restraint of any and all arms, legs, claws, jaws, tails, tentacles, and tendrils as appropriate."\n--Azorius Arrester Procedure, appendix B',
        art: 'http://mythicspoiler.com/grn/cards/luminousbonds.jpg'
      },
      {
        name: 'Parhelion Patrol',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Knight',
        rarity: 'Common',
        effects: 'Flying, vigilance\nMentor (Whenever this creature attacks, put a +1/+1 counter on target attacking creature with lesser power.)',
        flavor: '"Too many have disappeared in these dark days.  I am the light that will lead them home."',
        power: '2',
        toughness: '3',
        art: 'http://mythicspoiler.com/grn/cards/parhelionpatrol.jpg'
      },
      {
        name: 'Righteous Blow',
        set: 'Guilds of Ravnica',
        cost: '1',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Righteous Blow deals 2 damage to target attacking or blocking creature.',
        flavor: '"The Golgari believe they should be given what they deserve.  On this we agree."\n--Tajic',
        art: 'http://mythicspoiler.com/grn/cards/righteousblow.jpg'
      },
      {
        name: 'Roc Charger',
        set: 'Guilds of Ravnica',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Bird',
        rarity: 'Uncommon',
        effects: 'Flying\nWhenever Roc Charger attacks, target attacking creature without flying gains flying until end of turn.',
        flavor: 'Rocs\' innate fearlessness makes them ideal mounts for emergency response.',
        power: '1',
        toughness: '3',
        art: 'http://mythicspoiler.com/grn/cards/roccharger.jpg'
      },
      {
        name: 'Skyline Scout',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Scout',
        rarity: 'Common',
        effects: 'Whenever Skyline Scout attacks, you may pay {1W}.  If you do, it gains flying until end of turn.',
        flavor: '"Sometimes an angel passes by and gives me a little nod, like, "You\'re a daring one!"  That always makes my day."',
        power: '2',
        toughness: '1',
        art: 'http://mythicspoiler.com/grn/cards/skylinescout.jpg'
      },
      {
        name: 'Sunhome Stalwart',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Uncommon',
        effects: 'First strike\nMentor (Whenever this creature attacks, put a +1/+1 counter on target attacking creature with lesser power.)',
        flavor: '"Before I let you wield one of these, let\'s see you dodge one!"',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/grn/cards/sunhomestalwart.jpg'
      },
      {
        name: 'Sworn Companions',
        set: 'Guilds of Ravnica',
        cost: '3',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'Create two 1/1 white Soldier creature tokens with lifelink.',
        flavor: '"The trouble with youths these days is that, in outright defiance of their elders, they refuse to be bought."\n--Karlov of the Ghost Council',
        art: 'http://mythicspoiler.com/grn/cards/sworncompanions.jpg'
      },
      {
        name: 'Take Heart',
        set: 'Guilds of Ravnica',
        cost: '1',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Target creature gets +1/+1 until end of turn.  You gain 1 life for each attacking creature you control.',
        flavor: 'In the quiet before a battle, Boros soldiers whisper prayers that steady their nerves and focus their minds.',
        art: 'http://mythicspoiler.com/grn/cards/takeheart.jpg'
      },
      {
        name: 'Tenth District Guard',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Common',
        effects: 'When Tenth District Guard enters the battlefield, target creature gets +0/+1 until end of turn.',
        flavor: '"The Tenth has always been my home.  This city is constantly embroiled in one crisis or another, but I\'m determined to protect my piece."',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/grn/cards/tenthdistrictguard.jpg'
      },
      {
        name: 'Venerated Loxodon',
        set: 'Guilds of Ravnica',
        cost: '5',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Elephant Cleric',
        rarity: 'Rare',
        effects: 'Convoke (Your creatures can help cast this spell.  Each creature you tap while casting this spell pays for {1} or one mana of that creature\'s color.)\nWhen Venerated Loxodon enters the battlefield, put a +1/+1 counter on each creature that convoked it.',
        power: '4',
        toughness: '4',
        art: 'http://mythicspoiler.com/grn/cards/veneratedloxodon.jpg'
      },
      {
        name: 'Capture Sphere',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'Blue',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Common',
        effects: 'Flash\nEnchant creature\nWhen Capture Sphere enters the battlefield, tap enchanted creature.\nEnchanted creature doesn\'t untap during its controller\'s untap step.',
        art: 'http://mythicspoiler.com/grn/cards/capturesphere.jpg'
      },
      {
        name: 'Chemister\'s Insight',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'Draw two cards.\nJump-start (You may cast this card from your graveyard by discarding a card in addition to paying its other costs.  Then exile this card.)',
        flavor: '"My specialty is theoretical universal limits and ways to circumvent them."',
        art: 'http://mythicspoiler.com/grn/cards/chemistersinsight.jpg'
      },
      {
        name: 'Citywatch Sphinx',
        set: 'Guilds of Ravnica',
        cost: '6',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Sphinx',
        rarity: 'Uncommon',
        effects: 'Flying\nWhen Citywatch Sphinx dies, surveil 2. (Look at the top two cards of your library, then put any number of them into your graveyard and the rest on top of your library in any order.)',
        flavor: 'All those who trade in questions must answer to the Dimir.',
        power: '5',
        toughness: '4',
        art: 'http://mythicspoiler.com/grn/cards/citywatchsphinx.jpg'
      },
      {
        name: 'Dazzling Lights',
        set: 'Guilds of Ravnica',
        cost: '1',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Target creature gets -3/-0 until end of turn.\nSurveil 2. (Look at the top two cards of your library, then put any number of them into your graveyard and the rest on top of your library in any order.)',
        art: 'http://mythicspoiler.com/grn/cards/dazzlinglights.jpg'
      },
      {
        name: 'Devious Cover-Up',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Counter target spell.  If a spell is countered this way, exile it instead of putting it into its owner\'s graveyard.  You may shuffle up to four target cards from your graveyard into your library.',
        flavor: 'First, dispose of the evidence.  Then dispose of your knowledge of its disposal.',
        art: 'http://mythicspoiler.com/grn/cards/deviouscoverup.jpg'
      },
      {
        name: 'Dimir Informant',
        set: 'Guilds of Ravnica',
        cost: '3',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Human Rogue',
        rarity: 'Common',
        effects: 'When Dimir Informant enters the battlefield, surveil 2. (Look at the top two cards of your library, then put any number of them into your graveyard and the rest on top of your library in any order.)',
        flavor: 'The letters arrive, all sealed and read.',
        power: '1',
        toughness: '4',
        art: 'http://mythicspoiler.com/grn/cards/dimirinformant.jpg'
      },
      {
        name: 'Disdainful Stroke',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Counter target spell with converted mana cost 4 or greater.',
        flavor: '"Laws apply only to those who lack the vision to see past them."',
        art: 'http://mythicspoiler.com/grn/cards/disdainfulstroke.jpg'
      },
      {
        name: 'Dream Eater',
        set: 'Guilds of Ravnica',
        cost: '6',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Nightmare Sphinx',
        rarity: 'Mythic',
        effects: 'Flash\nFlying\nWhen Dream Eater enters the battlefield, surveil 4.  When you do, you may return target nonland permanent an opponent controls to its owner\'s hand. (To surveil 4, look at the top four cards of your library, then put any number of them into your graveyard and the rest on top of your library in any order.)',
        power: '4',
        toughness: '3',
        art: 'http://mythicspoiler.com/grn/cards/dreameater.jpg'
      },
      {
        name: 'Drowned Secrets',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'Blue',
        supertype: 'Enchantment',
        rarity: 'Rare',
        effects: 'Whenever you cast a blue spell, target player puts the top two cards of their library into their graveyard.',
        flavor: 'Beneath Ravnica\'s streets runs a layer of tunnels, then caverns and waterways, then terrors and nightmares.',
        art: 'http://mythicspoiler.com/grn/cards/drownedsecrets.jpg'
      },
      {
        name: 'Enhanced Surveillance',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'Blue',
        supertype: 'Enchantment',
        rarity: 'Uncommon',
        effects: 'You may look at an additional two cards each time you surveil.\nExile Enhanced Surveillance: Shuffle your graveyard into your library.',
        flavor: '"Who are the agents of the Dimir?  No one and everyone."\n--Lazav',
        art: 'http://mythicspoiler.com/grn/cards/enhancedsurveillance.jpg'
      },
      {
        name: 'Guild Summit',
        set: 'Guilds of Ravnica',
        cost: '3',
        color: 'Blue',
        supertype: 'Enchantment',
        rarity: 'Uncommon',
        effects: 'When Guild Summit enters the battlefield, you may tap any number of untapped Gates you control.  Draw a card for each Gate tapped this way.\nWhenever a Gate enters the battlefield under your control, draw a card.',
        flavor: 'In a climate of suspicion, Isperia gathered the guilds to propose a radical idea: cooperation.',
        art: 'http://mythicspoiler.com/grn/cards/guildsummit.jpg'
      },
      {
        name: 'Leapfrog',
        set: 'Guilds of Ravnica',
        cost: '3',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Frog',
        rarity: 'Common',
        effects: 'Leapfrog has flying as long as you\'ve cast an instant or sorcery spell this turn.',
        flavor: '"Most compete for insects at street level.  Some dwell near Izzet laboratories and ride the thermal updrafts."\n--Yolov, Simic bioengineer',
        power: '3',
        toughness: '1',
        art: 'http://mythicspoiler.com/grn/cards/leapfrog.jpg'
      },
      {
        name: 'Maximize Altitude',
        set: 'Guilds of Ravnica',
        cost: '1',
        color: 'Blue',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'Target creature gets +1/+1 and gains flying until end of turn.\nJump-start (You may cast this card from your graveyard by discarding a card in addition to paying its other costs.  Then exile this card.)',
        art: 'http://mythicspoiler.com/grn/cards/maximizealtitude.jpg'
      },
      {
        name: 'Mission Briefing',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Rare',
        effects: 'Surveil 2, then choose an instant or sorcery card in your graveyard.  You may cast that card this turn.  If that card would be put into your graveyard this turn, exile it instead. (To surveil 2, look at the top two cards of your library, then put any number of them into your graveyard and the rest on top of your library in any order.)',
        art: 'http://mythicspoiler.com/grn/cards/missionbriefing.jpg'
      },
      {
        name: 'Murmuring Mystic',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Human Wizard',
        rarity: 'Uncommon',
        effects: 'Whenever you cast an instant or sorcery spell, create a 1/1 blue Bird Illusion creature token with flying.',
        flavor: 'Rumors float through the city like crows, alighting on citizens seemingly at random.',
        power: '1',
        toughness: '5',
        art: 'http://mythicspoiler.com/grn/cards/murmuringmystic.jpg'
      },
      {
        name: 'Muse Drake',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Drake',
        rarity: 'Common',
        effects: 'Flying\nWhen Muse Drake enters the battlefield, draw a card.',
        flavor: 'A composer wrote a symphony based on the drakes screeching outside her window.  Reviews were mixed -- except among the drakes.',
        power: '1',
        toughness: '3',
        art: 'http://mythicspoiler.com/grn/cards/musedrake.jpg'
      },
      {
        name: 'Narcomoeba',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Illusion',
        rarity: 'Rare',
        effects: 'Flying\nWhen Narcomoeba is put into your graveyard from your library, you may put it onto the battlefield.',
        flavor: '"What bait do you cast to catch a dream?"\n--Ravnican riddle',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/grn/cards/narcomoeba.jpg'
      },
      {
        name: 'Nightveil Sprite',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Faerie Rogue',
        rarity: 'Uncommon',
        effects: 'Flying\nWhenever Nightveil Sprite attacks, surveil 1. (Look at the top card of your library.  You may put that card into your graveyard.)',
        flavor: '"We\'re on the fortieth floor with one window, no balcony.  No one could possibly get in."\nMinosz, Orzhov chief of security',
        power: '1',
        toughness: '2',
        art: 'http://mythicspoiler.com/grn/cards/nightveilsprite.jpg'
      },
      {
        name: 'Omnispell Adept',
        set: 'Guilds of Ravnica',
        cost: '5',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Human Wizard',
        rarity: 'Rare',
        effects: '{2U}, {T}: You may cast an instant or sorcery card from your hand without paying its mana cost.',
        flavor: 'She memorized every arcane text in the Ismeri Library by the time she was sixteen.  Now she quizzes sphinxes in her spare time.',
        power: '3',
        toughness: '4',
        art: 'http://mythicspoiler.com/grn/cards/omnispelladept.jpg'
      },
      {
        name: 'Passwall Adept',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Human Wizard',
        rarity: 'Common',
        effects: '{2U}: Target creature can\'t be blocked this turn.',
        flavor: '"My doors are called trespassing, my signatures, forgeries.  They don\'t respect my talents, and I don\'t respect their labels."',
        power: '1',
        toughness: '3',
        art: 'http://mythicspoiler.com/grn/cards/passwalladept.jpg'
      },
      {
        name: 'Quasiduplicate',
        set: 'Guilds of Ravnica',
        cost: '3',
        color: 'Blue',
        supertype: 'Sorcery',
        rarity: 'Rare',
        effects: 'Create a token that\'s a copy of target creature you control.\nJump-start (You may cast this spell from your graveyard by discarding a card in addition to paying its other costs.  Then exile this card.)',
        flavor: '"My greatest creation--me!"',
        art: 'http://mythicspoiler.com/grn/cards/quasiduplicate.jpg'
      },
      {
        name: 'Radical Idea',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Draw a card.\nJump-start (You may cast this card from your graveyard by discarding a card in addition to paying its other costs.  Then exile this card.)',
        flavor: 'Genius is finding the edge of what\'s possible, then jumping over it.',
        art: 'http://mythicspoiler.com/grn/cards/radicalidea.jpg'
      },
      {
        name: 'Selective Snare',
        set: 'Guilds of Ravnica',
        cost: '2+',
        color: 'Blue',
        supertype: 'Sorcery',
        rarity: 'Uncommon',
        effects: 'Return X target creatures of the creature type of your choice to their owner\'s hand.',
        flavor: '"How thoughtful of the Legion to train its soldiers to fit our spell\'s specifications."\n--Nefara, Dimir agent',
        art: 'http://mythicspoiler.com/grn/cards/selectivesnare.jpg'
      },
      {
        name: 'Sinister Sabotage',
        set: 'Guilds of Ravnica',
        cost: '3',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'Counter target spell.\nSurveil 1. (Look at the top card of your library.  You may put that card into your graveyard.)',
        flavor: '"We have intel that some guilds have fallen under an invader\'s influence.  Until we\'re sure, no venture succeeds."\n--Lazav',
        art: 'http://mythicspoiler.com/grn/cards/sinistersabotage.jpg'
      },
      {
        name: 'Thoughtbound Phantasm',
        set: 'Guilds of Ravnica',
        cost: '1',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Spirit',
        rarity: 'Uncommon',
        effects: 'Defender\nWhenever you surveil, put a +1/+1 counter on Thoughtbound Phantasm.\nAs long as Thoughtbound Phantasm has three or more +1/+1 counters on it, it may attack as though it didn\'t have defender.',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/grn/cards/thoughtboundphantasm.jpg'
      },
      {
        name: 'Unexplained Disappearance',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Return target creature to its owner\'s hand.\nSurveil 1. (Look at the top card of your library.  You may put that card into your graveyard.)',
        flavor: 'The first thing the mist chills is the mind.  Victims never cry out or even murmur in surprise.',
        art: 'http://mythicspoiler.com/grn/cards/unexplaineddisappearance.jpg'
      },
      {
        name: 'Vedalken Mesmerist',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Vedalken Wizard',
        rarity: 'Common',
        effects: 'Whenever Veldaken Mesmerist attacks, target creature an opponent controls gets -2/-0 until end of turn.',
        flavor: '"There\'s no need to sound the alarm.  You are minding your post admirably.  I am authorized.  All is well."',
        power: '2',
        toughness: '1',
        art: 'http://mythicspoiler.com/grn/cards/vedalkenmesmerist.jpg'
      },
      {
        name: 'Wall of Mist',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Wall',
        rarity: 'Common',
        effects: 'Defender',
        flavor: 'Fog haunts the streets, rendering the familiar as otherworldly, changing neighbors into shadows, and muffling cries for help.',
        power: '0',
        toughness: '5',
        art: 'http://mythicspoiler.com/grn/cards/wallofmist.jpg'
      },
      {
        name: 'Watcher in the Mist',
        set: 'Guilds of Ravnica',
        cost: '5',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Spirit',
        rarity: 'Common',
        effects: 'Flying\nWhen Watcher in the Mist enters the battlefield, surveil 2. (Look at the top two cards of your library, then put any number of them into your graveyard and the rest on top of your library in any order.',
        power: '3',
        toughness: '4',
        art: 'http://mythicspoiler.com/grn/cards/watcherinthemist.jpg'
      },
      {
        name: 'Wishcoin Crab',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Crab',
        rarity: 'Common',
        flavor: '"What wishes do they grant?  Mostly pinching-related ones."\n--Omik, superintendent of waterworks',
        power: '2',
        toughness: '5',
        art: 'http://mythicspoiler.com/grn/cards/wishcoincrab.jpg'
      },
      {
        name: 'Barrier of Bones',
        set: 'Guilds of Ravnica',
        cost: '1',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Wall',
        rarity: 'Common',
        effects: 'Defender\nWhen Barrier of Bones enters the battlefield, surveil 1. (Look at the top card of your library.  You may put that card into your graveyard.)',
        flavor: 'The Dimir rarely make statements, but when they do, the message is clear.',
        power: '0',
        toughness: '3',
        art: 'http://mythicspoiler.com/grn/cards/barrierofbones.jpg'
      },
      {
        name: 'Bartizan Bats',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Bat',
        rarity: 'Common',
        effects: 'Flying',
        flavor: '"Bats are welcome to eat thousands of my pets.  I have multitudes more that will ultimately eat the bats."\n--Izoni',
        power: '3',
        toughness: '1',
        art: 'http://mythicspoiler.com/grn/cards/bartizanbats.jpg'
      },
      {
        name: 'Blood Operative',
        set: 'Guilds of Ravnica',
        cost: '3',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Vampire Assassin',
        rarity: 'Rare',
        effects: 'Lifelink\nWhen Blood Operative enters the battlefield, exile target card from a graveyard.\nWhenever you surveil, if Blood Operative is in your graveyard, you may pay 3 life.  If you do, return Blood Operative to your hand.',
        power: '3',
        toughness: '1',
        art: 'http://mythicspoiler.com/grn/cards/bloodoperative.jpg'
      },
      {
        name: 'Burglar Rat',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Rat',
        rarity: 'Common',
        effects: 'When Burglar Rat enters the battlefield, each opponent discards a card.',
        flavor: '"Even rats hoard their treasures.  Are your precious things so different?"\n--Izoni',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/grn/cards/burglarrat.jpg'
      },
      {
        name: 'Child of Night',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Vampire',
        rarity: 'Common',
        effects: 'Lifelink',
        flavor: 'No guilds--that is her rule.  The House vampires unnerve her.  The Combine would dissect her, the Legion burn her, the Conclave "cure" her.  The shadows are all the family she needs.',
        power: '2',
        toughness: '1',
        art: 'http://mythicspoiler.com/grn/cards/childofnight.jpg'
      },
      {
        name: 'Creeping Chill',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'Black',
        supertype: 'Sorcery',
        rarity: 'Uncommon',
        effects: 'Creeping Chill deals 3 damage to each opponent and you gain 3 life.\nWhen Creeping Chill is put into your graveyard from your library, you may exile it.  If you do, Creeping Chill deals 3 damage to each opponent and you gain 3 life.',
        art: 'http://mythicspoiler.com/grn/cards/creepingchill.jpg'
      },
      {
        name: 'Dead Weight',
        set: 'Guilds of Ravnica',
        cost: '1',
        color: 'Black',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Common',
        effects: 'Enchant creature\nEnchanted creature gets -2/-2.',
        flavor: 'All things considered, his first day on patrol could have gone better.',
        art: 'http://mythicspoiler.com/grn/cards/deadweight.jpg'
      },
      {
        name: 'Deadly Visit',
        set: 'Guilds of Ravnica',
        cost: '5',
        color: 'Black',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'Destroy target creature.\nSurveil 2. (Look at the top two cards of your library, then put any number of them into your graveyard and the rest on top of your library in any order.)',
        art: 'http://mythicspoiler.com/grn/cards/deadlyvisit.jpg'
      },
      {
        name: 'Doom Whisperer',
        set: 'Guilds of Ravnica',
        cost: '5',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Nightmare Demon',
        rarity: 'Mythic',
        effects: 'Flying, trample\nPay 2 life: Surveil 2. (Look at the top two cards of your library, then put any number of them into your graveyard and the rest on top of your library in any order.)',
        flavor: 'The sound of every twisted secret tempts you to hear another.',
        power: '6',
        toughness: '6',
        art: 'http://mythicspoiler.com/grn/cards/doomwhisperer.jpg'
      },
      {
        name: 'Douser of Lights',
        set: 'Guilds of Ravnica',
        cost: '5',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Horror',
        rarity: 'Common',
        flavor: 'The party of Rakdos revelers cackled as the thing approached.  It hissed, and they jabbed their torches at it, giggling when it recoiled.  Then, one by one, the torches went out--and then the screaming began.',
        power: '4',
        toughness: '5',
        art: 'http://mythicspoiler.com/grn/cards/douseroflights.jpg'
      },
      {
        name: 'Gruesome Menagerie',
        set: 'Guilds of Ravnica',
        cost: '5',
        color: 'Black',
        supertype: 'Sorcery',
        rarity: 'Rare',
        effects: 'Choose a creature card with converted mana cost 1 in your graveyard, then do the same for creature cards with converted mana costs 2 and 3.  Return those cards to the battlefield.',
        flavor: '"Variety is also the spice of death."\n--Cevraya, Golgari shaman',
        art: 'http://mythicspoiler.com/grn/cards/gruesomemenagerie.jpg'
      },
      {
        name: 'Hired Poisoner',
        set: 'Guilds of Ravnica',
        cost: '1',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Human Assassin',
        rarity: 'Common',
        effects: 'Deathtouch',
        flavor: '"They don\'t even feel the cut.  I\'m ordering a drink in a nearby tavern  before anyone notices something\'s wrong."',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/grn/cards/hiredpoisoner.jpg'
      },
      {
        name: 'Kraul Swarm',
        set: 'Guilds of Ravnica',
        cost: '5',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Insect Warrior',
        rarity: 'Uncommon',
        effects: 'Flying\n{2B}, Discard a creature card: Return Kraul Swarm from your graveyard to your hand.',
        flavor: 'The hive has a long memory.  It knows how every member died, and to whom it owes the grudge.',
        power: '4',
        toughness: '1',
        art: 'http://mythicspoiler.com/grn/cards/kraulswarm.jpg'
      },
      {
        name: 'Lotleth Giant',
        set: 'Guilds of Ravnica',
        cost: '7',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Zombie Giant',
        rarity: 'Uncommon',
        effects: 'Undergrowth--When Lotleth Giant enters the battlefield, it deals 1 damage to target opponent for each creature card in your graveyard.',
        flavor: '"I prefer the big and looming to the small and skittering."\n--Cevraya, Golgari shaman',
        power: '6',
        toughness: '5',
        art: 'http://mythicspoiler.com/grn/cards/lotlethgiant.jpg'
      },
      {
        name: 'Mausoleum Secrets',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'Black',
        supertype: 'Instant',
        rarity: 'Rare',
        effects: 'Undergrowth--Search your library for a black card with converted mana cost less than or equal to the number of creature cards in your graveyard, reveal it, put it into your hand, then shuffle your library.',
        art: 'http://mythicspoiler.com/grn/cards/mausoleumsecrets.jpg'
      },
      {
        name: 'Mephitic Vapors',
        set: 'Guilds of Ravnica',
        cost: '3',
        color: 'Black',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'All creatures get -1/-1 until end of turn.\nSurveil 2. (Look at the top two cards of your graveyard, then put any number of them into your graveyard and the rest on top of your library in any order.)',
        flavor: 'Ravnica\'s safest strongholds are often neither.',
        art: 'http://mythicspoiler.com/grn/cards/mephiticvapors.jpg'
      },
      {
        name: 'Midnight Reaper',
        set: 'Guilds of Ravnica',
        cost: '3',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Zombie Knight',
        rarity: 'Rare',
        effects: 'Whenever a nontoken creature you control dies, Midnight Reaper deals 1 damage to you and you draw a card.',
        flavor: 'No one welcomes his visit, yet all must grant him tribute.',
        power: '3',
        toughness: '2',
        art: 'http://mythicspoiler.com/grn/cards/midnightreaper.jpg'
      },
      {
        name: 'Moodmark Painter',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Human Shaman',
        rarity: 'Common',
        effects: 'Undergrowth--When Moodmark Painter enters the battlefield, target creature gains menace and gets +X/+0, where X is the number of creature cards in your graveyard. (It can\'t be blocked except by two or more creatures.)',
        power: '2',
        toughness: '3',
        art: 'http://mythicspoiler.com/grn/cards/moodmarkpainter.jpg'
      },
      {
        name: 'Necrotic Wound',
        set: 'Guilds of Ravnica',
        cost: '1',
        color: 'Black',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'Undergrowth--Target creature gets -X/-X until end of turn, where X is the number of creature cards in your graveyard.  If that creature would die this turn, exile it instead.',
        flavor: 'The assassins of the Ochran distill toxins from the remains of their previous victims.',
        art: 'http://mythicspoiler.com/grn/cards/necroticwound.jpg'
      },
      {
        name: 'Never Happened',
        set: 'Guilds of Ravnica',
        cost: '3',
        color: 'Black',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'Target opponent reveals their hand.  You choose a nonland card from that player\'s graveyard or hand and exile it.',
        flavor: 'Dimir assassins have the precision to slay a single memory.',
        art: 'http://mythicspoiler.com/grn/cards/neverhappened.jpg'
      },
      {
        name: 'Pilfering Imp',
        set: 'Guilds of Ravnica',
        cost: '1',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Imp',
        rarity: 'Uncommon',
        effects: 'Flying\n{1B}, Sacrifice Pilfering Imp: Target opponent reveals their hand.  You choose a nonland card from it.  That player discards that card.  Activate this ability only any time you could cast a sorcery.',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/grn/cards/pilferingimp.jpg'
      },
      {
        name: 'Plaguecrafter',
        set: 'Guilds of Ravnica',
        cost: '3',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Human Shaman',
        rarity: 'Uncommon',
        effects: 'When Plaguecrafter enters the battlefield, each player sacrifices a creature or planeswalker.  Each player who can\'t discards a card.',
        flavor: '"My power is generosity, in a way.  I give my survivors an appreciation for their lives."',
        power: '3',
        toughness: '2',
        art: 'http://mythicspoiler.com/grn/cards/plaguecrafter.jpg'
      },
      {
        name: 'Price of Fame',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'Black',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'This spell costs {2} less to cast if it targets a legendary creature.\nDestroy target creature.\nSurveil 2. (Look at the top two cards of your library, then put any number of them into your graveyard and the rest on top of your library in any order.)',
        art: 'http://mythicspoiler.com/grn/cards/priceoffame.jpg'
      },
      {
        name: 'Ritual of Soot',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'Black',
        supertype: 'Sorcery',
        rarity: 'Rare',
        effects: 'Destroy all creatures with converted mana cost 3 or less.',
        flavor: 'Only the patrol\'s armor was found, so tainted with the acrid smell of sudden death that it could never be worn again.',
        art: 'http://mythicspoiler.com/grn/cards/ritualofsoot.jpg'
      },
      {
        name: 'Severed Strands',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'Black',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'As an additional cost to cast this spell, sacrifice a creature.\nYou gain life equal to the sacrificed creature\'s toughness.  Destroy target creature an opponent controls.',
        flavor: '"I\'ve seen Ravnica\'s fate.  Believe me, I\'m doing you a favor."',
        art: 'http://mythicspoiler.com/grn/cards/severedstrands.jpg'
      },
      {
        name: 'Spinal Centipede',
        set: 'Guilds of Ravnica',
        cost: '3',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Insect',
        rarity: 'Common',
        effects: 'When Spinal Centipede dies, put a +1/+1 counter on target creature you control.',
        flavor: 'The Golgari adorn themselves with the exoskeletons of iridescent insects.  It\'s only fair the insects do likewise.',
        power: '3',
        toughness: '2',
        art: 'http://mythicspoiler.com/grn/cards/spinalcentipede.jpg'
      },
      {
        name: 'Undercity Necrolisk',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Zombie Lizard',
        rarity: 'Uncommon',
        effects: '{1}, Sacrifice another creature: Put a +1/+1 counter on Undercity Necrolisk.  It gains menace until end of turn.  Activate this ability only any time you could cast a sorcery. (It can\'t be blocked except by two or more creatures.)',
        flavor: 'In its territory, living is an affront.',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/grn/cards/undercitynecrolisk.jpg'
      },
      {
        name: 'Veiled Shade',
        set: 'Guilds of Ravnica',
        cost: '3',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Shade',
        rarity: 'Common',
        effects: '{1B}: Veiled Shade gets +1/+1 until end of turn.',
        flavor: '"I sang songs of sorrow for my lost love.  Imagine my horror when, one night, they were answered."\n--Milana, Orzhov prelate',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/grn/cards/veiledshade.jpg'
      },
      {
        name: 'Vicious Rumors',
        set: 'Guilds of Ravnica',
        cost: '1',
        color: 'Black',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'Vicious Rumors deals 1 damage to each opponent.  Each opponent discards a card, then puts the top card of their library into their graveyard.  You gain 1 life.',
        flavor: '"The alliances were already frayed.  All we do is find the loose threads and pluck."\n--Lazav',
        art: 'http://mythicspoiler.com/grn/cards/viciousrumors.jpg'
      },
      {
        name: 'Whispering Snitch',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Vampire Rogue',
        rarity: 'Uncommon',
        effects: 'Whenever you surveil for the first time each turn, Whispering Snitch deals 1 damage to each opponent and you gain 1 life.',
        flavor: '"Sure, I hear things.  I hear plenty.  But how am I to talk with this parched throat?"',
        power: '1',
        toughness: '3',
        art: 'http://mythicspoiler.com/grn/cards/whisperingsnitch.jpg'
      },
      {
        name: 'Arclight Phoenix',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'Red',
        supertype: 'Creature',
        subtype: 'Phoenix',
        rarity: 'Mythic',
        effects: 'Flying, haste\nAt the beginning of combat on your turn, if you\'ve cast three or more instant and sorcery spells this turn, return Arclight Phoenix from your graveyard to the battlefield.',
        flavor: 'Some storms never blow over.',
        power: '3',
        toughness: '2',
        art: 'http://mythicspoiler.com/grn/cards/arclightphoenix.jpg'
      },
      {
        name: 'Barging Sergeant',
        set: 'Guilds of Ravnica',
        cost: '5',
        color: 'Red',
        supertype: 'Creature',
        subtype: 'Minotaur Soldier',
        rarity: 'Common',
        effects: 'Haste\nMentor (Whenever this creature attacks, put a +1/+1 counter on target attacking creature with lesser power.)',
        flavor: '"Don\'t stop till your horns come out their back."',
        power: '4',
        toughness: '2',
        art: 'http://mythicspoiler.com/grn/cards/bargingsergeant.jpg'
      },
      {
        name: 'Book Devourer',
        set: 'Guilds of Ravnica',
        cost: '6',
        color: 'Red',
        supertype: 'Creature',
        subtype: 'Beast',
        rarity: 'Uncommon',
        effects: 'Trample\nWhenever Book Devourer deals combat damage to a player, you may discard all the cards in your hand.  If you do, draw that many cards.',
        flavor: '"Not my first edition of The Advokist and the Urchin!"',
        power: '4',
        toughness: '5',
        art: 'http://mythicspoiler.com/grn/cards/bookdevourer.jpg'
      },
      {
        name: 'Command the Storm',
        set: 'Guilds of Ravnica',
        cost: '5',
        color: 'Red',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Command the Storm deals 5 damage to target creature.',
        flavor: 'In the wake of Niv-Mizzet\'s disappearance, Ral found himself leading the guild.  He had dreamed of this day, but couldn\'t help feeling like a pawn in someone else\'s game.',
        art: 'http://mythicspoiler.com/grn/cards/commandthestorm.jpg'
      },
      {
        name: 'Cosmotronic Wave',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'Red',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'Cosmotronic Wave deals 1 damage to each creature your opponents control.  Creatures your opponents control can\'t block this turn.',
        flavor: '"This sort of innovation occurs when you set out to improve an electric tea kettle and misplace a decimal."',
        art: 'http://mythicspoiler.com/grn/cards/comsotronicwave.jpg'
      },
      {
        name: 'Direct Current',
        set: 'Guilds of Ravnica',
        cost: '3',
        color: 'Red',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Direct Current deals 2 damage to any target.\nJump-start (You may cast this card from your graveyard by discarding a card in addition to paying its other costs.  Then exile this card.)',
        art: 'http://mythicspoiler.com/grn/cards/directcurrent.jpg'
      },
      {
        name: 'Electrostatic Field',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'Red',
        supertype: 'Creature',
        subtype: 'Wall',
        rarity: 'Common',
        effects: 'Defender\nWhenever you cast an instant or sorcery spell, Electrostatic Field deals 1 damage to each opponent.',
        flavor: '"It\'s both an ingress-denial mechanism and an attractive hallway light!"\n--Daxiver, Izzet electromancer',
        power: '0',
        toughness: '4',
        art: 'http://mythicspoiler.com/grn/cards/electrostaticfield.jpg'
      },
      {
        name: 'Erratic Cyclops',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'Red',
        supertype: 'Creature',
        subtype: 'Cyclops Shaman',
        rarity: 'Rare',
        effects: 'Trample\nWhenever you cast an instant or sorcery spell, Erratic Cyclops gets +X/+0 until end of turn, where X is that spell\'s converted mana cost.',
        flavor: '"The League accepts no responsibility for former members and the damage they may cause."\n--Maree, Izzet chamberlain',
        power: '0',
        toughness: '8',
        art: 'http://mythicspoiler.com/grn/cards/erraticcyclops.jpg'
      },
      {
        name: 'Experimental Frenzy',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'Red',
        supertype: 'Enchantment',
        rarity: 'Rare',
        effects: 'You may look at the top card of your library at any time.\nYou may play the top card of your library.\nYou can\'t play cards from your hand.\n{3R}: Destroy Experimental Frenzy.',
        flavor: 'Turns out coffee is the weird aunt of invention.',
        art: 'http://mythicspoiler.com/grn/cards/experimentalfrenzy.jpg'
      },
      {
        name: 'Fearless Halberdier',
        set: 'Guilds of Ravnica',
        cost: '3',
        color: 'Red',
        supertype: 'Creature',
        subtype: 'Human Warrior',
        rarity: 'Common',
        flavor: '"I spent some time in the Legion, but I\'m done taking orders all day."',
        power: '3',
        toughness: '2',
        art: 'http://mythicspoiler.com/grn/cards/fearlesshalberdier.jpg'
      },
      {
        name: 'Fire Urchin',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'Red',
        supertype: 'Creature',
        subtype: 'Elemental',
        rarity: 'Common',
        effects: 'Trample\nWhenever you cast an instant or sorcery spell, Fire Urchin gets +1/+0 until end of turn.',
        flavor: 'Rain runoff from the Smelting District is known to spontaneously burst into flame.',
        power: '1',
        toughness: '3',
        art: 'http://mythicspoiler.com/grn/cards/fireurchin.jpg'
      },
      {
        name: 'Goblin Banneret',
        set: 'Guilds of Ravnica',
        cost: '1',
        color: 'Red',
        supertype: 'Creature',
        subtype: 'Goblin Soldier',
        rarity: 'Uncommon',
        effects: 'Mentor (Whenever this creature attacks, put a +1/+1 counter on target attacking creature with lesser power.)\n{1R}: Goblin Banneret gets +2/+0 until end of turn.',
        flavor: 'The Boros banner stands tall even if its bearer doesn\'t.',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/grn/cards/goblinbanneret.jpg'
      },
      {
        name: 'Goblin Cratermaker',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'Red',
        supertype: 'Creature',
        subtype: 'Goblin Warrior',
        rarity: 'Uncommon',
        effects: '{1}, Sacrifice Goblin Cratermaker:\nChoose one --\n\tGoblin Cratermaker deals 2 damage to target creature.\n\tDestroy target colorless nonland permanent.',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/grn/cards/goblincratermaker.jpg'
      },
      {
        name: 'Goblin Locksmith',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'Red',
        supertype: 'Creature',
        subtype: 'Goblin Rogue',
        rarity: 'Common',
        effects: 'Whenever Goblin Locksmith attacks, creatures with defender can\'t block this turn.',
        flavor: '"He\'s got more finesse than most goblins.  He smashes windows with his fist rather than his forehead."\n--Arrester Polgar',
        power: '2',
        toughness: '1',
        art: 'http://mythicspoiler.com/grn/cards/goblinlocksmith.jpg'
      },
      {
        name: 'Gravitic Punch',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'Red',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'Target creature you control deals damage equal to its power to target player.\nJump-start (You may cast this card from your graveyard by discarding a card in addition to paying its other costs.  Then exile this card.)',
        art: 'http://mythicspoiler.com/grn/cards/graviticpunch.jpg'
      },
      {
        name: 'Hellkite Whelp',
        set: 'Guilds of Ravnica',
        cost: '5',
        color: 'Red',
        supertype: 'Creature',
        subtype: 'Dragon',
        rarity: 'Uncommon',
        effects: 'Flying\nWhenever Hellkite Whelp attacks, it deals 1 damage to target creature defending player controls.',
        flavor: '"They play by spitting fire at each other.  Don\'t be offended if one gives you a love-scorch."\n--Esfir, Rakdos dragon wrangler',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/grn/cards/hellkitewhelp.jpg'
      },
      {
        name: 'Inescapable Blaze',
        set: 'Guilds of Ravnica',
        cost: '6',
        color: 'Red',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'This spell can\'t be countered.\nInescapable Blaze deals 6 damage to any target.',
        flavor: '"The Izzet are blamed for every little disaster, which is unfair because we only cause most of them."\n--Mizzix of the Izmagnus',
        art: 'http://mythicspoiler.com/grn/cards/inescapableblaze.jpg'
      },
      {
        name: 'Lava Coil',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'Red',
        supertype: 'Sorcery',
        rarity: 'Uncommon',
        effects: 'Lava Coil deals 4 damage to target creature.  If that creature would die this turn, exile it instead.',
        flavor: '"Commander, we caught the Dimir spy and took her ashes into custody."\n--Kramm, Wojek security officer',
        art: 'http://mythicspoiler.com/grn/cards/lavacoil.jpg'
      },
      {
        name: 'Legion Warboss',
        set: 'Guilds of Ravnica',
        cost: '3',
        color: 'Red',
        supertype: 'Creature',
        subtype: 'Goblin Soldier',
        rarity: 'Rare',
        effects: 'Mentor (Whenever this creature attacks, put a +1/+1 counter on target attacking creature with lesser power.)\nAt the beginning of combat on your turn, create a 1/1 red Goblin creature token.  That token gains haste until end of turn and attacks this combat if able.',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/grn/cards/legionwarboss.jpg'
      },
      {
        name: 'Maniacal Rage',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'Red',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Common',
        effects: 'Enchant creature\nEnchanted creature gets +2/+2 and can\'t block.',
        flavor: '"They tell us the wilds are ours, then they brick them over.  They can lie to our faces but not to our fists."\n--Ghut Rak, Gruul guildmage',
        art: 'http://mythicspoiler.com/grn/cards/maniacalrage.jpg'
      },
      {
        name: 'Maximize Velocity',
        set: 'Guilds of Ravnica',
        cost: '1',
        color: 'Red',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Target creature gets +1/+1 and gains haste until end of turn.\nJump-start (You may cast this card from your graveyard by discarding a card in addition to paying its other costs.  Then exile this card.)',
        art: 'http://mythicspoiler.com/grn/cards/maximizevelocity.jpg'
      },
      {
        name: 'Ornery Goblin',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'Red',
        supertype: 'Creature',
        subtype: 'Goblin Warrior',
        rarity: 'Common',
        effects: 'Whenever Ornery Goblin blocks or becomes blocked by a creature, Ornery Goblin deals 1 damage to that creature.',
        flavor: '"Nobody ever listens to my complaints!  Not even when I use the listening stick."',
        power: '2',
        toughness: '1',
        art: 'http://mythicspoiler.com/grn/cards/ornerygoblin.jpg'
      },
      {
        name: 'Risk Factor',
        set: 'Guilds of Ravnica',
        cost: '3',
        color: 'Red',
        supertype: 'Instant',
        rarity: 'Rare',
        effects: 'Target opponent may have Risk Factor deal 4 damage to them.  If that player doesn\'t, you draw three cards.\nJump-start (You may cast this card from your graveyard by discarding a card in addition to paying its other costs.  Then exile this card.)',
        art: 'http://mythicspoiler.com/grn/cards/riskfactor.jpg'
      },
      {
        name: 'Rubblebelt Boar',
        set: 'Guilds of Ravnica',
        cost: '4',
        color: 'Red',
        supertype: 'Creature',
        subtype: 'Boar',
        rarity: 'Common',
        effects: 'When Rubblebelt Boar enters the battlefield, target creature gets +2/+0 until end of turn.',
        flavor: 'Some Gruul druids believe that boars are spawn of the great Ilharg, the mighty Raze-Boar who will one day rise and level the city.',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/grn/cards/rubblebeltboar.jpg'
      },
      {
        name: 'Runaway Steam-Kin',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'Red',
        supertype: 'Creature',
        subtype: 'Elemental',
        rarity: 'Rare',
        effects: 'Whenever you cast a red spell, if Runaway Steam-Kin has fewer than three +1/+1 counters on it, put a +1/+1 counter on Runaway Steam-Kin.\nRemove three +1/+1 counters from Runaway Steam-Kin: Add {RRR}.',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/grn/cards/runawaysteamkin.jpg'
      },
      {
        name: 'Smelt-Ward Minotaur',
        set: 'Guilds of Ravnica',
        cost: '3',
        color: 'Red',
        supertype: 'Creature',
        subtype: 'Minotaur Warrior',
        rarity: 'Uncommon',
        effects: 'Whenever you cast an instant or sorcery spell, target creature an opponent controls can\'t block this turn.',
        flavor: '"Don\'t arrest him--enlist him!"\n--Commander Yaszen',
        power: '2',
        toughness: '3',
        art: 'http://mythicspoiler.com/grn/cards/smeltwardminotaur.jpg'
      },
      {
        name: 'Street Riot',
        set: 'Guilds of Ravnica',
        cost: '5',
        color: 'Red',
        supertype: 'Enchantment',
        rarity: 'Uncommon',
        effects: 'As long as it\'s your turn, creatures you control get +1/+0 and have trample.',
        flavor: '"They said obey and you\'ll be happy.  They said you\'ll be safe.  But we\'re not safe.  We\'re not happy.  And we will not obey."\n--Domri Rade',
        art: 'http://mythicspoiler.com/grn/cards/streetriot.jpg'
      },
      {
        name: 'Sure Strike',
        set: 'Guilds of Ravnica',
        cost: '2',
        color: 'Red',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Target creature gets +3/+0 and gains first strike until end of turn.',
        flavor: '"I packed three more electroconduits into each test wand.  You\'ll experience a brief tingling sensation."',
        art: 'http://mythicspoiler.com/grn/cards/surestrike.jpg'
      },
      {
        name: 'Torch Courier',
        set: 'Guilds of Ravnica',
        cost: '1',
        color: 'Red',
        supertype: 'Creature',
        subtype: 'Goblin',
        rarity: 'Common',
        effects: 'Haste\nSacrifice Torch Courier: Another target creature gains haste until end of turn.',
        flavor: '"Light a torch and deliver this letter" were his instructions, which he unfortunately reversed.',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/grn/cards/torchcourier.jpg'
      },
      {
        name: 'Wojek Bodyguard',
        set: 'Guilds of Ravnica',
        cost: '3',
        color: 'Red',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Common',
        effects: 'Mentor (Whenever this creature attacks, put a +1/+1 counter on target attacking creature with lesser power.)\nWojek Bodyguard can\'t attack or block alone.',
        flavor: '"By all means, take another step towards the captain."',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/grn/cards/wojekbodyguard.jpg'
      },
      {
        name: '',
        set: 'Guilds of Ravnica',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
    ]);
  });
};