exports.seed = (knex, Promise) => {
  // Deletes ALL existing entries
  return knex('Card_List').del()
  .then( () => {
    // Inserts seed entries
    return knex('Card_List').insert([
      {
        name: 'Angel of Grace',
        set: 'Ravnica Allegiance',
        cost: '5',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Angel',
        rarity: 'Mythic',
        effects: 'Flash\nFlying\nWhen Angel of Grace enters the battlefield, until end of turn, damage that would reduce your life total to less than 1 reduces it to 1 instead.\n{4WW}, Exile Angel of Grace from your graveyard: Your life total becomes 10.',
        power: '5',
        toughness: '4',
        art: 'http://mythicspoiler.com/rna/cards/angelofgrace.jpg'
      },
      {
        name: 'Angelic Exaltation',
        set: 'Ravnica Allegiance',
        cost: '4',
        color: 'White',
        supertype: 'Enchantment',
        rarity: 'Uncommon',
        effects: 'Whenever a creature you control attacks alone, it gets +X/+X until end of turn, where X is the number of creatures you control.',
        flavor: '"If we cannot have peace, we will have justice."--Aurelia',
        art: 'http://mythicspoiler.com/rna/cards/angelicexaltation.jpg'
      },
      {
        name: 'Archway Angel',
        set: 'Ravnica Allegiance',
        cost: '6',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Angel',
        rarity: 'Uncommon',
        effects: 'Flying\nWhen Archway Angel enters the battlefield, you gain 2 life for each Gate you control.',
        flavor: 'A ray of hope breaks through the shroud of rain.',
        power: '3',
        toughness: '4',
        art: 'http://mythicspoiler.com/rna/cards/archwayangel.jpg'
      },
      {
        name: 'Arrester\'s Zeal',
        set: 'Ravnica Allegiance',
        cost: '1',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Target creature gets +2/+2 until end of turn.\nAddendum -- If you cast this spell during your main phase, that creature gains flying until end of turn.',
        flavor: 'Law is the light of civilization.',
        art: 'http://mythicspoiler.com/rna/cards/arresterszeal.jpg'
      },
      {
        name: 'Bring to Trial',
        set: 'Ravnica Allegiance',
        cost: '3',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'Exile target creature with power 4 or greater.',
        flavor: '"In you go, big guy.  Watch your head."',
        art: 'http://mythicspoiler.com/rna/cards/bringtotrial.jpg'
      },
      {
        name: 'Civic Stalwart',
        set: 'Ravnica Allegiance',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Elephant Soldier',
        rarity: 'Common',
        effects: 'When Civic Stalwart enters the battlefield, creatures you control get +1/+1 until end of turn.',
        flavor: '"These are your streets.  Defend them!\nThis is your neighborhood.  Honor it!\nThis is your city.  Save it!"',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/rna/cards/civicstalwart.jpg'
      },
      {
        name: 'Concordia Pegasus',
        set: 'Ravnica Allegiance',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Pegasus',
        rarity: 'Common',
        effects: 'Flying',
        flavor: '"What makes a frog lizard any different than a bird horse?  Prejudice against the Simic, that\'s what.  It\'s unfair!"\n--Thados Arquef, Guardian Project biomancer',
        power: '1',
        toughness: '3',
        art: 'http://mythicspoiler.com/rna/cards/concordiapegasus.jpg'
      },
      {
        name: 'Expose to Daylight',
        set: 'Ravnica Allegiance',
        cost: '3',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Destroy target artifact or enchantment.  Scry 1.',
        flavor: '"Lies cannot long withstand the harsh light of day."\n--Lavinia',
        art: 'http://mythicspoiler.com/rna/cards/exposetodaylight.jpg'
      },
      {
        name: 'Forbidding Spirit',
        set: 'Ravnica Allegiance',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Spirit Cleric',
        rarity: 'Uncommon',
        effects: 'When Forbidding Spirit enters the battlefield, until your next turn, creatures can\'t attack you or a planeswalker you control unless their controller pays {2} for each of those creatures.',
        flavor: '"You will respect the dead."',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/rna/cards/forbiddingspirit.jpg'
      },
      {
        name: 'Haazda Officer',
        set: 'Ravnica Allegiance',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Common',
        effects: 'When Haazda Officer enters the battlefield, target creature you control gets +1/+1 until end of turn.',
        flavor: '"You two, cover the alley!  You, with me!  Eyes on windows, balconies, and rooftops.  Who knows what a fish-octopus-crab can do!"',
        power: '3',
        toughness: '2',
        art: 'http://mythicspoiler.com/rna/cards/haazdaofficer.jpg'
      },
      {
        name: 'Hero of Precinct One',
        set: 'Ravnica Allegiance',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Warrior',
        rarity: 'Rare',
        effects: 'Whenever you cast a multicolored spell, create a 1/1 white Human creature token.',
        flavor: 'When the established order falters, what remains are ordinary people and their struggle to survive.',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/rna/cards/heroofprecinctone.jpg'
      },
      {
        name: 'Impassioned Orator',
        set: 'Ravnica Allegiance',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Cleric',
        rarity: 'Common',
        effects: 'Whenever another creature enters the battlefield under your control, you gain 1 life.',
        flavor: 'In times of unrest, the crowd is eager for the comfort of strong convictions.',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/rna/cards/impassionedorator.jpg'
      },
      {
        name: 'Justiciar\'s Portal',
        set: 'Ravnica Allegiance',
        cost: '2',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Exile target creature you control, then return that card to the battlefield under its owner\'s control.  It gains first strike until end of turn.',
        flavor: 'With the new guildmaster\'s innovations, arresters can arrive on the scene moments before a crime is committed.',
        art: 'http://mythicspoiler.com/rna/cards/justiciarsportal.jpg'
      },
      {
        name: 'Knight of Sorrows',
        set: 'Ravnica Allegiance',
        cost: '5',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Knight',
        rarity: 'Common',
        effects: 'Knight of Sorrows can block an additional creature each combat.\nAfterlife 1 (When this creature dies, create a 1/1 white and black Spirit creature token with flying.)',
        flavor: 'The helmet reveals no eyes to witness your penance, no mouth to offer absolution.',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/rna/cards/knightofsorrows.jpg'
      },
      {
        name: 'Lumbering Battlement',
        set: 'Ravnica Allegiance',
        cost: '5',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Beast',
        rarity: 'Rare',
        effects: 'Vigilance\nWhen Lumbering Battlement enters the battlefield, exile any number of nontoken creatures you control until it leaves the battlefield.\nLumbering Battlement gets +2/+2 for each card exiled with it.',
        power: '4',
        toughness: '5',
        art: 'http://mythicspoiler.com/rna/cards/lumberingbattlement.jpg'
      },
      {
        name: 'Ministrant of Obligation',
        set: 'Ravnica Allegiance',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Cleric',
        rarity: 'Uncommon',
        effects: 'Afterlife 2 (When this creature dies, create two 1/1 white and black Spirit creature tokens with flying.)',
        flavor: 'When the price of your sins comes due, the Church of Deals is there to collect.',
        power: '2',
        toughness: '1',
        art: 'http://mythicspoiler.com/rna/cards/ministrantofobligation.jpg'
      },
      {
        name: 'Prowling Caracal',
        set: 'Ravnica Allegiance',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Cat',
        rarity: 'Common',
        flavor: 'A hunter in the city requires the utmost cunning to survive.  It must pounce only if the kill is certain, and leave the remains where no one will see.',
        power: '3',
        toughness: '1',
        art: 'http://mythicspoiler.com/rna/cards/prowlingcaracal.jpg'
      },
      {
        name: 'Rally to Battle',
        set: 'Ravnica Allegiance',
        cost: '4',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'Creatures you control get +1/+3 until end of turn.  Untap them.',
        flavor: 'The guildmasters loom large in the political sphere, but in the end, the rulers of Ravnica are its people.',
        art: 'http://mythicspoiler.com/rna/cards/rallytobattle.jpg'
      },
      {
        name: 'Resolute Watchdog',
        set: 'Ravnica Allegiance',
        cost: '1',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Hound',
        rarity: 'Uncommon',
        effects: 'Defender\n{1}, Sacrifice Resolute Watchdog: Target creature you control gains indestructible until end of turn. (Damage and effects that say "destroy" don\'t destroy it.)',
        flavor: 'A friend in good times, a guardian in bad times, and a savior when all else fails.',
        power: '1',
        toughness: '3',
        art: 'http://mythicspoiler.com/rna/cards/resolutewatchdog.jpg'
      },
      {
        name: 'Sentinel\'s Mark',
        set: 'Ravnica Allegiance',
        cost: '2',
        color: 'White',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Uncommon',
        effects: 'Flash\nEnchant creature\nEnchanted creature gets +1/+2 and has vigilance.\nAddendum -- When Sentinel\'s Mark enters the battlefield, if you cast it during your main phase, enchanted creature gains lifelink until end of turn.',
        art: 'http://mythicspoiler.com/rna/cards/sentinelsmark.jpg'
      },
      {
        name: 'Sky Tether',
        set: 'Ravnica Allegiance',
        cost: '1',
        color: 'White',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Uncommon',
        effects: 'Enchant creature\nEnchanted creature has defender and loses flying.',
        flavor: '"If you can\'t control your mount, I\'ll control it for you."\n--Mirela, Azorius hussar',
        art: 'http://mythicspoiler.com/rna/cards/skytether.jpg'
      },
      {
        name: 'Smothering Tithe',
        set: 'Ravnica Allegiance',
        cost: '4',
        color: 'White',
        supertype: 'Enchantment',
        rarity: 'Rare',
        effects: 'Whenever an opponent draws a card, that player may pay {2}.  If the player doesn\'t, you create a colorless Treasure artifact token with "{T}, Sacrifice this artifact: Add one mana of any color."',
        flavor: '"I await your donation."\n--Dasha, Orzhov priest',
        art: 'http://mythicspoiler.com/rna/cards/smotheringtithe.jpg'
      },
      {
        name: 'Spirit of the Spires',
        set: 'Ravnica Allegiance',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Spirit',
        rarity: 'Uncommon',
        effects: 'Flying\nOther creatures you control with flying get +0/+1.',
        flavor: 'She breathes fair winds to tired griffins and lifts songbirds beyond the reach of stalking cats.',
        power: '2',
        toughness: '4',
        art: 'http://mythicspoiler.com/rna/cards/spiritofthespires.jpg'
      },
      {
        name: 'Summary Judgment',
        set: 'Ravnica Allegiance',
        cost: '2',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Summary Judgment deals 3 damage to target tapped creature.\nAddendum -- If you cast this spell during your main phase, it deals 5 damage to that creature instead.',
        flavor: 'Any challenge to Azorius authority is met with swift and potent retribution.',
        art: 'http://mythicspoiler.com/rna/cards/summaryjudgment.jpg'
      },
      {
        name: 'Syndicate Messenger',
        set: 'Ravnica Allegiance',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Bird',
        rarity: 'Common',
        effects: 'Flying\nAfterlife 1 (When this creature dies, create a 1/1 white and black Spirit creature token with flying.)',
        flavor: '"Many wings haunt the skies these days.  Few of them bring good tidings."\n--Lavinia',
        power: '2',
        toughness: '3',
        art: 'http://mythicspoiler.com/rna/cards/syndicatemessenger.jpg'
      },
      {
        name: 'Tenth District Veteran',
        set: 'Ravnica Allegiance',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Common',
        effects: 'Vigilance\nWhenever Tenth District Veteran attacks, untap another target creature you control.',
        flavor: '"I keep reminding myself we do this because others can\'t, because we love this city.  If we don\'t save it, no one will."',
        power: '2',
        toughness: '3',
        art: 'http://mythicspoiler.com/rna/cards/tenthdistrictveteran.jpg'
      },
      {
        name: 'Tithe Taker',
        set: 'Ravnica Allegiance',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Rare',
        effects: 'During your turn, spells your opponents cast cost {1} more to cast and abilities your opponents activate cost {1} more to activate unless they\'re mana abilities.\nAfterlife 1 (When this creature dies, create a 1/1 white and black Spirit creature token with flying.)',
        power: '2',
        toughness: '1',
        art: 'http://mythicspoiler.com/rna/cards/tithetaker.jpg'
      },
      {
        name: 'Twilight Panther',
        set: 'Ravnica Allegiance',
        cost: '1',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Cat Spirit',
        rarity: 'Common',
        effects: '{B}: Twilight Panther gains deathtouch until end of turn.',
        flavor: 'A pet that can hunt both flesh and spirit is precious in a place where smiling assassins keep company with ghostly shadows.',
        power: '1',
        toughness: '2',
        art: 'http://mythicspoiler.com/rna/cards/twilightpanther.jpg'
      },
      {
        name: 'Unbreakable Formation',
        set: 'Ravnica Allegiance',
        cost: '3',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Rare',
        effects: 'Creatures you control gain indestructible until end of turn.\nAddendum -- If you cast this spell during your main phase, put a +1/+1 counter on each of those creatures and they gain vigilance until end of turn.',
        art: 'http://mythicspoiler.com/rna/cards/unbreakableformation.jpg'
      },
      {
        name: 'Watchful Giant',
        set: 'Ravnica Allegiance',
        cost: '6',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Giant Soldier',
        rarity: 'Common',
        effects: 'When Watchful Giant enters the battlefield, create a 1/1 white Human creature token.',
        flavor: 'Loitering is not only illegal but unwise, since those who stay too long in one place are apt to be stepped on.',
        power: '3',
        toughness: '6',
        art: 'http://mythicspoiler.com/rna/cards/watchfulgiant.jpg'
      },
      {
        name: 'Arrester\'s Admonition',
        set: 'Ravnica Allegiance',
        cost: '3',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Return target creature to its owner\'s hand.\nAddendum -- If you cast this spell during your main phase, draw a card.',
        flavor: 'Law is the voice of reason.',
        art: 'http://mythicspoiler.com/rna/cards/arrestersadmonition.jpg'
      },
      {
        name: 'Benthic Biomancer',
        set: 'Ravnica Allegiance',
        cost: '1',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Merfolk Wizard Mutant',
        rarity: 'Rare',
        effects: '{1U}: Adapt 1. (If this creature has no +1/+1 counters on it, put a +1/+1 counter on it.)\nWhenever one or more +1/+1 counters are put on Benthic Biomancer, draw a card, then discard a card.',
        flavor: '"I am my life\'s work."',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/rna/cards/benthicbiomancer.jpg'
      },
      {
        name: 'Chillbringer',
        set: 'Ravnica Allegiance',
        cost: '5',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Elemental',
        rarity: 'Common',
        effects: 'Flying\nWhen Chillbringer enters the battlefield, tap target creature an opponent controls.  It doesn\'t untap during its controller\'s next untap step.',
        flavor: 'If you can see your breath, it\'s too late to run.',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/rna/cards/chillbringer.jpg'
      },
      {
        name: 'Clear the Mind',
        set: 'Ravnica Allegiance',
        cost: '3',
        color: 'Blue',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'Target player shuffles their graveyard into their library.\nDraw a card.',
        flavor: '"The best way to keep a secret is to forget it."\n--Lazav',
        art: 'http://mythicspoiler.com/rna/cards/clearthemind.jpg'
      },
      {
        name: 'Code of Constraint',
        set: 'Ravnica Allegiance',
        cost: '3',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'Target creature gets -4/-0 until end of turn.\nDraw a card.\nAddendum -- If you cast this spell during your main phase, tap that creature and it doesn\'t untap during its controller\'s next untap step.',
        art: 'http://mythicspoiler.com/rna/cards/codeofconstraint.jpg'
      },
      {
        name: 'Coral Commando',
        set: 'Ravnica Allegiance',
        cost: '3',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Merfolk Warrior',
        rarity: 'Common',
        flavor: 'Few Ravnicans are aware of the vast reefs in their world\'s hidden ocean.  Far beneath the great sinkholes, where the light is blue and dim, merfolk tend the coral labyrinths that feed the benthic ecosystem.',
        power: '3',
        toughness: '2',
        art: 'http://mythicspoiler.com/rna/cards/coralcommando.jpg'
      },
      {
        name: 'Essence Capture',
        set: 'Ravnica Allegiance',
        cost: '2',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'Counter target creature spell.  Put a +1/+1 counter on up to one target creature you control.',
        flavor: '"It\'s not enough to defeat our foes.  We must learn from them, too."\n--Vannifar',
        art: 'http://mythicspoiler.com/rna/cards/essencecapture.jpg'
      },
      {
        name: 'Eyes Everywhere',
        set: 'Ravnica Allegiance',
        cost: '3',
        color: 'Blue',
        supertype: 'Enchantment',
        rarity: 'Uncommon',
        effects: 'At the beginning of your upkeep, scry 1.\n{5U}: Exchange control of Eyes Everywhere and target nonland permanent.  Activate this ability only any time you could cast a sorcery.',
        flavor: '"They\'ve got eyes inside my head!"',
        art: 'http://mythicspoiler.com/rna/cards/eyeseverywhere.jpg'
      },
      {
        name: 'Faerie Duelist',
        set: 'Ravnica Allegiance',
        cost: '2',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Faerie Rogue',
        rarity: 'Common',
        effects: 'Flash\nFlying\nWhen Faerie Duelist enters the battlefield, target creature an opponent controls gets -2/-0 until end of turn.',
        flavor: 'Faeries are easily offended and quick to exact a quirky revenge.',
        power: '1',
        toughness: '2',
        art: 'http://mythicspoiler.com/rna/cards/faerieduelist.jpg'
      },
      {
        name: 'Gateway Sneak',
        set: 'Ravnica Allegiance',
        cost: '3',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Vedalken Rogue',
        rarity: 'Common',
        effects: 'Whenever a Gate enters the battlefield under your control, Gateway Sneak can\'t be blocked this turn.\nWhenever Gateway Sneak deals combat damage to a player, draw a card.',
        flavor: '"I\'ve been through every guildgate in the city, and no one sees me come or go."',
        power: '1',
        toughness: '3',
        art: 'http://mythicspoiler.com/rna/cards/gatewaysneak.jpg'
      },
      {
        name: 'Humongulus',
        set: 'Ravnica Allegiance',
        cost: '5',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Homunculus',
        rarity: 'Common',
        effects: 'Hexproof (This creature can\'t be the target of spells or abilities your opponents control.)',
        flavor: 'Searching the city for Fblthp felt like sifting the rain for a single drop of blood.',
        power: '2',
        toughness: '5',
        art: 'http://mythicspoiler.com/rna/cards/humongulus.jpg'
      },
      {
        name: 'Mass Manipulation',
        set: 'Ravnica Allegiance',
        cost: '6+',
        color: 'Blue',
        supertype: 'Sorcery',
        rarity: 'Rare',
        effects: 'Gain control of X target creatures and/or planeswalkers.',
        flavor: 'Those who cross the Dimir find enemies wherever they turn.',
        art: 'http://mythicspoiler.com/rna/cards/massmanipulation.jpg'
      },
      {
        name: 'Mesmerizing Benthid',
        set: 'Ravnica Allegiance',
        cost: '5',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Octopus',
        rarity: 'Mythic',
        effects: 'When Mesmerizing Benthid enters the battlefield, create two 0/2 blue Illusion creature tokens with "Whenever this creature blocks a creature, that creature doesn\'t untap during its controller\'s next untap step."\nMesmerizing Benthid has hexproof as long as you control an Illusion.',
        power: '4',
        toughness: '5',
        art: 'http://mythicspoiler.com/rna/cards/mesmerizingbenthid.jpg'
      },
      {
        name: 'Persistent Petitioners',
        set: 'Ravnica Allegiance',
        cost: '2',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Human Advisor',
        rarity: 'Common',
        effects: '{1}, {T}: Target player puts the top card of their library into their graveyard.\nTap four untapped Advisors you control: Target player puts the top twelve cards of their library into their graveyard.\nA deck can have any number of cards named Persistent Petitioners.',
        power: '1',
        toughness: '3',
        art: 'http://mythicspoiler.com/rna/cards/persistentpetitioners.jpg'
      },
      {
        name: 'Precognitive Perception',
        set: 'Ravnica Allegiance',
        cost: '5',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Rare',
        effects: 'Draw three cards.\nAddendum -- If you cast this spell during your main phase, instead scry 3, then draw three cards.',
        flavor: '"To control the present we must master the future."',
        art: 'http://mythicspoiler.com/rna/cards/precognitiveperception.jpg'
      },
      {
        name: 'Prying Eyes',
        set: 'Ravnica Allegiance',
        cost: '6',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Draw four cards, then discard two cards.',
        flavor: '"Citizen! Your crime has been recorded.  Cease movement and await arrest, or further penalties will be imposed."',
        art: 'http://mythicspoiler.com/rna/cards/pryingeyes.jpg'
      },
      {
        name: 'Pteramander',
        set: 'Ravnica Allegiance',
        cost: '1',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Salamander Drake',
        rarity: 'Uncommon',
        effects: 'Flying\n{7U}: Adapt 4. This ability costs {1} less for each instant and sorcery card in your graveyard. (If this creature has no +1/+1 counters on it, put four +1/+1 counters on it.)',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/rna/cards/pteramander.jpg'
      },
      {
        name: 'Quench',
        set: 'Ravnica Allegiance',
        cost: '2',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Counter target spell unless its controller pays {2}.',
        flavor: '"When properly invoked, the plasma globule encloses the offensive spell with a satisfying slurp."',
        art: 'http://mythicspoiler.com/rna/cards/quench.jpg'
      },
      {
        name: 'Sage\'s Row Savant',
        set: 'Ravnica Allegiance',
        cost: '2',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Vedalken Wizard',
        rarity: 'Common',
        effects: 'When Sage\'s Row Savant enters the battlefield, scry 2.',
        flavor: 'The streets of Ravnica are full of former guild members now using their institutional skills for personal gain.',
        power: '2',
        toughness: '1',
        art: 'http://mythicspoiler.com/rna/cards/sagesrowsavant.jpg'
      },
      {
        name: 'Senate Courier',
        set: 'Ravnica Allegiance',
        cost: '3',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Bird',
        rarity: 'Common',
        effects: 'Flying\n{1W}: Senate Courier gains vigilance until end of turn.',
        flavor: '"This Dovin Baan came from nowhere.  Watch him.  Read his letters.  He is more than he appears."\n--Lazav',
        power: '1',
        toughness: '4',
        art: 'http://mythicspoiler.com/rna/cards/senatecourier.jpg'
      },
      {
        name: 'Shimmer of Possibility',
        set: 'Ravnica Allegiance',
        cost: '2',
        color: 'Blue',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'Look at the top four cards of your library.  Put one of them into your hand and the rest on the bottom of your library in a random order.',
        flavor: '"There\'s something peculiar about the rain today."\n--Janoc, Tin Street tinker',
        art: 'http://mythicspoiler.com/rna/cards/shimmerofpossibility.jpg'
      },
      {
        name: 'Skatewing Spy',
        set: 'Ravnica Allegiance',
        cost: '4',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Vedalken Rogue Mutant',
        rarity: 'Uncommon',
        effects: '{5U}: Adapt 2. (If this creature has no +1/+1 counters on it, put two +1/+1 counters on it.)\nEach creature you control with a +1/+1 counter on it has flying.',
        flavor: '"A better Ravnica begins with a better Simic."\n--Vannifar',
        power: '2',
        toughness: '3',
        art: 'http://mythicspoiler.com/rna/cards/skatewingspy.jpg'
      },
      {
        name: 'Skitter Eel',
        set: 'Ravnica Allegiance',
        cost: '4',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Fish Crab',
        rarity: 'Common',
        effects: '{2U}: Adapt 2. (If this creature has no +1/+1 counters on it, put two +1/+1 counters on it.)',
        flavor: '"Life has no mistakes, only experiments."\nYolov, Simic bioengineer',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/rna/cards/skittereel.jpg'
      },
      {
        name: 'Slimebind',
        set: 'Ravnica Allegiance',
        cost: '2',
        color: 'Blue',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Common',
        effects: 'Flash\nEnchant creature\nEnchanted creature gets -4/-0.',
        flavor: '"Relax.  It\'s quite harmless.  And it will dissolve completely in a month or two."\n--Navona, Simic field tester',
        art: 'http://mythicspoiler.com/rna/cards/slimebind.jpg'
      },
      {
        name: 'Sphinx of Foresight',
        set: 'Ravnica Allegiance',
        cost: '4',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Sphinx',
        rarity: 'Rare',
        effects: 'You may reveal this card from your opening hand.  If you do, scry 3 at the beginning of your first upkeep.\nFlying\nAt the beginning of your upkeep, scry 1.',
        flavor: '"I do not understand the future I see: the guilds subverted, the world at war, armies bent to a cruel conqueror\'s will."',
        power: '4',
        toughness: '4',
        art: 'http://mythicspoiler.com/rna/cards/sphinxofforesight.jpg'
      },
      {
        name: 'Swirling Torrent',
        set: 'Ravnica Allegiance',
        cost: '6',
        color: 'Blue',
        supertype: 'Sorcery',
        rarity: 'Uncommon',
        effects: 'Choose one or both --\n\tPut target creature on top of its owner\'s library.\n\tReturn target creature to its owner\'s hand.',
        flavor: '"Oops!"\n--Grupgrup, sluiceway technician',
        art: 'http://mythicspoiler.com/rna/cards/swirlingtorrent.jpg'
      },
      {
        name: 'Thought Collapse',
        set: 'Ravnica Allegiance',
        cost: '3',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Counter target spell.  Its controller puts the top three cards of their library into their graveyard.',
        flavor: '"I can think of no greater punishment than answering your question in full."\n--Lazav',
        art: 'http://mythicspoiler.com/rna/cards/thoughtcollapse.jpg'
      },
      {
        name: 'Verity Circle',
        set: 'Ravnica Allegiance',
        cost: '3',
        color: 'Blue',
        supertype: 'Enchantment',
        rarity: 'Rare',
        effects: 'Whenever a creature an opponent controls becomes tapped, if it isn\'t being declared as an attacker, draw a card.\n{4U}: Tap target creature without flying.',
        flavor: '"Here, there is only truth."\n--Barvisa, Azorius emissary',
        art: 'http://mythicspoiler.com/rna/cards/veritycircle.jpg'
      },
      {
        name: 'Wall of Lost Thoughts',
        set: 'Ravnica Allegiance',
        cost: '2',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Wall',
        rarity: 'Uncommon',
        effects: 'Defender\nWhen Wall of Lost Thoughts enters the battlefield, target player puts the top four cards of their library into their graveyard.',
        flavor: 'Those who intrude upon the Dimir seldom remember that they have done so.',
        power: '0',
        toughness: '4',
        art: 'http://mythicspoiler.com/rna/cards/walloflostthoughts.jpg'
      },
      {
        name: 'Windstorm Drake',
        set: 'Ravnica Allegiance',
        cost: '5',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Drake',
        rarity: 'Uncommon',
        effects: 'Flying\nOther creatures you control with flying get +1/+0.',
        flavor: 'Drakes become especially voracious as they prepare for their autumn migration, hunting the city\'s thoroughfares from dawn to dusk.',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/rna/cards/windstormdrake.jpg'
      },
      {
        name: '',
        set: 'Ravnica Allegiance',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
    ]);
  });
};