exports.seed = (knex, Promise) => {
  // Deletes ALL existing entries
  return knex('Card_List').del()
  .then( () => {
    // Inserts seed entries
    return knex('Card_List').insert([
      {
        name: 'Angel of Grace',
        set: 'Ravnica Allegiance',
        cost: '5',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Angel',
        rarity: 'Mythic',
        effects: 'Flash\nFlying\nWhen Angel of Grace enters the battlefield, until end of turn, damage that would reduce your life total to less than 1 reduces it to 1 instead.\n{4WW}, Exile Angel of Grace from your graveyard: Your life total becomes 10.',
        power: '5',
        toughness: '4',
        art: 'http://mythicspoiler.com/rna/cards/angelofgrace.jpg'
      },
      {
        name: 'Angelic Exaltation',
        set: 'Ravnica Allegiance',
        cost: '4',
        color: 'White',
        supertype: 'Enchantment',
        rarity: 'Uncommon',
        effects: 'Whenever a creature you control attacks alone, it gets +X/+X until end of turn, where X is the number of creatures you control.',
        flavor: '"If we cannot have peace, we will have justice."--Aurelia',
        art: 'http://mythicspoiler.com/rna/cards/angelicexaltation.jpg'
      },
      {
        name: 'Archway Angel',
        set: 'Ravnica Allegiance',
        cost: '6',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Angel',
        rarity: 'Uncommon',
        effects: 'Flying\nWhen Archway Angel enters the battlefield, you gain 2 life for each Gate you control.',
        flavor: 'A ray of hope breaks through the shroud of rain.',
        power: '3',
        toughness: '4',
        art: 'http://mythicspoiler.com/rna/cards/archwayangel.jpg'
      },
      {
        name: 'Arrester\'s Zeal',
        set: 'Ravnica Allegiance',
        cost: '1',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Target creature gets +2/+2 until end of turn.\nAddendum -- If you cast this spell during your main phase, that creature gains flying until end of turn.',
        flavor: 'Law is the light of civilization.',
        art: 'http://mythicspoiler.com/rna/cards/arresterszeal.jpg'
      },
      {
        name: 'Bring to Trial',
        set: 'Ravnica Allegiance',
        cost: '3',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'Exile target creature with power 4 or greater.',
        flavor: '"In you go, big guy.  Watch your head."',
        art: 'http://mythicspoiler.com/rna/cards/bringtotrial.jpg'
      },
      {
        name: 'Civic Stalwart',
        set: 'Ravnica Allegiance',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Elephant Soldier',
        rarity: 'Common',
        effects: 'When Civic Stalwart enters the battlefield, creatures you control get +1/+1 until end of turn.',
        flavor: '"These are your streets.  Defend them!\nThis is your neighborhood.  Honor it!\nThis is your city.  Save it!"',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/rna/cards/civicstalwart.jpg'
      },
      {
        name: 'Concordia Pegasus',
        set: 'Ravnica Allegiance',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Pegasus',
        rarity: 'Common',
        effects: 'Flying',
        flavor: '"What makes a frog lizard any different than a bird horse?  Prejudice against the Simic, that\'s what.  It\'s unfair!"\n--Thados Arquef, Guardian Project biomancer',
        power: '1',
        toughness: '3',
        art: 'http://mythicspoiler.com/rna/cards/concordiapegasus.jpg'
      },
      {
        name: 'Expose to Daylight',
        set: 'Ravnica Allegiance',
        cost: '3',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Destroy target artifact or enchantment.  Scry 1.',
        flavor: '"Lies cannot long withstand the harsh light of day."\n--Lavinia',
        art: 'http://mythicspoiler.com/rna/cards/exposetodaylight.jpg'
      },
      {
        name: 'Forbidding Spirit',
        set: 'Ravnica Allegiance',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Spirit Cleric',
        rarity: 'Uncommon',
        effects: 'When Forbidding Spirit enters the battlefield, until your next turn, creatures can\'t attack you or a planeswalker you control unless their controller pays {2} for each of those creatures.',
        flavor: '"You will respect the dead."',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/rna/cards/forbiddingspirit.jpg'
      },
      {
        name: 'Haazda Officer',
        set: 'Ravnica Allegiance',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Common',
        effects: 'When Haazda Officer enters the battlefield, target creature you control gets +1/+1 until end of turn.',
        flavor: '"You two, cover the alley!  You, with me!  Eyes on windows, balconies, and rooftops.  Who knows what a fish-octopus-crab can do!"',
        power: '3',
        toughness: '2',
        art: 'http://mythicspoiler.com/rna/cards/haazdaofficer.jpg'
      },
      {
        name: 'Hero of Precinct One',
        set: 'Ravnica Allegiance',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Warrior',
        rarity: 'Rare',
        effects: 'Whenever you cast a multicolored spell, create a 1/1 white Human creature token.',
        flavor: 'When the established order falters, what remains are ordinary people and their struggle to survive.',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/rna/cards/heroofprecinctone.jpg'
      },
      {
        name: 'Impassioned Orator',
        set: 'Ravnica Allegiance',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Cleric',
        rarity: 'Common',
        effects: 'Whenever another creature enters the battlefield under your control, you gain 1 life.',
        flavor: 'In times of unrest, the crowd is eager for the comfort of strong convictions.',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/rna/cards/impassionedorator.jpg'
      },
      {
        name: 'Justiciar\'s Portal',
        set: 'Ravnica Allegiance',
        cost: '2',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Exile target creature you control, then return that card to the battlefield under its owner\'s control.  It gains first strike until end of turn.',
        flavor: 'With the new guildmaster\'s innovations, arresters can arrive on the scene moments before a crime is committed.',
        art: 'http://mythicspoiler.com/rna/cards/justiciarsportal.jpg'
      },
      {
        name: 'Knight of Sorrows',
        set: 'Ravnica Allegiance',
        cost: '5',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Knight',
        rarity: 'Common',
        effects: 'Knight of Sorrows can block an additional creature each combat.\nAfterlife 1 (When this creature dies, create a 1/1 white and black Spirit creature token with flying.)',
        flavor: 'The helmet reveals no eyes to witness your penance, no mouth to offer absolution.',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/rna/cards/knightofsorrows.jpg'
      },
      {
        name: 'Lumbering Battlement',
        set: 'Ravnica Allegiance',
        cost: '5',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Beast',
        rarity: 'Rare',
        effects: 'Vigilance\nWhen Lumbering Battlement enters the battlefield, exile any number of nontoken creatures you control until it leaves the battlefield.\nLumbering Battlement gets +2/+2 for each card exiled with it.',
        power: '4',
        toughness: '5',
        art: 'http://mythicspoiler.com/rna/cards/lumberingbattlement.jpg'
      },
      {
        name: 'Ministrant of Obligation',
        set: 'Ravnica Allegiance',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Cleric',
        rarity: 'Uncommon',
        effects: 'Afterlife 2 (When this creature dies, create two 1/1 white and black Spirit creature tokens with flying.)',
        flavor: 'When the price of your sins comes due, the Church of Deals is there to collect.',
        power: '2',
        toughness: '1',
        art: 'http://mythicspoiler.com/rna/cards/ministrantofobligation.jpg'
      },
      {
        name: 'Prowling Caracal',
        set: 'Ravnica Allegiance',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Cat',
        rarity: 'Common',
        flavor: 'A hunter in the city requires the utmost cunning to survive.  It must pounce only if the kill is certain, and leave the remains where no one will see.',
        power: '3',
        toughness: '1',
        art: 'http://mythicspoiler.com/rna/cards/prowlingcaracal.jpg'
      },
      {
        name: 'Rally to Battle',
        set: 'Ravnica Allegiance',
        cost: '4',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'Creatures you control get +1/+3 until end of turn.  Untap them.',
        flavor: 'The guildmasters loom large in the political sphere, but in the end, the rulers of Ravnica are its people.',
        art: 'http://mythicspoiler.com/rna/cards/rallytobattle.jpg'
      },
      {
        name: 'Resolute Watchdog',
        set: 'Ravnica Allegiance',
        cost: '1',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Hound',
        rarity: 'Uncommon',
        effects: 'Defender\n{1}, Sacrifice Resolute Watchdog: Target creature you control gains indestructible until end of turn. (Damage and effects that say "destroy" don\'t destroy it.)',
        flavor: 'A friend in good times, a guardian in bad times, and a savior when all else fails.',
        power: '1',
        toughness: '3',
        art: 'http://mythicspoiler.com/rna/cards/resolutewatchdog.jpg'
      },
      {
        name: 'Sentinel\'s Mark',
        set: 'Ravnica Allegiance',
        cost: '2',
        color: 'White',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Uncommon',
        effects: 'Flash\nEnchant creature\nEnchanted creature gets +1/+2 and has vigilance.\nAddendum -- When Sentinel\'s Mark enters the battlefield, if you cast it during your main phase, enchanted creature gains lifelink until end of turn.',
        art: 'http://mythicspoiler.com/rna/cards/sentinelsmark.jpg'
      },
      {
        name: 'Sky Tether',
        set: 'Ravnica Allegiance',
        cost: '1',
        color: 'White',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Uncommon',
        effects: 'Enchant creature\nEnchanted creature has defender and loses flying.',
        flavor: '"If you can\'t control your mount, I\'ll control it for you."\n--Mirela, Azorius hussar',
        art: 'http://mythicspoiler.com/rna/cards/skytether.jpg'
      },
      {
        name: 'Smothering Tithe',
        set: 'Ravnica Allegiance',
        cost: '4',
        color: 'White',
        supertype: 'Enchantment',
        rarity: 'Rare',
        effects: 'Whenever an opponent draws a card, that player may pay {2}.  If the player doesn\'t, you create a colorless Treasure artifact token with "{T}, Sacrifice this artifact: Add one mana of any color."',
        flavor: '"I await your donation."\n--Dasha, Orzhov priest',
        art: 'http://mythicspoiler.com/rna/cards/smotheringtithe.jpg'
      },
      {
        name: 'Spirit of the Spires',
        set: 'Ravnica Allegiance',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Spirit',
        rarity: 'Uncommon',
        effects: 'Flying\nOther creatures you control with flying get +0/+1.',
        flavor: 'She breathes fair winds to tired griffins and lifts songbirds beyond the reach of stalking cats.',
        power: '2',
        toughness: '4',
        art: 'http://mythicspoiler.com/rna/cards/spiritofthespires.jpg'
      },
      {
        name: 'Summary Judgment',
        set: 'Ravnica Allegiance',
        cost: '2',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Summary Judgment deals 3 damage to target tapped creature.\nAddendum -- If you cast this spell during your main phase, it deals 5 damage to that creature instead.',
        flavor: 'Any challenge to Azorius authority is met with swift and potent retribution.',
        art: 'http://mythicspoiler.com/rna/cards/summaryjudgment.jpg'
      },
      {
        name: 'Syndicate Messenger',
        set: 'Ravnica Allegiance',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Bird',
        rarity: 'Common',
        effects: 'Flying\nAfterlife 1 (When this creature dies, create a 1/1 white and black Spirit creature token with flying.)',
        flavor: '"Many wings haunt the skies these days.  Few of them bring good tidings."\n--Lavinia',
        power: '2',
        toughness: '3',
        art: 'http://mythicspoiler.com/rna/cards/syndicatemessenger.jpg'
      },
      {
        name: 'Tenth District Veteran',
        set: 'Ravnica Allegiance',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Common',
        effects: 'Vigilance\nWhenever Tenth District Veteran attacks, untap another target creature you control.',
        flavor: '"I keep reminding myself we do this because others can\'t, because we love this city.  If we don\'t save it, no one will."',
        power: '2',
        toughness: '3',
        art: 'http://mythicspoiler.com/rna/cards/tenthdistrictveteran.jpg'
      },
      {
        name: 'Tithe Taker',
        set: 'Ravnica Allegiance',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Rare',
        effects: 'During your turn, spells your opponents cast cost {1} more to cast and abilities your opponents activate cost {1} more to activate unless they\'re mana abilities.\nAfterlife 1 (When this creature dies, create a 1/1 white and black Spirit creature token with flying.)',
        power: '2',
        toughness: '1',
        art: 'http://mythicspoiler.com/rna/cards/tithetaker.jpg'
      },
      {
        name: 'Twilight Panther',
        set: 'Ravnica Allegiance',
        cost: '1',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Cat Spirit',
        rarity: 'Common',
        effects: '{B}: Twilight Panther gains deathtouch until end of turn.',
        flavor: 'A pet that can hunt both flesh and spirit is precious in a place where smiling assassins keep company with ghostly shadows.',
        power: '1',
        toughness: '2',
        art: 'http://mythicspoiler.com/rna/cards/twilightpanther.jpg'
      },
      {
        name: 'Unbreakable Formation',
        set: 'Ravnica Allegiance',
        cost: '3',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Rare',
        effects: 'Creatures you control gain indestructible until end of turn.\nAddendum -- If you cast this spell during your main phase, put a +1/+1 counter on each of those creatures and they gain vigilance until end of turn.',
        art: 'http://mythicspoiler.com/rna/cards/unbreakableformation.jpg'
      },
      {
        name: 'Watchful Giant',
        set: 'Ravnica Allegiance',
        cost: '6',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Giant Soldier',
        rarity: 'Common',
        effects: 'When Watchful Giant enters the battlefield, create a 1/1 white Human creature token.',
        flavor: 'Loitering is not only illegal but unwise, since those who stay too long in one place are apt to be stepped on.',
        power: '3',
        toughness: '6',
        art: 'http://mythicspoiler.com/rna/cards/watchfulgiant.jpg'
      },
      {
        name: '',
        set: 'Ravnica Allegiance',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
    ]);
  });
};