exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('Card_List').del()
  .then(function () {
    // Inserts seed entries
    return knex('Card_List').insert([
      {
        name: 'Karn, the Great Creator',
        set: 'War of the Spark',
        cost: '4',
        color: 'Colorless',
        supertype: 'Legendary Planeswalker',
        subtype: 'Karn',
        rarity: 'Rare',
        effects: 'Activated abilities of artifacts your opponents control can\'t be activated.\n+1: Until your next turn, up to one target noncreature artifact becomes an artifact creature with power and toughness each equal to its converted mana cost.\n-2: You may choose an artifact card from outside the game or in exile, reveal that card, and put it into your hand.',
        loyalty: '5',
        art: 'http://mythicspoiler.com/war/cards/karnthegreatcreator2.jpg'
      },
      {
        name: 'Ugin, the Ineffable',
        set: 'War of the Spark',
        cost: '6',
        color: 'Colorless',
        supertype: 'Legendary Planeswalker',
        subtype: 'Ugin',
        rarity: 'Rare',
        effects: 'Colorless spells you cast cost {2} less to cast.\n+1: Exile the top card of your library face down and look at it.  Create a 2/2 colorless Spirit creature token.  When that token leaves the battlefield, put the exiled card into your hand.\n-3: Destroy target permanent that\'s one or more colors.',
        loyalty: '4',
        art: 'http://mythicspoiler.com/war/cards/ugintheineffable2.jpg'
      },
      {
        name: 'Ugin\'s Conjurant',
        set: 'War of the Spark',
        cost: 'X',
        color: 'Colorless',
        supertype: 'Creature',
        subtype: 'Spirit Monk',
        rarity: 'Uncommon',
        effects: 'Ugin\'s Conjurant enters the battlefield with X +1/+1 counters on it.\nIf damage would be dealt to Ugin\'s Conjurant while it has a +1/+1 counter on it, prevent that damage and remove that many +1/+1 counters from Ugin\'s Conjurant.',
        power: '0',
        toughness: '0',
        art: 'http://mythicspoiler.com/war/cards/uginsconjurant.jpg'
      },
      {
        name: 'Ajani\'s Pridemate',
        set: 'War of the Spark',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Cat Soldier',
        rarity: 'Uncommon',
        effects: 'Whenever you gain life, put a +1/+1 counter on Ajani\'s Pridemate.',
        flavor: 'Planeswalkers conjured replicas of old allies, reminders of the homeworlds that would fall next if Bolas prevailed.',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/war/cards/ajanispridemate.jpg'
      },
      {
        name: 'Battlefield Promotion',
        set: 'War of the Spark',
        cost: '2',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Put a +1/+1 counter on target creature.  That creature gains first strike until end of turn.  You gain 2 life.',
        flavor: '"Welcome to the Legion.  You saved a district--now let\'s go save the world."',
        art: 'http://mythicspoiler.com/war/cards/battlefieldpromotion.jpg'
      },
      {
        name: 'Bond of Discipline',
        set: 'War of the Spark',
        cost: '5',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Uncommon',
        effects: 'Tap all creatures your opponents control.  Creatures you control gain lifelink until end of turn.',
        flavor: '"We agree that order benefits everyone, but not until you enforce it."',
        art: 'http://mythicspoiler.com/war/cards/bondofdiscipline.jpg'
      },
      {
        name: 'Bulwark Giant',
        set: 'War of the Spark',
        cost: '6',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Giant Soldier',
        rarity: 'Common',
        effects: 'When Bulwark Giant enters the battlefield, you gain 5 life.',
        flavor: '"Where did she come from?  More importantly, are there more like her?"\n--Gideon Jura',
        power: '3',
        toughness: '6',
        art: 'http://mythicspoiler.com/war/cards/bulwarkgiant.jpg'
      },
      {
        name: 'Charmed Stray',
        set: 'War of the Spark',
        cost: '1',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Cat',
        rarity: 'Common',
        effects: 'Lifelink\nWhen Charmed Stray enters the battlefield, put a +1/+1 counter on each other creature you control named Charmed Stray.',
        flavor: '"There\'s something peculiar about the cats today."\n--Janoc, Tin Street tinker',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/war/cards/charmedstray.jpg'
      },
      {
        name: 'Defiant Strike',
        set: 'War of the Spark',
        cost: '1',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Target creature gets +1/+0 until end of turn.\nDraw a card.',
        flavor: '"My family was saved thanks to a single Boros soldier.  It\'s why I joined the Legion.  I will be the protector now."',
        art: 'http://mythicspoiler.com/war/cards/defiantstrike.jpg'
      },
      {
        name: 'Divine Arrow',
        set: 'War of the Spark',
        cost: '2',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Divine Arrow deals 4 damage to target attacking or blocking creature.',
        flavor: 'Ravnica\'s defenders watched in horror as Oketra\'s shot pierced the body of the pegasus.  Gideon tumbled through the air, Blackblade in hand.',
        art: 'http://mythicspoiler.com/war/cards/divinearrow.jpg'
      },
      {
        name: 'Enforcer Griffin',
        set: 'War of the Spark',
        cost: '5',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Griffin',
        rarity: 'Common',
        effects: 'Flying',
        flavor: '"A company of infantry is trapped behind the lines.  We need to strike hard and fast to free them, or the casualties will be horrific.  Send the griffins."\n--Tajic',
        power: '3',
        toughness: '4',
        art: 'http://mythicspoiler.com/war/cards/enforcergriffin.jpg'
      },
      {
        name: 'Finale of Glory',
        set: 'War of the Spark',
        cost: '3+',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Mythic',
        effects: 'Create X 2/2 white Soldier creature tokens with vigilance.  If X is 10 or more, also create X 4/4 white Angel creature tokens with flying and vigilance.',
        flavor: 'The sky boiled over the citadel, dire and dark.  Then the angels brought the dawn.',
        art: 'http://mythicspoiler.com/war/cards/finaleofglory.jpg'
      },
      {
        name: 'Gideon Blackblade',
        set: 'War of the Spark',
        cost: '3',
        color: 'White',
        supertype: 'Legendary Planeswalker',
        subtype: 'Gideon',
        rarity: 'Mythic',
        effects: 'As long as it\'s your turn, Gideon Blackblade is a 4/4 Human Soldier creature with indestructible that\'s still a planeswalker.\nPrevent all damage that would be dealt to Gideon Blackblade during your turn.\n+1: Up to one target creature gets your choice of vigilance, lifelink, or indestructible until end of turn.\n-6: Exile target nonland permanent.',
        loyalty: '4',
        art: 'http://mythicspoiler.com/war/cards/gideonblackblade2.jpg'
      },
      {
        name: 'Gideon\'s Sacrifice',
        set: 'War of the Spark',
        cost: '1',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Choose a creature or planeswalker you control.  All damage that would be dealt to you and permanents you control is dealt to the chosen permanent instead (if it\'s still on the battlefield).',
        flavor: 'To Liliana\'s surprise, the cost of betraying Bolas did not fall on her.',
        art: 'http://mythicspoiler.com/war/cards/gideonssacrifice.jpg'
      },
      {
        name: 'Gideon\'s Triumph',
        set: 'War of the Spark',
        cost: '2',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'Target opponent sacrifices a creature that attacked or blocked this turn.  If you control a Gideon planeswalker, that player sacrifices two of those creatures instead.',
        flavor: 'His triumph came not from victory over his enemies, but from the salvation of those who survived.',
        art: 'http://mythicspoiler.com/war/cards/gideonstriumph.jpg'
      },
      {
        name: 'God-Eternal Oketra',
        set: 'War of the Spark',
        cost: '5',
        color: 'White',
        supertype: 'Legendary Creature',
        subtype: 'Zombie God',
        rarity: 'Mythic',
        effects: 'Double strike\nWhenever you cast a creature spell, create a 4/4 black Zombie Warrior creature token with vigilance.\nWhen God-Eternal Oketra dies or is put into exile from the battlefield, you may put it into its owner\'s library third from the top.',
        power: '3',
        toughness: '6',
        art: 'http://mythicspoiler.com/war/cards/godeternaloketra.jpg'
      },
      {
        name: 'Grateful Apparition',
        set: 'War of the Spark',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Spirit',
        rarity: 'Uncommon',
        effects: 'Flying\nWhenever Grateful Apparition deals combat damage to a player or planeswalker, proliferate. (Choose any number of permanents and/or players, then give each another counter of each kind already there.)',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/war/cards/gratefulapparition.jpg'
      },
      {
        name: 'Ignite the Beacon',
        set: 'War of the Spark',
        cost: '5',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Rare',
        effects: 'Search your library for up to two planeswalker cards, reveal them, put them into your hand, then shuffle your library.',
        flavor: '"If you can\'t save yourself, you fight to give someone else a chance."\n--Ajani Goldmane',
        art: 'http://mythicspoiler.com/war/cards/ignitethebeacon.jpg'
      },
      {
        name: 'Ironclad Krovod',
        set: 'War of the Spark',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Beast',
        rarity: 'Common',
        flavor: '"We need to block the exits from the plaza!  What\'s big, heavy, and available?"\n--Gideon Jura',
        power: '2',
        toughness: '5',
        art: 'http://mythicspoiler.com/war/cards/ironcladkrovod.jpg'
      },
      {
        name: 'Law-Rune Enforcer',
        set: 'War of the Spark',
        cost: '1',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Common',
        effects: '{1}, {T}: Tap target creature with converted mana cost 2 or greater.',
        flavor: '"See that no one enters or leaves New Prahv today.  And notify me at once of any planeswalker activity."\n--Dovin Baan',
        power: '1',
        toughness: '2',
        art: 'http://mythicspoiler.com/war/cards/lawruneenforcer.jpg'
      },
      {
        name: 'Loxodon Sergeant',
        set: 'War of the Spark',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Elephant Soldier',
        rarity: 'Common',
        effects: 'Vigilance\nWhen Loxodon Sergeant enters the battlefield, other creatures you control gain vigilance until end of turn.',
        flavor: 'His voice is both war horn and rallying cry, a trumpeting call that stirs even the faintest heart.',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/war/cards/loxodonsergeant.jpg'
      },
      {
        name: 'Makeshift Battalion',
        set: 'War of the Spark',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Common',
        effects: 'Whenever Makeshift Battalion and at least two other creatures attack, put a +1/+1 counter on Makeshift Battalion.',
        flavor: 'Their ranks are thin, their formation is improvised, their weapons are borrowed, and you\'d best get out of their way.',
        power: '3',
        toughness: '2',
        art: 'http://mythicspoiler.com/war/cards/makeshiftbattalion.jpg'
      },
      {
        name: 'Martyr for the Cause',
        set: 'War of the Spark',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Common',
        effects: 'When Martyr for the Cause dies, proliferate. (Choose any number of permanents and/or players, then give each another counter of each kind already there.)',
        flavor: '"If I am to die in service, there is no more worthy fight than this."',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/war/cards/martyrforthecause.jpg'
      },
      {
        name: 'Parhelion II',
        set: 'War of the Spark',
        cost: '8',
        color: 'White',
        supertype: 'Legendary Artifact',
        subtype: 'Vehicle',
        rarity: 'Rare',
        effects: 'Flying, first strike, vigilance\nWhenever Parhelion II attacks, create two 4/4 white Angel creature tokens with flying and vigilance that are attacking.\nCrew 4 (Tap any number of creatures you control with total power 4 or more: This Vehicle becomes an artifact creature until end of turn.)',
        power: '5',
        toughness: '5',
        art: 'http://mythicspoiler.com/war/cards/parhelionii.jpg'
      },
      {
        name: 'Pouncing Lynx',
        set: 'War of the Spark',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Cat',
        rarity: 'Common',
        effects: 'As long as it\'s your turn, Pouncing Lynx has first strike.',
        flavor: '"I don\'t understand.  He\'s normally so well-behaved!"',
        power: '2',
        toughness: '1',
        art: 'http://mythicspoiler.com/war/cards/pouncinglynx.jpg'
      },
      {
        name: 'Prison Realm',
        set: 'War of the Spark',
        cost: '3',
        color: 'White',
        supertype: 'Enchantment',
        rarity: 'Uncommon',
        effects: 'When Prison Realm enters the battlefield, exile target creature or planeswalker an opponent controls until Prison Realm leaves the battlefield.\nWhen Prison Realm enters the battlefield, scry 1.',
        flavor: 'After millennia to craft victory, Bolas had eternity to contemplate defeat.',
        art: 'http://mythicspoiler.com/war/cards/prisonrealm.jpg'
      },
      {
        name: 'Rally of Wings',
        set: 'War of the Spark',
        cost: '2',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'Untap all creatures you control.  Creatures you control with flying get +2/+2 until end of turn.',
        flavor: 'Even the clouds became a field of battle.  Known as the Sky Theater, it saw the Eternals clash with squadrons of angels.',
        art: 'http://mythicspoiler.com/war/cards/rallyofwings.jpg'
      },
      {
        name: 'Ravnica at War',
        set: 'War of the Spark',
        cost: '4',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Rare',
        effects: 'Exile all multicolored permanents.',
        flavor: 'The heart of Ravnica disappeared before anyone could strike a blow in its defense.',
        art: 'http://mythicspoiler.com/war/cards/ravnicaatwar.jpg'
      },
      {
        name: 'Rising Populace',
        set: 'War of the Spark',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human',
        rarity: 'Common',
        effects: 'Whenever another creature or planeswalker dies, put a +1/+1 counter on Rising Populace.',
        flavor: 'Grief is a crucible where resolve is tempered.',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/war/cards/risingpopulace.jpg'
      },
      {
        name: 'Single Combat',
        set: 'War of the Spark',
        cost: '5',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Rare',
        effects: 'Each player chooses a creature or planeswalker they control, then sacrifices the rest.  Players can\'t cast creature or planeswalker spells until the end of your next turn.',
        flavor: 'Not even a threat to the entire Multiverse could persuade them to put aside their feud.',
        art: 'http://mythicspoiler.com/war/cards/singlecombat.jpg'
      },
      {
        name: 'Sunblade Angel',
        set: 'War of the Spark',
        cost: '6',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Angel',
        rarity: 'Uncommon',
        effects: 'Flying, first strike, vigilance, lifelink',
        flavor: 'At Feather\'s command, squadrons of battle angels swarmed out of the Parhelion II, unsheathing blades made of molten dawn.',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/war/cards/sunbladeangel.jpg'
      },
      {
        name: 'Teyo, the Shieldmage',
        set: 'War of the Spark',
        cost: '3',
        color: 'White',
        supertype: 'Legendary Planeswalker',
        subtype: 'Teyo',
        rarity: 'Uncommon',
        effects: 'You have hexproof. (You can\'t be the target of spells or abilities your opponents control.)\n-2: Create a 0/3 white Wall creature token with defender.',
        loyalty: '5',
        art: 'http://mythicspoiler.com/war/cards/teyotheshieldmage2.jpg'
      },
      {
        name: 'Teyo\'s Lightshield',
        set: 'War of the Spark',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Illusion',
        rarity: 'Common',
        effects: 'When Teyo\'s Lightshield enters the battlefield, put a +1/+1 counter on target creature you control.',
        flavor: 'Teyo gifted his shields to as many allies as possible, knowing he could not always be there to protect them himself.',
        power: '0',
        toughness: '3',
        art: 'http://mythicspoiler.com/war/cards/teyoslightshield.jpg'
      },
      {
        name: 'Tomik, Distinguished Advokist',
        set: 'War of the Spark',
        cost: '2',
        color: 'White',
        supertype: 'Legendary Creature',
        subtype: 'Human Advisor',
        rarity: 'Rare',
        effects: 'Flying\nLands on the battlefield and lands in graveyards can\'t be the target of spells or abilities your opponents control.\nYour opponents can\'t play lands from graveyards.',
        flavor: '"Some bend the law.  I tie it into knots."',
        power: '2',
        toughness: '3',
        art: 'http://mythicspoiler.com/war/cards/tomikdistinguishedadvokist.jpg'
      },
      {
        name: 'Topple the Statue',
        set: 'War of the Spark',
        cost: '3',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Tap target permanent.  If it\'s an artifact, destroy it.\nDraw a card.',
        flavor: 'Bolas cared little when his statue fell, thinking it a useful distraction, underestimating the surge of resolve it gave his opponents.',
        art: 'http://mythicspoiler.com/war/cards/topplethestatue.jpg'
      },
      {
        name: 'Trusted Pegasus',
        set: 'War of the Spark',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Pegasus',
        rarity: 'Common',
        effects: 'Flying\nWhenever Trusted Pegasus attacks, target attacking creature without flying gains flying until end of turn.',
        flavor: '"Would you give your life to save this world?" Gideon murmured.  The pegasus snorted and spread wide its mighty wings.',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/war/cards/trustedpegasus.jpg'
      },
      {
        name: 'The Wanderer',
        set: 'War of the Spark',
        cost: '4',
        color: 'White',
        supertype: 'Legendary Planeswalker',
        rarity: 'Uncommon',
        effects: 'Prevent all noncombat damage that would be dealt to you and other permanents you control.\n-2: Exile target creature with power 4 or greater.',
        loyalty: '5',
        art: 'http://mythicspoiler.com/war/cards/thewanderer2.jpg'
      },
      {
        name: 'Wanderer\'s Strike',
        set: 'War of the Spark',
        cost: '5',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'Exile target creature, then proliferate. (Choose any number of permanents and/or players, then give each another counter of each kind already there.)',
        flavor: '"Precise, clean cuts.  No one saw anything.  Again.  Tag the report with my code and file it."\n--Lavinia',
        art: 'http://mythicspoiler.com/war/cards/wanderersstrike.jpg'
      },
      {
        name: 'War Screecher',
        set: 'War of the Spark',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Bird',
        rarity: 'Common',
        effects: 'Flying\n{5W}, {T}: Other creatures you control get +1/+1 until end of turn.',
        flavor: 'Soaring over Vitu-Ghazi, New Prahv, and Orzhova, the Conclave\'s trained falcons provided critical intelligence.',
        power: '1',
        toughness: '3',
        art: 'http://mythicspoiler.com/war/cards/warscreecher.jpg'
      },
      {
        name: 'Ashiok\'s Skulker',
        set: 'War of the Spark',
        cost: '5',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Nightmare',
        rarity: 'Common',
        effects: '{3U}: Ashiok\'s Skulker can\'t be blocked this turn.',
        flavor: '"Fear writhes and whispers in the shadows of your mind.  It is the enemy you always knew would come."\n--Ashiok',
        power: '3',
        toughness: '5',
        art: 'http://mythicspoiler.com/war/cards/ashioksskulker.jpg'
      },
      {
        name: 'Augur of Bolas',
        set: 'War of the Spark',
        cost: '2',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Merfolk Wizard',
        rarity: 'Uncommon',
        effects: 'When Augur of Bolas enters the battefield, look at the top three cards of your library.  You may reveal an instant or sorcery card from among them and put it into your hand.  Put the rest on the bottom of your library in any order.',
        flavor: '"There is no future save the one my master wills."',
        power: '1',
        toughness: '3',
        art: 'http://mythicspoiler.com/war/cards/augurofbolas.jpg'
      },
      {
        name: 'Aven Eternal',
        set: 'War of the Spark',
        cost: '3',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Zombie Bird Warrior',
        rarity: 'Common',
        effects: 'Flying\nWhen Aven Eternal enters the battlefield, amass 1. (Put a +1/+1 counter on an Army you control.  If you don\'t control one, create a 0/0 black Zombie Army creature token first.)',
        flavor: '"I\'ve never seen the firemane angels this anxious."\n--Tajic',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/war/cards/aveneternal.jpg'
      },
      {
        name: 'Bond of Insight',
        set: 'War of the Spark',
        cost: '4',
        color: 'Blue',
        supertype: 'Sorcery',
        rarity: 'Uncommon',
        effects: 'Each player puts the top four cards of their library into their graveyard.  Return up to two instant and/or sorcery cards from your graveyard to your hand.  Exile Bond of Insight.',
        flavor: '"Together we can unlock secrets no one has even dreamed of.  I might even let you remember some of them."',
        art: 'http://mythicspoiler.com/war/cards/bondofinsight.jpg'
      },
      {
        name: 'Callous Dismissal',
        set: 'War of the Spark',
        cost: '2',
        color: 'Blue',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'Return target nonland permanent to its owner\'s hand.\nAmass 1. (Put a +1/+1 counter on an Army you control.  If you don\'t control one, create a 0/0 black Zombie Army creature token first.)',
        flavor: '"They make it clear we are nothing to them."\n--Lavinia',
        art: 'http://mythicspoiler.com/war/cards/callousdismissal.jpg'
      },
      {
        name: 'Commence the Endgame',
        set: 'War of the Spark',
        cost: '6',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Rare',
        effects: 'This spell can\'t be countered.\nDraw two cards, then amass X, where X is the number of cards in your hand. (Put X +1/+1 counters on an Army you control.  If you don\'t control one, create a 0/0 black Zombie Army creature token first.)',
        flavor: '"Even gods shall kneel."\n--Nicol Bolas',
        art: 'http://mythicspoiler.com/war/cards/commencetheendgame.jpg'
      },
      {
        name: 'Contentious Plan',
        set: 'War of the Spark',
        cost: '2',
        color: 'Blue',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'Proliferate. (Choose any number of permanents and/or players, then give each another counter of each kind already there.)\nDraw a card.',
        flavor: 'Niv-Mizzet had perfected a plan, but he had no control over the mortal minds who had to agree to implement it.',
        art: 'http://mythicspoiler.com/war/cards/contentiousplan.jpg'
      },
      {
        name: 'Crush Dissent',
        set: 'War of the Spark',
        cost: '4',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Counter target spell unless its controller pays {2}.\nAmass 2. (Put two +2/+1 counters on an Army you control.  If you don\'t control one, create a 0/0 black Zombie Army creature token first.)',
        flavor: '"All I ask is complete obedience."\n--Nicol Bolas',
        art: 'http://mythicspoiler.com/war/cards/crushdissent.jpg'
      },
      {
        name: 'Erratic Visionary',
        set: 'War of the Spark',
        cost: '2',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Human Wizard',
        rarity: 'Common',
        effects: '{1U}, {T}: Draw a card, then discard a card.',
        flavor: 'An Izzet experiment begins with a "what if," gets approved with a "why not," and concludes with a "eureka!"',
        power: '1',
        toughness: '3',
        art: 'http://mythicspoiler.com/war/cards/erraticvisionary.jpg'
      },
      {
        name: 'Eternal Skylord',
        set: 'War of the Spark',
        cost: '5',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Zombie Wizard',
        rarity: 'Uncommon',
        effects: 'When Eternal Skylord enters the battlefield, amass 2. (Put two +1/+1 counters on an Army you control.  If you don\'t control one, create a 0/0 black Zombie Army creature token first.)\nZombie tokens you control have flying.',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/war/cards/eternalskylord.jpg'
      },
      {
        name: 'Fblthp, the Lost',
        set: 'War of the Spark',
        cost: '2',
        color: 'Blue',
        supertype: 'Legendary Creature',
        subtype: 'Homunculus',
        rarity: 'Rare',
        effects: 'When Fblthp, the Lost enters the battlefield, draw a card.  If it entered from your library or was cast from your library, draw two cards instead.\nWhen Fblthp becomes the target of a spell, shuffle Fblthp into its owner\'s library.',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/war/cards/fblthpthelost.jpg'
      },
      {
        name: 'Finale of Revelation',
        set: 'War of the Spark',
        cost: '3+',
        color: 'Blue',
        supertype: 'Sorcery',
        rarity: 'Mythic',
        effects: 'Draw X cards.  If X is 10 or more, shuffle your graveyard into your library, draw X cards, and you have no maximum hand size for the rest of the game.\nExile Finale of Revelation.',
        flavor: 'Ugin saw the gem that connected Bolas to his Meditation Realm as the key to his brother\'s downfall.',
        art: 'http://mythicspoiler.com/war/cards/finaleofrevelation.jpg'
      },
      {
        name: 'Flux Channeler',
        set: 'War of the Spark',
        cost: '3',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Human Wizard',
        rarity: 'Uncommon',
        effects: 'Whenever you cast a noncreature spell, proliferate. (Choose any number of permanents and/or players, then give each another counter of each kind already there.)',
        flavor: '"Inform our allies in the Tenth and throw the circuit.  It\'s about to get weird."',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/war/cards/fluxchanneler.jpg'
      },
      {
        name: 'God-Eternal Kefnet',
        set: 'War of the Spark',
        cost: '4',
        color: 'Blue',
        supertype: 'Legendary Creature',
        subtype: 'Zombie God',
        rarity: 'Mythic',
        effects: 'Flying\nYou may reveal the first card you draw each turn as you draw it.  Whenever you reveal an instant or sorcery card this way, copy that card and you may cast the copy.  That copy costs {2} less to cast.\nWhen God-Eternal Kefnet dies or is put into exile from the battlefield, you may return it to its owner\'s library third from the top.',
        power: '4',
        toughness: '5',
        art: 'http://mythicspoiler.com/war/cards/godeternalkefnet.jpg'
      },
      {
        name: 'Jace, Wielder of Mysteries',
        set: 'War of the Spark',
        cost: '4',
        color: 'Blue',
        supertype: 'Legendary Planeswalker',
        subtype: 'Jace',
        rarity: 'Rare',
        effects: 'If you would draw a card while your library has no cards in it, you win the game instead.\n+1: Target player puts the top two cards of their library into their graveyard.  Draw a card.\n-8: Draw seven cards.  Then if your library has no cards in it, you win the game.',
        loyalty: '4',
        art: 'http://mythicspoiler.com/war/cards/jacewielderofmysteries2.jpg'
      },
      {
        name: 'Jace\'s Triumph',
        set: 'War of the Spark',
        cost: '3',
        color: 'Blue',
        supertype: 'Sorcery',
        rarity: 'Uncommon',
        effects: 'Draw two cards.  If you control a Jace planeswalker, draw three cards instead.',
        flavor: 'His triumph was not in outsmarting Bolas\'s plan, but in understanding why ultimate power is self-defeating.',
        art: 'http://mythicspoiler.com/war/cards/jacestriumph.jpg'
      },
      {
        name: 'Kasmina, Enigmatic Mentor',
        set: 'War of the Spark',
        cost: '4',
        color: 'Blue',
        supertype: 'Legendary Planeswalker',
        subtype: 'Kasmina',
        rarity: 'Uncommon',
        effects: 'Spells your opponents cast that target a creature or planeswalker you control cost {2} more to cast.\n-2: Create a 2/2 blue Wizard creature token.  Draw a card, then discard a card.',
        loyalty: '5',
        art: 'http://mythicspoiler.com/war/cards/kasminaenigmaticmentor2.jpg'
      },
      {
        name: 'Kasmina\'s Transmutation',
        set: 'War of the Spark',
        cost: '2',
        color: 'Blue',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Common',
        effects: 'Enchant creature\nEnchanted creature loses all abilities and has base power and toughness 1/1.',
        flavor: '"Hop away now, little Eternal.  Go eat some flies."\n--Kasmina',
        art: 'http://mythicspoiler.com/war/cards/kasminastransmutation.jpg'
      },
      {
        name: 'Kiora\'s Dambreaker',
        set: 'War of the Spark',
        cost: '6',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Leviathan',
        rarity: 'Common',
        effects: 'When Kiora\'s Dambreaker enters the battlefield, proliferate. (Choose any number of permanents and/or players, then give each another counter of each kind already there.)',
        flavor: '"When your enemy flees, send the sea to pursue them."\n--Kiora',
        power: '5',
        toughness: '6',
        art: 'http://mythicspoiler.com/war/cards/kiorasdambreaker.jpg'
      },
      {
        name: 'Lazotep Plating',
        set: 'War of the Spark',
        cost: '2',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'Amass 1. (Put a +1/+1 counter on an Army you control.  If you don\'t control one, create a 0/0 black Zombie Army creature token first.)\nYou and permanents you control gain hexproof until end of turn. (You and they can\'t be the target of spells or abilities your opponents control.)',
        art: 'http://mythicspoiler.com/war/cards/lazotepplating.jpg'
      },
      {
        name: 'Naga Eternal',
        set: 'War of the Spark',
        cost: '3',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Zombie Naga',
        rarity: 'Common',
        flavor: '"I recognize that headdress.  This one was feared even by her fellow initiates."\n--Samut',
        power: '3',
        toughness: '2',
        art: 'http://mythicspoiler.com/war/cards/nagaeternal.jpg'
      },
      {
        name: 'Narset, Parter of Veils',
        set: 'War of the Spark',
        cost: '3',
        color: 'Blue',
        supertype: 'Legendary Planeswalker',
        subtype: 'Narset',
        rarity: 'Uncommon',
        effects: 'Each opponent can\'t draw more than one card each turn.\n-2: Look at the top four cards of your library.  You may reveal a noncreature, nonland card from among them and put it into your hand.  Put the rest on the bottom of your library in a random order.',
        loyalty: '5',
        art: 'http://mythicspoiler.com/war/cards/narsetparterofveils2.jpg'
      },
      {
        name: 'Narset\'s Reversal',
        set: 'War of the Spark',
        cost: '2',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Rare',
        effects: 'Copy target instant or sorcery spell, then return it to its owner\'s hand.  You may choose new targets for the copy.',
        flavor: '"In the disarray of battle, an enemy\'s attack may be your most convenient weapon."\n--Narset',
        art: 'http://mythicspoiler.com/war/cards/narsetsreversal.jpg'
      },
      {
        name: 'No Escape',
        set: 'War of the Spark',
        cost: '3',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Counter target creature or planeswalker spell.  If that spell is countered this way, exile it instead of putting it into its owner\'s graveyard.\nScry 1.',
        flavor: 'Jace surmised that they were walking into Bolas\'s trap.  He felt no joy in being right.',
        art: 'http://mythicspoiler.com/war/cards/noescape.jpg'
      },
      {
        name: 'Relentless Advance',
        set: 'War of the Spark',
        cost: '4',
        color: 'Blue',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'Amass 3. (Put three +1/+1 counters on an Army you control.  If you don\'t control one, create a 0/0 black Zombie Army creature token first.)',
        flavor: 'They approach in formation, every movement efficient and sure.  They halt, listen, and then press on in silent unison.',
        art: 'http://mythicspoiler.com/war/cards/relentlessadvance.jpg'
      },
      {
        name: 'Rescuer Sphinx',
        set: 'War of the Spark',
        cost: '4',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Sphinx',
        rarity: 'Uncommon',
        effects: 'Flying\nWhen Rescuer Sphinx enters the battlefield, you may return target nonland permanent you control to its owner\'s hand.  If you do, Rescuer Sphinx enters the battlefield with a +1/+1 counter on it.',
        flavor: '"Now, little fighter, show me you deserved this second chance."',
        power: '3',
        toughness: '2',
        art: 'http://mythicspoiler.com/war/cards/rescuersphinx.jpg'
      },
      {
        name: 'Silent Submersible',
        set: 'War of the Spark',
        cost: '2',
        color: 'Blue',
        supertype: 'Artifact',
        subtype: 'Vehicle',
        rarity: 'Rare',
        effects: 'Whenever Silent Submersible deals combat damage to a player or planeswalker, draw a card.\nCrew 2 (Tap any number of creatures you control with total power 2 or more: This Vehicle becomes an artifact creature until end of turn.)',
        power: '2',
        toughness: '3',
        art: 'http://mythicspoiler.com/war/cards/silentsubmersible.jpg'
      },
      {
        name: 'Sky Theater Strix',
        set: 'War of the Spark',
        cost: '2',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Bird',
        rarity: 'Common',
        effects: 'Flying\nWhenever you cast a noncreature spell, Sky Theater Strix gets +1/+0 until end of turn.',
        flavor: 'Courier owls joined the fray, attacking the Dreadhorde with a viciousness usually reserved for mail thieves.',
        power: '1',
        toughness: '2',
        art: 'http://mythicspoiler.com/war/cards/skytheaterstrix.jpg'
      },
      {
        name: 'Spark Double',
        set: 'War of the Spark',
        cost: '4',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Illusion',
        rarity: 'Rare',
        effects: 'You may have Spark Double enter the battlefield as a copy of a creature or planeswalker you control, except it enters with an additional +1/+1 counter on it if it\'s a creature, it enters with an additional loyalty counter on it if it\'s a planeswalker, and it isn\'t legendary if that permanent is legendary.',
        power: '0',
        toughness: '0',
        art: 'http://mythicspoiler.com/war/cards/sparkdouble.jpg'
      },
      {
        name: 'Spellkeeper Weird',
        set: 'War of the Spark',
        cost: '3',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Weird',
        rarity: 'Common',
        effects: '{2}, {T}, Sacrifice Spellkeeper Weird: Return target instant or sorcery card from your graveyard to your hand.',
        flavor: 'They worked well as a team, but they knew it couldn\'t last forever.',
        power: '1',
        toughness: '4',
        art: 'http://mythicspoiler.com/war/cards/spellkeeperweird.jpg'
      },
      {
        name: 'Stealth Mission',
        set: 'War of the Spark',
        cost: '3',
        color: 'Blue',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'Put two +1/+1 counters on target creature you control.  That creature can\'t be blocked this turn.',
        flavor: '"What they don\'t know will definitely hurt them."\n--Lazav',
        art: 'http://mythicspoiler.com/war/cards/stealthmission.jpg'
      },
      {
        name: 'Tamiyo\'s Epiphany',
        set: 'War of the Spark',
        cost: '4',
        color: 'Blue',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'Scry 4, then draw two cards.',
        flavor: 'Tamiyo wished only to observe the war, but she soon realized neutrality was not an option.',
        art: 'http://mythicspoiler.com/war/cards/tamiyosepiphany.jpg'
      },
      {
        name: 'Teferi\'s Time Twist',
        set: 'War of the Spark',
        cost: '2',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Exile target permanent you control.  Return that card to the battlefield under its owner\'s control at the beginning of the next end step.  If it enters the battlefield as a creature, it enters with an additional +1/+1 counter on it.',
        flavor: '"The safest place for you is not now."',
        art: 'http://mythicspoiler.com/war/cards/teferistimetwist.jpg'
      },
      {
        name: 'Thunder Drake',
        set: 'War of the Spark',
        cost: '4',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Elemental Drake',
        rarity: 'Common',
        effects: 'Flying\nWhenever you cast your second spell each turn, put a +1/+1 counter on Thunder Drake.',
        flavor: 'The arrival of the Planar Bridge caused eddies in the aether, creating some entirely new species while transforming others.',
        power: '2',
        toughness: '3',
        art: 'http://mythicspoiler.com/war/cards/thunderdrake.jpg'
      },
      {
        name: 'Totally Lost',
        set: 'War of the Spark',
        cost: '4',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Put target nonland permanent on top of its owner\'s library.',
        flavor: 'At least this was better than that week at the Juri Revue.',
        art: 'http://mythicspoiler.com/war/cards/totallylost.jpg'
      },
      {
        name: 'Wall of Runes',
        set: 'War of the Spark',
        cost: '1',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Wall',
        rarity: 'Common',
        effects: 'Defender\nWhen Wall of Runes enters the battlefield, scry 1.',
        flavor: '"It\'s strangely satisfying seeing an undead killing machine from another world standing befuddled in front of a wall of text."\n--Lavinia',
        power: '0',
        toughness: '4',
        art: 'http://mythicspoiler.com/war/cards/wallofrunes.jpg'
      },
      {
        name: '',
        set: 'War of the Spark',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
    ]);
  });
};