exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('Card_List').del()
  .then(function () {
    // Inserts seed entries
    return knex('Card_List').insert([
      {
        name: 'Aerial Assault',
        set: 'Core Set 2020',
        cost: '3',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'Destroy target tapped creature.  You gain 1 life for each creature you control with flying.',
        flavor: '"Oh, you must be mistaken.  Hawks are solitary hunters, you see."\n--Bunder Diedreck, ornithologist',
        art: 'http://mythicspoiler.com/m20/cards/aerialassault.jpg'
      },
      {
        name: 'Ajani, Strength of the Pride',
        set: 'Core Set 2020',
        cost: '4',
        color: 'White',
        supertype: 'Legendary Planeswalker',
        subtype: 'Ajani',
        rarity: 'Mythic',
        effects: '+1: You gain life equal to the number of creatures you control plus the number of planeswalkers you control.\n-2: Create a 2/2 white Cat Soldier creature token named Ajani\'s Pridemate with "Whenever you gain life, put a +1/+1 counter on Ajani\'s Pridemate."\n0: If you have at least 15 life more than your starting life total, exile Ajani, Strength of the Pride and each artifact and creature your opponents control.',
        loyalty: '5',
        art: 'http://mythicspoiler.com/m20/cards/ajanistrengthofthepride.jpg'
      },
      {
        name: 'Ancestral Blade',
        set: 'Core Set 2020',
        cost: '2',
        color: 'White',
        supertype: 'Artifact',
        subtype: 'Equipment',
        rarity: 'Uncommon',
        effects: 'When Ancestral Blade enters the battlefield, create a 1/1 white Soldier creature token, then attach Ancestral Blade to it.\nEquipped creature gets +1/+1.\nEquip {1} ({1}: Attach to target creature you control.  Equip only as a sorcery.)',
        art: 'http://mythicspoiler.com/m20/cards/ancestralblade.jpg'
      },
      {
        name: 'Angel of Vitality',
        set: 'Core Set 2020',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Angel',
        rarity: 'Uncommon',
        effects: 'Flying\nIf you would gain life, you gain that much life plus 1 instead.\nAngel of Vitality gets +2/+2 as long as you have 25 or more life.',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/m20/cards/angelofvitality.jpg'
      },
      {
        name: 'Angelic Gift',
        set: 'Core Set 2020',
        cost: '2',
        color: 'White',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Common',
        effects: 'Enchant creature\nWhen Angelic Gift enters the battlefield, draw a card.\nEnchanted creature has flying.',
        art: 'http://mythicspoiler.com/m20/cards/angelicgift.jpg'
      },
      {
        name: 'Apostle of Purifying Light',
        set: 'Core Set 2020',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Cleric',
        rarity: 'Uncommon',
        effects: 'Protection from black (This creature can\'t be blocked, targeted, dealt damage, enchanted, or equipped by anything black.)\n{2}: Exile target card from a graveyard.',
        flavor: 'Waves of gloom crash in vain against his unyielding light.',
        power: '2',
        toughness: '1',
        art: 'http://mythicspoiler.com/m20/cards/apostleofpurifyinglight.jpg'
      },
      {
        name: 'Battalion Foot Soldier',
        set: 'Core Set 2020',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Common',
        effects: 'When Battalion Foot Soldier enters the battlefield, you may search your library for any number of cards named Battalion Foot Soldier, reveal them, put them into your hand, then shuffle your library.',
        flavor: '"With me!  Break this line and the rest will fall!"',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/m20/cards/battalionfootsoldier.jpg'
      },
      {
        name: 'Bishop of Wings',
        set: 'Core Set 2020',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Cleric',
        rarity: 'Rare',
        effects: 'Whenever an Angel enters the battlefield under your control, you gain 4 life.\nWhenever an Angel you control dies, create a 1/1 white Spirit creature token with flying.',
        flavor: '"Within every angel is a spirit of light that will fight as long as there is darkness."',
        power: '1',
        toughness: '4',
        art: 'http://mythicspoiler.com/m20/cards/bishopofwings.jpg'
      },
      {
        name: 'Brought Back',
        set: 'Core Set 2020',
        cost: '2',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Rare',
        effects: 'Choose up to two target permanent cards in your graveyard that were put there from the battlefield this turn.  Return them to the battlefield tapped.',
        flavor: '"As long as your courage remains, your life will not falter."\n--Sephara, Sky\'s Blade',
        art: 'http://mythicspoiler.com/m20/cards/broughtback.jpg'
      },
      {
        name: 'Cavalier of Dawn',
        set: 'Core Set 2020',
        cost: '5',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Elemental Knight',
        rarity: 'Mythic',
        effects: 'Vigilance\nWhen Cavalier of Dawn enters the battlefield, destroy up to one target nonland permanent.  Its controller creates a 3/3 colorless Golem artifact creature token.\nWhen Cavalier of Dawn dies, return target artifact or enchantment card from your graveyard to your hand.',
        power: '4',
        toughness: '6',
        art: 'http://mythicspoiler.com/m20/cards/cavalierofdawn.jpg'
      },
      {
        name: 'Dawning Angel',
        set: 'Core Set 2020',
        cost: '5',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Angel',
        rarity: 'Uncommon',
        effects: 'Flying\nWhen Dawning Angel enters the battlefield, you gain 4 life.',
        flavor: '"As the sun rose behind the Bone Spire, an angel appeared over the charnel fields, bringing a surge of new hope."\n--Krinnea, Siege of the Bone Spire',
        power: '3',
        toughness: '2',
        art: 'http://mythicspoiler.com/m20/cards/dawningangel.jpg'
      },
      {
        name: 'Daybreak Chaplain',
        set: 'Core Set 2020',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Cleric',
        rarity: 'Common',
        effects: 'Lifelink (Damage dealt by this creature also causes you to gain that much life.)',
        flavor: '"May the light shine through me to guide the lost."',
        power: '1',
        toughness: '3',
        art: 'http://mythicspoiler.com/m20/cards/daybreakchaplain.jpg'
      },
      {
        name: 'Devout Decree',
        set: 'Core Set 2020',
        cost: '2',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Uncommon',
        effects: 'Exile target creature or planeswalker that\'s black or red.  Scry 1. (Look at the top card of your library.  You may put that card on the bottom of your library.)',
        flavor: '"It is not punishment.  I am simply making things as they should be."\n--Sephara, Sky\'s Blade',
        art: 'http://mythicspoiler.com/m20/cards/devoutdecree.jpg'
      },
      {
        name: 'Disenchant',
        set: 'Core Set 2020',
        cost: '2',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Destroy target artifact or enchantment.',
        flavor: 'Where the holy light of the angels has shone, only purity remains.',
        art: 'http://mythicspoiler.com/m20/cards/disenchant.jpg'
      },
      {
        name: 'Eternal Isolation',
        set: 'Core Set 2020',
        cost: '2',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Uncommon',
        effects: 'Put target creature with power 4 or greater on the bottom of its owner\'s library.',
        flavor: '"Well, at least it\'s a lovely view."',
        art: 'http://mythicspoiler.com/m20/cards/eternalisolation.jpg'
      },
      {
        name: 'Fencing Ace',
        set: 'Core Set 2020',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Uncommon',
        effects: 'Double strike (This creature deals both first strike and regular combat damage.)',
        flavor: '"Go find yourself a couple of friends, and bring me a blindfold.  Then we might have a fair fight."',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/m20/cards/fencingace.jpg'
      },
      {
        name: 'Gauntlets of Light',
        set: 'Core Set 2020',
        cost: '3',
        color: 'White',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Uncommon',
        effects: 'Enchant creature\nEnchanted creature gets +0/+2 and assigns combat damage equal to its toughness rather than its power.\nEnchanted creature has "{2W}: Untap this creature."',
        art: 'http://mythicspoiler.com/m20/cards/gauntletsoflight.jpg'
      },
      {
        name: 'Glaring Aegis',
        set: 'Core Set 2020',
        cost: '1',
        color: 'White',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Common',
        effects: 'Enchant creature\nWhen Glaring Aegis enters the battlefield, tap target creature an opponent controls.\nEnchanted creature gets +1/+3.',
        art: 'http://mythicspoiler.com/m20/cards/glaringaegis.jpg'
      },
      {
        name: 'Gods Willing',
        set: 'Core Set 2020',
        cost: '1',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'Target creature you control gains protection from the color of your choice until end of turn. (It can\'t be blocked, targeted, dealt damage, enchanted, or equipped by anything of that color.)\nScry 1. (Look at the top card of your library.  You may put that card on the bottom of your library.)',
        art: 'http://mythicspoiler.com/m20/cards/godswilling.jpg'
      },
      {
        name: 'Griffin Protector',
        set: 'Core Set 2020',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Griffin',
        rarity: 'Common',
        effects: 'Flying\nWhenever another creature enters the battlefield under your control, Griffin Protector gets +1/+1 until end of turn.',
        flavor: '"Here is a companion who will never falter, no matter how desperate the battle!"\n--Ajani Goldmane',
        power: '2',
        toughness: '3',
        art: 'http://mythicspoiler.com/m20/cards/griffinprotector.jpg'
      },
      {
        name: 'Griffin Sentinel',
        set: 'Core Set 2020',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Griffin',
        rarity: 'Common',
        effects: 'Flying\nVigilance (Attacking deosn\'t cause this creature to tap.)',
        flavor: 'Once a griffin sentinel adopts a territory as its own, only death can forse it to betray its post.',
        power: '1',
        toughness: '3',
        art: 'http://mythicspoiler.com/m20/cards/griffinsentinel.jpg'
      },
      {
        name: 'Hanged Executioner',
        set: 'Core Set 2020',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Spirit',
        rarity: 'Rare',
        effects: 'Flying\nWhen Hanged Executioner enters the battlefield, create a 1/1 white Spirit creature token with flying.\n{3W}, Exile Hanged Executioner: Exile target creature.',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/m20/cards/hangedexecutioner.jpg'
      },
      {
        name: 'Herald of the Sun',
        set: 'Core Set 2020',
        cost: '6',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Angel',
        rarity: 'Uncommon',
        effects: 'Flying\n{3W}: Put a +1/+1 counter on another target creature with flying.',
        flavor: '"Fear neither clouds nor darkness.  The light shall overcome them all."',
        power: '4',
        toughness: '4',
        art: 'http://mythicspoiler.com/m20/cards/heraldofthesun.jpg'
      },
      {
        name: 'Inspired Charge',
        set: 'Core Set 2020',
        cost: '4',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Creatures you control get +2/+1 until end of turn.',
        flavor: '"We are armed with light and steel.  Who can stand against us?"',
        art: 'http://mythicspoiler.com/m20/cards/inspiredcharge.jpg'
      },
      {
        name: 'Inspiring Captain',
        set: 'Core Set 2020',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Knight',
        rarity: 'Common',
        effects: 'When Inspiring Captain enters the battlefield, creatures you control get +1/+1 until end of turn',
        flavor: '"Time to show the foe our true mettle."',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/m20/cards/inspiringcaptain.jpg'
      },
      {
        name: 'Leyline of Sanctity',
        set: 'Core Set 2020',
        cost: '4',
        color: 'White',
        supertype: 'Enchantment',
        rarity: 'Rare',
        effects: 'You have hexproof. (You can\'t be the target of spells or abilities your opponents control.)',
        art: 'http://mythicspoiler.com/m20/cards/leylineofsanctity.jpg'
      },
      {
        name: 'Loxodon Lifechanter',
        set: 'Core Set 2020',
        cost: '6',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Elephant Cleric',
        rarity: 'Rare',
        effects: 'When Loxodon Lifechanter enters the battlefield, you may have your life total become the total toughness of creatures you control.\n{5W}: Loxodon Lifechanter gets +X/+X until end of turn, where X is your life total.',
        power: '4',
        toughness: '6',
        art: 'http://mythicspoiler.com/m20/cards/loxodonlifechanter.jpg'
      },
      {
        name: 'Loyal Pegasus',
        set: 'Core Set 2020',
        cost: '1',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Pegasus',
        rarity: 'Uncommon',
        effects: 'Flying\nLoyal Pegaus can\'t attack or block alone.',
        flavor: '"Even if I should die in the saddle, she will not let me fall to the ground."\n--Hypatia of the Winged Horse',
        power: '2',
        toughness: '1',
        art: 'http://mythicspoiler.com/m20/cards/loyalpegasus.jpg'
      },
      {
        name: 'Master Splicer',
        set: 'Core Set 2020',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Artificer',
        rarity: 'Uncommon',
        effects: 'When Master Splicer enters the battlefield, create a 3/3 colorless Golem creature token.\nGolems you control get +1/+1.',
        flavor: 'Phyrexian artificers remove the flesh they no longer need and use it to bring their unholy creations to a greater semblance of life.',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/m20/cards/mastersplicer.jpg'
      },
      {
        name: 'Moment of Heroism',
        set: 'Core Set 2020',
        cost: '2',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Target creature gets +2/+2 and gains lifelink until end of turn. (Damage dealt by the creature also causes you to gain that much life.)',
        flavor: '"My faith is stronger than fang, claw, or mindless hunger."',
        art: 'http://mythicspoiler.com/m20/cards/momentofheroism.jpg'
      },
      {
        name: 'Moorland Inquisitor',
        set: 'Core Set 2020',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Common',
        effects: '{2W}: Moorland Inquisitor gains first strike until end of turn. (It deals combat damage before creatures without first strike.)',
        flavor: 'Inquisitors are taught scripture, philosophy, and the fine art of sharpening an axe.',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/m20/cards/moorlandinquisitor.jpg'
      },
      {
        name: 'Pacifism',
        set: 'Core Set 2020',
        cost: '2',
        color: 'White',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Common',
        effects: 'Enchant creature\nEnchanted creature can\'t attack or block.',
        flavor: '"Can\'t a fella get a moment\'s peace around here?"',
        art: 'http://mythicspoiler.com/m20/cards/pacifism.jpg'
      },
      {
        name: 'Planar Cleansing',
        set: 'Core Set 2020',
        cost: '6',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Rare',
        effects: 'Destroy all nonland permanents.',
        art: 'http://mythicspoiler.com/m20/cards/planarcleansing.jpg'
      },
      {
        name: 'Raise the Alarm',
        set: 'Core Set 2020',
        cost: '2',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Create two 1/1 white Soldier creature tokens.',
        flavor: 'Like blinking or breathing, responding to an alarm is an involuntary reflex.',
        art: 'http://mythicspoiler.com/m20/cards/raisethealarm.jpg'
      },
      {
        name: 'Rule of Law',
        set: 'Core Set 2020',
        cost: '3',
        color: 'White',
        supertype: 'Enchantment',
        rarity: 'Uncommon',
        effects: 'Each player can\'t cast more than one spell each turn.',
        flavor: 'The law is meant to ensure that people kill each other with only the utmost fairness.',
        art: 'http://mythicspoiler.com/m20/cards/ruleoflaw.jpg'
      },
      {
        name: 'Sephara, Sky\'s Blade',
        set: 'Core Set 2020',
        cost: '7',
        color: 'White',
        supertype: 'Legendary Creature',
        subtype: 'Angel',
        rarity: 'Rare',
        effects: 'You may pay {W} and tap four untapped creatures you control with flying rather than pay this spell\'s mana cost.\nFlying, lifelink\nOther creatures you control with flying have indestructible. (Damage and effects that say "destroy don\'t destroy them.")',
        power: '7',
        toughness: '7',
        art: 'http://mythicspoiler.com/m20/cards/sepharaskysblade.jpg'
      },
      {
        name: 'Soulmender',
        set: 'Core Set 2020',
        cost: '1',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Cleric',
        rarity: 'Common',
        effects: '{T}: You gain 1 life.',
        flavor: '"Healing is more art than magic.  Well, there is still quite a bit of magic."',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/m20/cards/soulmender.jpg'
      },
      {
        name: 'Squad Captain',
        set: 'Core Set 2020',
        cost: '5',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Common',
        effects: 'Vigilance (Attacking doesn\'t cause this creature to tap.)\nSquad Captain enters the battlefield with a +1/+1 counter on it for each other creature you control.',
        flavor: 'The strength of the one is the strength of the many.',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/m20/cards/squadcaptain.jpg'
      },
      {
        name: 'Starfield Mystic',
        set: 'Core Set 2020',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Cleric',
        rarity: 'Rare',
        effects: 'Enchantment spells you cast cost {1} less to cast.\nWhenever an enchantment you control is put into a graveyard from the battlefield, put a +1/+1 counter on Starfield Mystic.',
        flavor: '"The realm of the gods opens before me!"',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/m20/cards/starfieldmystic.jpg'
      },
      {
        name: 'Steadfast Sentry',
        set: 'Core Set 2020',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Common',
        effects: 'Vigilance (Attacking doesn\'t cause this creature to tap.)\nWhen Steadfast Sentry dies, put a +1/+1 counter on target creature you control.',
        flavor: '"Get up, slugabeds!  We\'ve got company, and they\'re not dressed for a party!"',
        power: '3',
        toughness: '2',
        art: 'http://mythicspoiler.com/m20/cards/steadfastsentry.jpg'
      },
      {
        name: 'Yoked Ox',
        set: 'Core Set 2020',
        cost: '1',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Ox',
        rarity: 'Common',
        flavor: 'The courage of those who work the land is born of long days of labor in the hot summer sun and the cold winter wind.  It is the courage of the earth itself.',
        power: '0',
        toughness: '4',
        art: 'http://mythicspoiler.com/m20/cards/yokedox.jpg'
      },
      {
        name: 'Aether Gust',
        set: 'Core Set 2020',
        cost: '2',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'Choose target spell or permanent that\'s red or green.  Its owner puts it on the bottom of their library.',
        flavor: 'The chill wind extinguishes flame, and frosts the leaf on the branch.',
        art: 'http://mythicspoiler.com/m20/cards/aethergust.jpg'
      },
      {
        name: 'Agent of Treachery',
        set: 'Core Set 2020',
        cost: '7',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Human Rogue',
        rarity: 'Rare',
        effects: 'When Agent of Treachery enters the battlefield, gain control of target permanent.\nAt the beginning of your end step, if you control three or more permanents you don\'t own, draw three cards.',
        flavor: '"The more secrets you have, the more easily you become my pawn."',
        power: '2',
        toughness: '3',
        art: 'http://mythicspoiler.com/m20/cards/agentoftreachery.jpg'
      },
      {
        name: 'Air Elemental',
        set: 'Core Set 2020',
        cost: '5',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Elemental',
        rarity: 'Uncommon',
        effects: 'Flying',
        flavor: 'As the ship approached, the jade totem rose high overhead.  Power rippled.  Eyes of stone glowed and crackled.  Out hissed a breath of the world, and a windstorm came alive.',
        power: '4',
        toughness: '4',
        art: 'http://mythicspoiler.com/m20/cards/airelemental.jpg'
      },
      {
        name: 'Anticipate',
        set: 'Core Set 2020',
        cost: '2',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Look at the top three cards of your library.  Put one of them into your hand and the rest on the bottom of your library in any order.',
        flavor: 'Divining the future is easy when you hold the power to sway it.',
        art: 'http://mythicspoiler.com/m20/cards/anticipate.jpg'
      },
      {
        name: 'Atemsis, All-Seeing',
        set: 'Core Set 2020',
        cost: '6',
        color: 'Blue',
        supertype: 'Legendary Creature',
        subtype: 'Sphinx',
        rarity: 'Rare',
        effects: 'Flying\n{2U}, {T}: Draw two cards, then discard a card.\nWhenever Atemsis, All-Seeing deals damage to an opponent, you may reveal your hand.  If cards with at least six different converted mana costs are revealed this way, that player loses the game.',
        power: '4',
        toughness: '5',
        art: 'http://mythicspoiler.com/m20/cards/atemsisallseeing.jpg'
      },
      {
        name: 'Befuddle',
        set: 'Core Set 2020',
        cost: '3',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Target creature gets -4/-0 until end of turn.\nDraw a card.',
        flavor: 'The trick to talking sense into Keldons is getting them to hold still.',
        art: 'http://mythicspoiler.com/m20/cards/befuddle.jpg'
      },
      {
        name: 'Bone to Ash',
        set: 'Core Set 2020',
        cost: '4',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Counter target creature spell.\nDraw a card.',
        flavor: '"I can think of worse ways to go.  On second thought, maybe not."\n--Ludevic, necro-alchemist',
        art: 'http://mythicspoiler.com/m20/cards/bonetoash.jpg'
      },
      {
        name: 'Boreal Elemental',
        set: 'Core Set 2020',
        cost: '5',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Elemental',
        rarity: 'Common',
        effects: 'Flying\nSpells your opponents cast that target Boreal Elemental cost {2} more to cast.',
        flavor: 'Winter\'s breath given form.',
        power: '3',
        toughness: '4',
        art: 'http://mythicspoiler.com/m20/cards/borealelemental.jpg'
      },
      {
        name: 'Brineborn Cutthroat',
        set: 'Core Set 2020',
        cost: '2',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Merfolk Pirate',
        rarity: 'Uncommon',
        effects: 'Flash (You may cast this spell any time you could cast an instant.)\nWhenever you cast a spell during your opponent\'s turn, put a +1/+1 counter on Brineborn Cutthroat.',
        flavor: '"I always attack from where their spyglasses can\'t see."',
        power: '2',
        toughness: '1',
        art: 'http://mythicspoiler.com/m20/cards/brineborncutthroat.jpg'
      },
      {
        name: 'Captivating Gyre',
        set: 'Core Set 2020',
        cost: '6',
        color: 'Blue',
        supertype: 'Sorcery',
        rarity: 'Uncommon',
        effects: 'Return up to three target permanents to their owners\' hands.',
        flavor: '"That\'s enough of that."\n--Atemsis, All-Seeing',
        art: 'http://mythicspoiler.com/m20/cards/captivatinggyre.jpg'
      },
      {
        name: 'Cavalier of Gales',
        set: 'Core Set 2020',
        cost: '5',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Elemental Knight',
        rarity: 'Mythic',
        effects: 'Flying\nWhen Cavalier of Gales enters the battlefield, draw three cards, then put two cards from your hand on top of your library in any order.\nWhen Cavalier of Gales dies, shuffle it into its owner\'s library, then scry 2.',
        power: '5',
        toughness: '5',
        art: 'http://mythicspoiler.com/m20/cards/cavalierofgales.jpg'
      },
      {
        name: 'Cerulean Drake',
        set: 'Core Set 2020',
        cost: '2',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Drake',
        rarity: 'Uncommon',
        effects: 'Flying\nProtection from red (This creature can\'t be blocked, targeted, dealt damage, enchanted, or equipped by anything red.)\nSacrifice Cerulean Drake: Counter target spell that targets you.',
        flavor: 'Dragons avoid the bright colors of its wings.',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/m20/cards/ceruleandrake.jpg'
      },
      {
        name: 'Cloudkin Seer',
        set: 'Core Set 2020',
        cost: '3',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Elemental Wizard',
        rarity: 'Common',
        effects: 'Flying\nWhen Cloudkin Seer enters the battlefield, draw a card.',
        flavor: '"I can see which way the wind is blowing."',
        power: '2',
        toughness: '1',
        art: 'http://mythicspoiler.com/m20/cards/cloudkinseer.jpg'
      },
      {
        name: 'Convolute',
        set: 'Core Set 2020',
        cost: '3',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Counter target spell unless its controller pays {4}.',
        flavor: '"Let\'s see how badly you want what you came for!"',
        art: 'http://mythicspoiler.com/m20/cards/convolute.jpg'
      },
      {
        name: 'Drawn from Dreams',
        set: 'Core Set 2020',
        cost: '4',
        color: 'Blue',
        supertype: 'Sorcery',
        rarity: 'Rare',
        effects: 'Look at the top seven cards of your library.  Put two of them into your hand and the rest on the bottom of your library in a random order.',
        flavor: '"From a sea of infinite possibilities, our choices create the future."\n--Mu Yanling',
        art: 'http://mythicspoiler.com/m20/cards/drawnfromdreams.jpg'
      },
      {
        name: 'Dungeon Geists',
        set: 'Core Set 2020',
        cost: '4',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Spirit',
        rarity: 'Rare',
        effects: 'Flying\nWhen Dungeon Geists enters the battlefield, tap target creature an opponent controls.  That creature doesn\'t untap during its controller\'s untap step for as long as you control Dungeon Geists.',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/m20/cards/dungeongeists.jpg'
      },
      {
        name: 'Faerie Miscreant',
        set: 'Core Set 2020',
        cost: '1',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Faerie Rogue',
        rarity: 'Common',
        effects: 'Flying\nWhen Faerie Miscreant enters the battlefield, if you control another creature named Faerie Miscreant, draw a card.',
        flavor: 'One faerie distracts the judge while a second steals the law.',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/m20/cards/faeriemiscreant.jpg'
      },
      {
        name: 'Flood of Tears',
        set: 'Core Set 2020',
        cost: '6',
        color: 'Blue',
        supertype: 'Sorcery',
        rarity: 'Rare',
        effects: 'Return all nonland permanents to their owners\' hands.  If you return four or more permanents you control this way, you may put a permanent card from your hand onto the battlefield.',
        flavor: '"I have wept such a torrent as to scour the land clean."\n--Mu Yanling',
        art: 'http://mythicspoiler.com/m20/cards/floodoftears.jpg'
      },
      {
        name: 'Fortress Crab',
        set: 'Core Set 2020',
        cost: '4',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Crab',
        rarity: 'Common',
        flavor: 'Unbreakable and unappetizing, the crab grows uninterrupted, sometimes to the size of a cottage and beyond.',
        power: '1',
        toughness: '6',
        art: 'http://mythicspoiler.com/m20/cards/fortresscrab.jpg'
      },
      {
        name: 'Frilled Sea Serpent',
        set: 'Core Set 2020',
        cost: '6',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Serpent',
        rarity: 'Common',
        effects: '{5UU}: Frilled Sea Serpent can\'t be blocked this turn.',
        flavor: '"Reel it in.  No, wait!  Throw it back!"\nGertrude, deep-sea angler',
        power: '4',
        toughness: '6',
        art: 'http://mythicspoiler.com/m20/cards/frilledseaserpent.jpg'
      },
      {
        name: 'Frost Lynx',
        set: 'Core Set 2020',
        cost: '3',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Elemental Cat',
        rarity: 'Common',
        effects: 'When Frost Lynx enters the battlefield, tap target creature an opponent controls.  That creature doesn\'t untap during its controller\'s next untap step.',
        flavor: 'It readily attacks much larger prey, knowing retaliation is impossible.',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/m20/cards/frostlynx.jpg'
      },
      {
        name: 'Hard Cover',
        set: 'Core Set 2020',
        cost: '1',
        color: 'Blue',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Uncommon',
        effects: 'Enchant creature\nEnchanted creature gets +0/+2 and has "{T}: Draw a card, then discard a card."',
        flavor: 'A good book is a refuge, but a great book is a fortress.',
        art: 'http://mythicspoiler.com/m20/cards/hardcover.jpg'
      },
      {
        name: 'Leyline of Anticipation',
        set: 'Core Set 2020',
        cost: '4',
        color: 'Blue',
        supertype: 'Enchantment',
        rarity: 'Rare',
        effects: 'If Leyline of Anticipation is in your opening hand, you may begin the game with it on the battlefield.\nYou may cast spells as though they had flash.',
        art: 'http://mythicspoiler.com/m20/cards/leylineofanticipation.jpg'
      },
      {
        name: 'Masterful Replication',
        set: 'Core Set 2020',
        cost: '6',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Rare',
        effects: 'Choose one--\n\tCreate two 3/3 colorless Golem creature tokens.\nChoose target artifact you control.  Each other artifact you control becomes a copy of that artifact until end of turn.',
        art: 'http://mythicspoiler.com/m20/cards/masterfulreplication.jpg'
      },
      {
        name: 'Metropolis Sprite',
        set: 'Core Set 2020',
        cost: '2',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Faerie Rogue',
        rarity: 'Common',
        effects: 'Flying\n{U}: Metropolis Sprite gets +1/-1 until end of turn.',
        flavor: '"Well, if that goblin didn\'t want his tongue pierced, he shouldn\'t have stuck it out at me."',
        power: '1',
        toughness: '2',
        art: 'http://mythicspoiler.com/m20/cards/metropolissprite.jpg'
      },
      {
        name: 'Moat Piranhas',
        set: 'Core Set 2020',
        cost: '2',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Fish',
        rarity: 'Common',
        effects: 'Defender (This creature can\'t attack.)',
        flavor: '"Come on, it\'s not even that deep!"\n--Gorin the Brazen',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/m20/cards/moatpiranhas.jpg'
      },
      {
        name: 'Mu Yanling, Sky Dancer',
        set: 'Core Set 2020',
        cost: '3',
        color: 'Blue',
        supertype: 'Legendary Planeswalker',
        subtype: 'Yanling',
        rarity: 'Mythic',
        effects: '+2: Until your next turn, up to one target creature gets -2/-0 and loses flying.\n-3: Create a 4/4 blue Elemental Bird creature token.\n-8: You get an emblem with "Islands you control have \'{T}: Draw a card.\'"',
        loyalty: '2',
        art: 'http://mythicspoiler.com/m20/cards/muyanlingskydancer.jpg'
      },
      {
        name: 'Negate',
        set: 'Core Set 2020',
        cost: '2',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Counter target noncreature spell.',
        flavor: '"As one, nature lifts its voice to tell you this: \'No.\'"',
        art: 'http://mythicspoiler.com/m20/cards/negate.jpg'
      },
      {
        name: 'Octoprophet',
        set: 'Core Set 2020',
        cost: '4',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Octopus',
        rarity: 'Common',
        effects: 'When Octoprophet enters the battlefield, scry 2. (Look at the top two cards of your library, then you may put any number of them on the bottom of your library and the rest on top in any order.)',
        flavor: 'In every swirl of the tide, it sees the awakening of things to come.',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/m20/cards/octoprophet.jpg'
      },
      {
        name: 'Portal of Sanctuary',
        set: 'Core Set 2020',
        cost: '3',
        color: 'Blue',
        supertype: 'Artifact',
        rarity: 'Uncommon',
        effects: '{1}, {T}: Return target creature you control and each Aura attached to it to their owners\' hands.  Activate this ability only during your turn.',
        flavor: '"If you need to disappear for a while, I know a place."\n--Bilivus, master archivist',
        art: 'http://mythicspoiler.com/m20/cards/portalofsanctuary.jpg'
      },
      {
        name: 'Renowned Weaponsmith',
        set: 'Core Set 2020',
        cost: '2',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Human Artificer',
        rarity: 'Uncommon',
        effects: '{T}: Add {2}.  Spend this mana only to cast artifact spells or activate abilities of artifacts.\n{U}, {T}: Search your library for a card named Heart-Piercer Bow or Vial of Dragonfire, reveal it, put it into your hand, then shuffle your library.',
        power: '1',
        toughness: '3',
        art: 'http://mythicspoiler.com/m20/cards/renownedweaponsmith.jpg'
      },
      {
        name: 'Sage\'s Row Denizen',
        set: 'Core Set 2020',
        cost: '3',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Vedalken Wizard',
        rarity: 'Common',
        effects: 'Whenever another blue creature enters the battlefield under your control, target player puts the top two cards of their library into their graveyard.',
        flavor: '"Forget what you have learned from other teachers.  I bring you the truth."',
        power: '2',
        toughness: '3',
        art: 'http://mythicspoiler.com/m20/cards/sagesrowdenizen.jpg'
      },
      {
        name: 'Scholar of the Ages',
        set: 'Core Set 2020',
        cost: '7',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Human Wizard',
        rarity: 'Uncommon',
        effects: 'When Scholar of the Ages enters the battlefield, return up to two target instant and/or sorcery cards from your graveyard to your hand.',
        flavor: '"I study the past to find hope for the future."',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/m20/cards/scholaroftheages.jpg'
      },
      {
        name: 'Sleep Paralysis',
        set: 'Core Set 2020',
        cost: '4',
        color: 'Blue',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Common',
        effects: 'Enchant creature\nWhen Sleep Paralysis enters the battlefield, tap enchanted creature.\nEnchanted creature doesn\'t untap during its controller\'s untap step.',
        flavor: 'Sleep doesn\'t always mean rest.',
        art: 'http://mythicspoiler.com/m20/cards/sleepparalysis.jpg'
      },
      {
        name: 'Spectral Sailor',
        set: 'Core Set 2020',
        cost: '1',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Spirit Pirate',
        rarity: 'Uncommon',
        effects: 'Flash (You may cast this spell any time you could cast an instant.)\nFlying\n{3U}: Draw a card.',
        flavor: '"Any ship that sails these mean seas for long is bound to pick up a ghost or two."\n--Admiral Beckett Brass',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/m20/cards/spectralsailor.jpg'
      },
      {
        name: 'Tale\'s End',
        set: 'Core Set 2020',
        cost: '2',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Rare',
        effects: 'Counter target activated ability, triggered ability, or legendary spell.',
        flavor: '"When you are gone, will anyone remember your story?"\n--Unknown',
        art: 'http://mythicspoiler.com/m20/cards/talesend.jpg'
      },
      {
        name: 'Unsummon',
        set: 'Core Set 2020',
        cost: '1',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Return target creature to its owner\'s hand.',
        flavor: '"Don\'t you have somewhere else to be?"\n--Sharuum the Hegemon',
        art: 'http://mythicspoiler.com/m20/cards/unsummon.jpg'
      },
      {
        name: 'Warden of Evos Isle',
        set: 'Core Set 2020',
        cost: '3',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Bird Wizard',
        rarity: 'Uncommon',
        effects: 'Flying\nCreatures with flying you cast cost {1} less to cast.',
        flavor: 'On Evos Isle, the swift and formidable aven enforce the will of the ruling sphinxes.',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/m20/cards/wardenofevosisle.jpg'
      },
      {
        name: 'Winged Words',
        set: 'Core Set 2020',
        cost: '3',
        color: 'Blue',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'This spell costs {1} less to cast if you control a creature with flying.\nDraw two cards.',
        flavor: 'Magic written across the sky falls like rain on the thirsty ground, bringing forth wisdom in its season.',
        art: 'http://mythicspoiler.com/m20/cards/wingedwords.jpg'
      },
      {
        name: 'Yarok\'s Wavecrasher',
        set: 'Core Set 2020',
        cost: '4',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Elemental',
        rarity: 'Uncommon',
        effects: 'When Yarok\'s Wavecrasher enters the battlefield, return another creature you control to its owner\'s hand.',
        flavor: '"Yarok\'s waters rush and rage\nWhere armies bled into the sand."\n--Lament for Bala Ged, stanza 2',
        power: '4',
        toughness: '4',
        art: 'http://mythicspoiler.com/m20/cards/yarokswavecrasher.jpg'
      },
      {
        name: 'Zephyr Charge',
        set: 'Core Set 2020',
        cost: '2',
        color: 'Blue',
        supertype: 'Enchantment',
        rarity: 'Common',
        effects: '{1U}: Target creature gains flying until end of turn.',
        flavor: '"The knights charged forward on wings of wind, and the necromancer\'s horde roared in helpless rage."\n--Krinnea, Siege of the Bone Spire',
        art: 'http://mythicspoiler.com/m20/cards/zephyrcharge.jpg'
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Core Set 2020',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      }
    ]);
  });
};