exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('Card_List').del()
  .then(function () {
    // Inserts seed entries
    return knex('Card_List').insert([
      {
        name: 'Abundant Maw',
        set: 'Eldritch Moon',
        cost: '8',
        color: 'Colorless',
        supertype: 'Creature',
        subtype: 'Eldrazi Leech',
        rarity: 'Uncommon',
        effects: 'Emerge {6B} (You may cast this spell by sacrificing a creature and paying the emerge cost reduced by that creature\'s converted mana cost.)\nWhen you cast Abundant Maw, target opponent loses 3 life and you gain 3 life.',
        power: '6',
        toughness: '4',
        art: 'http://mythicspoiler.com/emn/cards/abundantmaw.jpg'
      },
      {
        name: 'Decimator of the Provinces',
        set: 'Eldritch Moon',
        cost: '10',
        color: 'Colorless',
        supertype: 'Creature',
        subtype: 'Eldrazi Boar',
        rarity: 'Mythic',
        effects: 'Emerge {6GGG} (You may cast this spell by sacrificing a creature and paying the emerge cost reduced by that creature\'s converted mana cost.)\nWhen you cast Decimator of the Provinces, creatures you control get +2/+2 and gain trample until end of turn.\nTrample, haste',
        power: '7',
        toughness: '7',
        art: 'http://mythicspoiler.com/emn/cards/decimatoroftheprovinces.jpg'
      },
      {
        name: 'Distended Mindbender',
        set: 'Eldritch Moon',
        cost: '8',
        color: 'Colorless',
        supertype: 'Creature',
        subtype: 'Eldrazi Insect',
        rarity: 'Rare',
        effects: 'Emerge {5BB} (You may cast this spell by sacrificing a creature and paying the emerge cost reduced by that creature\'s converted mana cost.)\nWhen you cast Distended Mindbender, target opponent reveals their hand.  You choose from it a nonland card with converted mana cost 3 or less and a card with converted mana cost 4 or greater.  That player discards those cards.',
        power: '5',
        toughness: '5',
        art: 'http://mythicspoiler.com/emn/cards/distendedmindbender.jpg'
      },
      {
        name: 'Drownyard Behemoth',
        set: 'Eldritch Moon',
        cost: '9',
        color: 'Colorless',
        supertype: 'Creature',
        subtype: 'Eldrazi Crab',
        rarity: 'Uncommon',
        effects: 'Flash (You may cast this spell any time you could cast an instant.)\nEmerge {7U} (You may cast this spell by sacrificing a creature and paying the emerge cost reduced by that creature\'s converted mana cost.)\nDrownyard Behemoth has hexproof as long as it entered the battlefield this turn.',
        power: '5',
        toughness: '7',
        art: 'http://mythicspoiler.com/emn/cards/drownyardbehemoth.jpg'
      },
      {
        name: 'Elder Deep-Fiend',
        set: 'Eldritch Moon',
        cost: '8',
        color: 'Colorless',
        supertype: 'Creature',
        subtype: 'Eldrazi Octopus',
        rarity: 'Rare',
        effects: 'Flash\nEmerge {5UU} (You may cast this spell by sacrificing a creature and paying the emerge cost reduced by that creature\'s converted mana cost.)\nWhen you cast Elder Deep-Fiend, tap up to four target permanents.',
        power: '5',
        toughness: '6',
        art: 'http://mythicspoiler.com/emn/cards/elderdeepfiend.jpg'
      },
      {
        name: 'Emrakul, the Promised End',
        set: 'Eldritch Moon',
        cost: '13',
        color: 'Colorless',
        supertype: 'Legendary Creature',
        subtype: 'Eldrazi',
        rarity: 'Mythic',
        effects: 'Emrakul, the Promised End costs {1} less to cast for each card type among cards in your graveyard.\nWhen you cast Emrakul, you gain control of target opponent during that player\'s next turn.  After that turn, that player takes an extra turn.\nFlying, trample, protection from instants',
        power: '13',
        toughness: '13',
        art: 'http://mythicspoiler.com/emn/cards/emrakulthepromisedend.jpg'
      },
      {
        name: 'Eternal Scourge',
        set: 'Eldritch Moon',
        cost: '3',
        color: 'Colorless',
        supertype: 'Creature',
        subtype: 'Eldrazi Horror',
        rarity: 'Rare',
        effects: 'You may cast Eternal Scourge from exile.\nWhen Eternal Scourge becomes the target of a spell or ability an opponent controls, exile Eternal Scourge.',
        flavor: '"It has latched onto this place like an infestation.  All efforts at eradication have proved futile."\n--Yeter, Trostad villager',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/emn/cards/eternalscourge.jpg'
      },
      {
        name: 'It of the Horrid Swarm',
        set: 'Eldritch Moon',
        cost: '8',
        color: 'Colorless',
        supertype: 'Creature',
        subtype: 'Eldrazi Insect',
        rarity: 'Common',
        effects: 'Emerge {6G} (You may cast this spell by sacrificing a creature and paying the emerge cost reduced by that creature\'s converted mana cost.)\nWhen you cast It of the Horrid Swarm, create two 2/2 green Insect creature tokens.',
        power: '4',
        toughness: '4',
        art: 'http://mythicspoiler.com/emn/cards/itofthehorridswarm.jpg'
      },
      {
        name: 'Lashweed Lurker',
        set: 'Eldritch Moon',
        cost: '8',
        color: 'Colorless',
        supertype: 'Creature',
        subtype: 'Eldrazi Horror',
        rarity: 'Uncommon',
        effects: 'Emerge {5GU} (You may cast this spell by sacrificing a creature and paying the emerge cost reduced by that creature\'s converted mana cost.)\nWhen you cast Lashweed Lurker, you may put target nonland permanent on top of its owner\'s library.',
        power: '5',
        toughness: '4',
        art: 'http://mythicspoiler.com/emn/cards/lashweedlurker.jpg'
      },
      {
        name: 'Mockery of Nature',
        set: 'Eldritch Moon',
        cost: '9',
        color: 'Colorless',
        supertype: 'Creature',
        subtype: 'Eldrazi Beast',
        rarity: 'Uncommon',
        effects: 'Emerge {7G} (You may cast this spell by sacrificing a creature and paying the emerge cost reduced by that creature\'s converted mana cost.)\nWhen you cast Mockery of Nature, you may destroy target artifact or enchantment.',
        power: '6',
        toughness: '5',
        art: 'http://mythicspoiler.com/emn/cards/mockeryofnature.jpg'
      },
      {
        name: 'Vexing Scuttler',
        set: 'Eldritch Moon',
        cost: '8',
        color: 'Colorless',
        supertype: 'Creature',
        subtype: 'Eldrazi Crab',
        rarity: 'Uncommon',
        effects: 'Emerge {6U} (You may cast this spell by sacrificing a creature and paying the emerge cost reduced by that creature\'s converted mana cost.)\nWhen you cast Vexing Scuttler, you may return target instant or sorcery card from your graveyard to your hand.',
        power: '4',
        toughness: '5',
        art: 'http://mythicspoiler.com/emn/cards/vexingscuttler.jpg'
      },
      {
        name: 'Wretched Gryff',
        set: 'Eldritch Moon',
        cost: '7',
        color: 'Colorless',
        supertype: 'Creature',
        subtype: 'Eldrazi Hippogriff',
        rarity: 'Common',
        effects: 'Emerge {5U} (You may cast this spell by sacrificing a creature and paying the emerge cost reduced by that creature\'s converted mana cost.)\nWhen you cast Wretched Gryff, draw a card.\nFlying',
        power: '3',
        toughness: '4',
        art: 'http://mythicspoiler.com/emn/cards/wretchedgryff.jpg'
      },
      {
        name: 'Blessed Alliance',
        set: 'Eldritch Moon',
        cost: '2',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'Escalate {2} (Pay this cost for each mode chosen beyond the first.)\nChoose one or more --\n\tTarget player gains 4 life.\n\tUntap up to two target creatures.\n\tTarget opponent sacrifices an attacking creature.',
        art: 'http://mythicspoiler.com/emn/cards/blessedalliance.jpg'
      },
      {
        name: 'Borrowed Grace',
        set: 'Eldritch Moon',
        cost: '3',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Escalate {1W} (Pay this cost for each mode chosen beyond the first.)\nChoose one or both --\n\tCreatures you control get +2/+0 until end of turn.\n\tCreatures you control get +0/+2 until end of turn.',
        art: 'http://mythicspoiler.com/emn/cards/borrowedgrace.jpg'
      },
      {
        name: 'Bruna, the Fading Light',
        set: 'Eldritch Moon',
        cost: '7',
        color: 'White',
        supertype: 'Legendary Creature',
        subtype: 'Angel Horror',
        rarity: 'Rare',
        effects: 'When you cast Bruna, the Fading Light, you may return target Angel or Human creature card from your graveyard to the battlefield.\nFlying, vigilance\n(Melds with Gisela, the Broken Blade)',
        flavor: 'She now sees only Emrakul\'s visions.',
        power: '5',
        toughness: '7',
        art: 'http://mythicspoiler.com/emn/cards/brunathefadinglight.jpg'
      },
      {
        name: 'Choking Restraints',
        set: 'Eldritch Moon',
        cost: '3',
        color: 'White',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Common',
        effects: 'Enchant creature\nEnchanted creature can\'t attack or block.\n{3WW}, Sacrifice Choking Restraints: Exile enchanted creature.',
        art: 'http://mythicspoiler.com/emn/cards/chokingrestraints.jpg'
      },
      {
        name: 'Collective Effort',
        set: 'Eldritch Moon',
        cost: '3',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Rare',
        effects: 'Escalate -- Tap an untapped creature you control. (Pay this cost for each mode chosen beyond the first.)\nChoose one or more --\n\tDestroy target creature with power 4 or greater.\n\tDestroy target enchantment.\n\tPut a +1/+1 counter on each creature target player controls.',
        art: 'http://mythicspoiler.com/emn/cards/collectiveeffort.jpg'
      },
      {
        name: 'Courageous Outrider',
        set: 'Eldritch Moon',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Scout',
        rarity: 'Uncommon',
        effects: 'When Courageous Outrider enters the battlefield, look at the top four cards of your library.  You may reveal a Human card from among them and put it into your hand.  Put the rest on the bottom of your library in any order.',
        flavor: 'One silvery blast signaled that she wouldn\'t be arriving at Thraben alone.',
        power: '3',
        toughness: '4',
        art: 'http://mythicspoiler.com/emn/cards/courageousoutrider.jpg'
      },
      {
        name: 'Dawn Gryff',
        set: 'Eldritch Moon',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Hippogriff',
        rarity: 'Common',
        effects: 'Flying',
        flavor: 'After facing so many horrors, the survivors of Videns parish couldn\'t comprehend the hope that the gryff represented.',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/emn/cards/dawngryff.jpg'
      },
      {
        name: 'Deploy the Gatewatch',
        set: 'Eldritch Moon',
        cost: '6',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Mythic',
        effects: 'Look at the top seven cards of your library.  Put up to two planeswalker cards from among them onto the battlefield.  Put the rest on the bottom of your library in a random order.',
        flavor: 'Gideon and Liliana may not have seen eye to eye, but that did not stop them from fighting side by side.',
        art: 'http://mythicspoiler.com/emn/cards/deploythegatewatch.jpg'
      },
      {
        name: 'Desperate Sentry',
        set: 'Eldritch Moon',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Common',
        effects: 'When Desperate Sentry enters the battlefield, create a 3/2 colorless Eldrazi Horror creature token.\nDelirium -- Desperate Sentry gets +3/+0 as long as there are four or more card types among cards in your graveyard.',
        power: '1',
        toughness: '2',
        art: 'http://mythicspoiler.com/emn/cards/desperatesentry.jpg'
      },
      {
        name: 'Drogskol Shieldmate',
        set: 'Eldritch Moon',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Spirit Soldier',
        rarity: 'Uncommon',
        effects: 'Flash (You may cast this spell any time you could cast an instant.)\nWhen Drogskol Shieldmate enters the battlefield, other creatures you control get +0/+1 until end of turn.',
        flavor: '"I will join you so that you will not yet join me."',
        power: '2',
        toughness: '3',
        art: 'http://mythicspoiler.com/emn/cards/drogskolshieldmate.jpg'
      },
      {
        name: 'Extricator of Sin // Extricator of Flesh',
        set: 'Eldritch Moon',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Cleric // Eldrazi Horror',
        rarity: 'Uncommon',
        effects: 'When Extricator of Sin enters the battlefield, you may sacrifice another permanent.  If you do, create a 3/2 colorless Eldrazi Horror creature token.\nDelirium -- At the beginning of your upkeep, if there are four or more card types among cards in your graveyard, transform Extricator of Sin. // Eldrazi you control have vigilance.\n{2}, {T}, Sacrifice a non-Eldrazi creature: Create a 3/2 colorless Eldrazi Horror creature token.',
        flavor: 'After the end, a new beginning.',
        power: '0 // 3',
        toughness: '3 // 5',
        art: 'http://mythicspoiler.com/emn/cards/extricatorofsin.jpg // http://mythicspoiler.com/emn/cards/extricatorofflesh.jpg'
      },
      {
        name: 'Faith Unbroken',
        set: 'Eldritch Moon',
        cost: '4',
        color: 'White',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Uncommon',
        effects: 'Enchant creature you control\nWhen Faith Unbroken enters the battlefield, exile target creature an opponent controls until Faith Unbroken leaves the battlefield.\nEnchanted creature gets +2/+2.',
        art: 'http://mythicspoiler.com/emn/cards/faithunbroken.jpg'
      },
      {
        name: 'Faithbearer Paladin',
        set: 'Eldritch Moon',
        cost: '5',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Knight',
        rarity: 'Common',
        effects: 'Lifelink (Damage dealt by this creature also causes you to gain that much life.)',
        flavor: '"I\'ve seen cathars riding to battle without a hint of fear.  Perhaps that is its own sort of madness."\n--Esler, Havengul mercenary',
        power: '3',
        toughness: '4',
        art: 'http://mythicspoiler.com/emn/cards/faithbearerpaladin.jpg'
      },
      {
        name: 'Fiend Binder',
        set: 'Eldritch Moon',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Common',
        effects: 'Whenever Fiend Binder attacks, tap target creature defending player controls.',
        flavor: 'She had not believed any shred of humanity remained in these writhing monsters until the twisted form of her partner appeared before her.',
        power: '3',
        toughness: '2',
        art: 'http://mythicspoiler.com/emn/cards/fiendbinder.jpg'
      },
      {
        name: 'Geist of the Lonely Vigil',
        set: 'Eldritch Moon',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Spirit Cleric',
        rarity: 'Uncommon',
        effects: 'Defender, flying\nDelirium -- Geist of the Lonely Vigil can attack as though it didn\'t have defender as long as there are four or more card types among cards in your graveyard.',
        flavor: 'The flicker of candlelight and the echo of hymns told the villagers that the monastery wasn\'t truly abandoned.',
        power: '2',
        toughness: '3',
        art: 'http://mythicspoiler.com/emn/cards/geistofthelonelyvigil.jpg'
      },
      {
        name: 'Gisela, the Broken Blade',
        set: 'Eldritch Moon',
        cost: '4',
        color: 'White',
        supertype: 'Legendary Creature',
        subtype: 'Angel Horror',
        rarity: 'Mythic',
        effects: 'Flying, first strike, lifelink\nAt the beginning of your end step, if you both own and control Gisela, the Broken Blade and a creature named Bruna, the Fading Light, exile them, then meld them into Brisela, Voice of Nightmares.',
        flavor: 'She now hears only Emrakul\s murmurs.',
        power: '4',
        toughness: '3',
        art: 'http://mythicspoiler.com/emn/cards/giselathebrokenblade.jpg'
      },
      {
        name: 'Give No Ground',
        set: 'Eldritch Moon',
        cost: '4',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'Target creature gets +2/+6 until end of turn and can block any number of creatures this turn.',
        flavor: '"Get behind me!"',
        art: 'http://mythicspoiler.com/emn/cards/givenoground.jpg'
      },
      {
        name: 'Guardian of Pilgrims',
        set: 'Eldritch Moon',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Spirit Cleric',
        rarity: 'Common',
        effects: 'When Guardian of Pilgrims enters the battlefield, target creature gets +1/+1 until end of turn.',
        flavor: 'Immune to the physical warping caused by Emrakul, geists proved to be some of humanity\'s most important allies.',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/emn/cards/guardianofpilgrims.jpg'
      },
      {
        name: 'Ironclad Slayer',
        set: 'Eldritch Moon',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Warrior',
        rarity: 'Common',
        effects: 'When Ironclad Slayer enters the battlefield, you may return target Aura or Equipment card from your graveyard to your hand.',
        flavor: 'The best weapon is the one at hand.',
        power: '3',
        toughness: '2',
        art: 'http://mythicspoiler.com/emn/cards/ironcladslayer.jpg'
      },
      {
        name: 'Ironwright\'s Cleansing',
        set: 'Eldritch Moon',
        cost: '3',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'Exile target artifact or enchantment.',
        flavor: '"Impurities must be pounded out."',
        art: 'http://mythicspoiler.com/emn/cards/ironwrightscleansing.jpg'
      },
      {
        name: 'Lone Rider // It That Rides as One',
        set: 'Eldritch Moon',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Knight // Eldrazi Horror',
        rarity: 'Uncommon',
        effects: 'First strike, lifelink\nAt the beginning of each end step, if you gained 3 or more life this turn, transform Lone Rider. // First strike, trample, lifelink',
        flavor: '"Horse and rider are often of one mind."\n--Ulda, Gavony Rider // "...but until this morning, I\'d never seen them be of one body."\n--Ulda, Gavony Rider',
        power: '1 // 4',
        toughness: '1 // 4',
        art: 'http://mythicspoiler.com/emn/cards/lonerider.jpg // http://mythicspoiler.com/emn/cards/itthatridesasone.jpg'
      },
      {
        name: 'Long Road Home',
        set: 'Eldritch Moon',
        cost: '2',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'Exile target creature.  At the beginning of the next end step, return it to the battlefield under its owner\'s control with a +1/+1 counter on it.',
        flavor: 'The person who finishes a journey is rarely the same as the one who starts it.',
        art: 'http://mythicspoiler.com/emn/cards/longroadhome.jpg'
      },
      {
        name: 'Lunarch Mantle',
        set: 'Eldritch Moon',
        cost: '2',
        color: 'White',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Common',
        effects: 'Enchant creature\nEnchanted creature gets +2/+2 and has "{1}, Sacrifice a permanent: This creature gains flying until end of turn."',
        flavor: '"A boon from the angels should never be cast aside."\n--Manfried Ulmach, Chief Inquisitor',
        art: 'http://mythicspoiler.com/emn/cards/lunarchmantle.jpg'
      },
      {
        name: 'Peace of Mind',
        set: 'Eldritch Moon',
        cost: '2',
        color: 'White',
        supertype: 'Enchantment',
        rarity: 'Uncommon',
        effects: '{W}, Discard a card: You gain 3 life.',
        flavor: 'Not all minds touched by the Eldrazi turn to raging psychosis.  Some simply withdraw from this world into memories of a better one.',
        art: 'http://mythicspoiler.com/emn/cards/peaceofmind.jpg'
      },
      {
        name: 'Providence',
        set: 'Eldritch Moon',
        cost: '7',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Rare',
        effects: 'You may reveal this card from your opening hand.  If you do, at the beginning of the first upkeep, your life total becomes 26.\nYour life total becomes 26.',
        flavor: 'There is power in prayer, regardless of who is listening.',
        art: 'http://mythicspoiler.com/emn/cards/providence.jpg'
      },
      {
        name: 'Repel the Abominable',
        set: 'Eldritch Moon',
        cost: '2',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'Prevent all damage that would be dealt this turn by non-Human sources.',
        flavor: '"Fight for a better future, even if you may not live to see it."\n--Grete, Order of Saint Traft',
        art: 'http://mythicspoiler.com/emn/cards/repeltheabominable.jpg'
      },
      {
        name: 'Sanctifier of Souls',
        set: 'Eldritch Moon',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Cleric',
        rarity: 'Rare',
        effects: 'Whenever another creature enters the battlefield under your control, Sanctifier of Souls gets +1/+1 until end of turn.\n{2W}, Exile a creature card from your graveyard: Create a 1/1 white Spirit creature token with flying.',
        power: '2',
        toughness: '3',
        art: 'http://mythicspoiler.com/emn/cards/sanctifierofsouls.jpg'
      },
      {
        name: 'Selfless Spirit',
        set: 'Eldritch Moon',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Spirit Cleric',
        rarity: 'Rare',
        effects: 'Flying\nSacrifice Selfless Spirit: Creatures you control gain indestructible until end of turn.',
        flavor: '"There is always more to give."',
        power: '2',
        toughness: '1',
        art: 'http://mythicspoiler.com/emn/cards/selflessspirit.jpg'
      },
      {
        name: 'Sigarda\'s Aid',
        set: 'Eldritch Moon',
        cost: '1',
        color: 'White',
        supertype: 'Enchantment',
        rarity: 'Rare',
        effects: 'You may cast Aura and Equipment spells as if they had flash.\nWhenever an Equipment enters the battlefield under your control, you may attach it to target creature you control.',
        flavor: 'The Order of Saint Traft found new strength with Sigarda\'s support',
        art: 'http://mythicspoiler.com/emn/cards/sigardasaid.jpg'
      },
      {
        name: 'Sigardian Priest',
        set: 'Eldritch Moon',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Cleric',
        rarity: 'Common',
        effects: '{1}, {T}: Tap target non-Human creature.',
        flavor: 'Many whose faith was destroyed by Avacyn turned to the only angel who remained true to humanity.',
        power: '1',
        toughness: '2',
        art: 'http://mythicspoiler.com/emn/cards/sigardianpriest.jpg'
      },
      {
        name: 'Spectral Reserves',
        set: 'Eldritch Moon',
        cost: '4',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'Create two 1/1 white Spirit creature tokens with flying.  You gain 2 life.',
        flavor: '"My predecessors taught me of duty and commitment.  It seems they have more to teach."\n--Wendin, veteran cathar',
        art: 'http://mythicspoiler.com/emn/cards/spectralreserves.jpg'
      },
      {
        name: 'Steadfast Cathar',
        set: 'Eldritch Moon',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Common',
        effects: 'Whenever Steadfast Cathar attacks, it gets +0/+2 until end of turn.',
        flavor: '"The most resolute soldiers will press forward in the face of overwhelming odds."\n--Gideon Jura',
        power: '2',
        toughness: '1',
        art: 'http://mythicspoiler.com/emn/cards/steadfastcathar.jpg'
      },
      {
        name: 'Subjugator Angel',
        set: 'Eldritch Moon',
        cost: '6',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Angel',
        rarity: 'Uncommon',
        effects: 'Flying\nWhen Subjugator Angel enters the battlefield, tap each creature your opponents control.',
        flavor: 'The remnants of Innistrad\'s corrupted angelic hosts collapsed to form the Flight of Nightmares.',
        power: '4',
        toughness: '3',
        art: 'http://mythicspoiler.com/emn/cards/subjugatorangel.jpg'
      },
      {
        name: 'Thalia, Heretic Cathar',
        set: 'Eldritch Moon',
        cost: '3',
        color: 'White',
        supertype: 'Legendary Creature',
        subtype: 'Human Soldier',
        rarity: 'Rare',
        effects: 'First strike\nCreatures and nonbasic lands your opponents control enter the battlefield tapped.',
        flavor: '"Salvation will not be granted by the Lunarch Council.  It must be earned--at the edge of a sword, if necessary."',
        power: '3',
        toughness: '2',
        art: 'http://mythicspoiler.com/emn/cards/thaliahereticcathar.jpg'
      },
      {
        name: 'Thalia\'s Lancers',
        set: 'Eldritch Moon',
        cost: '5',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Knight',
        rarity: 'Rare',
        effects: 'First strike\nWhen Thalia\'s Lancers enter the battlefield, you may search your library for a legendary card, reveal it, put it into your hand, then shuffle your library.',
        flavor: '"Let the points of our lances lead the way."',
        power: '4',
        toughness: '4',
        art: 'http://mythicspoiler.com/emn/cards/thaliaslancers.jpg'
      },
      {
        name: 'Thraben Standard Bearer',
        set: 'Eldritch Moon',
        cost: '1',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Common',
        effects: '{1W}, {T}, Discard a card: Create a 1/1 white Human Soldier creature token.',
        flavor: 'The uncorrupted rallied under Thalia\'s leadership and Sigarda\'s banner.',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/emn/cards/thrabenstandardbearer.jpg'
      },
      {
        name: 'Advanced Stitchwing',
        set: 'Eldritch Moon',
        cost: '5',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Zombie Horror',
        rarity: 'Uncommon',
        effects: 'Flying\n{2U}, Discard two cards: Return Advanced Stitchwing from your graveyard to the battlefield tapped.',
        flavor: '"Improvement is a consequence of practice."\n--Stitcher Geralf',
        power: '3',
        toughness: '4',
        art: 'http://mythicspoiler.com/emn/cards/advancedstitchwing.jpg'
      },
      {
        name: 'Chilling Grasp',
        set: 'Eldritch Moon',
        cost: '3',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'Tap up to two target creatures.  Those creatures don\'t untap during their controller\'s next untap step.\nMadness {3U} (If you discard this card, discard it into exile.  When you do, cast it for its madness cost or put it into your graveyard.)',
        art: 'http://mythicspoiler.com/emn/cards/chillinggrasp.jpg'
      },
      {
        name: 'Coax from the Blind Eternities',
        set: 'Eldritch Moon',
        cost: '3',
        color: 'Blue',
        supertype: 'Sorcery',
        rarity: 'Rare',
        effects: 'You may choose an Eldrazi card you own from outside the game or in exile, reveal that card, and put it into your hand.',
        flavor: 'At Nahiri\'s call, Emrakul traversed the vast emptiness between the planes and arrived on Innistrad.',
        art: 'http://mythicspoiler.com/emn/cards/coaxfromtheblindeternities.jpg'
      },
      {
        name: 'Contingency Plan',
        set: 'Eldritch Moon',
        cost: '2',
        color: 'Blue',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'Look at the top five cards of your library.  You may put any number of them into your graveyard and the rest on top of your library in any order.',
        flavor: '"Improvisation is for those who failed to prepare."\n--Jace Beleren',
        art: 'http://mythicspoiler.com/emn/cards/contingencyplan.jpg'
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Colorless',
        supertype: 'Legendary Land',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Colorless',
        supertype: 'Land',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Eldritch Moon',
        cost: '',
        color: 'Colorless',
        supertype: 'Land',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: 'Brisela, Voice of Nightmares',
        set: 'Eldritch Moon',
        cost: '0',
        color: 'Colorless',
        supertype: 'Legendary Creature',
        subtype: 'Eldrazi Angel',
        rarity: 'Mythic',
        effects: 'Flying, first strike, vigilance, lifelink\nYour opponents can\'t cast spells with converted mana cost 3 or less.',
        flavor: 'Upon discovering what had become of her sisters, Sigarda could only weep.',
        power: '9',
        toughness: '10',
        art: 'https://proxy.duckduckgo.com/iu/?u=http%3A%2F%2Fwww.magicspoiler.com%2Fwp-content%2Fuploads%2F2016%2F06%2FBrisela-Voice-of-Nightmares-MTG.jpg&f=1'
      },
    ]);
  });
};