exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('Card_List').del()
  .then(function () {
    // Inserts seed entries
    return knex('Card_List').insert([
      {
        name: 'Always Watching',
        set: 'Shadows over Innistrad',
        cost: '3',
        color: 'White',
        supertype: 'Enchantment',
        rarity: 'Rare',
        effects: 'Nontoken creatures you control get +1/+1 and have vigilance.',
        flavor: '"We pray to Avacyn on high.\nOn snow-white wings fearless you fly.\nKeep safe our souls.  Keep safe our lives.\n May angels watch us from the skies."\n--Children\'s prayer',
        art: 'http://mythicspoiler.com/soi/cards/alwayswatching.jpg'
      },
      {
        name: 'Angel of Deliverance',
        set: 'Shadows over Innistrad',
        cost: '8',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Angel',
        rarity: 'Rare',
        effects: 'Flying\nDelirium -- Whenever Angel of Deliverance deals damage, if there are four or more card types among cards in your graveyard, exile target creature an opponent controls.',
        power: '6',
        toughness: '6',
        art: 'http://mythicspoiler.com/soi/cards/angelofdeliverance.jpg'
      },
      {
        name: 'Angelic Purge',
        set: 'Shadows over Innistrad',
        cost: '3',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'As an additional cost to cast Angelic Purge, sacrifice a permanent.\nExile target artifact, creature, or enchantment.',
        flavor: '"We must save you from yourselves."',
        art: 'http://mythicspoiler.com/soi/cards/angelicpurge.jpg'
      },
      {
        name: 'Apothecary Geist',
        set: 'Shadows over Innistrad',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Spirit',
        rarity: 'Common',
        effects: 'Flying\nWhen Apothecary Geist enters the battlefield, if you control another Spirit, you gain 3 life.',
        flavor: 'For some customers, the old apothecary shop still opens its doors.',
        power: '2',
        toughness: '3',
        art: 'http://mythicspoiler.com/soi/cards/apothecarygeist.jpg'
      },
      {
        name: 'Archangel Avacyn // Avacyn, the Purifier',
        set: 'Shadows over Innistrad',
        cost: '5',
        color: 'White // Red',
        supertype: 'Legendary Creature',
        subtype: 'Angel',
        rarity: 'Mythic',
        effects: 'Flash\nFlying, vigilance\nWhen Archangel Avacyn enters the battlefield, creatures you control gain indestructible until end of turn.\nWhen a non-Angel creature you control dies, transform Archangel Avacyn at the beginning of the next upkeep.\n//\nFlying\nWhen this creature transforms into Avacyn, the Purifier, it deals 3 damage to each other creature and each opponent.',
        flavor: '"Wings that once bore hope are now stained with blood.  She is our guardian no longer."\n--Grete, cathar apostate',
        power: '4 // 6',
        toughness: '4 // 5',
        art: 'http://mythicspoiler.com/soi/cards/archangelavacyn.jpg // http://mythicspoiler.com/soi/cards/avacynthepurifier.jpg'
      },
      {
        name: 'Avacynian Missionaries // Lunarch Inquisitors',
        set: 'Shadows over Innistrad',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Cleric',
        rarity: 'Uncommon',
        effects: 'At the beginning of your end step, if Avacynian Missionaries is equipped, transform it.\n//\nWhen this creature transforms into Lunarch Inquisitors, exile another target creature until Lunarch Inquisitors leaves the battlefield.',
        flavor: '"We come bearing the word of Avacyn and the Lunarch Council."\n//\n"We come bearing the tools of confession and absolution."',
        power: '3 // 4',
        toughness: '3 // 4',
        art: 'http://mythicspoiler.com/soi/cards/avacynianmissionaries.jpg // http://mythicspoiler.com/soi/cards/lunarchinquisitors.jpg'
      },
      {
        name: 'Bound by Moonsilver',
        set: 'Shadows over Innistrad',
        cost: '3',
        color: 'White',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Uncommon',
        effects: 'Enchant creature\nEnchanted creature can\'t attack, block, or transform.\nSacrifice another permanent: Attach Bound by Moonsilver to target creature.  Activate this ability only any time you could cast a sorcery and only once each turn.',
        art: 'http://mythicspoiler.com/soi/cards/boundbymoonsilver.jpg'
      },
      {
        name: 'Bygone Bishop',
        set: 'Shadows over Innistrad',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Spirit Cleric',
        rarity: 'Rare',
        effects: 'Flying\nWhenever you cast a creature spell with converted mana cost 3 or less, investigate. (Create a colorless Clue artifact token with "{2}, Sacrifice this artifact: Draw a card.")',
        power: '2',
        toughness: '3',
        art: 'http://mythicspoiler.com/soi/cards/bygonebishop.jpg'
      },
      {
        name: 'Cathar\'s Companion',
        set: 'Shadows over Innistrad',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Hound',
        rarity: 'Common',
        effects: 'Whenever you cast a noncreature spell, Cathar\'s Companion gains indestructible until end of turn. (Damage and effects that say "destroy" don\'t destroy it.)',
        flavor: '"Unwavering and loyal, they represent stability in uncertain times."\n--Rem Karolus, Slayer of Angels',
        power: '3',
        toughness: '1',
        art: 'http://mythicspoiler.com/soi/cards/catharscompanion.jpg'
      },
      {
        name: 'Chaplain\'s Blessing',
        set: 'Shadows over Innistrad',
        cost: '1',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'You gain 5 life.',
        flavor: '"There was a time when the purpose of the church was to heal and protect.  I would see that time return."',
        art: 'http://mythicspoiler.com/soi/cards/chaplainsblessing.jpg'
      },
      {
        name: 'Dauntless Cathar',
        set: 'Shadows over Innistrad',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Common',
        effects: '{1W}, Exile Dauntless Cathar from your graveyard: Create a 1/1 white Spirit creature token with flying.  Activate this ability only any time you could cast a sorcery.',
        flavor: '"The harder they try to extinguish my faith, the brighter it burns in the darkness."',
        power: '3',
        toughness: '2',
        art: 'http://mythicspoiler.com/soi/cards/dauntlesscathar.jpg'
      },
      {
        name: 'Declaration in Stone',
        set: 'Shadows over Innistrad',
        cost: '2',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Rare',
        effects: 'Exile target creature and all other creatures with the same name as that creature.  That player investigates for each nontoken creature exiled this way.',
        flavor: 'The message was clear to Sorin--Nahiri had paid Markov Manor a visit.',
        art: 'http://mythicspoiler.com/soi/cards/declarationinstone.jpg'
      },
      {
        name: 'Descend upon the Sinful',
        set: 'Shadows over Innistrad',
        cost: '6',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Mythic',
        effects: 'Exile all creatures.\nDelirium -- Create a 4/4 white Angel creature token with flying if there are four or more card types among cards in your graveyard.',
        flavor: 'Above the cries, a phrase rang out:\n"You will all be saved."',
        art: 'http://mythicspoiler.com/soi/cards/descenduponthesinful.jpg'
      },
      {
        name: 'Devilthorn Fox',
        set: 'Shadows over Innistrad',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Fox',
        rarity: 'Common',
        flavor: 'On expeditions through Ashmouth, the hunters of Devilthorn Lodge rely on the cleverness of foxes to counteract the mischief of devils.',
        power: '3',
        toughness: '1',
        art: 'http://mythicspoiler.com/soi/cards/devilthornfox.jpg'
      },
      {
        name: 'Drogskol Cavalry',
        set: 'Shadows over Innistrad',
        cost: '7',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Spirit Knight',
        rarity: 'Rare',
        effects: 'Flying\nWhenever another Spirit enters the battlefield under your control, you gain 2 life.\n{3W}: Create a 1/1 white Spirit creature token with flying.',
        power: '4',
        toughness: '4',
        art: 'http://mythicspoiler.com/soi/cards/drogskolcavalry.jpg'
      },
      {
        name: 'Eerie Interlude',
        set: 'Shadows over Innistrad',
        cost: '3',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Rare',
        effects: 'Exile any number of target creatures you control.  Return those cards to the battlefield under their owner\'s control at the beginning of the next end step.',
        flavor: 'The barrier between existence and oblivion is thinner than you know.',
        art: 'http://mythicspoiler.com/soi/cards/eerieinterlude.jpg'
      },
      {
        name: 'Emissary of the Sleepless',
        set: 'Shadows over Innistrad',
        cost: '5',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Spirit',
        rarity: 'Common',
        effects: 'Flying\nWhen Emissary of the Sleepless enters the battlefield, if a creature died this turn, create a 1/1 white Spirit creature token with flying.',
        power: '2',
        toughness: '4',
        art: 'http://mythicspoiler.com/soi/cards/emissaryofthesleepless.jpg'
      },
      {
        name: 'Ethereal Guidance',
        set: 'Shadows over Innistrad',
        cost: '3',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'Creatures you control get +2/+1 until end of turn.',
        flavor: '"The call of the Blessed Sleep is not so strong as the call to protect those in need."\n--Saint Traft',
        art: 'http://mythicspoiler.com/soi/cards/etherealguidance.jpg'
      },
      {
        name: 'Expose Evil',
        set: 'Shadows over Innistrad',
        cost: '2',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Tap up to two target creatures.\nInvestigate. (Create a colorless Clue artifact token with "{2}, Sacrifice this artifact: Draw a card.")',
        flavor: '"Only the pure stand tall in the light."\n--Sigarda',
        art: 'http://mythicspoiler.com/soi/cards/exposeevil.jpg'
      },
      {
        name: 'Gryff\'s Boon',
        set: 'Shadows over Innistrad',
        cost: '1',
        color: 'White',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Uncommon',
        effects: 'Enchant creature\nEnchanted creature gets +1/+0 and has flying.\n{3W}: Return Gryff\'s Boon from your graveyard to the battlefield attached to target creature you control.  Activate this ability only any time you could cast a sorcery.',
        art: 'http://mythicspoiler.com/soi/cards/gryffsboon.jpg'
      },
      {
        name: 'Hanweir Militia Captain // Westvale Cult Leader',
        set: 'Shadows over Innistrad',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier // Human Cleric',
        rarity: 'Rare',
        effects: 'At the beginning of your upkeep, if you control four or more creatures, transform Hanweir Militia Captain.\n//\nWestvale Cult Leader\'s power and toughness are each equal to the number of creatures you control.\nAt the beginning of your end step, create a 1/1 white and black Human Cleric creature token.',
        flavor: 'Her reputation inspires both loyalty and admiration.',
        power: '2 // *',
        toughness: '2 // *',
        art: 'http://mythicspoiler.com/soi/cards/hanweirmilitiacaptain.jpg // http://mythicspoiler.com/soi/cards/westvalecultleader.jpg'
      },
      {
        name: 'Hope Against Hope',
        set: 'Shadows over Innistrad',
        cost: '3',
        color: 'White',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Uncommon',
        effects: 'Enchant creature\nEnchanted creature gets +1/+1 for each creature you control.\nAs long as enchanted creature is a Human, it has first strike.',
        flavor: '"I have given my life to the church, my soul to Avacyn, and my heart to the people."',
        art: 'http://mythicspoiler.com/soi/cards/hopeagainsthope.jpg'
      },
      {
        name: 'Humble the Brute',
        set: 'Shadows over Innistrad',
        cost: '5',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'Destroy target creature with power 4 or greater.\nInvestigate. (Create a colorless Clue artifact token with "{2}, Sacrifice this artifact: Draw a card.")',
        flavor: '"The element of surprise only works when it\'s backed up by a bolt between the eyes."',
        art: 'http://mythicspoiler.com/soi/cards/humblethebrute.jpg'
      },
      {
        name: 'Inquisitor\'s Ox',
        set: 'Shadows over Innistrad',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Ox',
        rarity: 'Common',
        effects: 'Delirium -- Inquisitor\'s Ox gets +1/+0 and has vigilance as long as there are four or more card types among cards in your graveyard.',
        flavor: 'Many fields now lie fallow in Gavony, as the oxen have been confiscated to perform other duties.',
        power: '2',
        toughness: '5',
        art: 'http://mythicspoiler.com/soi/cards/inquisitorsox.jpg'
      },
      {
        name: 'Inspiring Captain',
        set: 'Shadows over Innistrad',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Knight',
        rarity: 'Common',
        effects: 'When Inspiring Captain enters the battlefield, creatures you control get +1/+1 until end of turn.',
        flavor: '"Our enemies will soon discover that we are not as meek as they had believed."',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/soi/cards/inspiringcaptain.jpg'
      },
      {
        name: 'Militant Inquisitor',
        set: 'Shadows over Innistrad',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Cleric',
        rarity: 'Common',
        effects: 'Militant Inquisitor gets +1/+0 for each Equipment you control.',
        flavor: '"I am an instrument of the church wielded against Avacyn\'s enemies."',
        power: '2',
        toughness: '3',
        art: 'http://mythicspoiler.com/soi/cards/militantinquisitor.jpg'
      },
      {
        name: 'Moorland Drifter',
        set: 'Shadows over Innistrad',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Spirit',
        rarity: 'Common',
        effects: 'Delirium -- Moorland Drifter has flying as long as there are four or more card types among cards in your graveyard.',
        flavor: 'It has no apparent purpose or direction.  It simply drifts, buoyed by breezes both tangible and otherworldly.',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/soi/cards/moorlanddrifter.jpg'
      },
      {
        name: 'Nahiri\'s Machinations',
        set: 'Shadows over Innistrad',
        cost: '2',
        color: 'White',
        supertype: 'Enchantment',
        rarity: 'Uncommon',
        effects: 'At the beginning of combat on your turn, target creature you control gains indestructible until end of turn.\n{1R}: Nahiri\'s Machinations deals 1 damage to target blocking creature.',
        flavor: '"Sorin, I\'m going to take everything from you."',
        art: 'http://mythicspoiler.com/soi/cards/nahirismachinations.jpg'
      },
      {
        name: 'Nearheath Chaplain',
        set: 'Shadows over Innistrad',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Cleric',
        rarity: 'Uncommon',
        effects: 'Lifelink\n{2W}, Exile Nearheath Chaplain from your graveyard: Create two 1/1 white Spirit creature tokens with flying.  Activate this ability only any time you could cast a sorcery.',
        power: '3',
        toughness: '1',
        art: 'http://mythicspoiler.com/soi/cards/nearheathchaplain.jpg'
      },
      {
        name: 'Not Forgotten',
        set: 'Shadows over Innistrad',
        cost: '2',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Uncommon',
        effects: 'Put target card from a graveyard on the top or bottom of its owner\'s library.  Create a 1/1 white Spirit creature token with flying.',
        flavor: 'Visit the dead, and they may return the favor.',
        art: 'http://mythicspoiler.com/soi/cards/notforgotten.jpg'
      },
      {
        name: 'Odric, Lunarch Marshal',
        set: 'Shadows over Innistrad',
        cost: '4',
        color: 'White',
        supertype: 'Legendary Creature',
        subtype: 'Human Soldier',
        rarity: 'Rare',
        effects: 'At the beginning of each combat, creatures you control gain first strike until end of turn if a creature you control has first strike.  The same is true for flying, deathtouch, double strike, haste, hexproof, indestructible, menace, reach, skulk, trample, and vigilance.',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/soi/cards/odriclunarchmarshal.jpg'
      },
      {
        name: 'Open the Armory',
        set: 'Shadows over Innistrad',
        cost: '2',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Uncommon',
        effects: 'Search your library for an Aura or Equipment card, reveal it, and put it into your hand.  Then shuffle your library.',
        flavor: '"Once Avacyn returned, I hoped I\'d never need these things again.  I didn\'t think I\'d be dusting them off to use against angels."',
        art: 'http://mythicspoiler.com/soi/cards/openthearmory.jpg'
      },
      {
        name: 'Paranoid Parish-Blade',
        set: 'Shadows over Innistrad',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Uncommon',
        effects: 'Delirium -- Paranoid Parish-Blade gets +1/+0 and has first strike as long as there are four or more card types among cards in your graveyard.',
        flavor: 'The mind is perfectly capable of creating its own monsters.',
        power: '3',
        toughness: '2',
        art: 'http://mythicspoiler.com/soi/cards/paranoidparishblade.jpg'
      },
      {
        name: 'Pious Evangel // Wayward Disciple',
        set: 'Shadows over Innistrad',
        cost: '3',
        color: 'White // Black',
        supertype: 'Creature',
        subtype: 'Human Cleric',
        rarity: 'Uncommon',
        effects: 'Whenever Pious Evangel or another creature enters the battlefield under your control, you gain 1 life.\n{2}, {T}, Sacrifice another permanent: Transform Pious Evangel.\n//\nWhenever Wayward Disciple or another creature you control dies, target opponent loses 1 life and you gain 1 life.',
        flavor: '"My faith guides my hand ..." // "... and I will prove my devotion."',
        power: '2 // 2',
        toughness: '2 // 4',
        art: 'http://mythicspoiler.com/soi/cards/piousevangel.jpg // http://mythicspoiler.com/soi/cards/waywarddisciple.jpg'
      },
      {
        name: 'Puncturing Light',
        set: 'Shadows over Innistrad',
        cost: '2',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Destroy target attacking or blocking creature with power 3 or less.',
        flavor: '"If you refuse to see the light, then you will feel it."',
        art: 'http://mythicspoiler.com/soi/cards/puncturinglight.jpg'
      },
      {
        name: 'Reaper of Flight Moonsilver',
        set: 'Shadows over Innistrad',
        cost: '5',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Angel',
        rarity: 'Uncommon',
        effects: 'Flying\nDelirium -- Sacrifice another creature: Reaper of Flight Moonsilver gets +2/+1 until end of turn.  Activate this ability only if there are four or more card types among cards in your graveyard.',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/soi/cards/reaperofflightmoonsilver.jpg'
      },
      {
        name: 'Silverstrike',
        set: 'Shadows over Innistrad',
        cost: '4',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'Destroy target attacking creature.  You gain 3 life.',
        flavor: '"Shield yourself with faith.  Arm yourself with silver."\n--Slayer Kastinne',
        art: 'http://mythicspoiler.com/soi/cards/silverstrike.jpg'
      },
      {
        name: 'Spectral Shepherd',
        set: 'Shadows over Innistrad',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Spirit',
        rarity: 'Uncommon',
        effects: 'Flying\n{1U}: Return target Spirit you control to its owner\'s hand.',
        flavor: 'The restless geists of common folk often continue their lifelong labors.',
        power: '3',
        toughness: '2',
        art: 'http://mythicspoiler.com/soi/cards/spectralshepherd.jpg'
      },
      {
        name: 'Stern Constable',
        set: 'Shadows over Innistrad',
        cost: '1',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Common',
        effects: '{T}, Discard a card: Tap target creature.',
        flavor: '"I\'m sure you have a story.  Everyone has a story.  You can tell it to the bars."',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/soi/cards/sternconstable.jpg'
      },
      {
        name: 'Strength of Arms',
        set: 'Shadows over Innistrad',
        cost: '1',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Target creature gets +2/+2 until end of turn.  If you control an Equipment, create a 1/1 white Human Soldier creature token.',
        flavor: '"We fight not for Avacyn, but for her ideals; not for the church, but for its people."\n--Thalia, Guardian of Thraben',
        art: 'http://mythicspoiler.com/soi/cards/strengthofarms.jpg'
      },
      {
        name: 'Survive the Night',
        set: 'Shadows over Innistrad',
        cost: '3',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Target creature gets +1/+0 and gains indestructible until end of turn. (Damage and effects that say "destroy" don\'t destroy it.)\nInvestigate. (Create a colorless Clue artifact token with "{2}, Sacrifice this artifact: Draw a card.")',
        flavor: 'The longest nights are measured not in hours, but in heartbeats.',
        art: 'http://mythicspoiler.com/soi/cards/survivethenight.jpg'
      },
      {
        name: 'Tenacity',
        set: 'Shadows over Innistrad',
        cost: '4',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'Creatures you control get +1/+1 and gain lifelink until end of turn.  Untap those creatures.',
        flavor: 'Thalia established the Order of Saint Traft in an effort to bring together cathars who would stand against the corruption of the Lunarch Council.',
        art: 'http://mythicspoiler.com/soi/cards/tenacity.jpg'
      },
      {
        name: 'Thalia\'s Lieutenant',
        set: 'Shadows over Innistrad',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Rare',
        effects: 'When Thalia\'s Lieutenant enters the battlefield, put a +1/+1 counter on each other Human you control.\nWhenever another Human enters the battlefield under your control, put a +1/+1 counter on Thalia\'s Lieutenant.',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/soi/cards/thaliaslieutenant.jpg'
      },
      {
        name: 'Thraben Inspector',
        set: 'Shadows over Innistrad',
        cost: '1',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Soldier',
        rarity: 'Common',
        effects: 'When Thraben Inspector enters the battlefield, investigate. (Create a colorless Clue artifact token with "{2}, Sacrifice this artifact: Draw a card.")',
        flavor: '"If you\'ve been at this as long as I have, nothing can surprise you.  That\'s the hope, at least."',
        power: '1',
        toughness: '2',
        art: 'http://mythicspoiler.com/soi/cards/thrabeninspector.jpg'
      },
      {
        name: 'Topplegeist',
        set: 'Shadows over Innistrad',
        cost: '1',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Spirit',
        rarity: 'Uncommon',
        effects: 'Flying\nWhen Topplegeist enters the battlefield, tap target creature an opponent controls.\nDelirium -- At the beginning of each opponent\'s upkeep, if there are four or more card types among cards in your graveyard, tap target creature that player controls.',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/soi/cards/topplegeist.jpg'
      },
      {
        name: 'Town Gossipmonger // Incited Rabble',
        set: 'Shadows over Innistrad',
        cost: '1',
        color: 'White // Red',
        supertype: 'Creature',
        subtype: 'Human',
        rarity: 'Uncommon',
        effects: '{T}, Tap an untapped creature you control: Transform Town Gossipmonger.\n//\nIncited Rabble attacks each combat if able.\n{2}: Incited Rabble gets +1/+0 until end of turn.',
        flavor: '"You\'ll never believe what I heard." // Rumors are sparks: gather enough of them and something\'s going to catch fire.',
        power: '1 // 2',
        toughness: '1 // 3',
        art: 'http://mythicspoiler.com/soi/cards/towngossipmonger.jpg // http://mythicspoiler.com/soi/cards/incitedrabble.jpg'
      },
      {
        name: 'Unruly Mob',
        set: 'Shadows over Innistrad',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human',
        rarity: 'Common',
        effects: 'Whenever another creature you control dies, put a +1/+1 counter on Unruly Mob.',
        flavor: '"Those who aren\'t welcome will know it!"\n--Kolman, elder of Gatstaf',
        power: '1',
        toughness: '1',
        art: 'http://mythicspoiler.com/soi/cards/unrulymob.jpg'
      },
      {
        name: 'Vessel of Ephemera',
        set: 'Shadows over Innistrad',
        cost: '2',
        color: 'White',
        supertype: 'Enchantment',
        rarity: 'Common',
        effects: '{2W}, Sacrifice Vessel of Ephemera: Create two 1/1 white Spirit creature tokens with flying.',
        flavor: 'Geists seeking redemption must first be given the opportunity.',
        art: 'http://mythicspoiler.com/soi/cards/vesselofephemera.jpg'
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Shadows over Innistrad',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
    ]);
  });
};