exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('Card_List').del()
  .then(function () {
    // Inserts seed entries
    return knex('Card_List').insert([
      {
        name: 'Deceiver of Form',
        set: 'Oath of the Gatewatch',
        cost: '7',
        color: 'Colorless',
        supertype: 'Creature',
        subtype: 'Eldrazi',
        rarity: 'Rare',
        effects: '({C} represents colorless mana.)\nAt the beginning of combat on your turn, reveal the top card of your library.  If a creature card is revealed this way, you may have creatures you control other than Deceiver of Form become copies of that creature until end of turn.  You may put that card on the bottom of your library.',
        power: '8',
        toughness: '8',
        art: 'http://mythicspoiler.com/ogw/cards/deceiverofform.jpg'
      },
      {
        name: 'Eldrazi Mimic',
        set: 'Oath of the Gatewatch',
        cost: '2',
        color: 'Colorless',
        supertype: 'Creature',
        subtype: 'Eldrazi',
        rarity: 'Rare',
        effects: 'Whenever another colorless creature enters the battlefield under your control, you may change Eldrazi Mimic\'s base power and toughness to that creature\'s power and toughness until end of turn.',
        flavor: 'It is consistently inconsistent.',
        power: '2',
        toughness: '1',
        art: 'http://mythicspoiler.com/ogw/cards/eldrazimimic.jpg'
      },
      {
        name: 'Endbringer',
        set: 'Oath of the Gatewatch',
        cost: '6',
        color: 'Colorless',
        supertype: 'Creature',
        subtype: 'Eldrazi',
        rarity: 'Rare',
        effects: 'Untap Endbringer during each other player\'s untap step.\n{T}: Endbringer deals 1 damage to target creature or player.\n{1}, {T}: Target creature can\'t attack or block this turn.\n{2}, {T}: Draw a card.',
        power: '5',
        toughness: '5',
        art: 'http://mythicspoiler.com/ogw/cards/endbringer.jpg'
      },
      {
        name: 'Kozilek, the Great Distortion',
        set: 'Oath of the Gatewatch',
        cost: '10',
        color: 'Colorless',
        supertype: 'Legendary Creature',
        subtype: 'Eldrazi',
        rarity: 'Mythic',
        effects: 'When you cast Kozilek, the Great Distortion, if you have fewer than seven cards in hand, draw cards equal to the difference.\nMenace\nDiscard a card with converted mana cost X: Counter target spell with converted mana cost X.',
        flavor: 'A void as cryptic as reality itself.',
        power: '12',
        toughness: '12',
        art: 'http://mythicspoiler.com/ogw/cards/kozilekthegreatdistortion.jpg'
      },
      {
        name: 'Kozilek\'s Pathfinder',
        set: 'Oath of the Gatewatch',
        cost: '6',
        color: 'Colorless',
        supertype: 'Creature',
        subtype: 'Eldrazi',
        rarity: 'Common',
        effects: '{C}: Target creature can\'t block Kozilek\'s Pathfinder this turn. ({C} represents colorless mana.)',
        flavor: '"We didn\'t know where it came from or where it was going.  All we knew was that we did not matter."\n--Akiri, kor line-slinger',
        power: '5',
        toughness: '5',
        art: 'http://mythicspoiler.com/ogw/cards/kozilekspathfinder.jpg'
      },
      {
        name: 'Matter Reshaper',
        set: 'Oath of the Gatewatch',
        cost: '3',
        color: 'Colorless',
        supertype: 'Creature',
        subtype: 'Eldrazi',
        rarity: 'Rare',
        effects: '({C} represents colorless mana.)\nWhen Matter Reshaper dies, reveal the top card of your library.  Put that card onto the battlefield if it\'s a permanent card with converted mana cost 3 or less.  Otherwise, put that card into your hand.',
        power: '3',
        toughness: '2',
        art: 'http://mythicspoiler.com/ogw/cards/matterreshaper.jpg'
      },
      {
        name: 'Reality Smasher',
        set: 'Oath of the Gatewatch',
        cost: '5',
        color: 'Colorless',
        supertype: 'Creature',
        subtype: 'Eldrazi',
        rarity: 'Rare',
        effects: '({C} represents colorless mana.)\nTrample, haste\nWhenever Reality Smasher becomes the target of a spell an opponent controls, counter that spell unless its controller discards a card.',
        flavor: 'As easy to stop as it is to comprehend.',
        power: '5',
        toughness: '5',
        art: 'http://mythicspoiler.com/ogw/cards/realitysmasher.jpg'
      },
      {
        name: 'Spatial Distortion',
        set: 'Oath of the Gatewatch',
        cost: '2',
        color: 'Colorless',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: '({C} represents colorless mana.)\nTarget creature gets +3/-3 until end of turn.',
        flavor: '"For those without the Planeswalker spark, the merest touch of the Blind Eternities can kill."\n--Ugin',
        art: 'http://mythicspoiler.com/ogw/cards/spatialdistortion.jpg'
      },
      {
        name: 'Thought-Knot Seer',
        set: 'Oath of the Gatewatch',
        cost: '4',
        color: 'Colorless',
        supertype: 'Creature',
        subtype: 'Eldrazi',
        rarity: 'Rare',
        effects: '({C} represents colorless mana.)\nWhen Thought-Knot Seer enters the battlefield, target opponent reveals their hand.  You choose a nonland card from it and exile it.\nWhen Thought-Knot Seer leaves the battlefield, target opponent draws a card.',
        power: '4',
        toughness: '4',
        art: 'http://mythicspoiler.com/ogw/cards/thoughtknotseer.jpg'
      },
      {
        name: 'Walker of the Wastes',
        set: 'Oath of the Gatewatch',
        cost: '5',
        color: 'Colorless',
        supertype: 'Creature',
        subtype: 'Eldrazi',
        rarity: 'Uncommon',
        effects: '({C} represents colorless mana.)\nTrample\nWalker of the Wastes gets +1/+1 for each land you control named Wastes.',
        flavor: 'In the absence of life, something yet grows.',
        power: '4',
        toughness: '4',
        art: 'http://mythicspoiler.com/ogw/cards/walkerofthewastes.jpg'
      },
      {
        name: 'Warden of Geometries',
        set: 'Oath of the Gatewatch',
        cost: '4',
        color: 'Colorless',
        supertype: 'Creature',
        subtype: 'Eldrazi Drone',
        rarity: 'Common',
        effects: 'Vigilance\n{T}: Add {C} to your mana pool. ({C} represents colorless mana.)',
        flavor: 'The wastelands disorient even the most experienced scouts, making them easy prey for Kozilek\'s drones.',
        power: '2',
        toughness: '3',
        art: 'http://mythicspoiler.com/ogw/cards/wardenofgeometries.jpg'
      },
      {
        name: 'Warping Wail',
        set: 'Oath of the Gatewatch',
        cost: '2',
        color: 'Colorless',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: '({C} represents colorless mana.)\nChoose one --\n\tExile target creature with power or toughness 1 or less.\n\tCounter target sorcery spell.\n\tCreate a 1/1 colorless Eldrazi Scion creature token with "Sacrifice this creature: Add {C} to your mana pool."',
        art: 'http://mythicspoiler.com/ogw/cards/warpingwail.jpg'
      },
      {
        name: 'Eldrazi Displacer',
        set: 'Oath of the Gatewatch',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Eldrazi',
        rarity: 'Rare',
        effects: 'Devoid (This creature has no color.)\n{2C}: Exile another target creature, then return it to the battlefield tapped under its owner\'s control. ({C} represents colorless mana.)',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/ogw/cards/eldrazidisplacer.jpg'
      },
      {
        name: 'Allied Reinforcements',
        set: 'Oath of the Gatewatch',
        cost: '4',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Uncommon',
        effects: 'Create two 2/2 white Knight Ally creature tokens.',
        flavor: '"Our formation was scattered after Sea Gate fell.  If you\'re fighting the Eldrazi, consider us your newest recruits."',
        art: 'http://mythicspoiler.com/ogw/cards/alliedreinforcements.jpg'
      },
      {
        name: 'Call the Gatewatch',
        set: 'Oath of the Gatewatch',
        cost: '3',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Rare',
        effects: 'Search your library for a planeswalker card, reveal it, and put it into your hand.  Then shuffle your library.',
        flavor: '"I\'ve heard it said that a Planeswalker is someone who can always rin from danger.  But Gideon\'s right: we\'re also the ones who can choose to stay."\n--Jace Beleren',
        art: 'http://mythicspoiler.com/ogw/cards/callthegatewatch.jpg'
      },
      {
        name: 'Dazzling Reflection',
        set: 'Oath of the Gatewatch',
        cost: '2',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'You gain life equal to target creature\'s power.  The next time that creature would deal damage this turn, prevent that damage.',
        flavor: '"The light of a felidar\'s horns can give even an Eldrazi pause."\n--Zarra, lullmage',
        art: 'http://mythicspoiler.com/ogw/cards/dazzlingreflection.jpg'
      },
      {
        name: 'Expedition Raptor',
        set: 'Oath of the Gatewatch',
        cost: '5',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Bird',
        rarity: 'Common',
        effects: 'Flying\nWhen Expedition Raptor enters the battlefield, support 2. (Put a +1/+1 counter on up to two other creatures.)',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/ogw/cards/expeditionraptor.jpg'
      },
      {
        name: 'General Tazri',
        set: 'Oath of the Gatewatch',
        cost: '5',
        color: 'White',
        supertype: 'Legendary Creature',
        subtype: 'Human Ally',
        rarity: 'Mythic',
        effects: 'When General Tazri enters the battlefield, you may search your library for an Ally creature card, reveal it, put it into your hand, then shuffle your library.\n{WUBRG}: Ally creatures you control get +X/+X until end of turn, where X is the number of colors among those creatures.',
        power: '3',
        toughness: '4',
        art: 'http://mythicspoiler.com/ogw/cards/generaltazri.jpg'
      },
      {
        name: 'Immolating Glare',
        set: 'Oath of the Gatewatch',
        cost: '2',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'Destroy target attacking creature.',
        flavor: '"The sun can warm your skin or blister it, nurture your crops or wither them, light your path or blind you.  She is a fickle friend, but a far worse enemy."\n--Nazra of the Stone Havens',
        art: 'http://mythicspoiler.com/ogw/cards/immolatingglare.jpg'
      },
      {
        name: 'Iona\'s Blessing',
        set: 'Oath of the Gatewatch',
        cost: '4',
        color: 'White',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Uncommon',
        effects: 'Enchant creature\nEnchanted creature gets +2/+2, has vigilance, and can block an additional creature.',
        flavor: '"Walk now in my light.  When the rest of the world closes its eyes, you will still see."\n--Iona',
        art: 'http://mythicspoiler.com/ogw/cards/ionasblessing.jpg'
      },
      {
        name: 'Isolation Zone',
        set: 'Oath of the Gatewatch',
        cost: '4',
        color: 'White',
        supertype: 'Enchantment',
        rarity: 'Common',
        effects: 'When Isolation Zone enters the battlefield, exile target creature or enchantment an opponent controls until Isolation Zone leaves the battlefield.',
        flavor: 'When properly aligned, hedrons become powerful tools of binding.',
        art: 'http://mythicspoiler.com/ogw/cards/isolationzone.jpg'
      },
      {
        name: 'Kor Scythemaster',
        set: 'Oath of the Gatewatch',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Kor Soldier Ally',
        rarity: 'Common',
        effects: 'Kor Scythemaster has first strike as long as it\'s attacking.',
        flavor: 'The kor of Zendikar are known for quiet determination in the face of overwhelming odds.',
        power: '3',
        toughness: '1',
        art: 'http://mythicspoiler.com/ogw/cards/korscythemaster.jpg'
      },
      {
        name: 'Kor Sky Climber',
        set: 'Oath of the Gatewatch',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Kor Soldier Ally',
        rarity: 'Common',
        effects: '{1W}: Kor Sky Climber gains flying until end of turn.',
        flavor: '"With rope, I can fly as far as the rope can reach.  But with light, the sky is the limit."',
        power: '3',
        toughness: '2',
        art: 'http://mythicspoiler.com/ogw/cards/korskyclimber.jpg'
      },
      {
        name: 'Linvala, the Preserver',
        set: 'Oath of the Gatewatch',
        cost: '6',
        color: 'White',
        supertype: 'Legendary Creature',
        subtype: 'Angel',
        rarity: 'Mythic',
        effects: 'Flying\nWhen Linvala, the Preserver enters the battlefield, if an opponent has more life than you, you gain 5 life.\nWhen Linvala, the Preserver enters the battlefield, if an opponent controls more creatures than you, create a 3/3 white Angel creature token with flying.',
        power: '5',
        toughness: '5',
        art: 'http://mythicspoiler.com/ogw/cards/linvalathepreserver.jpg'
      },
      {
        name: 'Make a Stand',
        set: 'Oath of the Gatewatch',
        cost: '3',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'Creatures you control get +1/+0 and gain indestructible until end of turn. (Damage and effects that say "destroy" don\'t destroy them.)',
        flavor: 'For a moment they stood tall, all fear forgotten.',
        art: 'http://mythicspoiler.com/ogw/cards/makeastand.jpg'
      },
      {
        name: 'Makindi Aeronaut',
        set: 'Oath of the Gatewatch',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Kor Scout Ally',
        rarity: 'Common',
        effects: 'Flying',
        flavor: '"The Eldrazi have surprised us before.  It\'s my job to make sure that never happens again."',
        power: '1',
        toughness: '3',
        art: 'http://mythicspoiler.com/ogw/cards/makindiaeronaut.jpg'
      },
      {
        name: 'Mighty Leap',
        set: 'Oath of the Gatewatch',
        cost: '2',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Target creature gets +2/+2 and gains flying until end of turn.',
        flavor: '"We may have lost faith in our gods, but we are far from losing faith in ourselves."\n--Munda, ambush leader',
        art: 'http://mythicspoiler.com/ogw/cards/mightyleap.jpg'
      },
      {
        name: 'Munda\'s Vanguard',
        set: 'Oath of the Gatewatch',
        cost: '5',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Kor Knight Ally',
        rarity: 'Rare',
        effects: 'Cohort -- {T}, Tap an untapped Ally you control: Put a +1/+1 counter on each creature you control.',
        flavor: '"Do not let yourselves fall now.  Zendikar is depending on us--on you!"',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/ogw/cards/mundasvanguard.jpg'
      },
      {
        name: 'Oath of Gideon',
        set: 'Oath of the Gatewatch',
        cost: '3',
        color: 'White',
        supertype: 'Legendary Enchantment',
        rarity: 'Rare',
        effects: 'When Oath of Gideon enters the battlefield, create two 1/1 white Kor Ally creature tokens.\nEach planeswalker you control enters the battlefield with an additional loyalty counter on it.',
        flavor: '"For justice and peace, I will keep watch."',
        art: 'http://mythicspoiler.com/ogw/cards/oathofgideon.jpg'
      },
      {
        name: 'Ondu War Cleric',
        set: 'Oath of the Gatewatch',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Cleric Ally',
        rarity: 'Common',
        effects: 'Cohort -- {T}, Tap an untapped Ally you control: You gain 2 life.',
        flavor: '"I will follow the light of Iona into battle, and I will know no fear."',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/ogw/cards/onduwarcleric.jpg'
      },
      {
        name: 'Relief Captain',
        set: 'Oath of the Gatewatch',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Kor Knight Ally',
        rarity: 'Uncommon',
        effects: 'When Relief Captain enters the battlefield, support 3. (Put a +1/+1 counter on each of up to three other target creatures.)',
        flavor: 'Sometimes gestures of support are small.  Sometimes not.',
        power: '3',
        toughness: '2',
        art: 'http://mythicspoiler.com/ogw/cards/reliefcaptain.jpg'
      },
      {
        name: 'Searing Light',
        set: 'Oath of the Gatewatch',
        cost: '1',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Destroy target attacking or blocking creature with power 2 or less.',
        flavor: '"Light can lay bare our fears.  It can also make them go away."\n--Nazra of the Stone Havens',
        art: 'http://mythicspoiler.com/ogw/cards/searinglight.jpg'
      },
      {
        name: 'Shoulder to Shoulder',
        set: 'Oath of the Gatewatch',
        cost: '3',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'Support 2. (Put a +1/+1 counter on each of up to two target creatures.)\nDraw a card.',
        flavor: '"Sea Gate may have fallen, but we still stand.  We still fight."\n--Gideon Jura',
        art: 'http://mythicspoiler.com/ogw/cards/shouldertoshoulder.jpg'
      },
      {
        name: 'Spawnbinder Mage',
        set: 'Oath of the Gatewatch',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Wizard Ally',
        rarity: 'Common',
        effects: 'Cohort -- {T}, Tap an untapped Ally you control: Tap target creature.',
        flavor: '"Follow me.  Step lightly.  And resist the urge to kick them."',
        power: '2',
        toughness: '4',
        art: 'http://mythicspoiler.com/ogw/cards/spawnbindermage.jpg'
      },
      {
        name: 'Steppe Glider',
        set: 'Oath of the Gatewatch',
        cost: '5',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Elemental',
        rarity: 'Uncommon',
        effects: 'Flying, vigilance\n{1W}: Target creature with a +1/+1 counter on it gains flying and vigilance until end of turn.',
        flavor: 'It glides over the landscape.  It also happens to be one.',
        power: '2',
        toughness: '4',
        art: 'http://mythicspoiler.com/ogw/cards/steppeglider.jpg'
      },
      {
        name: 'Stone Haven Outfitter',
        set: 'Oath of the Gatewatch',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Kor Artificer Ally',
        rarity: 'Rare',
        effects: 'Equipped creatures get +1/+1.\nWhenever an equipped creature you control dies, draw a card.',
        flavor: 'The makers and menders are the first called to battle and the last to leave.',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/ogw/cards/stonehavenoutfitter.jpg'
      },
      {
        name: 'Stoneforge Acolyte',
        set: 'Oath of the Gatewatch',
        cost: '1',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Kor Artificer Ally',
        rarity: 'Uncommon',
        effects: 'Cohort -- {T}, Tap an untapped Ally you control: Look at the top four cards of your library.  You may reveal an Equipment card from among them and put it into your hand.  Put the rest on the bottom of your library in a random order.',
        flavor: '"The stone speaks.  We are merely interpreters."',
        power: '1',
        toughness: '2',
        art: 'http://mythicspoiler.com/ogw/cards/stoneforgeacolyte.jpg'
      },
      {
        name: 'Wall of Resurgence',
        set: 'Oath of the Gatewatch',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Wall',
        rarity: 'Uncommon',
        effects: 'Defender\nWhen Wall of Resurgence enters the battlefield, you may put three +1/+1 counters on target land you control.  If you do, that land becomes a 0/0 Elemental creature with haste that\'s still a land.',
        power: '0',
        toughness: '6',
        art: 'http://mythicspoiler.com/ogw/cards/wallofresurgence.jpg'
      },
      {
        name: 'Abstruse Interference',
        set: 'Oath of the Gatewatch',
        cost: '3',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Devoid (This card has no color.)\nCounter target spell unless its controller pays {1}.  Create a 1/1 colorless Eldrazi Scion creature token with "Sacrifice this creature: Add {C} to your mana pool." ({C} represents colorless mana.)',
        art: 'http://mythicspoiler.com/ogw/cards/abstruseinterference.jpg'
      },
      {
        name: 'Blinding Drone',
        set: 'Oath of the Gatewatch',
        cost: '2',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Eldrazi Drone',
        rarity: 'Common',
        effects: 'Devoid (This card has no color.)\n{C}, {T}: Tap target creature. ({C} represents colorless mana.)',
        flavor: '"Zendikar\'s true gods have risen.  Whether in reverence or agony, all the world will kneel."\nAyli, high priest of the Eternal Pilgrims',
        power: '1',
        toughness: '3',
        art: 'http://mythicspoiler.com/ogw/cards/blindingdrone.jpg'
      },
      {
        name: 'Cultivator Drone',
        set: 'Oath of the Gatewatch',
        cost: '3',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Eldrazi Drone',
        rarity: 'Common',
        effects: 'Devoid (This card has no color.)\n{T}: Add {C} to your mana pool.  Spend this mana only to cast a colorless spell, activate an ability of a colorless permanent, or pay a cost that contains {C}. ({C} represents colorless mana.)',
        power: '2',
        toughness: '3',
        art: 'http://mythicspoiler.com/ogw/cards/cultivatordrone.jpg'
      },
      {
        name: 'Deepfathom Skulker',
        set: 'Oath of the Gatewatch',
        cost: '6',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Eldrazi',
        rarity: 'Rare',
        effects: 'Devoid (This card has no color.)\nWhenever a creature you control deals combat damage to a player, you may draw a card.\n{3C}: Target creature can\'t be blocked this turn. ({C} represents colorless mana.)',
        power: '4',
        toughness: '4',
        art: 'http://mythicspoiler.com/ogw/cards/deepfathomskulker.jpg'
      },
      {
        name: 'Dimensional Infiltrator',
        set: 'Oath of the Gatewatch',
        cost: '2',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Eldrazi',
        rarity: 'Rare',
        effects: 'Devoid (This card has no color.)\nFlash\nFlying\n{1C}: Target opponent exiles the top card of their library.  If it\'s a land card, you may return Dimensional Infiltrator to its owner\'s hand. ({C} represents colorless mana.)',
        power: '2',
        toughness: '1',
        art: 'http://mythicspoiler.com/ogw/cards/dimensionalinfiltrator.jpg'
      },
      {
        name: 'Gravity Negator',
        set: 'Oath of the Gatewatch',
        cost: '4',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Eldrazi Drone',
        rarity: 'Common',
        effects: 'Devoid (This card has no color.)\nFlying\nWhenever Gravity Negator attacks, you may pay {C}.  If you do, another target creature gains flying until end of turn. ({C} represents colorless mana.)',
        power: '2',
        toughness: '3',
        art: 'http://mythicspoiler.com/ogw/cards/gravitynegator.jpg'
      },
      {
        name: 'Prophet of Distortion',
        set: 'Oath of the Gatewatch',
        cost: '1',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Eldrazi Drone',
        rarity: 'Uncommon',
        effects: 'Devoid (This card has no color.)\n{3C}: Draw a card. ({C} represents colorless mana.)',
        flavor: 'It doesn\'t twist words.  It twists worlds.',
        power: '1',
        toughness: '2',
        art: 'http://mythicspoiler.com/ogw/cards/prophetofdistortion.jpg'
      },
      {
        name: 'Slip Through Space',
        set: 'Oath of the Gatewatch',
        cost: '1',
        color: 'Blue',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'Devoid (This card has no color.)\nTarget creature can\'t be blocked this turn.\nDraw a card.',
        flavor: 'The Eldrazi twisted in a direction that had no name, and a frontal assault became a panicked rout.',
        art: 'http://mythicspoiler.com/ogw/cards/slipthroughspace.jpg'
      },
      {
        name: 'Thought Harvester',
        set: 'Oath of the Gatewatch',
        cost: '4',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Eldrazi Drone',
        rarity: 'Uncommon',
        effects: 'Devoid (This card has no color.)\nFlying\nWhenever you cast a colorless spell, target opponent exiles the top card of their library.',
        flavor: '"I never thought I\'d miss the gomazoa."\nTrinda, Hada spy patrol',
        power: '2',
        toughness: '4',
        art: 'http://mythicspoiler.com/ogw/cards/thoughtharvester.jpg'
      },
      {
        name: 'Void Shatter',
        set: 'Oath of the Gatewatch',
        cost: '3',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'Devoid (This card has no color.)\nCounter target spell.  If that spell would be countered this way, exile it instead of putting it into its owner\'s graveyard.',
        flavor: 'Eldrazi break concentration like glass.',
        art: 'http://mythicspoiler.com/ogw/cards/voidshatter.jpg'
      },
      {
        name: 'Ancient Crab',
        set: 'Oath of the Gatewatch',
        cost: '3',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Crab',
        rarity: 'Common',
        flavor: 'After the fall of Sea Gate and the draining of the Halimar basin, the crab set off to find a new home.',
        power: '1',
        toughness: '5',
        art: 'http://mythicspoiler.com/ogw/cards/ancientcrab.jpg'
      },
      {
        name: 'Comparative Analysis',
        set: 'Oath of the Gatewatch',
        cost: '4',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Surge {2U} (You may cast this spell for its surge cost if you or a teammate has cast another spell this turn.)\nTarget player draws two cards.',
        flavor: '"Our time grows short.  If we wish to vanquish the Eldrazi, we must unlock the hedrons\' secrets."\n--Jace Beleren',
        art: 'http://mythicspoiler.com/ogw/cards/comparativeanalysis.jpg'
      },
      {
        name: 'Containment Membrane',
        set: 'Oath of the Gatewatch',
        cost: '3',
        color: 'Blue',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Common',
        effects: 'Surge {U} (You may cast this spell for its surge cost if you or a teammate has cast another spell this turn.)\nEnchant creature\nEnchanted creature doesn\'t untap during its controller\'s untap step.',
        art: 'http://mythicspoiler.com/ogw/cards/containmentmembrane.jpg'
      },
      {
        name: 'Crush of Tentacles',
        set: 'Oath of the Gatewatch',
        cost: '6',
        color: 'Blue',
        supertype: 'Sorcery',
        rarity: 'Mythic',
        effects: 'Surge {3UU} (You may cast this spell for its surge cost if you or a teammate has cast another spell this turn.)\nReturn all nonland permanents to their owner\'s hands.  If Crush of Tentacles\'s surge cost was paid, create an 8/8 blue Octopus creature token.',
        art: 'http://mythicspoiler.com/ogw/cards/crushoftentacles.jpg'
      },
      {
        name: 'Cyclone Sire',
        set: 'Oath of the Gatewatch',
        cost: '5',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Elemental',
        rarity: 'Uncommon',
        effects: 'Flying\nWhen Cyclone Sire dies, you may put three +1/+1 counters on target land you control.  If you do, that land becomes a 0/0 Elemental creature with haste that\'s still a land.',
        flavor: 'The rampaging Roil creates life out of the most volatile elements.',
        power: '3',
        toughness: '4',
        art: 'http://mythicspoiler.com/ogw/cards/cyclonesire.jpg'
      },
      {
        name: 'Gift of Tusks',
        set: 'Oath of the Gatewatch',
        cost: '1',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'Until end of turn, target creature loses all abilities and becomes a green Elephant with base power and toughness 3/3.',
        flavor: 'It\'s an experience you\'ll never forget.',
        art: 'http://mythicspoiler.com/ogw/cards/giftoftusks.jpg'
      },
      {
        name: 'Grip of the Roil',
        set: 'Oath of the Gatewatch',
        cost: '3',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'Surge {1U} (You may cast this spell for its surge cost if you or a teammate has cast another spell this turn.)\nTap target creature.  It doesn\'t untap during its controller\'s untap step.\nDraw a card.',
        art: 'http://mythicspoiler.com/ogw/cards/gripoftheroil.jpg'
      },
      {
        name: 'Hedron Alignment',
        set: 'Oath of the Gatewatch',
        cost: '3',
        color: 'Blue',
        supertype: 'Enchantment',
        rarity: 'Rare',
        effects: 'Hexproof\nAt the beginning of your upkeep, you may reveal your hand.  If you do, you win the game if you a card named Hedron Alignment in exile, in your hand, in your graveyard, and on the battlefield.\n{1U}: Scry 1.',
        art: 'http://mythicspoiler.com/ogw/cards/hedronalignment.jpg'
      },
      {
        name: 'Jwar Isle Avenger',
        set: 'Oath of the Gatewatch',
        cost: '5',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Sphinx',
        rarity: 'Common',
        effects: 'Surge {2U} (You may cast this spell for its surge cost if you or a teammate has cast another spell this turn.)\nFlying',
        flavor: 'Though solitary by nature, the sphinxes did not hesitate to join in the fight against the Eldrazi.',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/ogw/cards/jwarisleavenger.jpg'
      },
      {
        name: 'Negate',
        set: 'Oath of the Gatewatch',
        cost: '2',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Counter target noncreature spell.',
        flavor: '"Eventually, everything returns to silence."\n--Zarra, lullmage',
        art: 'http://mythicspoiler.com/ogw/cards/negate.jpg'
      },
      {
        name: 'Oath of Jace',
        set: 'Oath of the Gatewatch',
        cost: '3',
        color: 'Blue',
        supertype: 'Legendary Enchantment',
        rarity: 'Rare',
        effects: 'When Oath of Jace enters the battlefield, draw three cards, then discard two cards.\nAt the beginning of your upkeep, scry X, where X is the number of planeswalkers you control.',
        flavor: '"For the sake of the Multiverse, I will keep watch."',
        art: 'http://mythicspoiler.com/ogw/cards/oathofjace.jpg'
      },
      {
        name: 'Overwhelming Denial',
        set: 'Oath of the Gatewatch',
        cost: '4',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Rare',
        effects: 'Surge {UU} (You may cast this spell for its surge cost if you or a teammate has cast another spell this turn.)\nOverwhelming Denial can\'t be countered by spells or abilities.\nCounter target spell.',
        art: 'http://mythicspoiler.com/ogw/cards/overwhelmingdenial.jpg'
      },
      {
        name: 'Roiling Waters',
        set: 'Oath of the Gatewatch',
        cost: '7',
        color: 'Blue',
        supertype: 'Sorcery',
        rarity: 'Uncommon',
        effects: 'Return up to two target creatures your opponents control to their owner\'s hands.  Target player draws two cards.',
        flavor: '"The Roil may be unpredictable, but it is not uncontrollable."\n--Noyan Dar, Tazeem roilmage',
        art: 'http://mythicspoiler.com/ogw/cards/roilingwaters.jpg'
      },
      {
        name: 'Sphinx of the Final Word',
        set: 'Oath of the Gatewatch',
        cost: '7',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Sphinx',
        rarity: 'Mythic',
        effects: 'Sphinx of the Final Word can\'t be countered.\nFlying, hexproof\nInstant and sorcery spells you control can\'t be countered by spells or abilities.',
        flavor: 'He answers questions as readily as he asks them, but his answer is always "no."',
        power: '5',
        toughness: '5',
        art: 'http://mythicspoiler.com/ogw/cards/sphinxofthefinalword.jpg'
      },
      {
        name: 'Sweep Away',
        set: 'Oath of the Gatewatch',
        cost: '3',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Return target creature to its owner\'s hand.  If that creature is attacking, you may put it on top of its owner\'s library instead.',
        flavor: 'The Roil takes many forms.  It also takes many victims.',
        art: 'http://mythicspoiler.com/ogw/cards/sweepaway.jpg'
      },
      {
        name: 'Umara Entangler',
        set: 'Oath of the Gatewatch',
        cost: '2',
        color: 'Blue',
        supertype: 'Creature',
        subtype: 'Merfolk Rogue Ally',
        rarity: 'Common',
        effects: 'Prowess (Whenever you cast a noncreature spell, this creature gets _1/+1 until end of turn.)',
        flavor: '"Sea Gate is gone, the Halimar basin empty.  But rebuild the seawall and give these waters time, and they will fill the basin anew."',
        power: '2',
        toughness: '1',
        art: 'http://mythicspoiler.com/ogw/cards/umaraentangler.jpg'
      },
      {
        name: 'Unity of Purpose',
        set: 'Oath of the Gatewatch',
        cost: '4',
        color: 'Blue',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'Support 2. (Put a +1/+1 counter on each of up to two target creatures you control.)\nUntap each creature you control with a +1/+1 counter on it.',
        flavor: 'Faced with the novel problem of inspiring an army, Jace asked himself: "What would Gideon say?"',
        art: 'http://mythicspoiler.com/ogw/cards/unityofpurpose.jpg'
      },
      {
        name: 'Bearer of Silence',
        set: 'Oath of the Gatewatch',
        cost: '2',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Eldrazi',
        rarity: 'Rare',
        effects: 'Devoid (This card has no color.)\nWhen you cast Bearer of Silence, you may pay {1C}.  If you do, target opponent sacrifices a creature. ({C} represents colorless mana.)\nFlying\nBearer of Silence can\'t block.',
        power: '2',
        toughness: '1',
        art: 'http://mythicspoiler.com/ogw/cards/bearerofsilence.jpg'
      },
      {
        name: 'Dread Defiler',
        set: 'Oath of the Gatewatch',
        cost: '7',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Eldrazi',
        rarity: 'Rare',
        effects: 'Devoid (This card has no color.)\n{3C}, Exile a creature card from your graveyard: Target opponent loses life equal to the exiled card\'s power. ({C} represents colorless mana.)',
        flavor: 'It left behind an echoing emptiness more horrible than the grave.',
        power: '6',
        toughness: '8',
        art: 'http://mythicspoiler.com/ogw/cards/dreaddefiler.jpg'
      },
      {
        name: 'Essence Depleter',
        set: 'Oath of the Gatewatch',
        cost: '3',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Eldrazi Drone',
        rarity: 'Uncommon',
        effects: 'Devoid (This card has no color.)\n{1C}: Target opponent loses 1 life and you gain 1 life. ({C} represents colorless mana.)',
        flavor: 'When Kozilek emerged at Sea Gate, his brood lineage swarmed to the surface.',
        power: '2',
        toughness: '3',
        art: 'http://mythicspoiler.com/ogw/cards/essencedepleter.jpg'
      },
      {
        name: 'Flaying Tendrils',
        set: 'Oath of the Gatewatch',
        cost: '3',
        color: 'Black',
        supertype: 'Sorcery',
        rarity: 'Uncommon',
        effects: 'Devoid (This card has no color.)\nAll creatures get -2/-2 until end of turn.  If a creature would die this turn, exile it instead.',
        flavor: 'Only one Eldrazi stood against them, yet the defenders were outnumbered.',
        art: 'http://mythicspoiler.com/ogw/cards/flayingtendrils.jpg'
      },
      {
        name: 'Havoc Sower',
        set: 'Oath of the Gatewatch',
        cost: '4',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Eldrazi Drone',
        rarity: 'Uncommon',
        effects: 'Devoid (This card has no color.)\n{1C}: Havoc Sower gets +2/+1 until end of turn. ({C} represents colorless mana.)',
        flavor: 'It grew with a terrible swiftness.',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/ogw/cards/havocsower.jpg'
      },
      {
        name: 'Inverter of Truth',
        set: 'Oath of the Gatewatch',
        cost: '4',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Eldrazi',
        rarity: 'Mythic',
        effects: 'Devoid (This card has no color.)\nFlying\nWhen Inverter of Truth enters the battlefield, exile all cards from your library facedown, then shuffle all cards from your graveyard into your library.',
        flavor: 'In its shadow, everything changed.',
        power: '6',
        toughness: '6',
        art: 'http://mythicspoiler.com/ogw/cards/inverteroftruth.jpg'
      },
      {
        name: 'Kozilek\'s Shrieker',
        set: 'Oath of the Gatewatch',
        cost: '3',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Eldrazi Drone',
        rarity: 'Common',
        effects: 'Devoid (This card has no color.)\n{C}: Kozilek\'s Shrieker gets +1/+0 and gains menace until end of turn. (It can\'t be blocked except by two or more creatures.  {C} represents colorless mana.)',
        flavor: 'Listen to the sound of defeat.',
        power: '3',
        toughness: '2',
        art: 'http://mythicspoiler.com/ogw/cards/kozileksshrieker.jpg'
      },
      {
        name: 'Kozilek\'s Translator',
        set: 'Oath of the Gatewatch',
        cost: '5',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Eldrazi Drone',
        rarity: 'Common',
        effects: 'Devoid (This card has no color.)\nPay 1 life: Add {C} to your mana pool.  Activate this ability only once each turn. ({C} represents colorless mana.)',
        flavor: 'From nothingness, sustenance.',
        power: '3',
        toughness: '5',
        art: 'http://mythicspoiler.com/ogw/cards/kozilekstranslator.jpg'
      },
      {
        name: 'Oblivion Strike',
        set: 'Oath of the Gatewatch',
        cost: '4',
        color: 'Black',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'Devoid (This card has no color.)\nExile target creature.',
        flavor: 'It\'s bad enough to be torn to pieces.  It\'s worse by far to be torn from the world itself.',
        art: 'http://mythicspoiler.com/ogw/cards/oblivionstrike.jpg'
      },
      {
        name: 'Reaver Drone',
        set: 'Oath of the Gatewatch',
        cost: '1',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Eldrazi Drone',
        rarity: 'Uncommon',
        effects: 'Devoid (This card has no color.)\nAt the beginning of your upkeep, you lose 1 life unless you control another colorless creature.',
        flavor: 'Kozilek\'s brood infiltrates and deceives.  The spawn of Ulamog mindlessly consume.',
        power: '2',
        toughness: '1',
        art: 'http://mythicspoiler.com/ogw/cards/reaverdrone.jpg'
      },
      {
        name: 'Sifter of Skulls',
        set: 'Oath of the Gatewatch',
        cost: '4',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Eldrazi',
        rarity: 'Rare',
        effects: 'Devoid (This card has no color.)\nWhenever another nontoken creature you control dies, create a 1/1 colorless Eldrazi Scion creature token with "Sacrifice this creature: Add {C} to your mana pool." ({C} represents colorless mana.)',
        power: '4',
        toughness: '3',
        art: 'http://mythicspoiler.com/ogw/cards/sifterofskulls.jpg'
      },
      {
        name: 'Sky Scourer',
        set: 'Oath of the Gatewatch',
        cost: '2',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Eldrazi Drone',
        rarity: 'Common',
        effects: 'Devoid (This card hasno color.)\nFlying\nWhenever you cast a colorless spell, Sky Scourer gets +1/+0 until end of turn.',
        flavor: '"The Eldrazi are nothing if not thorough."\n--Jace Beleren',
        power: '1',
        toughness: '2',
        art: 'http://mythicspoiler.com/ogw/cards/skyscourer.jpg'
      },
      {
        name: 'Slaughter Drone',
        set: 'Oath of the Gatewatch',
        cost: '2',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Eldrazi Drone',
        rarity: 'Common',
        effects: 'Devoid (This card has no color.)\n{C}: Slaughter Drone gains deathtouch until end of turn. (Any amount of damage it deals to a creature is enough to destroy it.  {C} represents colorless mana.)',
        flavor: 'It kills what is, making way for what should not be.',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/ogw/cards/slaughterdrone.jpg'
      },
      {
        name: 'Unnatural Endurance',
        set: 'Oath of the Gatewatch',
        cost: '1',
        color: 'Black',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Devoid (This card has no color.)\nTarget creature gets +2/+0 until end of turn.  Regenerate it.',
        flavor: '"Eldrazi don\'t die easy.  Sometimes they don\'t die at all."\n--Yon Basrel, Oran-Rief survivalist',
        art: 'http://mythicspoiler.com/ogw/cards/unnaturalendurance.jpg'
      },
      {
        name: 'Visions of Brutality',
        set: 'Oath of the Gatewatch',
        cost: '2',
        color: 'Black',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Uncommon',
        effects: 'Devoid (This card has no color.)\nEnchant creature\nEnchanted creature can\'t block.\nWhenever enchanted creature deals damage, its controller loses that much life.',
        art: 'http://mythicspoiler.com/ogw/cards/visionsofbrutality.jpg'
      },
      {
        name: 'Witness the End',
        set: 'Oath of the Gatewatch',
        cost: '4',
        color: 'Black',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'Devoid (This card has no color.)\nTarget opponent exiles two cards from their hand and loses 2 life.',
        flavor: '"Ulamog stood before us at Sea Gate, ready to succumb... and then Kozilek arose.  Whatever hope I had for our world died."\n--Vandri, Kalastria emissary',
        art: 'http://mythicspoiler.com/ogw/cards/witnesstheend.jpg'
      },
      {
        name: 'Corpse Churn',
        set: 'Oath of the Gatewatch',
        cost: '2',
        color: 'Black',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Put the top three cards of your library into your graveyard, then you may return a creature card from your graveyard to your hand.',
        flavor: '"The distraction of your life has ended.  Now your service begins."\n--Kalitas, thrall of Ulamog',
        art: 'http://mythicspoiler.com/ogw/cards/corpsechurn.jpg'
      },
      {
        name: 'Drana\'s Chosen',
        set: 'Oath of the Gatewatch',
        cost: '4',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Vampire Shaman Ally',
        rarity: 'Rare',
        effects: 'Cohort -- {T}, Tap an untapped Ally you control: Create a 2/2 black Zombie creature token.',
        flavor: '"Drana commands me.  I command my nulls.  And so her bidding is done."',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/ogw/cards/dranaschosen.jpg'
      },
      {
        name: 'Grasp of Darkness',
        set: 'Oath of the Gatewatch',
        cost: '2',
        color: 'Black',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'Target creature gets -4/-4 until end of turn.',
        flavor: '"I welcome the use of even the foulest magic if it will rid us of the monstrosities that plague our world."\n--Munda, ambush leader',
        art: 'http://mythicspoiler.com/ogw/cards/graspofdarkenss.jpg'
      },
      {
        name: 'Kalitas, Traitor of Ghet',
        set: 'Oath of the Gatewatch',
        cost: '4',
        color: 'Black',
        supertype: 'Legendary Creature',
        subtype: 'Vampire Warrior',
        rarity: 'Mythic',
        effects: 'Lifelink\nIf a nontoken creature an opponent controls would die, exile that card and create a 2/2 black Zombie creature token.\n{2B}, Sacrifice another Vampire or Zombie: Put two +1/+1 counters on Kalitas, Traitor of Ghet.',
        power: '3',
        toughness: '4',
        art: 'http://mythicspoiler.com/ogw/cards/kalitastraitorofghet.jpg'
      },
      {
        name: 'Malakir Soothsayer',
        set: 'Oath of the Gatewatch',
        cost: '5',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Vampire Shaman Ally',
        rarity: 'Uncommon',
        effects: 'Cohort -- {T}, Tap an untapped Ally you control: You draw a card and lose 1 life.',
        flavor: '"Your blood whispers secrets your mind could never comprehend."',
        power: '4',
        toughness: '4',
        art: 'http://mythicspoiler.com/ogw/cards/malakirsoothsayer.jpg'
      },
      {
        name: 'Null Caller',
        set: 'Oath of the Gatewatch',
        cost: '4',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Vampire Shaman',
        rarity: 'Uncommon',
        effects: '{3B}, Exile a creature card from your graveyard: Create a tapped 2/2 black Zombie creature token.',
        flavor: 'Zendikar\'s defenders include both healers and vampires.  One way or another, the fallen will return to the fight.',
        power: '2',
        toughness: '4',
        art: 'http://mythicspoiler.com/ogw/cards/nullcaller.jpg'
      },
      {
        name: 'Remorseless Punishment',
        set: 'Oath of the Gatewatch',
        cost: '5',
        color: 'Black',
        supertype: 'Sorcery',
        rarity: 'Rare',
        effects: 'Target opponent loses 5 life unless that player discards two cards or sacrifices a creature or planeswalker.  Repeat this process once.',
        flavor: '"I have suffered a thousand lifetimes of agony on this wretched world.  I\'ve far less time to share with you, but I assure you, no less pain."\n--Ob Nixilis',
        art: 'http://mythicspoiler.com/ogw/cards/remorselesspunishment.jpg'
      },
      {
        name: 'Tar Snare',
        set: 'Oath of the Gatewatch',
        cost: '3',
        color: 'Black',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Target creature gets -3/-2 until end of turn.',
        flavor: 'The amorphous, magically animated residue known as the Fathom Sludge lurks in the Hagra Cistern, attacking its prey with pseudopods and dragging it down to be digested.',
        art: 'http://mythicspoiler.com/ogw/cards/tarsnare.jpg'
      },
      {
        name: 'Untamed Hunger',
        set: 'Oath of the Gatewatch',
        cost: '3',
        color: 'Black',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Common',
        effects: 'Enchant creature\nEnchanted creature gets +2/+1 and has menace. (It can\'t be blocked except by two or more creatures.)',
        flavor: '"Mindlessness is not weakness.  When we are lost to hunger we are unstoppable."\n--Drana, Kalastria bloodchief',
        art: 'http://mythicspoiler.com/ogw/cards/untamedhunger.jpg'
      },
      {
        name: 'Vampire Envoy',
        set: 'Oath of the Gatewatch',
        cost: '3',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Vampire Cleric Ally',
        rarity: 'Common',
        effects: 'Flying\nWhenever Vampire Envoy becomes tapped, you gain 1 life.',
        flavor: '"Zendikar will fight until it has bled its last."',
        power: '1',
        toughness: '4',
        art: 'http://mythicspoiler.com/ogw/cards/vampireenvoy.jpg'
      },
      {
        name: 'Zulaport Chainmage',
        set: 'Oath of the Gatewatch',
        cost: '4',
        color: 'Black',
        supertype: 'Creature',
        subtype: 'Human Shaman Ally',
        rarity: 'Common',
        effects: 'Cohort -- {T}, Tap an untapped Ally you control: Target opponent loses 2 life.',
        flavor: 'The chains obey her.  Everything else would do best to get out of her way.',
        power: '4',
        toughness: '2',
        art: 'http://mythicspoiler.com/ogw/cards/zulaportchainmage.jpg'
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      }
    ]);
  });
};