exports.seed = function(knex, Promise) {
  // Deletes ALL existing entries
  return knex('Card_List').del()
  .then(function () {
    // Inserts seed entries
    return knex('Card_List').insert([
      {
        name: 'Deceiver of Form',
        set: 'Oath of the Gatewatch',
        cost: '7',
        color: 'Colorless',
        supertype: 'Creature',
        subtype: 'Eldrazi',
        rarity: 'Rare',
        effects: '({C} represents colorless mana.)\nAt the beginning of combat on your turn, reveal the top card of your library.  If a creature card is revealed this way, you may have creatures you control other than Deceiver of Form become copies of that creature until end of turn.  You may put that card on the bottom of your library.',
        power: '8',
        toughness: '8',
        art: 'http://mythicspoiler.com/ogw/cards/deceiverofform.jpg'
      },
      {
        name: 'Eldrazi Mimic',
        set: 'Oath of the Gatewatch',
        cost: '2',
        color: 'Colorless',
        supertype: 'Creature',
        subtype: 'Eldrazi',
        rarity: 'Rare',
        effects: 'Whenever another colorless creature enters the battlefield under your control, you may change Eldrazi Mimic\'s base power and toughness to that creature\'s power and toughness until end of turn.',
        flavor: 'It is consistently inconsistent.',
        power: '2',
        toughness: '1',
        art: 'http://mythicspoiler.com/ogw/cards/eldrazimimic.jpg'
      },
      {
        name: 'Endbringer',
        set: 'Oath of the Gatewatch',
        cost: '6',
        color: 'Colorless',
        supertype: 'Creature',
        subtype: 'Eldrazi',
        rarity: 'Rare',
        effects: 'Untap Endbringer during each other player\'s untap step.\n{T}: Endbringer deals 1 damage to target creature or player.\n{1}, {T}: Target creature can\'t attack or block this turn.\n{2}, {T}: Draw a card.',
        power: '5',
        toughness: '5',
        art: 'http://mythicspoiler.com/ogw/cards/endbringer.jpg'
      },
      {
        name: 'Kozilek, the Great Distortion',
        set: 'Oath of the Gatewatch',
        cost: '10',
        color: 'Colorless',
        supertype: 'Legendary Creature',
        subtype: 'Eldrazi',
        rarity: 'Mythic',
        effects: 'When you cast Kozilek, the Great Distortion, if you have fewer than seven cards in hand, draw cards equal to the difference.\nMenace\nDiscard a card with converted mana cost X: Counter target spell with converted mana cost X.',
        flavor: 'A void as cryptic as reality itself.',
        power: '12',
        toughness: '12',
        art: 'http://mythicspoiler.com/ogw/cards/kozilekthegreatdistortion.jpg'
      },
      {
        name: 'Kozilek\'s Pathfinder',
        set: 'Oath of the Gatewatch',
        cost: '6',
        color: 'Colorless',
        supertype: 'Creature',
        subtype: 'Eldrazi',
        rarity: 'Common',
        effects: '{C}: Target creature can\'t block Kozilek\'s Pathfinder this turn. ({C} represents colorless mana.)',
        flavor: '"We didn\'t know where it came from or where it was going.  All we knew was that we did not matter."\n--Akiri, kor line-slinger',
        power: '5',
        toughness: '5',
        art: 'http://mythicspoiler.com/ogw/cards/kozilekspathfinder.jpg'
      },
      {
        name: 'Matter Reshaper',
        set: 'Oath of the Gatewatch',
        cost: '3',
        color: 'Colorless',
        supertype: 'Creature',
        subtype: 'Eldrazi',
        rarity: 'Rare',
        effects: '({C} represents colorless mana.)\nWhen Matter Reshaper dies, reveal the top card of your library.  Put that card onto the battlefield if it\'s a permanent card with converted mana cost 3 or less.  Otherwise, put that card into your hand.',
        power: '3',
        toughness: '2',
        art: 'http://mythicspoiler.com/ogw/cards/matterreshaper.jpg'
      },
      {
        name: 'Reality Smasher',
        set: 'Oath of the Gatewatch',
        cost: '5',
        color: 'Colorless',
        supertype: 'Creature',
        subtype: 'Eldrazi',
        rarity: 'Rare',
        effects: '({C} represents colorless mana.)\nTrample, haste\nWhenever Reality Smasher becomes the target of a spell an opponent controls, counter that spell unless its controller discards a card.',
        flavor: 'As easy to stop as it is to comprehend.',
        power: '5',
        toughness: '5',
        art: 'http://mythicspoiler.com/ogw/cards/realitysmasher.jpg'
      },
      {
        name: 'Spatial Distortion',
        set: 'Oath of the Gatewatch',
        cost: '2',
        color: 'Colorless',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: '({C} represents colorless mana.)\nTarget creature gets +3/-3 until end of turn.',
        flavor: '"For those without the Planeswalker spark, the merest touch of the Blind Eternities can kill."\n--Ugin',
        art: 'http://mythicspoiler.com/ogw/cards/spatialdistortion.jpg'
      },
      {
        name: 'Thought-Knot Seer',
        set: 'Oath of the Gatewatch',
        cost: '4',
        color: 'Colorless',
        supertype: 'Creature',
        subtype: 'Eldrazi',
        rarity: 'Rare',
        effects: '({C} represents colorless mana.)\nWhen Thought-Knot Seer enters the battlefield, target opponent reveals their hand.  You choose a nonland card from it and exile it.\nWhen Thought-Knot Seer leaves the battlefield, target opponent draws a card.',
        power: '4',
        toughness: '4',
        art: 'http://mythicspoiler.com/ogw/cards/thoughtknotseer.jpg'
      },
      {
        name: 'Walker of the Wastes',
        set: 'Oath of the Gatewatch',
        cost: '5',
        color: 'Colorless',
        supertype: 'Creature',
        subtype: 'Eldrazi',
        rarity: 'Uncommon',
        effects: '({C} represents colorless mana.)\nTrample\nWalker of the Wastes gets +1/+1 for each land you control named Wastes.',
        flavor: 'In the absence of life, something yet grows.',
        power: '4',
        toughness: '4',
        art: 'http://mythicspoiler.com/ogw/cards/walkerofthewastes.jpg'
      },
      {
        name: 'Warden of Geometries',
        set: 'Oath of the Gatewatch',
        cost: '4',
        color: 'Colorless',
        supertype: 'Creature',
        subtype: 'Eldrazi Drone',
        rarity: 'Common',
        effects: 'Vigilance\n{T}: Add {C} to your mana pool. ({C} represents colorless mana.)',
        flavor: 'The wastelands disorient even the most experienced scouts, making them easy prey for Kozilek\'s drones.',
        power: '2',
        toughness: '3',
        art: 'http://mythicspoiler.com/ogw/cards/wardenofgeometries.jpg'
      },
      {
        name: 'Warping Wail',
        set: 'Oath of the Gatewatch',
        cost: '2',
        color: 'Colorless',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: '({C} represents colorless mana.)\nChoose one --\n\tExile target creature with power or toughness 1 or less.\n\tCounter target sorcery spell.\n\tCreate a 1/1 colorless Eldrazi Scion creature token with "Sacrifice this creature: Add {C} to your mana pool."',
        art: 'http://mythicspoiler.com/ogw/cards/warpingwail.jpg'
      },
      {
        name: 'Eldrazi Displacer',
        set: 'Oath of the Gatewatch',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Eldrazi',
        rarity: 'Rare',
        effects: 'Devoid (This creature has no color.)\n{2C}: Exile another target creature, then return it to the battlefield tapped under its owner\'s control. ({C} represents colorless mana.)',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/ogw/cards/eldrazidisplacer.jpg'
      },
      {
        name: 'Allied Reinforcements',
        set: 'Oath of the Gatewatch',
        cost: '4',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Uncommon',
        effects: 'Create two 2/2 white Knight Ally creature tokens.',
        flavor: '"Our formation was scattered after Sea Gate fell.  If you\'re fighting the Eldrazi, consider us your newest recruits."',
        art: 'http://mythicspoiler.com/ogw/cards/alliedreinforcements.jpg'
      },
      {
        name: 'Call the Gatewatch',
        set: 'Oath of the Gatewatch',
        cost: '3',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Rare',
        effects: 'Search your library for a planeswalker card, reveal it, and put it into your hand.  Then shuffle your library.',
        flavor: '"I\'ve heard it said that a Planeswalker is someone who can always rin from danger.  But Gideon\'s right: we\'re also the ones who can choose to stay."\n--Jace Beleren',
        art: 'http://mythicspoiler.com/ogw/cards/callthegatewatch.jpg'
      },
      {
        name: 'Dazzling Reflection',
        set: 'Oath of the Gatewatch',
        cost: '2',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'You gain life equal to target creature\'s power.  The next time that creature would deal damage this turn, prevent that damage.',
        flavor: '"The light of a felidar\'s horns can give even an Eldrazi pause."\n--Zarra, lullmage',
        art: 'http://mythicspoiler.com/ogw/cards/dazzlingreflection.jpg'
      },
      {
        name: 'Expedition Raptor',
        set: 'Oath of the Gatewatch',
        cost: '5',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Bird',
        rarity: 'Common',
        effects: 'Flying\nWhen Expedition Raptor enters the battlefield, support 2. (Put a +1/+1 counter on up to two other creatures.)',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/ogw/cards/expeditionraptor.jpg'
      },
      {
        name: 'General Tazri',
        set: 'Oath of the Gatewatch',
        cost: '5',
        color: 'White',
        supertype: 'Legendary Creature',
        subtype: 'Human Ally',
        rarity: 'Mythic',
        effects: 'When General Tazri enters the battlefield, you may search your library for an Ally creature card, reveal it, put it into your hand, then shuffle your library.\n{WUBRG}: Ally creatures you control get +X/+X until end of turn, where X is the number of colors among those creatures.',
        power: '3',
        toughness: '4',
        art: 'http://mythicspoiler.com/ogw/cards/generaltazri.jpg'
      },
      {
        name: 'Immolating Glare',
        set: 'Oath of the Gatewatch',
        cost: '2',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'Destroy target attacking creature.',
        flavor: '"The sun can warm your skin or blister it, nurture your crops or wither them, light your path or blind you.  She is a fickle friend, but a far worse enemy."\n--Nazra of the Stone Havens',
        art: 'http://mythicspoiler.com/ogw/cards/immolatingglare.jpg'
      },
      {
        name: 'Iona\'s Blessing',
        set: 'Oath of the Gatewatch',
        cost: '4',
        color: 'White',
        supertype: 'Enchantment',
        subtype: 'Aura',
        rarity: 'Uncommon',
        effects: 'Enchant creature\nEnchanted creature gets +2/+2, has vigilance, and can block an additional creature.',
        flavor: '"Walk now in my light.  When the rest of the world closes its eyes, you will still see."\n--Iona',
        art: 'http://mythicspoiler.com/ogw/cards/ionasblessing.jpg'
      },
      {
        name: 'Isolation Zone',
        set: 'Oath of the Gatewatch',
        cost: '4',
        color: 'White',
        supertype: 'Enchantment',
        rarity: 'Common',
        effects: 'When Isolation Zone enters the battlefield, exile target creature or enchantment an opponent controls until Isolation Zone leaves the battlefield.',
        flavor: 'When properly aligned, hedrons become powerful tools of binding.',
        art: 'http://mythicspoiler.com/ogw/cards/isolationzone.jpg'
      },
      {
        name: 'Kor Scythemaster',
        set: 'Oath of the Gatewatch',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Kor Soldier Ally',
        rarity: 'Common',
        effects: 'Kor Scythemaster has first strike as long as it\'s attacking.',
        flavor: 'The kor of Zendikar are known for quiet determination in the face of overwhelming odds.',
        power: '3',
        toughness: '1',
        art: 'http://mythicspoiler.com/ogw/cards/korscythemaster.jpg'
      },
      {
        name: 'Kor Sky Climber',
        set: 'Oath of the Gatewatch',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Kor Soldier Ally',
        rarity: 'Common',
        effects: '{1W}: Kor Sky Climber gains flying until end of turn.',
        flavor: '"With rope, I can fly as far as the rope can reach.  But with light, the sky is the limit."',
        power: '3',
        toughness: '2',
        art: 'http://mythicspoiler.com/ogw/cards/korskyclimber.jpg'
      },
      {
        name: 'Linvala, the Preserver',
        set: 'Oath of the Gatewatch',
        cost: '6',
        color: 'White',
        supertype: 'Legendary Creature',
        subtype: 'Angel',
        rarity: 'Mythic',
        effects: 'Flying\nWhen Linvala, the Preserver enters the battlefield, if an opponent has more life than you, you gain 5 life.\nWhen Linvala, the Preserver enters the battlefield, if an opponent controls more creatures than you, create a 3/3 white Angel creature token with flying.',
        power: '5',
        toughness: '5',
        art: 'http://mythicspoiler.com/ogw/cards/linvalathepreserver.jpg'
      },
      {
        name: 'Make a Stand',
        set: 'Oath of the Gatewatch',
        cost: '3',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Uncommon',
        effects: 'Creatures you control get +1/+0 and gain indestructible until end of turn. (Damage and effects that say "destroy" don\'t destroy them.)',
        flavor: 'For a moment they stood tall, all fear forgotten.',
        art: 'http://mythicspoiler.com/ogw/cards/makeastand.jpg'
      },
      {
        name: 'Makindi Aeronaut',
        set: 'Oath of the Gatewatch',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Kor Scout Ally',
        rarity: 'Common',
        effects: 'Flying',
        flavor: '"The Eldrazi have surprised us before.  It\'s my job to make sure that never happens again."',
        power: '1',
        toughness: '3',
        art: 'http://mythicspoiler.com/ogw/cards/makindiaeronaut.jpg'
      },
      {
        name: 'Mighty Leap',
        set: 'Oath of the Gatewatch',
        cost: '2',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Target creature gets +2/+2 and gains flying until end of turn.',
        flavor: '"We may have lost faith in our gods, but we are far from losing faith in ourselves."\n--Munda, ambush leader',
        art: 'http://mythicspoiler.com/ogw/cards/mightyleap.jpg'
      },
      {
        name: 'Munda\'s Vanguard',
        set: 'Oath of the Gatewatch',
        cost: '5',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Kor Knight Ally',
        rarity: 'Rare',
        effects: 'Cohort -- {T}, Tap an untapped Ally you control: Put a +1/+1 counter on each creature you control.',
        flavor: '"Do not let yourselves fall now.  Zendikar is depending on us--on you!"',
        power: '3',
        toughness: '3',
        art: 'http://mythicspoiler.com/ogw/cards/mundasvanguard.jpg'
      },
      {
        name: 'Oath of Gideon',
        set: 'Oath of the Gatewatch',
        cost: '3',
        color: 'White',
        supertype: 'Legendary Enchantment',
        rarity: 'Rare',
        effects: 'When Oath of Gideon enters the battlefield, create two 1/1 white Kor Ally creature tokens.\nEach planeswalker you control enters the battlefield with an additional loyalty counter on it.',
        flavor: '"For justice and peace, I will keep watch."',
        art: 'http://mythicspoiler.com/ogw/cards/oathofgideon.jpg'
      },
      {
        name: 'Ondu War Cleric',
        set: 'Oath of the Gatewatch',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Cleric Ally',
        rarity: 'Common',
        effects: 'Cohort -- {T}, Tap an untapped Ally you control: You gain 2 life.',
        flavor: '"I will follow the light of Iona into battle, and I will know no fear."',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/ogw/cards/onduwarcleric.jpg'
      },
      {
        name: 'Relief Captain',
        set: 'Oath of the Gatewatch',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Kor Knight Ally',
        rarity: 'Uncommon',
        effects: 'When Relief Captain enters the battlefield, support 3. (Put a +1/+1 counter on each of up to three other target creatures.)',
        flavor: 'Sometimes gestures of support are small.  Sometimes not.',
        power: '3',
        toughness: '2',
        art: 'http://mythicspoiler.com/ogw/cards/reliefcaptain.jpg'
      },
      {
        name: 'Searing Light',
        set: 'Oath of the Gatewatch',
        cost: '1',
        color: 'White',
        supertype: 'Instant',
        rarity: 'Common',
        effects: 'Destroy target attacking or blocking creature with power 2 or less.',
        flavor: '"Light can lay bare our fears.  It can also make them go away."\n--Nazra of the Stone Havens',
        art: 'http://mythicspoiler.com/ogw/cards/searinglight.jpg'
      },
      {
        name: 'Shoulder to Shoulder',
        set: 'Oath of the Gatewatch',
        cost: '3',
        color: 'White',
        supertype: 'Sorcery',
        rarity: 'Common',
        effects: 'Support 2. (Put a +1/+1 counter on each of up to two target creatures.)\nDraw a card.',
        flavor: '"Sea Gate may have fallen, but we still stand.  We still fight."\n--Gideon Jura',
        art: 'http://mythicspoiler.com/ogw/cards/shouldertoshoulder.jpg'
      },
      {
        name: 'Spawnbinder Mage',
        set: 'Oath of the Gatewatch',
        cost: '4',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Human Wizard Ally',
        rarity: 'Common',
        effects: 'Cohort -- {T}, Tap an untapped Ally you control: Tap target creature.',
        flavor: '"Follow me.  Step lightly.  And resist the urge to kick them."',
        power: '2',
        toughness: '4',
        art: 'http://mythicspoiler.com/ogw/cards/spawnbindermage.jpg'
      },
      {
        name: 'Steppe Glider',
        set: 'Oath of the Gatewatch',
        cost: '5',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Elemental',
        rarity: 'Uncommon',
        effects: 'Flying, vigilance\n{1W}: Target creature with a +1/+1 counter on it gains flying and vigilance until end of turn.',
        flavor: 'It glides over the landscape.  It also happens to be one.',
        power: '2',
        toughness: '4',
        art: 'http://mythicspoiler.com/ogw/cards/steppeglider.jpg'
      },
      {
        name: 'Stone Haven Outfitter',
        set: 'Oath of the Gatewatch',
        cost: '2',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Kor Artificer Ally',
        rarity: 'Rare',
        effects: 'Equipped creatures get +1/+1.\nWhenever an equipped creature you control dies, draw a card.',
        flavor: 'The makers and menders are the first called to battle and the last to leave.',
        power: '2',
        toughness: '2',
        art: 'http://mythicspoiler.com/ogw/cards/stonehavenoutfitter.jpg'
      },
      {
        name: 'Stoneforge Acolyte',
        set: 'Oath of the Gatewatch',
        cost: '1',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Kor Artificer Ally',
        rarity: 'Uncommon',
        effects: 'Cohort -- {T}, Tap an untapped Ally you control: Look at the top four cards of your library.  You may reveal an Equipment card from among them and put it into your hand.  Put the rest on the bottom of your library in a random order.',
        flavor: '"The stone speaks.  We are merely interpreters."',
        power: '1',
        toughness: '2',
        art: 'http://mythicspoiler.com/ogw/cards/stoneforgeacolyte.jpg'
      },
      {
        name: 'Wall of Resurgence',
        set: 'Oath of the Gatewatch',
        cost: '3',
        color: 'White',
        supertype: 'Creature',
        subtype: 'Wall',
        rarity: 'Uncommon',
        effects: 'Defender\nWhen Wall of Resurgence enters the battlefield, you may put three +1/+1 counters on target land you control.  If you do, that land becomes a 0/0 Elemental creature with haste that\'s still a land.',
        power: '0',
        toughness: '6',
        art: 'http://mythicspoiler.com/ogw/cards/wallofresurgence.jpg'
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Blue',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Black',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Red',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Green',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: '',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      },
      {
        name: '',
        set: 'Oath of the Gatewatch',
        cost: '',
        color: 'Colorless',
        supertype: '',
        subtype: '',
        rarity: '',
        effects: '',
        flavor: '',
        power: '',
        toughness: '',
        loyalty: '',
        art: ''
      }
    ]);
  });
};